; MacSHAPA Open Database
( setf macshapa-db
 '(
    ( HEADER>
      (
        ( NAME> "sync_and_stamps.VCR.odb" )
        ( VERSION> 1 )
        ( DEBUG-LEVEL> 0 )
        ( MAX-ERRORS> 1 )
        ( MAX-WARNINGS> 1 )
      )
    )
    ( USER>
      (
        ( PREDICATE-DEFINITIONS>
          (
          )
        )
        ( SPREADSHEET-VARIABLE-DECLARATIONS>
          (
            ( |onset and offset|
              (
                ( TYPE> <<NOMINAL>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 183 )
              )
            )
            ( |offset only|
              (
                ( TYPE> <<NOMINAL>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 183 )
              )
            )
            ( |onset only|
              (
                ( TYPE> <<NOMINAL>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 183 )
              )
            )
            ( |continuous time|
              (
                ( TYPE> <<NOMINAL>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 183 )
              )
            )
          )
        )
        ( SPREADSHEET-VARIABLE-DEFINITIONS>
          (
            ( |onset and offset|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 648036 )
                      ( OFFSET> 648112 )
                      ( |<val>| |<val>| )
                    )
                    (
                      ( ONSET> 648165 )
                      ( OFFSET> 648219 )
                      ( |<val>| |<val>| )
                    )
                    (
                      ( ONSET> 648271 )
                      ( OFFSET> 648328 )
                      ( |<val>| |<val>| )
                    )
                    (
                      ( ONSET> 648382 )
                      ( OFFSET> 648436 )
                      ( |<val>| |<val>| )
                    )
                    (
                      ( ONSET> 648481 )
                      ( OFFSET> 648558 )
                      ( |<val>| |<val>| )
                    )
                  )
                )
              )
            )
            ( |offset only|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 149 )
                      ( |<val>| |<val>| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 279 )
                      ( |<val>| |<val>| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 396 )
                      ( |<val>| |<val>| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 512 )
                      ( |<val>| |<val>| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 625 )
                      ( |<val>| |<val>| )
                    )
                  )
                )
              )
            )
            ( |onset only|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 648094 )
                      ( OFFSET> 0 )
                      ( |<val>| |<val>| )
                    )
                    (
                      ( ONSET> 648210 )
                      ( OFFSET> 0 )
                      ( |<val>| |<val>| )
                    )
                    (
                      ( ONSET> 648328 )
                      ( OFFSET> 0 )
                      ( |<val>| |<val>| )
                    )
                    (
                      ( ONSET> 648447 )
                      ( OFFSET> 0 )
                      ( |<val>| |<val>| )
                    )
                    (
                      ( ONSET> 648562 )
                      ( OFFSET> 0 )
                      ( |<val>| |<val>| )
                    )
                  )
                )
              )
            )
            ( |continuous time|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 146 )
                      ( OFFSET> 369 )
                      ( |<val>| |<val>| )
                    )
                    (
                      ( ONSET> 369 )
                      ( OFFSET> 531 )
                      ( |<val>| |<val>| )
                    )
                    (
                      ( ONSET> 531 )
                      ( OFFSET> 693 )
                      ( |<val>| |<val>| )
                    )
                    (
                      ( ONSET> 693 )
                      ( OFFSET> 874 )
                      ( |<val>| |<val>| )
                    )
                    (
                      ( ONSET> 874 )
                      ( OFFSET> 984 )
                      ( |<val>| |<val>| )
                    )
                  )
                )
              )
            )
          )
        )
      )
    )
    ( QUERY>
      (
        ( |query| ( |onset only| |<ord>| |?on| |<offset>| |<val>| ) ( |insert| ( |onset only| |<ord>| ( |plus| |?on| ( TIME> 648000 ) ) |<offset>| |<val>| ) ) ) 
        ( |query| ( |onset and offset| |<ord>| |?on| |?off| |<val>| ) ( |insert| ( |onset and offset| |<ord>| ( |plus| |?on| ( TIME> 648000 ) ) ( |plus| |?off| ( TIME> 648000 ) ) |<val>| ) ) ) 
      )
    )
    ( SYSTEM>
      (
        ( SHAPA-PANE-VARS>
          (
            |onset only|
            |onset and offset|
            |continuous time|
            |offset only|
          )
        )
      )
    )
  )
)
