; MacSHAPA Open Database
( setf macshapa-db
 '(
    ( HEADER>
      (
        ( NAME> "content_mem_loss.odb" )
        ( VERSION> 1 )
        ( DEBUG-LEVEL> 0 )
        ( MAX-ERRORS> 1 )
        ( MAX-WARNINGS> 1 )
      )
    )
    ( USER>
      (
        ( PREDICATE-DEFINITIONS>
          (
            ( |a| ( ( VARIABLE-LENGTH> TRUE ) ( FORMAL-ARG-LIST> ( |<val>| ) ) ) )
          )
        )
        ( SPREADSHEET-VARIABLE-DECLARATIONS>
          (
            ( |float|
              (
                ( TYPE> <<FLOAT>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 125 )
              )
            )
            ( |asdf|
              (
                ( TYPE> <<PREDICATE>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 125 )
              )
            )
            ( |matr|
              (
                ( TYPE> <<MATRIX>> )
                ( VARIABLE-LENGTH> TRUE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| |<v2>| |<arg3>| |<arg4>| |<arg5>| ) )
                ( COLUMN-WIDTH> 125 )
              )
            )
            ( |nom|
              (
                ( TYPE> <<NOMINAL>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 125 )
              )
            )
            ( |int|
              (
                ( TYPE> <<INTEGER>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 125 )
              )
            )
            ( |text|
              (
                ( TYPE> <<TEXT>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 125 )
              )
            )
          )
        )
        ( SPREADSHEET-VARIABLE-DEFINITIONS>
          (
            ( |float|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| 10.000000 )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| 20.000000 )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| 30.000000 )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| 40.000000 )
                    )
                  )
                )
              )
            )
            ( |asdf|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| () )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| ( |a| |<val>| ) )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| ( |a| |b| ) )
                    )
                  )
                )
                ( VOCAB> ( |a| ) )
              )
            )
            ( |matr|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |b| )
                      ( |<v2>| |c| )
                      ( |<arg3>| |d| )
                      ( |<arg4>| |e| )
                      ( |<arg5>| |f| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| ( |a| |cd| ) )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |b| )
                      ( |<v2>| |c| )
                    )
                  )
                )
                ( VOCAB> ( |a| ) )
              )
            )
            ( |nom|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |a| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |b| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |c| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |d| )
                    )
                  )
                )
              )
            )
            ( |int|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| 0 )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| 10 )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| 20 )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| 30 )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| 40 )
                    )
                  )
                )
              )
            )
            ( |text|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| "this" )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| "is" )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| "the" )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| "way" )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| "you" )
                    )
                  )
                )
              )
            )
          )
        )
      )
    )
    ( QUERY>
      (
      )
    )
    ( SYSTEM>
      (
        ( SHAPA-PANE-VARS>
          (
            |asdf|
            |matr|
            |int|
            |float|
            |nom|
            |text|
          )
        )
      )
    )
  )
)
