; MacSHAPA Open Database
( setf macshapa-db
 '(
    ( HEADER>
      (
        ( NAME> "Bad Sync.odb" )
        ( VERSION> 1 )
        ( DEBUG-LEVEL> 0 )
        ( MAX-ERRORS> 1 )
        ( MAX-WARNINGS> 1 )
      )
    )
    ( USER>
      (
        ( PREDICATE-DEFINITIONS>
          (
            ( |Newvar| ( ( VARIABLE-LENGTH> TRUE ) ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| |<arg3>| |<arg4>| ) ) ) )
            ( |PREDICT| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<SPEAKER>| |<MITIGATION>| ) ) ) )
            ( |REASON| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<SPEAKER>| |<MITIGATION>| ) ) ) )
            ( |OBSERVE| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<SPEAKER>| |<MITIGATION>| ) ) ) )
            ( |ANNOUNCE| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<SPEAKER>| |<MITIGATION>| ) ) ) )
            ( |ACKNOWL| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<SPEAKER>| |<TO>| |<MITIGATION>| ) ) ) )
            ( |COMMAND| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<SPEAKER>| |<TO>| |<MITIGATION>| ) ) ) )
            ( |GOAL| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<TEMPERATURE>| |<VOLUME>| |<FLOWRATE>| ) ) ) )
          )
        )
        ( SPREADSHEET-VARIABLE-DECLARATIONS>
          (
            ( |sys.var|
              (
                ( TYPE> <<MATRIX>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<PARAM>| |<SUBSYS>| |<VAL>| ) )
                ( COLUMN-WIDTH> 200 )
              )
            )
            ( |state.var|
              (
                ( TYPE> <<MATRIX>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<PARAM>| |<SUBSYS>| |<VAL>| ) )
                ( COLUMN-WIDTH> 183 )
              )
            )
            ( |verbal|
              (
                ( TYPE> <<TEXT>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 183 )
              )
            )
            ( |Mola|
              (
                ( TYPE> <<FLOAT>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 200 )
              )
            )
            ( |speechcode|
              (
                ( TYPE> <<PREDICATE>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 183 )
              )
            )
            ( |newvar|
              (
                ( TYPE> <<MATRIX>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 200 )
              )
            )
          )
        )
        ( SPREADSHEET-VARIABLE-DEFINITIONS>
          (
            ( |sys.var|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<PARAM>| |FR| )
                      ( |<SUBSYS>| |A| )
                      ( |<VAL>| 5 )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 1320 )
                      ( |<PARAM>| |<PARAM>| )
                      ( |<SUBSYS>| |<SUBSYS>| )
                      ( |<VAL>| |<VAL>| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 1320 )
                      ( |<PARAM>| |T| )
                      ( |<SUBSYS>| |A| )
                      ( |<VAL>| 3 )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 1440 )
                      ( |<PARAM>| |V| )
                      ( |<SUBSYS>| |A| )
                      ( |<VAL>| 22 )
                    )
                    (
                      ( ONSET> 660 )
                      ( OFFSET> 540 )
                      ( |<PARAM>| |FR| )
                      ( |<SUBSYS>| |A| )
                      ( |<VAL>| 6 )
                    )
                    (
                      ( ONSET> 1320 )
                      ( OFFSET> 1500 )
                      ( |<PARAM>| |V| )
                      ( |<SUBSYS>| |A| )
                      ( |<VAL>| 23 )
                    )
                    (
                      ( ONSET> 1440 )
                      ( OFFSET> 1680 )
                      ( |<PARAM>| |FR| )
                      ( |<SUBSYS>| |A| )
                      ( |<VAL>| 5 )
                    )
                    (
                      ( ONSET> 1500 )
                      ( OFFSET> 1860 )
                      ( |<PARAM>| |V| )
                      ( |<SUBSYS>| |A| )
                      ( |<VAL>| 24 )
                    )
                    (
                      ( ONSET> 1680 )
                      ( OFFSET> 1920 )
                      ( |<PARAM>| |FR| )
                      ( |<SUBSYS>| |A| )
                      ( |<VAL>| 4 )
                    )
                    (
                      ( ONSET> 1860 )
                      ( OFFSET> 1980 )
                      ( |<PARAM>| |V| )
                      ( |<SUBSYS>| |A| )
                      ( |<VAL>| 25 )
                    )
                    (
                      ( ONSET> 1920 )
                      ( OFFSET> 2760 )
                      ( |<PARAM>| |V| )
                      ( |<SUBSYS>| |A| )
                      ( |<VAL>| 26 )
                    )
                    (
                      ( ONSET> 1980 )
                      ( OFFSET> 2040 )
                      ( |<PARAM>| |V| )
                      ( |<SUBSYS>| |A| )
                      ( |<VAL>| 25 )
                    )
                    (
                      ( ONSET> 2280 )
                      ( OFFSET> 2400 )
                      ( |<PARAM>| |FR| )
                      ( |<SUBSYS>| |A| )
                      ( |<VAL>| 5 )
                    )
                    (
                      ( ONSET> 2700 )
                      ( OFFSET> 2880 )
                      ( |<PARAM>| |T| )
                      ( |<SUBSYS>| |A| )
                      ( |<VAL>| 24 )
                    )
                    (
                      ( ONSET> 2760 )
                      ( OFFSET> 2820 )
                      ( |<PARAM>| |FR| )
                      ( |<SUBSYS>| |A| )
                      ( |<VAL>| 6 )
                    )
                    (
                      ( ONSET> 2760 )
                      ( OFFSET> 2820 )
                      ( |<PARAM>| |FR| )
                      ( |<SUBSYS>| |A| )
                      ( |<VAL>| 5 )
                    )
                    (
                      ( ONSET> 2880 )
                      ( OFFSET> 3000 )
                      ( |<PARAM>| |T| )
                      ( |<SUBSYS>| |A| )
                      ( |<VAL>| 25 )
                    )
                    (
                      ( ONSET> 2880 )
                      ( OFFSET> 3000 )
                      ( |<PARAM>| |FR| )
                      ( |<SUBSYS>| |A| )
                      ( |<VAL>| 4 )
                    )
                    (
                      ( ONSET> 3000 )
                      ( OFFSET> 3120 )
                      ( |<PARAM>| |FR| )
                      ( |<SUBSYS>| |A| )
                      ( |<VAL>| 3 )
                    )
                    (
                      ( ONSET> 3300 )
                      ( OFFSET> 3480 )
                      ( |<PARAM>| |T| )
                      ( |<SUBSYS>| |A| )
                      ( |<VAL>| 26 )
                    )
                  )
                )
                ( VOCAB> ( ) )
              )
            )
            ( |state.var|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<PARAM>| |M| )
                      ( |<SUBSYS>| |L| )
                      ( |<VAL>| 5 )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<PARAM>| |I| )
                      ( |<SUBSYS>| |A| )
                      ( |<VAL>| |<VAL>| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<PARAM>| |<PARAM>| )
                      ( |<SUBSYS>| |<SUBSYS>| )
                      ( |<VAL>| 1 )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<PARAM>| |<PARAM>| )
                      ( |<SUBSYS>| |<SUBSYS>| )
                      ( |<VAL>| |<VAL>| )
                    )
                    (
                      ( ONSET> 420 )
                      ( OFFSET> 540 )
                      ( |<PARAM>| |H| )
                      ( |<SUBSYS>| |A| )
                      ( |<VAL>| 9 )
                    )
                    (
                      ( ONSET> 796 )
                      ( OFFSET> 2520 )
                      ( |<PARAM>| |M| )
                      ( |<SUBSYS>| |L| )
                      ( |<VAL>| 8 )
                    )
                    (
                      ( ONSET> 1140 )
                      ( OFFSET> 1260 )
                      ( |<PARAM>| |O| )
                      ( |<SUBSYS>| |A| )
                      ( |<VAL>| 8 )
                    )
                    (
                      ( ONSET> 1260 )
                      ( OFFSET> 1380 )
                      ( |<PARAM>| |I| )
                      ( |<SUBSYS>| |A| )
                      ( |<VAL>| 8 )
                    )
                    (
                      ( ONSET> 1800 )
                      ( OFFSET> 1920 )
                      ( |<PARAM>| |H| )
                      ( |<SUBSYS>| |A| )
                      ( |<VAL>| 9 )
                    )
                  )
                )
                ( VOCAB> ( ) )
              )
            )
            ( |verbal|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 131 )
                      ( OFFSET> 540 )
                      ( |<val>| "Sam:  Tomr: Please try to increase tempeture, increase volume and increase , you cando the hydraulic side and I'll do the heat side.Tom:  If you like.Sam:  I'll set heater up to 8 for now.Tom:  OK.  First to increase flowrate I'm going to open the input valve a bit more and open up the output valve.Sam:  OK, volume is starting to increase...Sam:  ...and so is flow rate.Sam:  Nothing happening so far on temperature...Sam:  ...so I'll send it up to 9.Sam:  You haven't done anything to the mixer value and volume is going up pretty fast." )
                    )
                    (
                      ( ONSET> 581 )
                      ( OFFSET> 2220 )
                      ( |<val>| "Tom:  Oh sorry...I always forget that!" )
                    )
                    (
                      ( ONSET> 681 )
                      ( OFFSET> 2400 )
                      ( |<val>| "Tom:  I wonder why the flow rate is decreasing?" )
                    )
                    (
                      ( ONSET> 796 )
                      ( OFFSET> 2520 )
                      ( |<val>| "Tom:  I increased input and output so flow rate should increase." )
                    )
                    (
                      ( ONSET> 2580 )
                      ( OFFSET> 2700 )
                      ( |<val>| "Tom:  Oh!  It's because I forgot to open the mixer valve." )
                    )
                    (
                      ( ONSET> 2700 )
                      ( OFFSET> 2880 )
                      ( |<val>| "Tom:  So flow rate should increase in a minute or two." )
                    )
                    (
                      ( ONSET> 2760 )
                      ( OFFSET> 2820 )
                      ( |<val>| "Sam:  There the temperature goes!" )
                    )
                    (
                      ( ONSET> 2880 )
                      ( OFFSET> 3000 )
                      ( |<val>| "Tom:  ...and that's what it's doing." )
                    )
                    (
                      ( ONSET> 3000 )
                      ( OFFSET> 3120 )
                      ( |<val>| "Tom:  Oh hell!  It's going down again." )
                    )
                    (
                      ( ONSET> 3120 )
                      ( OFFSET> 3180 )
                      ( |<val>| "Tom:  So I'll open the output a bit." )
                    )
                    (
                      ( ONSET> 3300 )
                      ( OFFSET> 3480 )
                      ( |<val>| "Sam:  Why don't you let it settle rather than keeping on playing with it?" )
                    )
                    (
                      ( ONSET> 3540 )
                      ( OFFSET> 3840 )
                      ( |<val>| "Tom:  Oh well...I don't think I play with it too much." )
                    )
                    (
                      ( ONSET> 3840 )
                      ( OFFSET> 3960 )
                      ( |<val>| "Sam:  You o, you know." )
                    )
                    (
                      ( ONSET> 4200 )
                      ( OFFSET> 4320 )
                      ( |<val>| "Sam:  Temperature's still rising." )
                    )
                    (
                      ( ONSET> 4500 )
                      ( OFFSET> 4680 )
                      ( |<val>| "Tom:  You've confused me about the flowrate now, Sam!" )
                    )
                  )
                )
              )
            )
            ( |Mola|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 2760 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 2760 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 420 )
                      ( OFFSET> 540 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 420 )
                      ( OFFSET> 540 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 420 )
                      ( OFFSET> 540 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 420 )
                      ( OFFSET> 540 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 420 )
                      ( OFFSET> 540 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 600 )
                      ( OFFSET> 660 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 660 )
                      ( OFFSET> 780 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 780 )
                      ( OFFSET> 1260 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 1260 )
                      ( OFFSET> 1440 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 1440 )
                      ( OFFSET> 1560 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 1680 )
                      ( OFFSET> 1800 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 1800 )
                      ( OFFSET> 1860 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 1920 )
                      ( OFFSET> 2040 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 2160 )
                      ( OFFSET> 2220 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 2280 )
                      ( OFFSET> 2400 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 2460 )
                      ( OFFSET> 2520 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 2580 )
                      ( OFFSET> 2700 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 2700 )
                      ( OFFSET> 2880 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 2760 )
                      ( OFFSET> 2820 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 2880 )
                      ( OFFSET> 3000 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 3000 )
                      ( OFFSET> 3120 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 3120 )
                      ( OFFSET> 3180 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 3300 )
                      ( OFFSET> 3480 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 3540 )
                      ( OFFSET> 3840 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 3540 )
                      ( OFFSET> 3840 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 3540 )
                      ( OFFSET> 3840 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 3840 )
                      ( OFFSET> 3960 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 4200 )
                      ( OFFSET> 4320 )
                      ( |<val>| 0.000000 )
                    )
                    (
                      ( ONSET> 4500 )
                      ( OFFSET> 4680 )
                      ( |<val>| 0.000000 )
                    )
                  )
                )
              )
            )
            ( |speechcode|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 45 )
                      ( OFFSET> 360 )
                      ( |<val>| ( |GOAL| |+| |+| |+| ) )
                    )
                    (
                      ( ONSET> 100 )
                      ( OFFSET> 540 )
                      ( |<val>| () )
                    )
                    (
                      ( ONSET> 131 )
                      ( OFFSET> 540 )
                      ( |<val>| ( |ANNOUNCE| |Sam| 0 ) )
                    )
                    (
                      ( ONSET> 158 )
                      ( OFFSET> 1260 )
                      ( |<val>| ( |ANNOUNCE| |Tom| 0 ) )
                    )
                    (
                      ( ONSET> 210 )
                      ( OFFSET> 540 )
                      ( |<val>| () )
                    )
                    (
                      ( ONSET> 286 )
                      ( OFFSET> 1440 )
                      ( |<val>| ( |OBSERVE| |Sam| 0 ) )
                    )
                    (
                      ( ONSET> 387 )
                      ( OFFSET> 1560 )
                      ( |<val>| ( |OBSERVE| |Sam| 0 ) )
                    )
                    (
                      ( ONSET> 445 )
                      ( OFFSET> 1800 )
                      ( |<val>| ( |OBSERVE| |Sam| 0 ) )
                    )
                    (
                      ( ONSET> 496 )
                      ( OFFSET> 1860 )
                      ( |<val>| ( |ANNOUNCE| |Sam| 0 ) )
                    )
                    (
                      ( ONSET> 530 )
                      ( OFFSET> 2040 )
                      ( |<val>| ( |COMMAND| |Sam| |Tom| -1 ) )
                    )
                    (
                      ( ONSET> 581 )
                      ( OFFSET> 2220 )
                      ( |<val>| ( |ACKNOWL| |Tom| |Sam| -1 ) )
                    )
                    (
                      ( ONSET> 681 )
                      ( OFFSET> 2400 )
                      ( |<val>| ( |OBSERVE| |Tom| -1 ) )
                    )
                    (
                      ( ONSET> 796 )
                      ( OFFSET> 2520 )
                      ( |<val>| ( |REASON| |Tom| 0 ) )
                    )
                    (
                      ( ONSET> 2580 )
                      ( OFFSET> 2700 )
                      ( |<val>| ( |REASON| |Tom| 0 ) )
                    )
                    (
                      ( ONSET> 2700 )
                      ( OFFSET> 2880 )
                      ( |<val>| ( |PREDICT| |Tom| 0 ) )
                    )
                    (
                      ( ONSET> 2760 )
                      ( OFFSET> 2820 )
                      ( |<val>| ( |OBSERVE| |Sam| 0 ) )
                    )
                    (
                      ( ONSET> 2880 )
                      ( OFFSET> 3000 )
                      ( |<val>| ( |OBSERVE| |Tom| 0 ) )
                    )
                    (
                      ( ONSET> 3000 )
                      ( OFFSET> 3120 )
                      ( |<val>| ( |OBSERVE| |Tom| |+1| ) )
                    )
                    (
                      ( ONSET> 3120 )
                      ( OFFSET> 3180 )
                      ( |<val>| ( |ANNOUNCE| |Tom| 0 ) )
                    )
                    (
                      ( ONSET> 3300 )
                      ( OFFSET> 3480 )
                      ( |<val>| ( |COMMAND| |Sam| |Tom| |+1| ) )
                    )
                    (
                      ( ONSET> 3540 )
                      ( OFFSET> 3840 )
                      ( |<val>| ( |ACKNOWL| |Tom| |Sam| -1 ) )
                    )
                    (
                      ( ONSET> 3840 )
                      ( OFFSET> 3960 )
                      ( |<val>| ( |ACKNOWL| |Sam| |Tom| |+1| ) )
                    )
                    (
                      ( ONSET> 4200 )
                      ( OFFSET> 4320 )
                      ( |<val>| ( |OBSERVE| |Sam| 0 ) )
                    )
                    (
                      ( ONSET> 4500 )
                      ( OFFSET> 4680 )
                      ( |<val>| ( |ACKNOWL| |Tom| |Sam| |+1| ) )
                    )
                  )
                )
                ( VOCAB> ( |ACKNOWL| |ANNOUNCE| |COMMAND| |GOAL| |OBSERVE| |PREDICT| |REASON| ) )
              )
            )
            ( |newvar|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |<val>| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 1320 )
                      ( |<val>| 42 )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 1320 )
                      ( |<val>| |<val>| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 1440 )
                      ( |<val>| 10 )
                    )
                    (
                      ( ONSET> 660 )
                      ( OFFSET> 540 )
                      ( |<val>| 6 )
                    )
                    (
                      ( ONSET> 1320 )
                      ( OFFSET> 1500 )
                      ( |<val>| 44 )
                    )
                    (
                      ( ONSET> 1440 )
                      ( OFFSET> 1680 )
                      ( |<val>| 12 )
                    )
                    (
                      ( ONSET> 1500 )
                      ( OFFSET> 1860 )
                      ( |<val>| 46 )
                    )
                    (
                      ( ONSET> 1680 )
                      ( OFFSET> 1920 )
                      ( |<val>| 10 )
                    )
                    (
                      ( ONSET> 1860 )
                      ( OFFSET> 1980 )
                      ( |<val>| 48 )
                    )
                    (
                      ( ONSET> 1920 )
                      ( OFFSET> 2760 )
                      ( |<val>| 8 )
                    )
                    (
                      ( ONSET> 1980 )
                      ( OFFSET> 2040 )
                      ( |<val>| 50 )
                    )
                    (
                      ( ONSET> 2280 )
                      ( OFFSET> 2400 )
                      ( |<val>| 52 )
                    )
                    (
                      ( ONSET> 2700 )
                      ( OFFSET> 2880 )
                      ( |<val>| 50 )
                    )
                    (
                      ( ONSET> 2760 )
                      ( OFFSET> 2820 )
                      ( |<val>| 10 )
                    )
                    (
                      ( ONSET> 2760 )
                      ( OFFSET> 2820 )
                      ( |<val>| 48 )
                    )
                    (
                      ( ONSET> 2880 )
                      ( OFFSET> 3000 )
                      ( |<val>| 12 )
                    )
                    (
                      ( ONSET> 2880 )
                      ( OFFSET> 3000 )
                      ( |<val>| 10 )
                    )
                    (
                      ( ONSET> 3000 )
                      ( OFFSET> 3120 )
                      ( |<val>| 50 )
                    )
                    (
                      ( ONSET> 3300 )
                      ( OFFSET> 3480 )
                      ( |<val>| 8 )
                    )
                    (
                      ( ONSET> 3840 )
                      ( OFFSET> 3960 )
                      ( |<val>| 6 )
                    )
                    (
                      ( ONSET> 4200 )
                      ( OFFSET> 4320 )
                      ( |<val>| 52 )
                    )
                  )
                )
                ( VOCAB> ( ) )
              )
            )
          )
        )
      )
    )
    ( QUERY>
      (
        ( |query| ( |or| ( |and| ( |sys.var| |?ordsys| |?onsys| |?offsys| |V| |<SUBSYS>| |?a| ) ( |ge| |?a| 23 ) |state.| ( |le| |?onstate| |?offsys| ) ( |ge| |?onstate| |?onsys| ) ) ( |and| ( |sys.var| |?ordsys| |?onsys| |?offsys| |V| |<SUBSYS>| |?a| ) ( |ge| |?a| 23 ) ( |state.var| |?ordstate| |?onstate| |?offstate| |?b| |?c| |?d| ) ( |le| |?offstate| |?offsys| ) ( |ge| |?offstate| |?onsys| ) ) ) ( |print| |?ordsys| |?a| |?ordstate| |?b| |?c| |?d| ) ) 
        ( |query| ( |sys.var| |?ord| |?on| |?off| |<PARAM>| |<SUBSYS>| |?a| ) ( |insert| ( |newvar| |?ord| |?on| |?off| ( |times| |?a| 2 ) ) ) ) 
        ( |query| ( |and| ( |speechcode| |?ords| |?ons| |?offst| ( |OBSERVE| |Sam| |?mit| ) ) ( |sys.var| |?ordf| |?onf| |?offf| |FR| |<SUBSYS>| |<VAL>| ) ( |lt| |?ons| |?onf| ) ( |not| ( |and| ( |speechcode| |<ord>| |?ons2| |?offs2| ( |OBSERVE| |Sam| |<MITIGATION>| ) ) ( |gt| |?ons2| |?ons| ) ( |lt| |?ons2| |?onf| ) ) ) ) ( |print| |?ords| |?ordf| |?mit| ) ) 
        ( |query| ( |and| ( |sys.var| |?ord| |?on| |?off| |V| |<SUBSYS>| |?a| ) ) ( |insert| ( |newvar| |?ord| |?on| |?off| ( |times| 2 |<y>| ) ) ) ) 
        ( |query| ( |or| ( |and| ( |sys.var| |?ordv| |?onv| |?offv| |V| |<SUBSYS>| |?v| ) ( |state.var| |?ordh| |?onh| |?offh| |H| |<SUBSYS>| |<VAL>| ) ( |le| ( |minus| |?onh| ( TIME> 600 ) ) |?onv| ) ( |ge| ( |minus| |?onh| ( TIME> 300 ) ) |?onv| ) ) ( |and| ( |sys.var| |?ordv| |?onv| |?offv| |V| |<SUBSYS>| |?v| ) ( |state.var| |?ordh| |?onh| |?offh| |H| |<SUBSYS>| |<VAL>| ) ( |ge| ( |minus| |?onh| ( TIME> 300 ) ) |?offv| ) ( |le| ( |minus| |?onh| ( TIME> 600 ) ) |?offv| ) ) ( |and| ( |sys.var| |?ordv| |?onv| |?offv| |V| |<SUBSYS>| |?v| ) ( |state.var| |?ordh| |?onh| |?offh| |H| |<SUBSYS>| |<VAL>| ) ( |ge| ( |minus| |?onh| ( TIME> 600 ) ) |?onv| ) ( |le| ( |minus| |?onh| ( TIME> 300 ) ) |?offv| ) ) ) ( |print| |?ordh| |?ordv| |?v| ) ) 
        ( |query| ( |and| ( |sys.var| |?ordsys| |?onsys| |?offsys| |V| |<SUBSYS>| |?v| ) ( |state.var| |?ordstate| |?onstate| |?offstate| |H| |<SUBSYS>| |<VAL>| ) ( |ge| ( |minus| |?onstate| ( TIME> 300 ) ) |?onsys| ) ( |le| ( |minus| |?onstate| ( TIME> 300 ) ) |?offsys| ) ) ( |print| |?ordsys| |?ordstate| |?v| ) ) 
        ( |query| ( |and| ( |state.var| |?ordh| |?onh| |?offh| |H| |<SUBSYS>| |<VAL>| ) ( |sys.var| |?ordv| |?onv| |?offv| |V| |<SUBSYS>| |?v| ) ( |le| |?onv| ( |plus| |?onh| ( TIME> 300 ) ) ) ( |ge| |?offv| ( |plus| |?onh| ( TIME> 300 ) ) ) ) ( |print| |?ordh| |?ordv| |?v| ) ) 
        ( |query| ( |or| ( |and| ( |speechcode| |?ord| |?onset| |?offset| ( |COMMAND| |?sp| |<TO>| 0 ) ) ( |ge| |?onset| ( TIME> 600 ) ) ( |le| |?offset| ( TIME> 2400 ) ) ) ( |and| ( |speechcode| |?ord| |?onset| |?offset| ( |ACKNOWL| |?sp| |<TO>| 0 ) ) ( |ge| |?onset| ( TIME> 600 ) ) ( |le| |?offset| ( TIME> 2400 ) ) ) ( |and| ( |speechcode| |?ord| |?onset| |?offset| ( |ANNOUNCE| |?sp| 0 ) ) ( |ge| |?onset| ( TIME> 600 ) ) ( |le| |?offset| ( TIME> 2400 ) ) ) ( |and| ( |speechcode| |?ord| |?onset| |?offset| ( |OBSERVE| |?sp| 0 ) ) ( |ge| |?onset| ( TIME> 600 ) ) ( |le| |?offset| ( TIME> 2400 ) ) ) ( |and| ( |speechcode| |?ord| |?onset| |?offset| ( |REASON| |?sp| 0 ) ) ( |ge| |?onset| ( TIME> 600 ) ) ( |le| |?offset| ( TIME> 2400 ) ) ) ( |and| ( |speechcode| |?ord| |?onset| |?offset| ( |PREDICT| |?sp| 0 ) ) ( |ge| |?onset| ( TIME> 600 ) ) ( |le| |?offset| ( TIME> 2400 ) ) ) ) ( |print| |?ord| |?sp| ) ) 
        ( |query| ( |and| ( |speechcode| |?orda| |?ona| |?offa| ( |ANNOUNCE| |<SPEAKER>| 0 ) ) ( |speechcode| |?ordo| |?ono| |?offo| ( |OBSERVE| |<SPEAKER>| |<MITIGATION>| ) ) ( |gt| |?ono| |?offa| ) ( |not| ( |and| ( |speechcode| |<ord>| |?ono2| |?offo2| ( |OBSERVE| |<SPEAKER>| |<MITIGATION>| ) ) ( |ge| |?ono2| |?offa| ) ( |lt| |?ono2| |?ono| ) ) ) ) ( |print| |?orda| |?ordo| ) ) 
        ( |query| ( |and| ( |sys.var| |?ordsys| |?onsys| |?offsys| |V| |<SUBSYS>| |?a| ) ( |ge| |?a| 21 ) ( |state.var| |?ordstate| |?onstate| |<offset>| |?b| |?c| |?d| ) ( |ge| |?onstate| |?onsys| ) ( |le| |?onstate| |?offsys| ) ) ( |print| |?ordsys| |?a| |?ordstate| |?b| |?c| |?d| ) ) 
        ( |query| ( |or| ( |and| ( |sys.var| |?ordsys| |?onsys| |?offsys| |V| |<SUBSYS>| |?a| ) ( |ge| |?a| 23 ) ( |state.var| |?ordstate| |?onstate| |?offstate| |?b| |?c| |?d| ) ( |ge| |?onstate| |?onsys| ) ( |le| |?onstate| |?offsys| ) ) ( |and| ( |sys.var| |?ordsys| |?onsys| |?offsys| |V| |<SUBSYS>| |?a| ) ( |ge| |?a| 23 ) ( |state.var| |?ordstate| |?onstate| |?offstate| |?b| |?c| |?d| ) ( |le| |?offstate| |?offsys| ) ( |ge| |?offstate| |?onsys| ) ) ) ( |print| |?ordsys| |?a| |?ordstate| |?b| |?c| |?d| ) ) 
        ( |query| ( |and| ( |sys.var| |?ordsys| |?onsys| |?offsys| |V| |<SUBSYS>| |?v| ) ( |state.var| |?ordstate| |?onstate| |?offstate| |H| |<SUBSYS>| |<VAL>| ) ( |le| ( |minus| |?onstate| ( TIME> 300 ) ) |?offsys| ) ( |ge| ( |minus| |?onstate| ( TIME> 300 ) ) |?onsys| ) ) ( |print| |?ordsys| |?ordstate| |?v| ) ) 
        ( |query| ( |or| ( |speechcode| |<ord>| |<onset>| |<offset>| ( |COMMAND| |?sp| |<TO>| -1 ) ) ( |speechcode| |<ord>| |<onset>| |<offset>| ( |ACKNOWL| |?sp| |<TO>| -1 ) ) ( |speechcode| |<ord>| |<onset>| |<offset>| ( |ANNOUNCE| |?sp| -1 ) ) ( |speechcode| |<ord>| |<onset>| |<offset>| ( |OBSERVE| |?sp| -1 ) ) ( |speechcode| |<ord>| |<onset>| |<offset>| ( |REASON| |?sp| -1 ) ) ( |speechcode| |<ord>| |<onset>| |<offset>| ( |PREDICT| |?sp| -1 ) ) ) ( |print| |?sp| ) ) 
        ( |query| ( |and| ( |speechcode| |?eord| |?eon| |?eoff| |?b| ) ( |sys.var| |?sord| |?son| |?soff| |V| |<SUBSYS>| |?c| ) ( |le| |?c| 23 ) ( |ge| |?eon| |?son| ) ( |le| |?eon| |?soff| ) ) ( |print| |?eord| |?b| |?c| ) ) 
        ( |query| ( |or| ( |and| ( |sys.var| |?ordv| |?onv| |?offv| |V| |<SUBSYS>| |?val| ) ( |state.var| |?ordh| |?onh| |?offh| |H| |<SUBSYS>| |<VAL>| ) ( |ge| |?onv| ( |minus| |?onh| ( TIME> 600 ) ) ) ( |le| |?onv| ( |minus| |?onh| ( TIME> 300 ) ) ) ) ) ( |print| |?ordh| |?ordv| |?val| ) ) 
        ( |query| ( |or| ( |and| ( |sys.var| |?ordv| |?onv| |?offv| |V| |<SUBSYS>| |?val| ) ( |state.var| |?ordh| |?onh| |?offh| |H| |<SUBSYS>| |<VAL>| ) ( |ge| |?onv| ( |minus| |?onh| ( TIME> 600 ) ) ) ( |le| |?onv| ( |minus| |?onh| ( TIME> 300 ) ) ) ) ) ( |print| |?ordh| |?ordv| |?val| ) ) 
        ( |query| ( |sys.var| |?ord1| |?on1| |?off1| |V| |<SUBSYS>| |<VAL>| ) ( |print| |?ord1| |?on1| |?off1| ) ) 
      )
    )
    ( SYSTEM>
      (
        ( SHAPA-PANE-VARS>
          (
            |verbal|
            |speechcode|
            |state.var|
            |sys.var|
            |newvar|
          )
        )
      )
    )
  )
)
