; MacSHAPA Open Database
( setf macshapa-db
 '(
    ( HEADER>
      (
        ( NAME> "mtest.odb" )
        ( VERSION> 1 )
        ( DEBUG-LEVEL> 0 )
        ( MAX-ERRORS> 1 )
        ( MAX-WARNINGS> 1 )
      )
    )
    ( USER>
      (
        ( PREDICATE-DEFINITIONS>
          (
            ( |varnumargspred| ( ( VARIABLE-LENGTH> TRUE ) ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| |<arg3>| |<arg4>| |<arg5>| |<arg6>| ) ) ) )
            ( |pred2| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<var1>| |<var2>| |<var3>| ) ) ) )
            ( |pred1| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<var1>| |<var2>| ) ) ) )
          )
        )
        ( SPREADSHEET-VARIABLE-DECLARATIONS>
          (
            ( |predvar|
              (
                ( TYPE> <<PREDICATE>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 200 )
              )
            )
            ( |nomvar|
              (
                ( TYPE> <<NOMINAL>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 200 )
              )
            )
            ( |intvar|
              (
                ( TYPE> <<INTEGER>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 200 )
              )
            )
            ( |textvar|
              (
                ( TYPE> <<TEXT>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 200 )
              )
            )
            ( |var_len_matrix|
              (
                ( TYPE> <<MATRIX>> )
                ( VARIABLE-LENGTH> TRUE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg1>| |<arg2>| |<arg3>| |<arg4>| |<arg5>| ) )
                ( COLUMN-WIDTH> 200 )
              )
            )
            ( |matrixvar|
              (
                ( TYPE> <<MATRIX>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg1>| |<arg2>| ) )
                ( COLUMN-WIDTH> 200 )
              )
            )
            ( |floatvar|
              (
                ( TYPE> <<FLOAT>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 200 )
              )
            )
          )
        )
        ( SPREADSHEET-VARIABLE-DEFINITIONS>
          (
            ( |predvar|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| ( |pred2| |<var1>| |<var2>| |<var3>| ) )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| ( |pred2| ( |pred1| 3 ( |pred2| |alpha| ( |pred1| |bravo| ( |pred1| ( |varnumargspred| 1 2 3 4 5 6 ) ( |pred1| |alpha| |bravo| ) ) ) ( |pred1| |charley| |foxtrot| ) ) ) ( |pred1| |echo| ( |pred1| |xray| ( |pred1| |zulu| |echo| ) ) ) ( |pred2| 1 2 ( |pred1| |golf| |india| ) ) ) )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| ( |pred1| 1 1.234560 ) )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| ( |pred2| |alpha| "Hello world  " |victor| ) )
                    )
                  )
                )
                ( VOCAB> ( |pred1| |pred2| |varnumargspred| ) )
              )
            )
            ( |nomvar|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |<val>| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |alpha| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |bravo| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |charley| )
                    )
                  )
                )
              )
            )
            ( |intvar|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| 10 )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| 20 )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| 30 )
                    )
                  )
                )
              )
            )
            ( |textvar|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| "Twas brillig and the slithey toves did gyre and gymbal in the wabe." )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| "All mimsey were the borrow groves and the momraths outgabe." )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| "Beware the Jabberwock my son. The jaws that bite!  The claws that catch!  Beware the JubJub bird and shun the frumious Bandersnatch." )
                    )
                  )
                )
              )
            )
            ( |var_len_matrix|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<arg1>| |one_arg| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<arg1>| |one_arg| )
                      ( |<arg2>| |two_arg| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<arg1>| |one_arg| )
                      ( |<arg2>| |two_arg| )
                      ( |<arg3>| |three_arg| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<arg1>| |one_arg| )
                      ( |<arg2>| |two_arg| )
                      ( |<arg3>| |three_arg| )
                      ( |<arg4>| |four_arg| )
                      ( |<arg5>| |five_arg| )
                    )
                  )
                )
                ( VOCAB> ( ) )
              )
            )
            ( |matrixvar|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<arg1>| |nominal?| )
                      ( |<arg2>| |or string?| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<arg1>| 3.141590 )
                      ( |<arg2>| |22skidoo| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<arg1>| |alpha| )
                      ( |<arg2>| |bravo| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<arg1>| |charley| )
                      ( |<arg2>| |delta| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<arg1>| ( |pred1| ( |pred2| |alpha| "Hello world" 3.141590 ) 6 ) )
                      ( |<arg2>| "Goodby world" )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<arg1>| ( |varnumargspred| |first_arg| |second_arg| ) )
                      ( |<arg2>| |<arg2>| )
                    )
                  )
                )
                ( VOCAB> ( |pred1| |pred2| |varnumargspred| ) )
              )
            )
            ( |floatvar|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| 10.000000 )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| 20.000000 )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| 30.000000 )
                    )
                  )
                )
              )
            )
          )
        )
      )
    )
    ( QUERY>
      (
      )
    )
    ( SYSTEM>
      (
        ( SHAPA-PANE-VARS>
          (
            |var_len_matrix|
            |predvar|
            |textvar|
            |matrixvar|
            |nomvar|
            |floatvar|
            |intvar|
          )
        )
      )
    )
  )
)
