; MacSHAPA Open Database
( setf macshapa-db
 '(
    ( HEADER>
      (
        ( NAME> "senso.1.odb" )
        ( VERSION> 1 )
        ( DEBUG-LEVEL> 0 )
        ( MAX-ERRORS> 1 )
        ( MAX-WARNINGS> 1 )
      )
    )
    ( USER>
      (
        ( PREDICATE-DEFINITIONS>
          (
          )
        )
        ( SPREADSHEET-VARIABLE-DECLARATIONS>
          (
            ( |senso|
              (
                ( TYPE> <<MATRIX>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<page>| |<action>| |<key>| |<value>| ) )
                ( COLUMN-WIDTH> 200 )
              )
            )
            ( |page|
              (
                ( TYPE> <<NOMINAL>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 200 )
              )
            )
            ( |txt|
              (
                ( TYPE> <<TEXT>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 200 )
              )
            )
            ( |senso1|
              (
                ( TYPE> <<MATRIX>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<action>| |<page>| |<key>| |<value>| ) )
                ( COLUMN-WIDTH> 200 )
              )
            )
          )
        )
        ( SPREADSHEET-VARIABLE-DEFINITIONS>
          (
            ( |senso|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 90 )
                      ( OFFSET> 118 )
                      ( |<page>| |p14| )
                      ( |<action>| |sp| )
                      ( |<key>| 2 )
                      ( |<value>| 10 )
                    )
                    (
                      ( ONSET> 145 )
                      ( OFFSET> 168 )
                      ( |<page>| |p14| )
                      ( |<action>| |sp| )
                      ( |<key>| 2 )
                      ( |<value>| 10.000000 )
                    )
                    (
                      ( ONSET> 190 )
                      ( OFFSET> 213 )
                      ( |<page>| |p14| )
                      ( |<action>| |sp| )
                      ( |<key>| 2 )
                      ( |<value>| |<value>| )
                    )
                    (
                      ( ONSET> 237 )
                      ( OFFSET> 260 )
                      ( |<page>| |ams| )
                      ( |<action>| |sp| )
                      ( |<key>| 2 )
                      ( |<value>| 1 )
                    )
                    (
                      ( ONSET> 284 )
                      ( OFFSET> 307 )
                      ( |<page>| |ams| )
                      ( |<action>| |sp| )
                      ( |<key>| 2 )
                      ( |<value>| 10 )
                    )
                    (
                      ( ONSET> 328 )
                      ( OFFSET> 352 )
                      ( |<page>| |ams| )
                      ( |<action>| |sp| )
                      ( |<key>| 2 )
                      ( |<value>| 10.000000 )
                    )
                    (
                      ( ONSET> 375 )
                      ( OFFSET> 399 )
                      ( |<page>| |ams| )
                      ( |<action>| |sp| )
                      ( |<key>| 2 )
                      ( |<value>| |<value>| )
                    )
                    (
                      ( ONSET> 422 )
                      ( OFFSET> 445 )
                      ( |<page>| |a23| )
                      ( |<action>| |sp| )
                      ( |<key>| 2 )
                      ( |<value>| 1 )
                    )
                    (
                      ( ONSET> 471 )
                      ( OFFSET> 494 )
                      ( |<page>| |a23| )
                      ( |<action>| |sp| )
                      ( |<key>| 2 )
                      ( |<value>| 10 )
                    )
                    (
                      ( ONSET> 518 )
                      ( OFFSET> 543 )
                      ( |<page>| |a23| )
                      ( |<action>| |sp| )
                      ( |<key>| 2 )
                      ( |<value>| 10.000000 )
                    )
                    (
                      ( ONSET> 567 )
                      ( OFFSET> 589 )
                      ( |<page>| |a23| )
                      ( |<action>| |sp| )
                      ( |<key>| 2 )
                      ( |<value>| 10.100000 )
                    )
                    (
                      ( ONSET> 612 )
                      ( OFFSET> 637 )
                      ( |<page>| |a23| )
                      ( |<action>| 8 )
                      ( |<key>| 2 )
                      ( |<value>| |<value>| )
                    )
                    (
                      ( ONSET> 662 )
                      ( OFFSET> 686 )
                      ( |<page>| |ams| )
                      ( |<action>| |sp| )
                      ( |<key>| 2 )
                      ( |<value>| 1 )
                    )
                    (
                      ( ONSET> 710 )
                      ( OFFSET> 734 )
                      ( |<page>| |ams| )
                      ( |<action>| |sp| )
                      ( |<key>| 2 )
                      ( |<value>| 10 )
                    )
                    (
                      ( ONSET> 758 )
                      ( OFFSET> 782 )
                      ( |<page>| |ams| )
                      ( |<action>| |sp| )
                      ( |<key>| 2 )
                      ( |<value>| 10.000000 )
                    )
                    (
                      ( ONSET> 806 )
                      ( OFFSET> 832 )
                      ( |<page>| |ams| )
                      ( |<action>| |sp| )
                      ( |<key>| 2 )
                      ( |<value>| 10.100000 )
                    )
                    (
                      ( ONSET> 855 )
                      ( OFFSET> 880 )
                      ( |<page>| |ams| )
                      ( |<action>| 8 )
                      ( |<key>| 2 )
                      ( |<value>| |<value>| )
                    )
                  )
                )
                ( VOCAB> ( ) )
              )
            )
            ( |page|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |<val>| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |<val>| )
                    )
                    (
                      ( ONSET> 90 )
                      ( OFFSET> 399 )
                      ( |<val>| |ams| )
                    )
                    (
                      ( ONSET> 422 )
                      ( OFFSET> 637 )
                      ( |<val>| |a23| )
                    )
                    (
                      ( ONSET> 662 )
                      ( OFFSET> 880 )
                      ( |<val>| |ams| )
                    )
                  )
                )
              )
            )
            ( |txt|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| "" )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| "hello world" )
                    )
                  )
                )
              )
            )
            ( |senso1|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<action>| |sp| )
                      ( |<page>| |ams| )
                      ( |<key>| 2 )
                      ( |<value>| 1 )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<action>| |sp| )
                      ( |<page>| |ams| )
                      ( |<key>| 2 )
                      ( |<value>| 10 )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<action>| |sp| )
                      ( |<page>| |ams| )
                      ( |<key>| 2 )
                      ( |<value>| 10.000000 )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<action>| |sp| )
                      ( |<page>| |ams| )
                      ( |<key>| 2 )
                      ( |<value>| 10.100000 )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<action>| 8 )
                      ( |<page>| |ams| )
                      ( |<key>| 2 )
                      ( |<value>| |<value>| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<action>| |sp| )
                      ( |<page>| |ams| )
                      ( |<key>| 2 )
                      ( |<value>| 1 )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<action>| |sp| )
                      ( |<page>| |ams| )
                      ( |<key>| 2 )
                      ( |<value>| 10 )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<action>| |sp| )
                      ( |<page>| |ams| )
                      ( |<key>| 2 )
                      ( |<value>| 10.000000 )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<action>| |sp| )
                      ( |<page>| |ams| )
                      ( |<key>| 2 )
                      ( |<value>| 10.100000 )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<action>| 8 )
                      ( |<page>| |ams| )
                      ( |<key>| 2 )
                      ( |<value>| |<value>| )
                    )
                  )
                )
                ( VOCAB> ( ) )
              )
            )
          )
        )
      )
    )
    ( QUERY>
      (
        ( |query| ( |and| ( |senso| |?ord| |<onset>| |<offset>| |?p| |sp| |?k| |?val| ) ( |senso| ( |plus| |?ord| 1 ) |<onset>| |<offset>| |?p| 8 |<key>| |<value>| ) ) ( |print| |Page=| |?p| |Key=| |?k| |value=| |?val| ) ) 
        ( |query| ( |not| ( |nexto| ( |senso| |?old| |<onset>| |<offset>| |?p| |<action>| |<key>| |<value>| ) ( |senso| |?new| |<onset>| |<offset>| |?p| |<action>| |<key>| |<value>| ) ) ) ( |print| |?oldoff| |?newon| ) ) 
        ( |query| ( |and| ( |senso| |?old| |<onset>| |<offset>| |?p| |<action>| |<key>| |<value>| ) ( |senso| |?new| |<onset>| |<offset>| |?p| |<action>| |<key>| |<value>| ) ( |not| ( |nexto| ( |senso| |?old| |<onset>| |<offset>| |?p| |<action>| |<key>| |<value>| ) ( |senso| |?new| |<onset>| |<offset>| |?p| |<action>| |<key>| |<value>| ) ) ) ) ( |print| |?old| |?new| ) ) 
        ( |query| ( |and| ( |nexto| ( |senso| |?1| |<onset>| |<offset>| |?p1| |<action>| |<key>| |<value>| ) ( |senso| |?2| |<onset>| |<offset>| |?p2| |<action>| |<key>| |<value>| ) ) ( |ne| |?p1| |?p2| ) ) ( |print| |?1| |?2| ) ) 
        ( |query| ( |and| ( |senso| |?1| |<onset>| |<offset>| |?p1| |<action>| |<key>| |<value>| ) ( |senso| ( |plus| |?1| 1 ) |?on| |<offset>| |?p2| |<action>| |<key>| |<value>| ) ( |ne| |?p1| |?p2| ) ) ( |print| |?on| |?p2| ) ) 
        ( |query| ( |and| ( |senso| |?1| |<onset>| |<offset>| |?p1| |<action>| |<key>| |<value>| ) ( |senso| ( |plus| |?1| 1 ) |?on2| |<offset>| |?p2| |<action>| |<key>| |<value>| ) ( |ne| |?p1| |?p2| ) ) ( |insert| ( |page| |<ord>| |?on2| |<offset>| |?p2| ) ) ) 
        ( |query| ( |and| ( |senso| |?1| |<onset>| |<offset>| |?p1| |<action>| |<key>| |<value>| ) ( |senso| ( |plus| |?1| 1 ) |?on2| |<offset>| |?p2| |<action>| |<key>| |<value>| ) ( |ne| |?p1| |?p2| ) ) ( |modify| ( |page| |<ord>| |<onset>| |<offset>| |<val>| ) ) ) 
        ( |query| ( |and| ( |senso| |?1| |<onset>| |<offset>| |?p1| |<action>| |<key>| |<value>| ) ( |senso| ( |minus| |?1| 1 ) |?on2| |<offset>| |?p2| |<action>| |<key>| |<value>| ) ( |ne| |?p1| |?p2| ) ) |<action>| ) 
        ( |query| ( |senso| |<ord>| |<onset>| |<offset>| |ams| |?action| 2 |?value| ) ( |print| |While on asps mode select and doing enter key--action is| |?action| |with value| |?value| ) ) 
        ( |query| ( |and| ( |senso| |?ord| |<onset>| |?off| |?p| |<action>| |<key>| |?cal| ) ( |senso| ( |plus| |?ord| 1 ) |?on| |<offset>| |?p2| |<action>| |<key>| |<value>| ) ( |ne| |?p| |?p2| ) ( |page| |?pord| |?on| |<offset>| |<val>| ) ) ( |print| ( |minus| |?pord| 1 ) |?off| ) ) 
        ( |query| ( |and| ( |senso| |?ord| |<onset>| |?off| |?p| |<action>| |<key>| |?cal| ) ( |senso| ( |plus| |?ord| 1 ) |?on| |<offset>| |?p2| |<action>| |<key>| |<value>| ) ( |ne| |?p| |?p2| ) ( |page| |?pord| |?on| |<offset>| |<val>| ) ) ( |modify| ( |page| ( |minus| |?pord| 1 ) |<onset>| |?off| |<val>| ) ) ) 
        ( |query| ( |senso| |<ord>| |<onset>| |<offset>| |<page>| |<action>| |<key>| |?1| ) ( |cmin| |?1| ) ) 
        ( |query| ( |page| |<ord>| |<onset>| |<offset>| |?1| ) ( |cmin| |?1| ) ) 
        ( |query| ( |txt| |<ord>| |<onset>| |<offset>| |?val| ) ( |cmin| |?val| ) ) 
      )
    )
    ( SYSTEM>
      (
        ( SHAPA-PANE-VARS>
          (
            |senso1|
            |senso|
            |page|
            |txt|
          )
        )
      )
    )
  )
)
