; MacSHAPA Open Database
( setf macshapa-db
 '(
    ( HEADER>
      (
        ( NAME> "b&g.test.odb" )
        ( VERSION> 1 )
        ( DEBUG-LEVEL> 0 )
        ( MAX-ERRORS> 1 )
        ( MAX-WARNINGS> 1 )
      )
    )
    ( USER>
      (
        ( PREDICATE-DEFINITIONS>
          (
          )
        )
        ( SPREADSHEET-VARIABLE-DECLARATIONS>
          (
            ( |codes2|
              (
                ( TYPE> <<NOMINAL>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 200 )
              )
            )
          )
        )
        ( SPREADSHEET-VARIABLE-DEFINITIONS>
          (
            ( |codes2|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |U| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |S| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |U| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |S| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |U| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |S| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |U| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |S| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |U| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |S| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |U| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |S| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |S| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |S| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |S| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |S| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |S| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |S| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |S| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |S| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |S| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |S| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |S| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |S| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |S| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |G| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |S| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |G| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |S| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |G| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |S| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |G| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |S| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |G| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |G| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |G| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |G| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |G| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |G| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |G| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |G| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |G| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |G| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |G| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |G| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |G| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |G| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |G| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |G| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |G| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |G| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |G| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |G| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |G| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |U| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |U| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |U| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |U| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |U| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |T| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |U| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |U| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |P| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |U| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |G| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |U| )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| |G| )
                    )
                  )
                )
              )
            )
          )
        )
      )
    )
    ( QUERY>
      (
        ( |query| ( |codes2| |?o| |<onset>| |<offset>| |Q| ) ( |modify| ( |codes2| |?o| |<onset>| |<offset>| |G| ) ) ) 
      )
    )
    ( SYSTEM>
      (
        ( SHAPA-PANE-VARS>
          (
            |codes2|
          )
        )
      )
    )
  )
)
