; MacSHAPA Open Database
( setf macshapa-db
 '(
    ( HEADER>
      (
        ( NAME> "garbage1.odb" )
        ( VERSION> 1 )
        ( DEBUG-LEVEL> 0 )
        ( MAX-ERRORS> 1 )
        ( MAX-WARNINGS> 1 )
      )
    )
    ( USER>
      (
        ( PREDICATE-DEFINITIONS>
          (
          )
        )
        ( SPREADSHEET-VARIABLE-DECLARATIONS>
          (
            ( |a4|
              (
                ( TYPE> <<TEXT>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 200 )
              )
            )
            ( |a2|
              (
                ( TYPE> <<TEXT>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 200 )
              )
            )
          )
        )
        ( SPREADSHEET-VARIABLE-DEFINITIONS>
          (
            ( |a4|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| "" )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| "" )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| "" )
                    )
                  )
                )
              )
            )
            ( |a2|
              (
                ( CELLS>
                  (
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| "" )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| "" )
                    )
                    (
                      ( ONSET> 0 )
                      ( OFFSET> 0 )
                      ( |<val>| "" )
                    )
                  )
                )
              )
            )
          )
        )
      )
    )
    ( QUERY>
      (
        ( |query| ( |and| |<arg1>| ( |substring| "a" |?val| ) ) |<action>| ) 
        () 
      )
    )
    ( SYSTEM>
      (
        ( SHAPA-PANE-VARS>
          (
            |a2|
            |a4|
          )
        )
      )
    )
  )
)
