/*
 * QTVideoViewer.java
 *
 * Created on June 14, 2008, 10:02 PM
 */
package au.com.nicta.openshapa.cont;

import au.com.nicta.openshapa.Executive;
import java.io.File;

/**
 *
 * @author  FGA
 */
public class QTVideoViewer
        extends javax.swing.JPanel
        implements ContinuousDataViewer {

    /**
     * Constructor.
     *
     * Creates a new form of QTVideoViewer.
     *
     * @param exec
     * @param cont
     */
    public QTVideoViewer(Executive exec, ContinuousDataController cont)
    {
        initComponents();
    }
    
    public void setVideoFile(File videoFile)
    {
    }

    public void createNewCell(){}
    public void jogBack(){}
    public void stop(){}
    public void jogForward(){}
    public void shuttleBack(){}
    public void pause(){}
    public void shuttleForward(){}
    public void rewind(){}
    public void play()
    {
        System.out.println("Got Play Command");
    }
    public void forward(){}
    public void setCellOffset(){}
    public void find(){}
    public void goBack(){}
    public void setNewCellOnset(){}
    public void syncCtrl(){}
    public void sync(){}
    public void setCellOnset(){}

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
