#include "MpvErrorUtils.h"
#include "MediaPlayerErrors.h"

#define __STDC_CONSTANT_MACROS
#define inline __inline

#ifndef INT64_C
#define INT64_C(c) (c##LL)
#define UINT64_C(c) (c##ULL)
#endif

#include "MPV/client.h"

int MpvToJavaErrNo(int mpvErrNo) {
  switch (mpvErrNo) {
  case MPV_ERROR_SUCCESS:
    return ERROR_NONE;
  case MPV_ERROR_NOMEM:
    return ERROR_MPV_NOMEM;
  case MPV_ERROR_UNINITIALIZED:
    return ERROR_FFMPEG_AUDIO_FORMAT_CHANNELS_ID_NULL;
  case MPV_ERROR_INVALID_PARAMETER:
    return ERROR_MPV_INVALID_PARAMETER;
  case MPV_ERROR_OPTION_NOT_FOUND:
    return ERROR_MPV_OPTION_NOT_FOUND;
  case MPV_ERROR_OPTION_FORMAT:
    return ERROR_MPV_OPTION_FORMAT;
  case MPV_ERROR_OPTION_ERROR:
    return ERROR_MPV_OPTION_ERROR;
  case MPV_ERROR_PROPERTY_NOT_FOUND:
    return ERROR_MPV_PROPERTY_NOT_FOUND;
  case MPV_ERROR_PROPERTY_FORMAT:
    return ERROR_MPV_PROPERTY_FORMAT;
  case MPV_ERROR_PROPERTY_UNAVAILABLE:
    return ERROR_MPV_PROPERTY_UNAVAILABLE;
  case MPV_ERROR_PROPERTY_ERROR:
    return ERROR_MPV_PROPERTY_ERROR;
  case MPV_ERROR_COMMAND:
    return ERROR_MPV_COMMAND;
  case MPV_ERROR_LOADING_FAILED:
    return ERROR_MPV_LOADING_FAILED;
  case MPV_ERROR_AO_INIT_FAILED:
    return ERROR_MPV_AO_INIT_FAILED;
  case MPV_ERROR_VO_INIT_FAILED:
    return ERROR_MPV_VO_INIT_FAILED;
  case MPV_ERROR_NOTHING_TO_PLAY:
    return ERROR_MPV_NOTHING_TO_PLAY;
  case MPV_ERROR_UNKNOWN_FORMAT:
    return ERROR_MPV_UNKNOWN_FORMAT;
  case MPV_ERROR_UNSUPPORTED:
    return ERROR_MPV_UNSUPPORTED;
  case MPV_ERROR_NOT_IMPLEMENTED:
    return ERROR_MPV_NOT_IMPLEMENTED;
  case MPV_ERROR_GENERIC:
    return ERROR_MPV_GENERIC;
  }

  return ERROR_MPV_GENERIC;
}
