/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_datavyu_util_Utils */

#ifndef _Included_org_datavyu_util_Utils
#define _Included_org_datavyu_util_Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_datavyu_util_Utils
 * Method:    getHWnd
 * Signature: (Ljava/awt/Container;[J)I
 */
JNIEXPORT jint JNICALL Java_org_datavyu_util_Utils_getHWnd
  (JNIEnv *, jclass, jobject, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
