/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PlaySoundFromJNI_PlayerThread */

#ifndef _Included_PlaySoundFromJNI_PlayerThread
#define _Included_PlaySoundFromJNI_PlayerThread
#ifdef __cplusplus
extern "C" {
#endif
#undef PlaySoundFromJNI_PlayerThread_MIN_PRIORITY
#define PlaySoundFromJNI_PlayerThread_MIN_PRIORITY 1L
#undef PlaySoundFromJNI_PlayerThread_NORM_PRIORITY
#define PlaySoundFromJNI_PlayerThread_NORM_PRIORITY 5L
#undef PlaySoundFromJNI_PlayerThread_MAX_PRIORITY
#define PlaySoundFromJNI_PlayerThread_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
