/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_datavyu_plugins_ffmpegplayer_MediaPlayer1 */

#ifndef _Included_org_datavyu_plugins_ffmpegplayer_MediaPlayer1
#define _Included_org_datavyu_plugins_ffmpegplayer_MediaPlayer1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MediaPlayer1
 * Method:    open0
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljavax/sound/sampled/AudioFormat;)[I
 */
JNIEXPORT jintArray JNICALL Java_org_datavyu_plugins_ffmpegplayer_MediaPlayer1_open0
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MediaPlayer1
 * Method:    hasVideoStream0
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_datavyu_plugins_ffmpegplayer_MediaPlayer1_hasVideoStream0
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MediaPlayer1
 * Method:    hasAudioStream0
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_datavyu_plugins_ffmpegplayer_MediaPlayer1_hasAudioStream0
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MediaPlayer1
 * Method:    play0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_datavyu_plugins_ffmpegplayer_MediaPlayer1_play0
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MediaPlayer1
 * Method:    stop0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_datavyu_plugins_ffmpegplayer_MediaPlayer1_stop0
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MediaPlayer1
 * Method:    pause0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_datavyu_plugins_ffmpegplayer_MediaPlayer1_pause0
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MediaPlayer1
 * Method:    close0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_datavyu_plugins_ffmpegplayer_MediaPlayer1_close0
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MediaPlayer1
 * Method:    getImageBuffer0
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_datavyu_plugins_ffmpegplayer_MediaPlayer1_getImageBuffer0
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MediaPlayer1
 * Method:    loadNextImageFrame0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_datavyu_plugins_ffmpegplayer_MediaPlayer1_loadNextImageFrame0
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MediaPlayer1
 * Method:    getWidth0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_datavyu_plugins_ffmpegplayer_MediaPlayer1_getWidth0
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MediaPlayer1
 * Method:    getHeight0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_datavyu_plugins_ffmpegplayer_MediaPlayer1_getHeight0
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MediaPlayer1
 * Method:    getNumberOfColorChannels0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_datavyu_plugins_ffmpegplayer_MediaPlayer1_getNumberOfColorChannels0
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MediaPlayer1
 * Method:    getStartTime0
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_datavyu_plugins_ffmpegplayer_MediaPlayer1_getStartTime0
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MediaPlayer1
 * Method:    getEndTime0
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_datavyu_plugins_ffmpegplayer_MediaPlayer1_getEndTime0
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MediaPlayer1
 * Method:    getDuration0
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_datavyu_plugins_ffmpegplayer_MediaPlayer1_getDuration0
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MediaPlayer1
 * Method:    getCurrentTime0
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_datavyu_plugins_ffmpegplayer_MediaPlayer1_getCurrentTime0
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MediaPlayer1
 * Method:    getAverageFrameRate0
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_datavyu_plugins_ffmpegplayer_MediaPlayer1_getAverageFrameRate0
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MediaPlayer1
 * Method:    seek0
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_datavyu_plugins_ffmpegplayer_MediaPlayer1_seek0
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MediaPlayer1
 * Method:    setSpeed0
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_datavyu_plugins_ffmpegplayer_MediaPlayer1_setSpeed0
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MediaPlayer1
 * Method:    getAudioBuffer0
 * Signature: (II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_datavyu_plugins_ffmpegplayer_MediaPlayer1_getAudioBuffer0
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MediaPlayer1
 * Method:    loadNextAudioData0
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_datavyu_plugins_ffmpegplayer_MediaPlayer1_loadNextAudioData0
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MediaPlayer1
 * Method:    setAudioSyncDelay0
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_org_datavyu_plugins_ffmpegplayer_MediaPlayer1_setAudioSyncDelay0
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MediaPlayer1
 * Method:    getCodecName0
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_datavyu_plugins_ffmpegplayer_MediaPlayer1_getCodecName0
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MediaPlayer1
 * Method:    getSampleRate0
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_org_datavyu_plugins_ffmpegplayer_MediaPlayer1_getSampleRate0
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MediaPlayer1
 * Method:    getSampleSizeInBits0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_datavyu_plugins_ffmpegplayer_MediaPlayer1_getSampleSizeInBits0
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MediaPlayer1
 * Method:    getNumberOfSoundChannels0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_datavyu_plugins_ffmpegplayer_MediaPlayer1_getNumberOfSoundChannels0
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MediaPlayer1
 * Method:    getFrameSize0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_datavyu_plugins_ffmpegplayer_MediaPlayer1_getFrameSize0
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MediaPlayer1
 * Method:    getFrameRate0
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_org_datavyu_plugins_ffmpegplayer_MediaPlayer1_getFrameRate0
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
