/*
 * ColumnDataPanel.java
 *
 * Created on 26/11/2008, 2:21:02 PM
 */

package au.com.nicta.openshapa.views.discrete;

import au.com.nicta.openshapa.db.DataCell;
import au.com.nicta.openshapa.db.DataColumn;
import au.com.nicta.openshapa.db.SystemErrorException;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import org.apache.log4j.Logger;

/**
 * ColumnDataPanel panel that contains the SpreadsheetCell panels.
 * @author swhitcher
 */
public class ColumnDataPanel extends javax.swing.JPanel {

    /** Logger for this class. */
    private static Logger logger = Logger.getLogger(ColumnDataPanel.class);

    /** Creates new ColumnDataPanel panel. */
    public ColumnDataPanel() {
        initComponents();

        // keep a ref to a Box Layout Manager
        this.setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        this.setAlignmentY(TOP_ALIGNMENT);
        this.setBorder(BorderFactory.createLineBorder(Color.black));
    }

    /**
     * Creates new ColumnDataPanel panel.
     * @param dbColumn Database column to display.
     */
    public ColumnDataPanel(final DataColumn dbColumn) {
        this();

        updateComponents(dbColumn);
    }

    /**
     * updateComponents. Called when the SpreadsheetCell panels need to be
     * built and added to this Column panel.
     * @param dbColumn Database column to display.
     */
    private void updateComponents(final DataColumn dbColumn) {
        try {
            // TODO: getNumCells should be zero based. likewise getCell
            int numCells = dbColumn.getNumCells();
            // traverse and build the cells
            for (int j = 1; j <= numCells; j++) {
                DataCell dc = (DataCell) dbColumn.getDB()
                                    .getCell(dbColumn.getID(), j);

                SpreadsheetCell sc =
                                new SpreadsheetCell(dbColumn.getDB(), dc);
                sc.setSize(200,50);
                add(sc);
            }
        } catch (SystemErrorException e) {
           logger.error("Failed to populate Spreadsheet.", e);
        }
    }

    /**
     * Brute force rebuild of all cells in the Spreadsheet column.
     * @param dbColumn The column to display.
     */
    public final void rebuildAll(final DataColumn dbColumn) {
        removeAll();
        // would not work without setting the size to something
        // I guess after first building the panel with no cells
        // the size goes to 0 by 0 and never regrows after that
        setSize(200,1000);
        updateComponents(dbColumn);
        validate();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
