package org.openshapa.views.component;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.RenderingHints;
import java.awt.geom.GeneralPath;

import javax.swing.JComponent;

import org.openshapa.models.component.RegionModel;
import org.openshapa.models.component.ViewableModel;


/**
 * This class paints the custom playback region.
 */
public class RegionPainter extends JComponent {

    /** Auto-generated by Eclipse. */
    private static final long serialVersionUID = 3570489696805853386L;

    /** Polygon region for the start marker. */
    private GeneralPath startMarkerPolygon;

    /** Polygon region for the end marker. */
    private GeneralPath endMarkerPolygon;

    /** Region model. */
    private RegionModel regionModel;

    /** Viewable model. */
    private ViewableModel viewableModel;

    /**
     * @return The region model in use.
     */
    public final RegionModel getRegionModel() {
        return regionModel;
    }

    /**
     * @param newRegionModel The new region model to use.
     */
    public final void setRegionModel(final RegionModel newRegionModel) {
        regionModel = newRegionModel;
        repaint();
    }

    /**
     * @param newModel The new viewable model to use.
     */
    public final void setViewableModel(final ViewableModel newModel) {
        viewableModel = newModel;
        repaint();
    }

    /**
     * @return The polygon used to represent the end marker.
     */
    public final GeneralPath getEndMarkerPolygon() {
        return endMarkerPolygon;
    }

    /**
     * @return The polygon used to represent the start marker.
     */
    public final GeneralPath getStartMarkerPolygon() {
        return startMarkerPolygon;
    }

    @Override public final boolean contains(final Point p) {
        return startMarkerPolygon.contains(p) || endMarkerPolygon.contains(p);
    }

    @Override public final boolean contains(final int x, final int y) {
        return startMarkerPolygon != null && startMarkerPolygon.contains(x, y)
            || endMarkerPolygon != null && endMarkerPolygon.contains(x, y);
    }

    @Override public final void paint(final Graphics g) {
        if ((regionModel == null) || (viewableModel == null)) {
            return;
        }

        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        
        Dimension size = this.getSize();

        final float ratio = viewableModel.getIntervalWidth()
            / viewableModel.getIntervalTime();

        // If the left region marker is visible, paint the marker
        final long regionStart = regionModel.getRegionStart();
        final long regionEnd = regionModel.getRegionEnd();
        final int paddingTop = regionModel.getPaddingTop();

        final float paddingHorizontal = 1;
        final int markerHeight = 38;

        // If the left region marker is visible, paint the marker
        if (regionStart >= viewableModel.getZoomWindowStart()) {
            g2d.setColor(new Color(15, 135, 0, 100)); // Semi-transparent green

            // The polygon tip
            int pos = Math.round((regionModel.getRegionStart() * ratio)
                    - (viewableModel.getZoomWindowStart() * ratio))
                + regionModel.getPaddingLeft();

            // Make an arrow
            startMarkerPolygon = new GeneralPath();
            startMarkerPolygon.moveTo(pos - 10 - paddingHorizontal, paddingTop);
            startMarkerPolygon.lineTo(pos - paddingHorizontal, 19 + paddingTop - paddingHorizontal);
            startMarkerPolygon.lineTo(pos - paddingHorizontal, getSize().height);
            startMarkerPolygon.lineTo(pos - 10 - paddingHorizontal, getSize().height);
            startMarkerPolygon.closePath();
            g2d.fill(startMarkerPolygon);

            // Draw outline
            g2d.setColor(new Color(15, 135, 0));
            g2d.draw(startMarkerPolygon);

            // Draw drop down line
            GeneralPath line = new GeneralPath();
            line.moveTo(pos - paddingHorizontal, markerHeight);
            line.lineTo(pos - paddingHorizontal, markerHeight + size.height - 1);
            g2d.draw(line);
        } else {
        	startMarkerPolygon = new GeneralPath();
        }

        // If the right region marker is visible, paint the marker
        if ((viewableModel.getZoomWindowStart() <= regionEnd)
                && (regionEnd <= viewableModel.getZoomWindowEnd())) {
            g.setColor(new Color(15, 135, 0, 100)); // Semi-transparent green

            // The polygon tip
            int pos = Math.round((regionModel.getRegionEnd() * ratio)
                    - (viewableModel.getZoomWindowStart() * ratio))
                + regionModel.getPaddingLeft();
            endMarkerPolygon = new GeneralPath();
            endMarkerPolygon.moveTo(pos + paddingHorizontal, 19 + paddingTop);
            endMarkerPolygon.lineTo(pos + 10 + paddingHorizontal, paddingTop - paddingHorizontal);
            endMarkerPolygon.lineTo(pos + 10 + paddingHorizontal, getSize().height);
            endMarkerPolygon.lineTo(pos + paddingHorizontal, getSize().height);
            endMarkerPolygon.closePath();
            g2d.fill(endMarkerPolygon);

            // Draw outline
            g2d.setColor(new Color(15, 135, 0));
            g2d.draw(endMarkerPolygon);

            // Draw drop down line
            GeneralPath line = new GeneralPath();
            line.moveTo(pos + paddingHorizontal, markerHeight);
            line.lineTo(pos + paddingHorizontal, markerHeight + size.height - 1);
            g2d.draw(line);
        } else {
        	endMarkerPolygon = new GeneralPath();
        }

        /*
         * Check if the selected region is not the maximum viewing window, if it
         * is not the maximum, dim the unplayed regions.
         */
        if (regionStart > 0) {
            long endTimePos = viewableModel.getZoomWindowEnd();

            if (regionStart <= viewableModel.getZoomWindowEnd()) {
                endTimePos = regionStart;
            }

            long endXPos = Math.round((endTimePos * ratio)
                    - (viewableModel.getZoomWindowStart() * ratio))
                + regionModel.getPaddingLeft();

            int startPos = regionModel.getPaddingLeft();

            // Gray
            g.setColor(new Color(63, 63, 63, 100));
            g.fillRect(startPos, markerHeight + 1, (int) (endXPos - startPos - paddingHorizontal),
                size.height);
        }

        if (regionEnd < viewableModel.getZoomWindowEnd()) {
            long startTimePos = regionEnd;

            if (regionEnd > viewableModel.getZoomWindowEnd()) {
                startTimePos = viewableModel.getZoomWindowEnd();
            }

            if (startTimePos < viewableModel.getZoomWindowStart()) {
                startTimePos = viewableModel.getZoomWindowStart();
            }


            int startXPos = Math.round((startTimePos * ratio)
                    - (viewableModel.getZoomWindowStart() * ratio))
                + regionModel.getPaddingLeft();

            int endXPos = getSize().width - 21;

            g.setColor(new Color(63, 63, 63, 100));
            g.fillRect((int) (startXPos + paddingHorizontal + paddingHorizontal), markerHeight + 1, (int) (endXPos - startXPos - paddingHorizontal - paddingHorizontal),
                size.height);
        }

    }
}
