package org.openshapa.views.component;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;

import javax.swing.JComponent;

import org.openshapa.models.component.MixerView;
import org.openshapa.models.component.SnapMarkerModel;
import org.openshapa.models.component.Viewport;


/**
 * This class paints a timing needle.
 */
public final class SnapMarkerPainter extends JComponent {

    /**
     * Auto generated by Eclipse
     */
    private static final long serialVersionUID = -6157748998316240030L;

    private static final Color SNAP_MARKER_COLOR = new Color(169, 149, 202);

    private SnapMarkerModel snapMarkerModel;

    private MixerView mixer;

    public SnapMarkerPainter() {
        super();
    }

    public SnapMarkerModel getSnapMarkerModel() {
        return snapMarkerModel;
    }

    public void setSnapMarkerModel(final SnapMarkerModel snapMarkerModel) {
        this.snapMarkerModel = snapMarkerModel;
        repaint();
    }

    public void setMixerView(final MixerView mixer) {
        this.mixer = mixer;
        repaint();
    }

    @Override public void paintComponent(final Graphics g) {

        if ((snapMarkerModel == null) || (mixer == null)) {
            return;
        }

        Viewport viewport = mixer.getViewport();

        final long markerTime = snapMarkerModel.getMarkerTime();

        // Don't paint if the needle is out of the current window
        if (!viewport.isTimeInViewport(markerTime)) {
            return;
        }

        Dimension size = this.getSize();

        g.setColor(SNAP_MARKER_COLOR);

        // Calculate the needle position based on the selected time
        int pos = (int) viewport.computePixelXOffset(markerTime);

        // Draw the snap marker needle
        int x1 = pos;
        int y1 = 0;
        int x2 = pos + 1;
        int y2 = size.height;

        g.drawLine(x1, y1, x1, y2);
        g.drawLine(x2, y1, x2, y2);

    }

}
