/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DisplayImageFromJNI */

#ifndef _Included_DisplayImageFromJNI
#define _Included_DisplayImageFromJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef DisplayImageFromJNI_FOCUS_TRAVERSABLE_UNKNOWN
#define DisplayImageFromJNI_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef DisplayImageFromJNI_FOCUS_TRAVERSABLE_DEFAULT
#define DisplayImageFromJNI_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef DisplayImageFromJNI_FOCUS_TRAVERSABLE_SET
#define DisplayImageFromJNI_FOCUS_TRAVERSABLE_SET 2L
#undef DisplayImageFromJNI_TOP_ALIGNMENT
#define DisplayImageFromJNI_TOP_ALIGNMENT 0.0f
#undef DisplayImageFromJNI_CENTER_ALIGNMENT
#define DisplayImageFromJNI_CENTER_ALIGNMENT 0.5f
#undef DisplayImageFromJNI_BOTTOM_ALIGNMENT
#define DisplayImageFromJNI_BOTTOM_ALIGNMENT 1.0f
#undef DisplayImageFromJNI_LEFT_ALIGNMENT
#define DisplayImageFromJNI_LEFT_ALIGNMENT 0.0f
#undef DisplayImageFromJNI_RIGHT_ALIGNMENT
#define DisplayImageFromJNI_RIGHT_ALIGNMENT 1.0f
#undef DisplayImageFromJNI_serialVersionUID
#define DisplayImageFromJNI_serialVersionUID -7644114512714619750i64
#undef DisplayImageFromJNI_serialVersionUID
#define DisplayImageFromJNI_serialVersionUID -2284879212465893870i64
#undef DisplayImageFromJNI_serialVersionUID
#define DisplayImageFromJNI_serialVersionUID -1946946053851857166i64
/*
 * Class:     DisplayImageFromJNI
 * Method:    getByteBuffer
 * Signature: (III)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_DisplayImageFromJNI_getByteBuffer
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
