/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_datavyu_plugins_ffmpegplayer_MovieStream */

#ifndef _Included_org_datavyu_plugins_ffmpegplayer_MovieStream
#define _Included_org_datavyu_plugins_ffmpegplayer_MovieStream
#ifdef __cplusplus
extern "C" {
#endif
#undef org_datavyu_plugins_ffmpegplayer_MovieStream_MIN_SPEED
#define org_datavyu_plugins_ffmpegplayer_MovieStream_MIN_SPEED -4.0f
#undef org_datavyu_plugins_ffmpegplayer_MovieStream_MAX_SPEED
#define org_datavyu_plugins_ffmpegplayer_MovieStream_MAX_SPEED 4.0f
#undef org_datavyu_plugins_ffmpegplayer_MovieStream_AUDIO_BUFFER_SIZE
#define org_datavyu_plugins_ffmpegplayer_MovieStream_AUDIO_BUFFER_SIZE 65536L
/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    hasVideoStream
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_hasVideoStream
  (JNIEnv *, jobject);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    hasAudioStream
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_hasAudioStream
  (JNIEnv *, jobject);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    getStartTime0
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_getStartTime0
  (JNIEnv *, jobject);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    getEndTime0
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_getEndTime0
  (JNIEnv *, jobject);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    getDuration0
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_getDuration0
  (JNIEnv *, jobject);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    getCurrentTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_getCurrentTime
  (JNIEnv *, jobject);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    setTime0
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_setTime0
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    setPlaybackSpeed0
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_setPlaybackSpeed0
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_reset
  (JNIEnv *, jobject);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    close0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_close0
  (JNIEnv *, jobject);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    availableAudioData
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_availableAudioData
  (JNIEnv *, jobject);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    availableImageFrame
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_availableImageFrame
  (JNIEnv *, jobject);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    loadNextAudioData
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_loadNextAudioData
  (JNIEnv *, jobject);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    getAudioBuffer
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_getAudioBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    getSampleFormat
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_getSampleFormat
  (JNIEnv *, jobject);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    getCodecName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_getCodecName
  (JNIEnv *, jobject);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    getSampleRate
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_getSampleRate
  (JNIEnv *, jobject);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    getSampleSizeInBits
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_getSampleSizeInBits
  (JNIEnv *, jobject);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    getNumberOfSoundChannels
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_getNumberOfSoundChannels
  (JNIEnv *, jobject);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    getFrameSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_getFrameSize
  (JNIEnv *, jobject);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    getFrameRate
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_getFrameRate
  (JNIEnv *, jobject);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    bigEndian
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_bigEndian
  (JNIEnv *, jobject);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    setPlaySound
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_setPlaySound
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    open0
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljavax/sound/sampled/AudioFormat;)I
 */
JNIEXPORT jint JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_open0
  (JNIEnv *, jobject, jstring, jstring, jobject);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    getNumberOfColorChannels0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_getNumberOfColorChannels0
  (JNIEnv *, jobject);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    getHeight0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_getHeight0
  (JNIEnv *, jobject);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    getWidth0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_getWidth0
  (JNIEnv *, jobject);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    view
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_view
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    getFrameBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_getFrameBuffer
  (JNIEnv *, jobject);

/*
 * Class:     org_datavyu_plugins_ffmpegplayer_MovieStream
 * Method:    loadNextImageFrame
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_datavyu_plugins_ffmpegplayer_MovieStream_loadNextImageFrame
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
