/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PlaySoundTranscodedFromJNI_PlayerThread */

#ifndef _Included_PlaySoundTranscodedFromJNI_PlayerThread
#define _Included_PlaySoundTranscodedFromJNI_PlayerThread
#ifdef __cplusplus
extern "C" {
#endif
#undef PlaySoundTranscodedFromJNI_PlayerThread_MIN_PRIORITY
#define PlaySoundTranscodedFromJNI_PlayerThread_MIN_PRIORITY 1L
#undef PlaySoundTranscodedFromJNI_PlayerThread_NORM_PRIORITY
#define PlaySoundTranscodedFromJNI_PlayerThread_NORM_PRIORITY 5L
#undef PlaySoundTranscodedFromJNI_PlayerThread_MAX_PRIORITY
#define PlaySoundTranscodedFromJNI_PlayerThread_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
