/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PlayImageFromVideo */

#ifndef _Included_PlayImageFromVideo
#define _Included_PlayImageFromVideo
#ifdef __cplusplus
extern "C" {
#endif
#undef PlayImageFromVideo_serialVersionUID
#define PlayImageFromVideo_serialVersionUID -6199180436635445511i64
/*
 * Class:     PlayImageFromVideo
 * Method:    getFrameBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_PlayImageFromVideo_getFrameBuffer
  (JNIEnv *, jobject);

/*
 * Class:     PlayImageFromVideo
 * Method:    loadNextFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_PlayImageFromVideo_loadNextFrame
  (JNIEnv *, jobject);

/*
 * Class:     PlayImageFromVideo
 * Method:    loadMovie
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_PlayImageFromVideo_loadMovie
  (JNIEnv *, jobject, jstring);

/*
 * Class:     PlayImageFromVideo
 * Method:    getMovieHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_PlayImageFromVideo_getMovieHeight
  (JNIEnv *, jobject);

/*
 * Class:     PlayImageFromVideo
 * Method:    getMovieWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_PlayImageFromVideo_getMovieWidth
  (JNIEnv *, jobject);

/*
 * Class:     PlayImageFromVideo
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_PlayImageFromVideo_release
  (JNIEnv *, jobject);

/*
 * Class:     PlayImageFromVideo
 * Method:    setPlaybackSpeed
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_PlayImageFromVideo_setPlaybackSpeed
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     PlayImageFromVideo
 * Method:    setTime
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_PlayImageFromVideo_setTime
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
