/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PlaySoundTranscodedFromJNI */

#ifndef _Included_PlaySoundTranscodedFromJNI
#define _Included_PlaySoundTranscodedFromJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PlaySoundTranscodedFromJNI
 * Method:    getAudioBuffer
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_PlaySoundTranscodedFromJNI_getAudioBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     PlaySoundTranscodedFromJNI
 * Method:    loadNextFrame
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_PlaySoundTranscodedFromJNI_loadNextFrame
  (JNIEnv *, jobject);

/*
 * Class:     PlaySoundTranscodedFromJNI
 * Method:    loadAudio
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_PlaySoundTranscodedFromJNI_loadAudio
  (JNIEnv *, jobject, jstring);

/*
 * Class:     PlaySoundTranscodedFromJNI
 * Method:    getSampleFormat
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_PlaySoundTranscodedFromJNI_getSampleFormat
  (JNIEnv *, jobject);

/*
 * Class:     PlaySoundTranscodedFromJNI
 * Method:    getCodecName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_PlaySoundTranscodedFromJNI_getCodecName
  (JNIEnv *, jobject);

/*
 * Class:     PlaySoundTranscodedFromJNI
 * Method:    getSampleRate
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_PlaySoundTranscodedFromJNI_getSampleRate
  (JNIEnv *, jobject);

/*
 * Class:     PlaySoundTranscodedFromJNI
 * Method:    getSampleSizeInBits
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_PlaySoundTranscodedFromJNI_getSampleSizeInBits
  (JNIEnv *, jobject);

/*
 * Class:     PlaySoundTranscodedFromJNI
 * Method:    getNumberOfChannels
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_PlaySoundTranscodedFromJNI_getNumberOfChannels
  (JNIEnv *, jobject);

/*
 * Class:     PlaySoundTranscodedFromJNI
 * Method:    getFrameSizeInBy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_PlaySoundTranscodedFromJNI_getFrameSizeInBy
  (JNIEnv *, jobject);

/*
 * Class:     PlaySoundTranscodedFromJNI
 * Method:    getFramesPerSecond
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_PlaySoundTranscodedFromJNI_getFramesPerSecond
  (JNIEnv *, jobject);

/*
 * Class:     PlaySoundTranscodedFromJNI
 * Method:    bigEndian
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_PlaySoundTranscodedFromJNI_bigEndian
  (JNIEnv *, jobject);

/*
 * Class:     PlaySoundTranscodedFromJNI
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_PlaySoundTranscodedFromJNI_release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
