/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PlaySoundTranscodedFromJNI */

#ifndef _Included_PlaySoundTranscodedFromJNI
#define _Included_PlaySoundTranscodedFromJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PlaySoundTranscodedFromJNI
 * Method:    getAudioBuffer
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_PlaySoundTranscodedFromJNI_getAudioBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     PlaySoundTranscodedFromJNI
 * Method:    loadNextFrame
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_PlaySoundTranscodedFromJNI_loadNextFrame
  (JNIEnv *, jobject);

/*
 * Class:     PlaySoundTranscodedFromJNI
 * Method:    loadAudio
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_PlaySoundTranscodedFromJNI_loadAudio
  (JNIEnv *, jobject, jstring);

/*
 * Class:     PlaySoundTranscodedFromJNI
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_PlaySoundTranscodedFromJNI_release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
