/**
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.datavyu.views;

import java.awt.Color;
import javax.swing.GroupLayout;

import javax.swing.JLabel;

import org.jdesktop.application.Application;
import org.jdesktop.application.ResourceMap;


import org.datavyu.Build;
import org.datavyu.Datavyu;


public class AboutV extends DatavyuDialog {

    /** Creates new form AboutV */
    public AboutV(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setName(this.getClass().getSimpleName());

        BackgroundPanel p = new BackgroundPanel("/icons/splash.png");

        JLabel version = new JLabel();
        version.setForeground(new Color(119, 187, 33));

        ResourceMap bMap = Application.getInstance(Datavyu.class).getContext()
            .getResourceMap(Build.class);

        ResourceMap rMap = Application.getInstance(Datavyu.class).getContext()
            .getResourceMap(Datavyu.class);

        version.setText("<html>" + rMap.getString("Application.version")
            + "<br>" + bMap.getString("Application.build") + "</html>");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(
                GroupLayout.Alignment.LEADING).addGroup(GroupLayout.Alignment.TRAILING,
                layout.createSequentialGroup().addContainerGap(380,
                    Short.MAX_VALUE).addComponent(version).addGap(136, 136, 136)));
        layout.setVerticalGroup(layout.createParallelGroup(
                GroupLayout.Alignment.LEADING).addGroup(GroupLayout.Alignment.TRAILING,
                layout.createSequentialGroup().addContainerGap(250,
                    Short.MAX_VALUE).addComponent(version).addGap(38, 38, 38)));

        this.add(p);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.datavyu.Datavyu.class).getContext().getResourceMap(AboutV.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
