/**
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.datavyu.views;

import com.usermetrix.jclient.Logger;
import com.usermetrix.jclient.UserMetrix;
import org.datavyu.Datavyu;
import org.datavyu.controllers.NewProjectC;
import org.datavyu.models.db.Datastore;
import org.datavyu.models.db.DatastoreFactory;
import org.jdesktop.application.Application;
import org.jdesktop.application.ResourceMap;

import javax.swing.*;
import java.awt.*;


/**
 * The dialog for users to create a new project.
 */
public final class NewProjectV extends DatavyuDialog {

    /**
     * The logger for this class.
     */
    private static Logger LOGGER = UserMetrix.getLogger(NewProjectV.class);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextArea descriptionField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form NewDatabaseView.
     *
     * @param parent The parent of this JDialog.
     * @param modal  Is this dialog modal or not?
     */
    public NewProjectV(final Frame parent, final boolean modal) {
        super(parent, modal);
        LOGGER.event("newProj - show");
        initComponents();

        // Need to set a unique name so that we save and restore session data
        // i.e. window size, position, etc.
        setName(this.getClass().getSimpleName());
        getRootPane().setDefaultButton(okButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionField = new javax.swing.JTextArea();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        org.jdesktop.application.ResourceMap resourceMap =
                org.jdesktop.application.Application.getInstance(
                        org.datavyu.Datavyu.class).getContext().getResourceMap(
                        NewProjectV.class);
        setTitle(resourceMap.getString("Form.title")); 
        setName("Form"); 
        setResizable(false);

        jLabel1.setText(resourceMap.getString("jLabel1.text")); 
        jLabel1.setToolTipText(resourceMap.getString("jLabel1.toolTipText")); 
        jLabel1.setName("jLabel1"); 

        jLabel2.setText(resourceMap.getString("jLabel2.text")); 
        jLabel2.setToolTipText(resourceMap.getString("jLabel2.toolTipText")); 
        jLabel2.setName("jLabel2"); 

        nameField.setName("nameField"); 

        jScrollPane1.setName("jScrollPane1"); 

        descriptionField.setColumns(20);
        descriptionField.setFont(resourceMap.getFont("descriptionField.font")); 
        descriptionField.setRows(5);
        descriptionField.setName("descriptionField"); 
        jScrollPane1.setViewportView(descriptionField);

        cancelButton.setText(resourceMap.getString("cancelButton.text")); 
        cancelButton.setName("cancelButton"); 
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(
                    final java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setText(resourceMap.getString("okButton.text")); 
        okButton.setName("okButton"); 
        okButton.setPreferredSize(new java.awt.Dimension(65, 23));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(
                    final java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(
                GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addContainerGap().addGroup(
                        layout.createParallelGroup(
                                GroupLayout.Alignment.LEADING).addGroup(
                                layout.createSequentialGroup().addGroup(
                                        layout.createParallelGroup(
                                                GroupLayout.Alignment.LEADING).addComponent(
                                                jLabel2).addComponent(jLabel1)).addPreferredGap(
                                        LayoutStyle.ComponentPlacement.RELATED).addGroup(
                                        layout.createParallelGroup(
                                                GroupLayout.Alignment.TRAILING).addComponent(
                                                nameField, GroupLayout.DEFAULT_SIZE, 274,
                                                Short.MAX_VALUE).addComponent(jScrollPane1,
                                                GroupLayout.Alignment.TRAILING,
                                                GroupLayout.DEFAULT_SIZE, 274,
                                                Short.MAX_VALUE))).addGroup(
                                GroupLayout.Alignment.TRAILING,
                                layout.createSequentialGroup().addComponent(okButton,
                                        GroupLayout.PREFERRED_SIZE,
                                        GroupLayout.DEFAULT_SIZE,
                                        GroupLayout.PREFERRED_SIZE).addPreferredGap(
                                        LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cancelButton))).addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(
                GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addContainerGap().addGroup(
                        layout.createParallelGroup(
                                GroupLayout.Alignment.BASELINE).addComponent(
                                jLabel1).addComponent(nameField,
                                GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE)).addPreferredGap(
                        LayoutStyle.ComponentPlacement.RELATED).addGroup(
                        layout.createParallelGroup(
                                GroupLayout.Alignment.LEADING).addComponent(jLabel2)
                                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE,
                                        111, GroupLayout.PREFERRED_SIZE)).addPreferredGap(
                        LayoutStyle.ComponentPlacement.UNRELATED).addGroup(
                        layout.createParallelGroup(
                                GroupLayout.Alignment.BASELINE).addComponent(
                                cancelButton).addComponent(okButton,
                                GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE)).addContainerGap(
                        GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pack();
    } // </editor-fold>//GEN-END:initComponents

    /**
     * The action to invoke when a user clicks on the CANCEL button.
     *
     * @param evt The event that triggered this action
     */
    private void cancelButtonActionPerformed(final java.awt.event.ActionEvent evt) { // GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    } // GEN-LAST:event_cancelButtonActionPerformed

    /**
     * The action to invoke when a user clicks on the OK button.
     *
     * @param evt The event that triggered this action.
     */
    private void okButtonActionPerformed(final java.awt.event.ActionEvent evt) { // GEN-FIRST:event_okButtonActionPerformed
        LOGGER.event("create new project");
        ResourceMap r = Application.getInstance(Datavyu.class).getContext().getResourceMap(NewProjectV.class);
        DatavyuView s = (DatavyuView) Datavyu.getView();

        // clear the contents of the existing spreadsheet.
        Datavyu.getProjectController().setLastCreatedCell(null);

        if (!isValidProjectName(getProjectName())) {
            Datavyu.getApplication().showWarningDialog(r.getString("Error.invalidName"));
            dispose();
            new NewProjectC();
        } else {
            // BugzID:2352 - Clean up spreadsheet resources before creating a
            // new spreadsheet.
//            s.clearSpreadsheet();

            Datastore ds = DatastoreFactory.newDatastore();
            ds.setName(getProjectName());
            ds.setTitleNotifier(Datavyu.getApplication());

            Datavyu.getProjectController().createNewProject(getProjectName());
            Datavyu.getProjectController().setDatastore(ds);

            s.createNewSpreadsheet();

            // The DB we justed created doesn't really have any unsaved changes.
            Datavyu.getProjectController().getDB().markAsUnchanged();

            dispose();
        }

//        Datavyu.getApplication().resetApp();

        // BugzID:2411 - Show data controller after creating a new project.
//        Datavyu.getApplication().show(Datavyu.getDataController());
    } // GEN-LAST:event_okButtonActionPerformed

    private boolean isValidProjectName(final String name) {
        if (name == null) {
            return false;
        }

        if (name.length() == 0) {
            return false;
        }

        return true;
    }

    /**
     * @return The new name of the database as specified by the user.
     */
    public String getProjectName() {
        return nameField.getText();
    }

    /**
     * @return The new description of the database as specified by the user.
     */
    public String getProjectDescription() {
        return descriptionField.getText();
    }
}
