package org.openshapa.views;

import java.awt.Color;
import javax.swing.GroupLayout;

import javax.swing.JLabel;

import org.jdesktop.application.Application;
import org.jdesktop.application.ResourceMap;


import org.openshapa.Build;
import org.openshapa.OpenSHAPA;


public class AboutV extends OpenSHAPADialog {

    /** Creates new form AboutV */
    public AboutV(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setName(this.getClass().getSimpleName());

        BackgroundPanel p = new BackgroundPanel("/icons/splash.png");

        JLabel version = new JLabel();
        version.setForeground(new Color(119, 187, 33));

        ResourceMap bMap = Application.getInstance(OpenSHAPA.class).getContext()
            .getResourceMap(Build.class);

        ResourceMap rMap = Application.getInstance(OpenSHAPA.class).getContext()
            .getResourceMap(OpenSHAPA.class);

        version.setText("<html>" + rMap.getString("Application.version")
            + "<br>" + bMap.getString("Application.build") + "</html>");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(
                GroupLayout.Alignment.LEADING).addGroup(GroupLayout.Alignment.TRAILING,
                layout.createSequentialGroup().addContainerGap(380,
                    Short.MAX_VALUE).addComponent(version).addGap(136, 136, 136)));
        layout.setVerticalGroup(layout.createParallelGroup(
                GroupLayout.Alignment.LEADING).addGroup(GroupLayout.Alignment.TRAILING,
                layout.createSequentialGroup().addContainerGap(250,
                    Short.MAX_VALUE).addComponent(version).addGap(38, 38, 38)));

        this.add(p);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.openshapa.OpenSHAPA.class).getContext().getResourceMap(AboutV.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
