package org.openshapa.views;

import com.usermetrix.jclient.Logger;
import com.usermetrix.jclient.UserMetrix;
import javax.swing.GroupLayout;
import org.openshapa.OpenSHAPA;
import javax.swing.JFrame;
import javax.swing.JTextArea;
import javax.swing.LayoutStyle;

/**
 * The dialog for the scripting console. Renders output from scripts and other
 * things which dumps things to the console. Implemented as a singleton. Only
 * A single console is used in OpenSHAPA.
 */
public final class ConsoleV extends OpenSHAPADialog {

    /** The logger for this class. */
    private Logger logger = UserMetrix.getLogger(ListVariables.class);

    /** The instance of the console. */
    private static ConsoleV instance;

    /**
     * Constructor.
     *
     * @param parent The parent of this dialog.
     * @param modal Is the scripting console modal or not?
     */
    public ConsoleV(final java.awt.Frame parent,
                    final boolean modal) {
        super(parent, modal);
        initComponents();
        setName(this.getClass().getSimpleName());
    }

    /**
     * @return The text area that makes up the console.
     */
    public JTextArea getConsole() {
        return this.console;
    }

    /**
     * @return The single instance of the console viewer.
     */
    public static ConsoleV getInstance() {
        if (instance == null) {
            JFrame mainFrame = OpenSHAPA.getApplication().getMainFrame();
            instance = new ConsoleV(mainFrame, false);
        }

        return instance;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        console = new javax.swing.JTextArea();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.openshapa.OpenSHAPA.class).getContext().getResourceMap(ConsoleV.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        console.setColumns(20);
        console.setRows(5);
        console.setMinimumSize(new java.awt.Dimension(200, 150));
        console.setName("console"); // NOI18N
        jScrollPane1.setViewportView(console);

        closeButton.setText(resourceMap.getString("closeButton.text")); // NOI18N
        closeButton.setName("closeButton"); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(closeButton, GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * The action to invoke when the user clicks on the close button.
     *
     * @param evt The event that triggered this action.
     */
    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        try {
            getInstance().dispose();
            getInstance().finalize();
            instance = null;

        // Whoops, unable to destroy dialog correctly.
        } catch (Throwable e) {
            logger.error("Unable to release window NewVariableV.", e);
        }
}//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JTextArea console;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
