package org.openshapa.views;

import com.usermetrix.jclient.UserMetrix;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import org.openshapa.Configuration;

public class UserMetrixV extends OpenSHAPADialog {

    /** Creates new form UserMetrixV */
    public UserMetrixV(final java.awt.Frame parent, final boolean modal) {
        super(parent, modal);
        initComponents();
        groupCanSend.add(radioCanSend);
        groupCanSend.add(radioDoNotSend);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupCanSend = new javax.swing.ButtonGroup();
        radioCanSend = new javax.swing.JRadioButton();
        radioDoNotSend = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Blurb = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.openshapa.OpenSHAPA.class).getContext().getResourceMap(UserMetrixV.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        radioCanSend.setFont(resourceMap.getFont("radioCanSend.font")); // NOI18N
        radioCanSend.setText(resourceMap.getString("radioCanSend.text")); // NOI18N
        radioCanSend.setName("radioCanSend"); // NOI18N
        radioCanSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCanSendActionPerformed(evt);
            }
        });

        radioDoNotSend.setText(resourceMap.getString("radioDoNotSend.text")); // NOI18N
        radioDoNotSend.setName("radioDoNotSend"); // NOI18N
        radioDoNotSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDoNotSendActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        Blurb.setBackground(resourceMap.getColor("Blurb.background")); // NOI18N
        Blurb.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        Blurb.setEditable(false);
        Blurb.setText(resourceMap.getString("Blurb.text")); // NOI18N
        Blurb.setMargin(new java.awt.Insets(10, 10, 10, 10));
        Blurb.setName("Blurb"); // NOI18N
        jScrollPane1.setViewportView(Blurb);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(radioCanSend)
                    .addComponent(radioDoNotSend))
                .addContainerGap(115, Short.MAX_VALUE))
            .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioCanSend)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioDoNotSend)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Action to invoke when the user has clicked on the can send radio button.
     *
     * @param evt The event that triggered this action.
     */
    private void radioCanSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCanSendActionPerformed
        Configuration.getInstance().setCanSendLogs(radioCanSend.isSelected());
        UserMetrix.setCanSendLogs(radioCanSend.isSelected());
        this.dispose();
    }//GEN-LAST:event_radioCanSendActionPerformed

    /**
     * Action to invoke when the user has clicked on the do not send radio
     * button.
     *
     * @param evt The event that triggered this action.
     */
    private void radioDoNotSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDoNotSendActionPerformed
        Configuration.getInstance().setCanSendLogs(radioCanSend.isSelected());
        UserMetrix.setCanSendLogs(radioCanSend.isSelected());
        this.dispose();
    }//GEN-LAST:event_radioDoNotSendActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane Blurb;
    private javax.swing.ButtonGroup groupCanSend;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioCanSend;
    private javax.swing.JRadioButton radioDoNotSend;
    // End of variables declaration//GEN-END:variables
}
