package au.com.nicta.openshapa.views;

import au.com.nicta.openshapa.db.MatrixVocabElement;
import java.awt.event.ActionListener;

/**
 * The dialog for users to add new variables to the spreadsheet.
 *
 * @author cfreeman
 */
public final class NewVariableV extends OpenSHAPADialog {

    /** The parent action to notify when the user completes this dialog. */
    private ActionListener notifier;

    /**
     * Constructor, creates a new form to create a new variable.
     *
     * @param parent The parent of this form.
     * @param modal Should the dialog be modal or not?
     * @param listener The listener to notify when the user has created a new
     * variable.
     */
    public NewVariableV(final java.awt.Frame parent, final boolean modal,
                           final ActionListener listener) {
        super(parent, modal);
        initComponents();
        setName(this.getClass().getSimpleName());

        notifier = listener;

        // init button group
        buttonGroup1.add(textTypeButton);
        buttonGroup1.add(nominalTypeButton);
        buttonGroup1.add(predicateTypeButton);
        buttonGroup1.add(matrixTypeButton);
        buttonGroup1.add(integerTypeButton);
        buttonGroup1.add(floatTypeButton);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        textTypeButton = new javax.swing.JRadioButton();
        nominalTypeButton = new javax.swing.JRadioButton();
        predicateTypeButton = new javax.swing.JRadioButton();
        matrixTypeButton = new javax.swing.JRadioButton();
        integerTypeButton = new javax.swing.JRadioButton();
        floatTypeButton = new javax.swing.JRadioButton();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("au/com/nicta/openshapa/views/resources/NewVariableV"); // NOI18N
        jLabel1.setText(bundle.getString("jLabel2.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(bundle.getString("nameField.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        nameField.setName("nameField"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Type:"));
        jPanel1.setName("jPanel1"); // NOI18N

        textTypeButton.setSelected(true);
        textTypeButton.setLabel(bundle.getString("textTypeButton.text")); // NOI18N
        textTypeButton.setName("textTypeButton"); // NOI18N

        nominalTypeButton.setLabel(bundle.getString("nominalTypeButton.text")); // NOI18N
        nominalTypeButton.setName("nominalTypeButton"); // NOI18N

        predicateTypeButton.setLabel(bundle.getString("predicateTypeButton.text")); // NOI18N
        predicateTypeButton.setName("predicateTypeButton"); // NOI18N

        matrixTypeButton.setLabel(bundle.getString("matrixTypeButton.text")); // NOI18N
        matrixTypeButton.setName("matrixTypeButton"); // NOI18N

        integerTypeButton.setLabel(bundle.getString("integerTypeButton.text")); // NOI18N
        integerTypeButton.setName("integerTypeButton"); // NOI18N

        floatTypeButton.setLabel(bundle.getString("floatTypeButton.text")); // NOI18N
        floatTypeButton.setName("floatTypeButton"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(textTypeButton)
                        .add(18, 18, 18)
                        .add(predicateTypeButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(integerTypeButton))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(nominalTypeButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(matrixTypeButton)
                        .add(18, 18, 18)
                        .add(floatTypeButton)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(textTypeButton)
                    .add(predicateTypeButton)
                    .add(integerTypeButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nominalTypeButton)
                    .add(matrixTypeButton)
                    .add(floatTypeButton))
                .addContainerGap())
        );

        okButton.setLabel(bundle.getString("okButton.text")); // NOI18N
        okButton.setName("okButton"); // NOI18N
        okButton.setPreferredSize(new java.awt.Dimension(65, 23));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setLabel(bundle.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(nameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 278, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(okButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cancelButton))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel2)
                        .addContainerGap(193, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(nameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(cancelButton)
                            .add(okButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(37, 37, 37))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * The action to invoke when the user selects the ok button.
     *
     * @param evt The event that triggered this action.
     */
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        notifier.actionPerformed(evt);
        this.dispose();
}//GEN-LAST:event_okButtonActionPerformed

    /**
     * The action to invoke when the user selects the cancel button.
     *
     * @param evt The event that triggered this action.
     */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
}//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @return The name of the new variable the user has specified.
     */
    public String getVariableName() {
        return nameField.getText();
    }

    /**
     * @return The type of variable the user has selected to use.
     */
    public MatrixVocabElement.MatrixType getVariableType() {
        if (textTypeButton.isSelected()) {
            return MatrixVocabElement.MatrixType.TEXT;
        } else if (nominalTypeButton.isSelected()) {
            return MatrixVocabElement.MatrixType.NOMINAL;
        } else if (predicateTypeButton.isSelected()) {
            return MatrixVocabElement.MatrixType.PREDICATE;
        } else if (matrixTypeButton.isSelected()) {
            return MatrixVocabElement.MatrixType.MATRIX;
        } else if (integerTypeButton.isSelected()) {
            return MatrixVocabElement.MatrixType.INTEGER;
        } else if (floatTypeButton.isSelected()) {
            return MatrixVocabElement.MatrixType.FLOAT;
        } else {
            return MatrixVocabElement.MatrixType.UNDEFINED;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton floatTypeButton;
    private javax.swing.JRadioButton integerTypeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton matrixTypeButton;
    private javax.swing.JTextField nameField;
    private javax.swing.JRadioButton nominalTypeButton;
    private javax.swing.JButton okButton;
    private javax.swing.JRadioButton predicateTypeButton;
    private javax.swing.JRadioButton textTypeButton;
    // End of variables declaration//GEN-END:variables
}
