/*
 * SpreadsheetColumn.java
 *
 * Created on 26/11/2008, 2:21:02 PM
 */

package au.com.nicta.openshapa.disc.spreadsheet;

import au.com.nicta.openshapa.db.DataCell;
import au.com.nicta.openshapa.db.DataColumn;
import au.com.nicta.openshapa.db.SystemErrorException;
import javax.swing.BoxLayout;
import org.apache.log4j.Logger;

/**
 * Column panel that contains the SpreadsheetCell panels.
 * @author swhitcher
 */
public class SpreadsheetColumn extends javax.swing.JPanel {

    /** Logger for this class. */
    private static Logger logger = Logger.getLogger(SpreadsheetColumn.class);

    /** DataColumn to display. */
    private DataColumn dbColumn;

    /** Creates new SpreadsheetColumn. No reference to a database column. */
    public SpreadsheetColumn() {
        initComponents();
    }

    /**
     * Creates new SpreadsheetColumn.
     * @param dbCol the database column this panel displays
     */
    public SpreadsheetColumn(final DataColumn dbCol) {
        this();

        this.dbColumn = dbCol;

        this.setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        this.setAlignmentY(TOP_ALIGNMENT);

        updateComponents();
    }

    /**
     * updateComponents. Called when the SpreadsheetCell panels need to be
     * built and added to this Column panel.
     */
    private void updateComponents() {
        try {
            for (int j = 1; j < dbColumn.getNumCells(); j++) {
                DataCell dc = (DataCell) dbColumn.getDB()
                                    .getCell(dbColumn.getID(), j);

                SpreadsheetCell sc =
                                new SpreadsheetCell(dbColumn.getDB(), dc);
                sc.setSize(200,50);
                this.add(sc);
            }
        } catch (SystemErrorException e) {
           logger.error("Failed to populate Spreadsheet.", e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
