/*
 * Spreadsheet.java
 *
 * Created on 26/11/2008, 2:14:43 PM
 */

package au.com.nicta.openshapa.disc.spreadsheet;

import au.com.nicta.openshapa.db.DataColumn;
import au.com.nicta.openshapa.db.Database;
import au.com.nicta.openshapa.db.SystemErrorException;
import java.awt.BorderLayout;
import java.util.Vector;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import org.apache.log4j.Logger;

/**
 * The main spreadsheet window. Displays the database it refers
 * to, showing the database columns and cells within.
 * @author swhitcher
 */
public class Spreadsheet extends javax.swing.JFrame {

    /** Scrollable view inserted into the JScrollPane. */
    private SpreadsheetView mainview;
    /** View showing the Column titles. */
    private SpreadsheetColumnHeader headerView;

    /** The Database being viewed. */
    private Database database;

    /** Logger for this class. */
    private static Logger logger = Logger.getLogger(Spreadsheet.class);

    /** Creates new, empty Spreadsheet. No database referred to as yet */
    public Spreadsheet() {
        initComponents();

        this.setLayout(new BorderLayout());

        mainview = new SpreadsheetView();
        mainview.setLayout(new BoxLayout(mainview, BoxLayout.X_AXIS));

        headerView = new SpreadsheetColumnHeader();

        JScrollPane jScrollPane3 = new JScrollPane();
        this.add(jScrollPane3, BorderLayout.CENTER);
        jScrollPane3.setViewportView(mainview);
        jScrollPane3.setColumnHeaderView(headerView);
    }

    /**
     * Creates new Spreadsheet to display a database.
     * @param db The database to display
     */
    public Spreadsheet(final Database db) {
        this();

        this.setDatabase(db);

        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        this.updateComponents();
    }

    /**
     * Populate from the database.
     */
    private void updateComponents() {
        try {
            Vector <DataColumn> dbColumns = getDatabase().getDataColumns();

            for (int i = 0; i < dbColumns.size(); i++) {
                DataColumn dbColumn = dbColumns.elementAt(i);

                SpreadsheetColumn col = new SpreadsheetColumn(dbColumn);

                addColumn(col, dbColumn.getName());

            }
        } catch (SystemErrorException e) {
           logger.error("Failed to populate Spreadsheet.", e);
        }

    }

    /**
     * Add a column panel to the scroll panel.
     * @param col Column to add
     * @param name Name of column
     */
    private void addColumn(final SpreadsheetColumn col, final String name) {
        mainview.add(col);

        headerView.addColumn(name);
    }

    /**
     * Set Database.
     * @param db Database to set
     */
    public final void setDatabase(final Database db) {
        this.database = db;
    }

    /**
     * @return Database this spreadsheet displays
     */
    public final Database getDatabase() {
        return (this.database);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
