/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SpreadsheetColumnHeader.java
 *
 * Created on 26/11/2008, 2:37:13 PM
 */

package au.com.nicta.openshapa.disc.spreadsheet;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JLabel;

/**
 *
 * @author swhitcher
 */
public class SpreadsheetColumnHeader extends javax.swing.JPanel {

    /** Creates new form SpreadsheetColumnHeader */
    public SpreadsheetColumnHeader() {
        initComponents();

        this.setLayout(new BoxLayout(this, BoxLayout.X_AXIS));
    }

    public void addColumn(final String name) {
        JLabel nameLabel = new JLabel(name);
        nameLabel.setOpaque(true);
        nameLabel.setHorizontalTextPosition(JLabel.CENTER);
        nameLabel.setHorizontalAlignment(JLabel.CENTER);
        nameLabel.setBorder(BorderFactory.createLineBorder(Color.black));
        nameLabel.setPreferredSize(new Dimension(200,14));

        this.add(nameLabel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
