00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 2 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 


Current Header Settings:
db.name = "parser_test.db"
odb file format version = 1
warning limit = 50
error limit = 10
debug level = 2

00019        (
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022              ( |pred_1| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| ) ) ) )
00023              ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )


Predicate Definition:
	name = "pred_1"
	variable length = false
	arg 0 = "<arg1>"
	arg 1 = "<arg2>"

00024            )
00025          ) 


Predicate Definition:
	name = "pred_2"
	variable length = true
	arg 0 = "<arg1>"

00026          ( SPREADSHEET-VARIABLE-DECLARATIONS> 
00027            (
00028              ( |a text var| 
00029                ( 
00030                  ( TYPE> <<TEXT>> ) 
00031                  ( VARIABLE-LENGTH> FALSE )
00032                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) ) 
00033                  ( COLUMN-WIDTH> 200 ) 
00034                ) 
00035              )
00036              ( |a nominal var| 


Spreadsheet Variable Definition:
	name = "a text var"
	type = TEXT
	variable length = false
	column width = 200
00037                ( 
00038                  ( TYPE> <<NOMINAL>> ) 
00039                  ( VARIABLE-LENGTH> FALSE )
00040                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00041                  ( COLUMN-WIDTH> 200 ) 
00042                ) 
00043              )
00044              ( |an integer var| 


Spreadsheet Variable Definition:
	name = "a nominal var"
	type = NOMINAL
	variable length = false
	column width = 200
00045                ( 
00046                  ( TYPE> <<INTEGER>> ) 
00047                  ( VARIABLE-LENGTH> FALSE )
00048                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00049                  ( COLUMN-WIDTH> 200 ) 
00050                ) 
00051              )
00052              ( |a float var| 


Spreadsheet Variable Definition:
	name = "an integer var"
	type = INTEGER
	variable length = false
	column width = 200
00053                ( 
00054                  ( TYPE> <<FLOAT>> ) 
00055                  ( VARIABLE-LENGTH> FALSE )
00056                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00057                  ( COLUMN-WIDTH> 200 ) 
00058                ) 
00059              )
00060              ( |a predicate var| 


Spreadsheet Variable Definition:
	name = "a float var"
	type = FLOAT
	variable length = false
	column width = 200
00061                ( 
00062                  ( TYPE> <<PREDICATE>> ) 
00063                  ( VARIABLE-LENGTH> FALSE )
00064                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00065                  ( COLUMN-WIDTH> 200 ) 
00066                ) 
00067              )
00068              ( |fixed len matrix| 


Spreadsheet Variable Definition:
	name = "a predicate var"
	type = PREDICATE
	variable length = false
	column width = 200
00069                ( 
00070                  ( TYPE> <<MATRIX>> ) 
00071                  ( VARIABLE-LENGTH> FALSE )
00072                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg1>| |<arg2>| ) )  
00073                  ( COLUMN-WIDTH> 200 ) 
00074                ) 
00075              )
00076              ( |var len matrix| 


Spreadsheet Variable Definition:
	name = "fixed len matrix"
	type = MATRIX
	variable length = false
	column width = 200
00077                ( 
00078                  ( TYPE> <<MATRIX>> ) 
00079                  ( VARIABLE-LENGTH> TRUE )
00080                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg1>| |<arg2>| ) )  
00081                  ( COLUMN-WIDTH> 225 ) 
00082                ) 
00083              )
00084            ) 
00085          ) 


Spreadsheet Variable Definition:
	name = "var len matrix"
	type = MATRIX
	variable length = true
	column width = 225
00086          ( SPREADSHEET-VARIABLE-DEFINITIONS>
00087           ( 
00088              ( |a text var|
00089                ( 
00090                  ( CELLS>
00091                    ( 
00092                      ; ( missing left paren in a var cell a-list
00093                        ( ONSET>  0 ) 

      WARNING   9 (Line 93:25): Left parentheses expected.  Left parenthesis inserted to allow continued parse.
        The opening left parenthesis of a spreadsheet variable cell a-list appears to be missing.

00094                        ( OFFSET>  0 ) 
00095                        ( |<val>| "this is a text cell") 
00096                      )
00097                      ( 
00098                        33 ; leading atom in a var cell a-list
00099                        ( ONSET> 60 ) 


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = this is a text cell

      WARNING  20 (Line 98:23): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in a spreadsheet variable cell a-list.

00100                        ( OFFSET> 60 ) 
00101                        ( |<val>| "") 
00102                      )
00103                      ( 
00104                        ( ONSET>  0 ) 


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 
00105                        ( OFFSET>  0 ) 
00106                        ; text cell with missing value
00107                        ; ( |<val>| "this is a text cell") 
00108                      )
00109                    )
00110                  )
00111                )

      WARNING  78 (Line 109:19): Encountered a spreadsheet cell whose value is undefined.  Will use a default value.



Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 
00112              )
00113              
00114              ( |a nominal var|
00115                (
00116                  ( CELLS>
00117                    (
00118                      ( 
00119                        ( ONSET>  0 ) 
00120                        ( OFFSET>  0 ) 
00121                        ( |<val>| |this is nominal cell| ) 
00122                        ( NONE-SUCH> 10 )                      ; unknown attribute

      WARNING  18 (Line 122:25): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in a spreadsheet variable cell a-list.

00123                        ( ONSET>  0 )                          ; duplicate onset

      WARNING  17 (Line 123:25): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate ONSET> entry in a spreadsheet variable cell a-list.

00124                        ( OFFSET>  0 )                         ; dupliaate offset

      WARNING  17 (Line 124:25): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate OFFSET> entry in a spreadsheet variable cell a-list.

00125                        ( |<val>| |this is nominal cell| )     ; duplicate value

      WARNING  62 (Line 125:25): Encountered an undefined or out of order spreadsheet variable cell argument value.  The value will be discarded.

00126                        ( "this" "is" "an" "arbitrary" "list" )

      WARNING  19 (Line 126:25): Encountered list that is not an a-list entry in an a-list.  The list will be read and discarded.
        The list is located in a spreadsheet variable cell a-list.

00127                        |j random atom|
00128                      )
00129                      ( ; empty cell

      WARNING  20 (Line 127:23): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in a spreadsheet variable cell a-list.

00130                        ; ( ONSET> 60 ) 
00131                        ; ( OFFSET> 60 ) 
00132                        ; ( |<val>| |<val>| ) 
00133                      )
00134                    )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = this is nominal cell
00135                  )
00136                )

      WARNING  79 (Line 134:19): Encountered a spreadsheet cell whose onset is undefined.  Will force onset to 00:00:00:00.


      WARNING  80 (Line 134:19): Encountered a spreadsheet cell whose offset is undefined.  Will force offset to 00:00:00:00.


      WARNING  78 (Line 134:19): Encountered a spreadsheet cell whose value is undefined.  Will use a default value.



Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 
00137              )
00138              ( |an integer var|
00139                (
00140                  ( CELLS>
00141                    (
00142                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| 10 ) )
00143                      ( 
00144                        ( ONSET> 60 ) 


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 10
00145                        ( OFFSET> 60 )
00146                        ; integer cell with missing value
00147                        ; ( |<val>| 0) 
00148                      )
00149                    )
00150                  )
00151                )

      WARNING  78 (Line 149:19): Encountered a spreadsheet cell whose value is undefined.  Will use a default value.



Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 0
00152              )
00153              ( |a float var|
00154                (
00155                  ( CELLS>
00156                    (
00157                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| 10.0 ) )
00158                      ( 
00159                        ( ONSET> 60 ) 


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 10.000000
00160                        ( OFFSET> 60 ) 
00161                        ; float cell with missing value
00162                        ; ( |<val>| 0.0 ) 
00163                      )
00164                    )
00165                  )
00166                )

      WARNING  78 (Line 164:19): Encountered a spreadsheet cell whose value is undefined.  Will use a default value.



Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 0.000000
00167              )
00168              ( |a predicate var|
00169                (
00170                  ( CELLS>
00171                    (
00172                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| ( |pred_1| ( TIME> 120 ) |a nominal| ) ) )
00173                      ( ( ONSET> 10 ) ( OFFSET> 20 ) ( |<val>| ( |pred_1| "a string" |<arg2>| ) ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = pred_1(00:00:02:000, a nominal)
00174                      ( ( ONSET> 20 ) ( OFFSET> 30 ) ( |<val>| ( |pred_1| 10 1.0 ) ) )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:010
	offset = 00:00:00:020
	value = pred_1("a string", <arg2>)
00175                      ( ( ONSET> 30 ) ( OFFSET> 40 ) ( |<val>| ( |pred_1| ( |pred_2| |<arg1>| ) |<arg2>| ) ) )


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:020
	offset = 00:00:00:030
	value = pred_1(10, 1.000000)
00176                      ( 
00177                        ( ONSET> 60 ) 


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:00:030
	offset = 00:00:00:040
	value = pred_1(pred_2(<arg1>), <arg2>)
00178                        ( OFFSET> 60 ) 
00179                        ; predicate cell with missing value
00180                        ; ( |<val>| ( ) ) 
00181                      )
00182                    )
00183                  )
00184                  ( VOCAB> ( |pred_1| |pred_2| ) )

      WARNING  78 (Line 182:19): Encountered a spreadsheet cell whose value is undefined.  Will use a default value.



Spreadsheet Variable Cell Definition:
	ord = 5
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = ()
00185                )
00186              )
00187              ( |fixed len matrix|
00188                (
00189                  ( CELLS>
00190                    (
00191                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<arg1>| 1 ) ( |<arg2>| 2.0 ) )
00192                      ( ( ONSET> 10 ) ( OFFSET> 20 ) ( |<arg1>| |a nominal| ) ( |<arg2>| "a string" ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 1, 2.000000
00193                      ( ( ONSET> 20 ) ( OFFSET> 30 ) ( |<arg1>| ( |pred_2| |<arg1>| ) ) ( |<arg2>| ( TIME> 120 ) ) )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:010
	offset = 00:00:00:020
	value = a nominal, "a string"
00194                      ( 
00195                        ( ONSET> 60 ) 


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:020
	offset = 00:00:00:030
	value = pred_2(<arg1>), 00:00:02:000
00196                        ( OFFSET> 60 ) 
00197                        ( |<arg1>| |<arg1>| ) 
00198                        ( |<arg2>| |<arg2>| ) 
00199                      )
00200                      ( 
00201                        ( ONSET> 60 ) 


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = <arg1>, <arg2>
00202                        ( OFFSET> 60 ) 
00203                        ( |<arg1>| "first arg" ) 
00204                        ( |<arg2>| "second arg" ) 
00205                      )
00206                      ( 
00207                        ( ONSET> 61 ) 


Spreadsheet Variable Cell Definition:
	ord = 5
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = "first arg", "second arg"
00208                        ( OFFSET> 61 )
00209                        ; first arg missing 
00210                        ; ( |<arg1>| "first arg" ) 
00211                        ( |<arg2>| "second arg" ) 

      WARNING  62 (Line 211:25): Encountered an undefined or out of order spreadsheet variable cell argument value.  The value will be discarded.

00212                      )
00213                      ( 
00214                        ( ONSET> 62 ) 

      WARNING  77 (Line 213:21): Encountered matrix spreadsheet cell which is missing one or more required arguments. These argument(s) will be filled in with formal arguments.



Spreadsheet Variable Cell Definition:
	ord = 6
	onset = 00:00:01:001
	offset = 00:00:01:001
	value = <arg1>, <arg2>
00215                        ( OFFSET> 62 ) 
00216                        ( |<arg1>| "first arg" ) 
00217                        ; second arg missing
00218                        ; ( |<arg2>| "second arg" ) 
00219                      )
00220                      ( 
00221                        ( ONSET> 63 ) 

      WARNING  77 (Line 220:21): Encountered matrix spreadsheet cell which is missing one or more required arguments. These argument(s) will be filled in with formal arguments.



Spreadsheet Variable Cell Definition:
	ord = 7
	onset = 00:00:01:002
	offset = 00:00:01:002
	value = "first arg", <arg2>
00222                        ( OFFSET> 63 )
00223                        ; both args missing 
00224                        ; ( |<arg1>| "first arg" ) 
00225                        ; ( |<arg2>| "second arg" ) 
00226                      )
00227                    )
00228                  )
00229                  ( VOCAB> ( |pred_1| |pred_2| ) ) 

      WARNING  77 (Line 227:19): Encountered matrix spreadsheet cell which is missing one or more required arguments. These argument(s) will be filled in with formal arguments.



Spreadsheet Variable Cell Definition:
	ord = 8
	onset = 00:00:01:003
	offset = 00:00:01:003
	value = <arg1>, <arg2>
00230                )
00231              )
00232              ( |var len matrix|
00233                (
00234                  ( CELLS>
00235                    (
00236                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<arg1>| 1 ) ( |<arg2>| 2.0 ) )
00237                      ( ( ONSET> 10 ) ( OFFSET> 20 ) ( |<arg1>| |a nominal| ) ( |<arg2>| "a string" ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 1, 2.000000
00238                      ( ( ONSET> 20 ) ( OFFSET> 30 ) ( |<arg1>| ( |pred_2| |<arg1>| ) ) ( |<arg2>| ( TIME> 120 ) ) )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:010
	offset = 00:00:00:020
	value = a nominal, "a string"
00239                      ( ( ONSET> 60 ) ( OFFSET> 60 ) ( |<arg1>| |<arg1>| ) )


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:020
	offset = 00:00:00:030
	value = pred_2(<arg1>), 00:00:02:000
00240                      ( ( ONSET> 60 ) ( OFFSET> 60 ) ( |<arg1>| |<arg1>| ) ( |<arg2>| |<arg2>| ) )


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = <arg1>, <arg2>
00241                      ( 
00242                        ( ONSET> 61 ) 


Spreadsheet Variable Cell Definition:
	ord = 5
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = <arg1>, <arg2>
00243                        ( OFFSET> 61 ) 
00244                        ( |<arg1>| "first arg" ) 
00245                        ( |<arg2>| "second arg" ) 
00246                      )
00247                      ( 
00248                        ( ONSET> 62 ) 


Spreadsheet Variable Cell Definition:
	ord = 6
	onset = 00:00:01:001
	offset = 00:00:01:001
	value = "first arg", "second arg"
00249                        ( OFFSET> 62 ) 
00250                        ; first arg missing
00251                        ; ( |<arg1>| "first arg" ) 
00252                        ( |<arg2>| "second arg" ) 

      WARNING  62 (Line 252:25): Encountered an undefined or out of order spreadsheet variable cell argument value.  The value will be discarded.

00253                      )
00254                      ( 
00255                        ( ONSET> 63 ) 

      WARNING  77 (Line 254:21): Encountered matrix spreadsheet cell which is missing one or more required arguments. These argument(s) will be filled in with formal arguments.



Spreadsheet Variable Cell Definition:
	ord = 7
	onset = 00:00:01:002
	offset = 00:00:01:002
	value = <arg1>, <arg2>
00256                        ( OFFSET> 63 ) 
00257                        ( |<arg1>| "first arg" ) 
00258                        ; second arg missing
00259                        ; ( |<arg2>| "second arg" ) 
00260                      )
00261                      ( 
00262                        ( ONSET> 64 ) 


Spreadsheet Variable Cell Definition:
	ord = 8
	onset = 00:00:01:003
	offset = 00:00:01:003
	value = "first arg", <arg2>
00263                        ( OFFSET> 64 ) 
00264                        ; both args missing
00265                        ; ( |<arg1>| "first arg" ) 
00266                        ; ( |<arg2>| "second arg" ) 
00267                      )
00268                      ( 
00269                        ( ONSET> 65 ) 

      WARNING  77 (Line 268:21): Encountered matrix spreadsheet cell which is missing one or more required arguments. These argument(s) will be filled in with formal arguments.



Spreadsheet Variable Cell Definition:
	ord = 9
	onset = 00:00:01:004
	offset = 00:00:01:004
	value = <arg1>, <arg2>
00270                        ( OFFSET> 65 ) 
00271                        ( |<arg1>| "first arg" ) 
00272                        ( |<arg2>| "second arg" ) 
00273                        ; EOF in a cell a-list
00274  ;                    )
00275  ;                  )
00276  ;                )
00277  ;                ( VOCAB> ( |pred_1| |pred_2| ) )
00278  ;              )
00279  ;            )
00280  ;          )
00281  ;        )
00282  ;      ) 
00283  ;    ) 
00284  ;    ( QUERY> 2 )
00285  ;    ( SYSTEM> 3 )
00286  ;  ) 
00287  ;)

      ERROR  4 (Line 287:0): Encountered end of file unexpectedly.
        EOF occurred in a spreadsheet variable cell a-list.

Unable to continue parse -- Aborting...
