00001  ; MacSHAPA Open Database
00002  ( setf macshapa-db 
00003   '( 
00004      ( HEADER>
00005        ( 
00006          ( VERSION> 1 ) 
00007          ( NAME> "parser_test.db" )
00008          ;( DEBUG-LEVEL> 2 ) 
00009          ( MAX-ERRORS> 20 )
00010          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 9:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00011        )
00012      )
00013      (
00014        USER>
00015        (
00016          (
00017            PREDICATE-DEFINITIONS>
00018            (
00019              ( 
00020                |GOAL| 
00021                ( 
00022                  ( VARIABLE-LENGTH> FALSE )
00023                  ( FORMAL-ARG-LIST> ( |<TEMPERATURE>| |<VOLUME>| |<FLOWRATE>| ) ) 
00024                )
00025              )
00026              ( 
00027                |COMMAND|
00028                (
00029                  ( VARIABLE-LENGTH> FALSE )
00030                  ( FORMAL-ARG-LIST> ( |<SPEAKER>| |<TO>| |<MITIGATION>| ) ) 
00031                )
00032              )
00033              ( 
00034                |ACKNOWL|
00035                (
00036                  ( VARIABLE-LENGTH> FALSE )
00037                  ( FORMAL-ARG-LIST> ( |<SPEAKER>| |<TO>| |<MITIGATION>| ) ) 
00038                )
00039              )
00040              ( 
00041                |ANNOUNCE|
00042                (
00043                  ( VARIABLE-LENGTH> FALSE )
00044                  ( FORMAL-ARG-LIST> ( |<SPEAKER>| |<MITIGATION>| ) ) 
00045                )
00046              )
00047              ( 
00048                |OBSERVE|
00049                (
00050                  ( VARIABLE-LENGTH> FALSE )
00051                  ( FORMAL-ARG-LIST> ( |<SPEAKER>| |<MITIGATION>| ) ) 
00052                )
00053              )
00054              ( 
00055                |REASON|
00056                (
00057                  ( VARIABLE-LENGTH> FALSE )
00058                  ( FORMAL-ARG-LIST> ( |<SPEAKER>| |<MITIGATION>| ) ) 
00059                )
00060              )
00061              ( 
00062                |PREDICT|
00063                (
00064                  ( VARIABLE-LENGTH> FALSE )
00065                  ( FORMAL-ARG-LIST> ( |<SPEAKER>| |<MITIGATION>| ) ) 
00066                )
00067              )
00068            )
00069          )
00070          (
00071            SPREADSHEET-VARIABLE-DECLARATIONS>
00072            (
00073              (
00074                |verbal|
00075                (
00076                  ( TYPE>            <<TEXT>> )
00077                  ( VARIABLE-LENGTH> FALSE  )
00078                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
00079                  ( COLUMN-WIDTH>    183 )
00080                )
00081              )
00082              (
00083                |state.var|
00084                (
00085                  ( TYPE>            <<MATRIX>> )
00086                  ( VARIABLE-LENGTH> FALSE  )
00087                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<PARAM>| |<SUBSYS>| |<VAL>| ) )
00088                  ( COLUMN-WIDTH>    183 )
00089                )
00090              )
00091              (
00092                |sys.var|
00093                (
00094                  ( TYPE>            <<MATRIX>> )
00095                  ( VARIABLE-LENGTH> FALSE  )
00096                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<PARAM>| |<SUBSYS>| |<VAL>| ) )
00097                  ( COLUMN-WIDTH>    200 )
00098                )
00099              )
00100              (
00101                |speechcode|
00102                (
00103                  ( TYPE>            <<PREDICATE>> )
00104                  ( VARIABLE-LENGTH> FALSE  )
00105                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
00106                  ( COLUMN-WIDTH>    200 )
00107                )
00108              )
00109            )
00110          )
00111          (
00112            SPREADSHEET-VARIABLE-DEFINITIONS>
00113            (
00114              (
00115                |verbal|
00116                (
00117                  (
00118                    CELLS>
00119                    (
00120                      ( ( ONSET>   60 ) ( OFFSET>  360 ) ( |<val>| "Expter:  Please try to increase temperature, increase volume and increase flowrate." ) ) 
00121                      ( ( ONSET>  420 ) ( OFFSET>  540 ) ( |<val>| "Sam:  Tom, you can do the hydraulic side and I'll do the heat side." ) ) 
00122                      ( ( ONSET>  600 ) ( OFFSET>  660 ) ( |<val>| "Tom:  If you like." ) ) 
00123                      ( ( ONSET>  660 ) ( OFFSET>  780 ) ( |<val>| "Sam:  I'll set heater up to 8 for now." ) ) 
00124                      ( ( ONSET>  780 ) ( OFFSET> 1260 ) ( |<val>| "Tom:  OK.  First to increase flowrate I'm going to open the input valve a bit more and open up the output valve." ) ) 
00125                      ( ( ONSET> 1260 ) ( OFFSET> 1440 ) ( |<val>| "Sam:  OK, volume is starting to increase..." ) ) 
00126                      ( ( ONSET> 1440 ) ( OFFSET> 1560 ) ( |<val>| "Sam:  ...and so is flow rate." ) ) 
00127                      ( ( ONSET> 1680 ) ( OFFSET> 1800 ) ( |<val>| "Sam:  Nothing happening so far on temperature..." ) ) 
00128                      ( ( ONSET> 1800 ) ( OFFSET> 1860 ) ( |<val>| "Sam:  ...so I'll send it up to 9." ) ) 
00129                      ( ( ONSET> 1920 ) ( OFFSET> 2040 ) ( |<val>| "Sam:  You haven't done anything to the mixer value and volume is going up pretty fast." ) ) 
00130                      ( ( ONSET> 2160 ) ( OFFSET> 2220 ) ( |<val>| "Tom:  Oh sorry...I always forget that!" ) ) 
00131                      ( ( ONSET> 2280 ) ( OFFSET> 2400 ) ( |<val>| "Tom:  I wonder why the flow rate is decreasing?" ) ) 
00132                      ( ( ONSET> 2460 ) ( OFFSET> 2520 ) ( |<val>| "Tom:  I increased input and output so flow rate should increase." ) ) 
00133                      ( ( ONSET> 2580 ) ( OFFSET> 2700 ) ( |<val>| "Tom:  Oh!  It's because I forgot to open the mixer valve." ) ) 
00134                      ( ( ONSET> 2700 ) ( OFFSET> 2880 ) ( |<val>| "Tom:  So flow rate should increase in a minute or two." ) ) 
00135                      ( ( ONSET> 2760 ) ( OFFSET> 2820 ) ( |<val>| "Sam:  There the temperature goes!" ) ) 
00136                      ( ( ONSET> 2880 ) ( OFFSET> 3000 ) ( |<val>| "Tom:  ...and that's what it's doing." ) ) 
00137                      ( ( ONSET> 3000 ) ( OFFSET> 3120 ) ( |<val>| "Tom:  Oh hell!  It's going down again." ) ) 
00138                      ( ( ONSET> 3120 ) ( OFFSET> 3180 ) ( |<val>| "Tom:  So I'll open the output a bit." ) ) 
00139                      ( ( ONSET> 3300 ) ( OFFSET> 3480 ) ( |<val>| "Sam:  Why don't you let it settle rather than keeping on playing with it?" ) ) 
00140                      ( ( ONSET> 3540 ) ( OFFSET> 3840 ) ( |<val>| "Tom:  Oh well...I don't think I play with it too much." ) ) 
00141                      ( ( ONSET> 3840 ) ( OFFSET> 3960 ) ( |<val>| "Sam:  You do, you know." ) ) 
00142                      ( ( ONSET> 4200 ) ( OFFSET> 4320 ) ( |<val>| "Sam:  Temperature's still rising." ) ) 
00143                      ( ( ONSET> 4500 ) ( OFFSET> 4680 ) ( |<val>| "Tom:  You've confused me about the flowrate now, Sam!" ) ) 
00144                    )
00145                  )
00146                )
00147              )
00148              (
00149                |state.var|
00150                (
00151                  (
00152                    CELLS>
00153                    (
00154                      ( ( ONSET>    0 ) ( OFFSET>    0 ) ( |<PARAM>| |M| ) ( |<SUBSYS>| |L| ) ( |<VAL>| 5 ) ) 
00155                      ( ( ONSET>    0 ) ( OFFSET>    0 ) ( |<PARAM>| |I| ) ( |<SUBSYS>| |A| ) ( |<VAL>| 5 ) ) 
00156                      ( ( ONSET>    0 ) ( OFFSET>    0 ) ( |<PARAM>| |O| ) ( |<SUBSYS>| |A| ) ( |<VAL>| 1 ) ) 
00157                      ( ( ONSET>    0 ) ( OFFSET>    0 ) ( |<PARAM>| |H| ) ( |<SUBSYS>| |A| ) ( |<VAL>| 5 ) ) 
00158                      ( ( ONSET>  660 ) ( OFFSET>  720 ) ( |<PARAM>| |H| ) ( |<SUBSYS>| |A| ) ( |<VAL>| 9 ) ) 
00159                      ( ( ONSET> 1140 ) ( OFFSET> 1260 ) ( |<PARAM>| |O| ) ( |<SUBSYS>| |A| ) ( |<VAL>| 8 ) ) 
00160                      ( ( ONSET> 1260 ) ( OFFSET> 1380 ) ( |<PARAM>| |I| ) ( |<SUBSYS>| |A| ) ( |<VAL>| 8 ) ) 
00161                      ( ( ONSET> 1800 ) ( OFFSET> 1920 ) ( |<PARAM>| |H| ) ( |<SUBSYS>| |A| ) ( |<VAL>| 9 ) ) 
00162                      ( ( ONSET> 2460 ) ( OFFSET> 2580 ) ( |<PARAM>| |M| ) ( |<SUBSYS>| |L| ) ( |<VAL>| 8 ) ) 
00163                    )
00164                  )
00165                  ( VOCAB> ( ) )
00166                )
00167              )
00168              (
00169                |sys.var|
00170                (
00171                  (
00172                    CELLS>
00173                    (
00174                      ( ( ONSET>    0 ) ( OFFSET> 1320 ) ( |<PARAM>| |V|  ) ( |<SUBSYS>| |A| ) ( |<VAL>| 21 ) ) 
00175                      ( ( ONSET>    0 ) ( OFFSET> 1440 ) ( |<PARAM>| |FR| ) ( |<SUBSYS>| |A| ) ( |<VAL>|  5 ) ) 
00176                      ( ( ONSET>    0 ) ( OFFSET> 2760 ) ( |<PARAM>| |T|  ) ( |<SUBSYS>| |A| ) ( |<VAL>|  3 ) ) 
00177                      ( ( ONSET> 1320 ) ( OFFSET> 1500 ) ( |<PARAM>| |V|  ) ( |<SUBSYS>| |A| ) ( |<VAL>| 22 ) ) 
00178                      ( ( ONSET> 1440 ) ( OFFSET> 1680 ) ( |<PARAM>| |FR| ) ( |<SUBSYS>| |A| ) ( |<VAL>|  6 ) ) 
00179                      ( ( ONSET> 1500 ) ( OFFSET> 1860 ) ( |<PARAM>| |V|  ) ( |<SUBSYS>| |A| ) ( |<VAL>| 23 ) ) 
00180                      ( ( ONSET> 1680 ) ( OFFSET> 1920 ) ( |<PARAM>| |FR| ) ( |<SUBSYS>| |A| ) ( |<VAL>|  5 ) ) 
00181                      ( ( ONSET> 1860 ) ( OFFSET> 1980 ) ( |<PARAM>| |V|  ) ( |<SUBSYS>| |A| ) ( |<VAL>| 24 ) ) 
00182                      ( ( ONSET> 1920 ) ( OFFSET> 2760 ) ( |<PARAM>| |FR| ) ( |<SUBSYS>| |A| ) ( |<VAL>|  4 ) ) 
00183                      ( ( ONSET> 1980 ) ( OFFSET> 2040 ) ( |<PARAM>| |V|  ) ( |<SUBSYS>| |A| ) ( |<VAL>| 25 ) ) 
00184                      ( ( ONSET> 2040 ) ( OFFSET> 2580 ) ( |<PARAM>| |V|  ) ( |<SUBSYS>| |A| ) ( |<VAL>| 26 ) ) 
00185                      ( ( ONSET> 2580 ) ( OFFSET> 4800 ) ( |<PARAM>| |V|  ) ( |<SUBSYS>| |A| ) ( |<VAL>| 25 ) ) 
00186                      ( ( ONSET> 2760 ) ( OFFSET> 2820 ) ( |<PARAM>| |FR| ) ( |<SUBSYS>| |A| ) ( |<VAL>|  5 ) ) 
00187                      ( ( ONSET> 2760 ) ( OFFSET> 2880 ) ( |<PARAM>| |T|  ) ( |<SUBSYS>| |A| ) ( |<VAL>| 24 ) ) 
00188                      ( ( ONSET> 2820 ) ( OFFSET> 2880 ) ( |<PARAM>| |FR| ) ( |<SUBSYS>| |A| ) ( |<VAL>|  6 ) ) 
00189                      ( ( ONSET> 2880 ) ( OFFSET> 3300 ) ( |<PARAM>| |FR| ) ( |<SUBSYS>| |A| ) ( |<VAL>|  5 ) ) 
00190                      ( ( ONSET> 2880 ) ( OFFSET> 4200 ) ( |<PARAM>| |T|  ) ( |<SUBSYS>| |A| ) ( |<VAL>| 25 ) ) 
00191                      ( ( ONSET> 3300 ) ( OFFSET> 3780 ) ( |<PARAM>| |FR| ) ( |<SUBSYS>| |A| ) ( |<VAL>|  4 ) ) 
00192                      ( ( ONSET> 3780 ) ( OFFSET> 4800 ) ( |<PARAM>| |FR| ) ( |<SUBSYS>| |A| ) ( |<VAL>|  3 ) ) 
00193                      ( ( ONSET> 4200 ) ( OFFSET> 4800 ) ( |<PARAM>| |T|  ) ( |<SUBSYS>| |A| ) ( |<VAL>| 26 ) ) 
00194                    )
00195                  )
00196                  ( VOCAB> ( ) )
00197                )
00198              )
00199              ( |speechcode|
00200                (
00201                  (
00202                    CELLS>
00203                    (
00204                      ( ( ONSET>   60 ) ( OFFSET>  360 ) ( |<val>| ( |GOAL|     |+|   |+|   |+| ) ) ) 
00205                      ( ( ONSET>  420 ) ( OFFSET>  540 ) ( |<val>| ( |COMMAND|  |Sam| |Tom| +1  ) ) )
00206                      ( ( ONSET>  600 ) ( OFFSET>  660 ) ( |<val>| ( |ACKNOWL|  |Tom| |Sam| -1  ) ) ) 
00207                      ( ( ONSET>  660 ) ( OFFSET>  780 ) ( |<val>| ( |ANNOUNCE| |Sam| 0         ) ) ) 
00208                      ( ( ONSET>  780 ) ( OFFSET> 1260 ) ( |<val>| ( |ANNOUNCE| |Tom| 0         ) ) ) 
00209                      ( ( ONSET> 1260 ) ( OFFSET> 1440 ) ( |<val>| ( |OBSERVE|  |Sam| 0         ) ) ) 
00210                      ( ( ONSET> 1440 ) ( OFFSET> 1560 ) ( |<val>| ( |OBSERVE|  |Sam| 0         ) ) ) 
00211                      ( ( ONSET> 1680 ) ( OFFSET> 1800 ) ( |<val>| ( |OBSERVE|  |Sam| 0         ) ) ) 
00212                      ( ( ONSET> 1800 ) ( OFFSET> 1860 ) ( |<val>| ( |ANNOUNCE| |Sam| 0         ) ) ) 
00213                      ( ( ONSET> 1920 ) ( OFFSET> 2040 ) ( |<val>| ( |COMMAND|  |Sam| |Tom| -1  ) ) ) 
00214                      ( ( ONSET> 2160 ) ( OFFSET> 2220 ) ( |<val>| ( |ACKNOWL|  |Tom| |Sam| -1  ) ) ) 
00215                      ( ( ONSET> 2280 ) ( OFFSET> 2400 ) ( |<val>| ( |OBSERVE|  |Tom| -1        ) ) ) 
00216                      ( ( ONSET> 2460 ) ( OFFSET> 2520 ) ( |<val>| ( |REASON|   |Tom| 0         ) ) ) 
00217                      ( ( ONSET> 2580 ) ( OFFSET> 2700 ) ( |<val>| ( |REASON|   |Tom| 0         ) ) ) 
00218                      ( ( ONSET> 2700 ) ( OFFSET> 2880 ) ( |<val>| ( |PREDICT|  |Tom| 0         ) ) ) 
00219                      ( ( ONSET> 2760 ) ( OFFSET> 2820 ) ( |<val>| ( |OBSERVE|  |Sam| 0         ) ) ) 
00220                      ( ( ONSET> 2880 ) ( OFFSET> 3000 ) ( |<val>| ( |OBSERVE|  |Tom| 0         ) ) ) 
00221                      ( ( ONSET> 3000 ) ( OFFSET> 3120 ) ( |<val>| ( |OBSERVE|  |Tom| +1        ) ) ) 
00222                      ( ( ONSET> 3120 ) ( OFFSET> 3180 ) ( |<val>| ( |ANNOUNCE| |Tom| 0         ) ) ) 
00223                      ( ( ONSET> 3300 ) ( OFFSET> 3480 ) ( |<val>| ( |COMMAND|  |Sam| |Tom| +1  ) ) ) 
00224                      ( ( ONSET> 3540 ) ( OFFSET> 3840 ) ( |<val>| ( |ACKNOWL|  |Tom| |Sam| -1  ) ) ) 
00225                      ( ( ONSET> 3840 ) ( OFFSET> 3960 ) ( |<val>| ( |ACKNOWL|  |Sam| |Tom| +1  ) ) ) 
00226                      ( ( ONSET> 4200 ) ( OFFSET> 4320 ) ( |<val>| ( |OBSERVE|  |Sam| 0         ) ) ) 
00227                      ( ( ONSET> 4500 ) ( OFFSET> 4680 ) ( |<val>| ( |ACKNOWL|  |Tom| |Sam| +1  ) ) ) 
00228                    )
00229                  )
00230                  ( VOCAB> ( |GOAL| |COMMAND| |ACKNOWL| |ANNOUNCE| |OBSERVE| |REASON| |PREDICT| ) )
00231                )
00232              )
00233            )
00234          )
00235        )
00236      )
00237      (
00238        QUERY>
00239        (
00240          ( 
00241            |query| 
00242            ( 
00243              |or| 
00244              ( |speechcode| |?o1| |<onset>| |<offset>| |?x| ) 
00245              ( |speechcode| |?o2| |<onset>| |<offset>| |?y| ) 
00246            ) 
00247            ( |print| |?x| ) 
00248          ) 
00249        )
00250      )
00251      ( SYSTEM>
00252        ( 
00253          (
00254            ALIGNMENTS>
00255            (
00256              (
00257                |&*=[^^an-alignment|
00258                (
00259                  ( TYPE>            <<MATRIX>> )
00260                  ( VARIABLE-LENGTH> FALSE  )
00261                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg1>| |<arg2>| |<status>| ) )
00262                  ( COLUMN-WIDTH>    200 )
00263                  (
00264                    CELLS>
00265                    (
00266                      ( ( ONSET>  0 ) ( OFFSET>    0 ) ( |<arg1>| |speechcode| ) ( |<arg2>| |speechcode| ) ( |<status>| 1 ) )  
00267                      ( ( ONSET> 30 ) ( OFFSET>    0 ) ( |<arg1>| ":pred" )      ( |<arg2>| ":pred" )      ( |<status>| 0 ) ) 
00268                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>|  1 )           ( |<arg2>|  1 )           ( |<status>| 0 ) ) 
00269                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>|  2 )           ( |<arg2>|  2 )           ( |<status>| 0 ) ) 
00270                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>|  3 )           ( |<arg2>|  3 )           ( |<status>| 0 ) ) 
00271                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>|  4 )           ( |<arg2>|  4 )           ( |<status>| 0 ) ) 
00272                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>|  5 )           ( |<arg2>|  5 )           ( |<status>| 0 ) ) 
00273                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>|  6 )           ( |<arg2>|  6 )           ( |<status>| 0 ) ) 
00274                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>|  7 )           ( |<arg2>|  7 )           ( |<status>| 0 ) ) 
00275                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>|  8 )           ( |<arg2>|  8 )           ( |<status>| 0 ) ) 
00276                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>|  9 )           ( |<arg2>|  9 )           ( |<status>| 0 ) ) 
00277                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>| 10 )           ( |<arg2>| 10 )           ( |<status>| 0 ) ) 
00278                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>| 11 )           ( |<arg2>| 11 )           ( |<status>| 0 ) ) 
00279                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>| 12 )           ( |<arg2>| 12 )           ( |<status>| 0 ) ) 
00280                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>| 13 )           ( |<arg2>| 13 )           ( |<status>| 0 ) ) 
00281                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>| 14 )           ( |<arg2>| 14 )           ( |<status>| 0 ) ) 
00282                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>| 15 )           ( |<arg2>| 15 )           ( |<status>| 0 ) ) 
00283                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>| 16 )           ( |<arg2>| 16 )           ( |<status>| 0 ) ) 
00284                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>| 17 )           ( |<arg2>| 17 )           ( |<status>| 0 ) ) 
00285                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>| 18 )           ( |<arg2>| 18 )           ( |<status>| 0 ) ) 
00286                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>| 19 )           ( |<arg2>| 19 )           ( |<status>| 0 ) ) 
00287                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>| 20 )           ( |<arg2>| 20 )           ( |<status>| 0 ) ) 
00288                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>| 21 )           ( |<arg2>| 21 )           ( |<status>| 0 ) ) 
00289                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>| 22 )           ( |<arg2>| 22 )           ( |<status>| 0 ) ) 
00290                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>| 23 )           ( |<arg2>| 23 )           ( |<status>| 0 ) ) 
00291                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>| 24 )           ( |<arg2>| 24 )           ( |<status>| 0 ) ) 
00292                    )
00293                  )
00294                )
00295              )
00296              (
00297                |&*=[^^another-alignment|
00298                (
00299                  ( TYPE>            <<MATRIX>> )
00300                  ( VARIABLE-LENGTH> FALSE  )
00301  ;                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg1>| |<arg2>| |<status>| ) )
00302                  ( COLUMN-WIDTH>    200 )
00303                  (
00304                    CELLS>
00305                    (
00306                      ( ( ONSET>  0 ) ( OFFSET>    0 ) ( |<arg1>| |state.var| ) ( |<arg2>| |state.var| ) ( |<status>| 1 ) ) 
00307                      ( ( ONSET> 30 ) ( OFFSET>    0 ) ( |<arg1>| ":<PARAM>" )  ( |<arg2>| ":<PARAM>" )  ( |<status>| 0 ) ) 
00308                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>| 1 )           ( |<arg2>| 1 )           ( |<status>| 0 ) ) 
00309                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>| 2 )           ( |<arg2>| 2 )           ( |<status>| 0 ) ) 
00310                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>| 3 )           ( |<arg2>| 3 )           ( |<status>| 0 ) ) 
00311                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>| 4 )           ( |<arg2>| 4 )           ( |<status>| 0 ) ) 
00312                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>| 5 )           ( |<arg2>| 5 )           ( |<status>| 0 ) ) 
00313                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>| 6 )           ( |<arg2>| 6 )           ( |<status>| 0 ) ) 
00314                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>| 7 )           ( |<arg2>| 7 )           ( |<status>| 0 ) ) 
00315                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>| 8 )           ( |<arg2>| 8 )           ( |<status>| 0 ) ) 
00316                      ( ( ONSET> 60 ) ( OFFSET>    0 ) ( |<arg1>| 9 )           ( |<arg2>| 9 )           ( |<status>| 0 ) ) 
00317                    )
00318                  )
00319                )
00320              )
00321            ) 
00322          )
00323          ( SHAPA-PANE-VARS> ( |verbal| |speechcode| |state.var| |sys.var| ) )
00324          ( GROUPS> 
00325            ( 
00326              ( ( |verbal|  1 ) ( |speechcode|  1 ) )
00327              ( ( |verbal|  2 ) ( |speechcode|  2 ) )
00328              ( ( |verbal|  3 ) ( |speechcode|  3 ) )
00329              ( ( |verbal|  4 ) ( |speechcode|  4 ) )
00330              ( ( |verbal|  5 ) ( |speechcode|  5 ) )
00331              ( ( |verbal|  6 ) ( |speechcode|  6 ) )
00332              ( ( |verbal|  7 ) ( |speechcode|  7 ) )
00333              ( ( |verbal|  8 ) ( |speechcode|  8 ) )
00334              ( ( |verbal|  9 ) ( |speechcode|  9 ) )
00335              ( ( |verbal| 10 ) ( |speechcode| 10 ) )
00336              ( ( |verbal| 11 ) ( |speechcode| 11 ) )
00337              ( ( |verbal| 12 ) ( |speechcode| 12 ) )
00338              ( ( |verbal| 13 ) ( |speechcode| 13 ) )
00339              ( ( |verbal| 14 ) ( |speechcode| 14 ) )
00340              ( ( |verbal| 15 ) ( |speechcode| 15 ) )
00341              ( ( |verbal| 16 ) ( |speechcode| 16 ) )
00342              ( ( |verbal| 17 ) ( |speechcode| 17 ) )
00343              ( ( |verbal| 18 ) ( |speechcode| 18 ) )
00344              ( ( |verbal| 19 ) ( |speechcode| 19 ) )
00345              ( ( |verbal| 20 ) ( |speechcode| 20 ) )
00346              ( ( |verbal| 21 ) ( |speechcode| 21 ) )
00347              ( ( |verbal| 22 ) ( |speechcode| 22 ) )
00348              ( ( |verbal| 23 ) ( |speechcode| 24 ) ( |speechcode| 23 ) ( |sys.var| 20 ) ( |verbal| 24 ) )
00349            )
00350          )
00351          ( IMPORT-FORMATS-LIST> ( ) )
00352        )
00353      )
00354    )
00355  )
00356  
