00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 0 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 
00019         ( 
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022              ( |pred_1| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| ) ) ) )
00023              ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )
00024              ( |pred_3| ) ; an empty predicate definition
00025              ( |pred_4| ' ) ; type mismatch

      WARNING  32 (Line 24:24): Encountered a predicate definition that appears to be missing its a-list.  The definition will be ignored.

00026              ( |pred_5| 

      WARNING  33 (Line 25:24): Type mis-match in the second item in a predicate definition.  This item must be an attribute list describing the predicate.
        The predicate definition will be discarded.

00027                ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) )
00028                (|an arbitrary list| "with a variety of values" 22 1.1) TRUE ; some excess values 
00029              )
00030              ( |pred_6| ; unexpected EOF

      WARNING  34 (Line 29:13): Encountered excess values in a predicate definition.  The excess values were discarded.

00031  ;              ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )
00032  ;          )
00033  ;        ) 
00034  ;        ( SPREADSHEET-VARIABLE-DECLARATIONS> 1 ) 
00035  ;        ( SPREADSHEET-VARIABLE-DEFINITIONS> 1 )
00036  ;      ) 
00037  ;    ) 
00038  ;    ( QUERY> 2 )
00039  ;    ( SYSTEM> 3 )
00040  ;  ) 
00041  ;)

      ERROR  4 (Line 41:0): Encountered end of file unexpectedly.
        EOF in a predicate definition.

Unable to continue parse -- Aborting...
