00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 2 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 


Current Header Settings:
db.name = "parser_test.db"
odb file format version = 1
warning limit = 50
error limit = 10
debug level = 2

00019        (
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022              ( |pred_1| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| ) ) ) )
00023              ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )


Predicate Definition:
	name = "pred_1"
	variable length = false
	arg 0 = "<arg1>"
	arg 1 = "<arg2>"

00024            )
00025          ) 


Predicate Definition:
	name = "pred_2"
	variable length = true
	arg 0 = "<arg1>"

00026          ( SPREADSHEET-VARIABLE-DECLARATIONS> 
00027            (
00028              ( |a text var| 
00029                ( 
00030                  ( TYPE> <<TEXT>> ) 
00031                  ( VARIABLE-LENGTH> FALSE )
00032                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) ) 
00033                  ( COLUMN-WIDTH> 200 ) 
00034                ) 
00035              )
00036              ( |a nominal var| 


Spreadsheet Variable Definition:
	name = "a text var"
	type = TEXT
	variable length = false
	column width = 200
00037                ( 
00038                  ( TYPE> <<NOMINAL>> ) 
00039                  ( VARIABLE-LENGTH> FALSE )
00040                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00041                  ( COLUMN-WIDTH> 200 ) 
00042                ) 
00043              )
00044              ( |an integer var| 


Spreadsheet Variable Definition:
	name = "a nominal var"
	type = NOMINAL
	variable length = false
	column width = 200
00045                ( 
00046                  ( TYPE> <<INTEGER>> ) 
00047                  ( VARIABLE-LENGTH> FALSE )
00048                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00049                  ( COLUMN-WIDTH> 200 ) 
00050                ) 
00051              )
00052              ( |a float var| 


Spreadsheet Variable Definition:
	name = "an integer var"
	type = INTEGER
	variable length = false
	column width = 200
00053                ( 
00054                  ( TYPE> <<FLOAT>> ) 
00055                  ( VARIABLE-LENGTH> FALSE )
00056                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00057                  ( COLUMN-WIDTH> 200 ) 
00058                ) 
00059              )
00060              ( |a predicate var| 


Spreadsheet Variable Definition:
	name = "a float var"
	type = FLOAT
	variable length = false
	column width = 200
00061                ( 
00062                  ( TYPE> <<PREDICATE>> ) 
00063                  ( VARIABLE-LENGTH> FALSE )
00064                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00065                  ( COLUMN-WIDTH> 200 ) 
00066                ) 
00067              )
00068              ( |fixed len matrix| 


Spreadsheet Variable Definition:
	name = "a predicate var"
	type = PREDICATE
	variable length = false
	column width = 200
00069                ( 
00070                  ( TYPE> <<MATRIX>> ) 
00071                  ( VARIABLE-LENGTH> FALSE )
00072                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg1>| |<arg2>| ) )  
00073                  ( COLUMN-WIDTH> 200 ) 
00074                ) 
00075              )
00076              ( |var len matrix| 


Spreadsheet Variable Definition:
	name = "fixed len matrix"
	type = MATRIX
	variable length = false
	column width = 200
00077                ( 
00078                  ( TYPE> <<MATRIX>> ) 
00079                  ( VARIABLE-LENGTH> TRUE )
00080                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg1>| |<arg2>| ) )  
00081                  ( COLUMN-WIDTH> 225 ) 
00082                ) 
00083              )
00084            ) 
00085          ) 


Spreadsheet Variable Definition:
	name = "var len matrix"
	type = MATRIX
	variable length = true
	column width = 225
00086          ( SPREADSHEET-VARIABLE-DEFINITIONS>
00087           ( 
00088              ( |a text var|
00089                ( 
00090                  ( CELLS>
00091                    ( 
00092                      (
00093                        ( ONSET>  0 ) 
00094                        ( OFFSET> 0 ) 
00095                        ( |<val>| "this is a text cell") 
00096                      )
00097                      ( 
00098                        ( ONSET>  60 ) 


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = this is a text cell
00099                        ( OFFSET> 60 ) 
00100                        ( |<val>| "") 
00101                      )
00102                    )
00103                  )
00104                )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 
00105              )
00106              
00107  
00108              ( |an integer var|
00109                (
00110                  ( CELLS>
00111                    (
00112                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| 10 ) )
00113                      ( 
00114                        ( ONSET> 60 )  


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 10
00115                        ( OFFSET> 60 ) 
00116                        ( |<val>| 0) 
00117                      )
00118                    )
00119                  )
00120                )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 0
00121              )
00122              ( |a float var|
00123                (
00124                  ( CELLS>
00125                    (
00126                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| 10.0 ) )
00127                      ( 
00128                        ( ONSET> 60 )  


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 10.000000
00129                        ( OFFSET> 60 ) 
00130                        ( |<val>| 0.0 ) 
00131                      )
00132                    )
00133                  )
00134                )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 0.000000
00135              )
00136              ( |a predicate var|
00137                (
00138                  ( CELLS>
00139                    (
00140                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| ( |pred_1| ( TIME> 120 ) |a nominal| ) ) )
00141                      ( ( ONSET> 10 ) ( OFFSET> 20 ) ( |<val>| ( |pred_1| "a string" |<arg2>| ) ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = pred_1(00:00:02:000, a nominal)
00142                      ( ( ONSET> 20 ) ( OFFSET> 30 ) ( |<val>| ( |pred_1| 10 1.0 ) ) )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:010
	offset = 00:00:00:020
	value = pred_1("a string", <arg2>)
00143                      ( ( ONSET> 30 ) ( OFFSET> 40 ) ( |<val>| ( |pred_1| ( |pred_2| |<arg1>| ) |<arg2>| ) ) )


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:020
	offset = 00:00:00:030
	value = pred_1(10, 1.000000)
00144                      ( 
00145                        ( ONSET> 60 ) 


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:00:030
	offset = 00:00:00:040
	value = pred_1(pred_2(<arg1>), <arg2>)
00146                        ( OFFSET> 60 ) 
00147                        ( |<val>| ( ) ) 
00148                      )
00149                    )
00150                  )
00151                  ( VOCAB> ( |pred_1| |pred_2| ) )


Spreadsheet Variable Cell Definition:
	ord = 5
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = ()
00152                )
00153              )
00154              ( |fixed len matrix|
00155                (
00156                  ( CELLS>
00157                    (
00158                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<arg1>| 1 ) ( |<arg2>| 2.0 ) )
00159                      ( ( ONSET> 10 ) ( OFFSET> 20 ) ( |<arg1>| |a nominal| ) ( |<arg2>| "a string" ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 1, 2.000000
00160                      ( ( ONSET> 20 ) ( OFFSET> 30 ) ( |<arg1>| ( |pred_2| |<arg1>| ) ) ( |<arg2>| ( TIME> 120 ) ) )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:010
	offset = 00:00:00:020
	value = a nominal, "a string"
00161                      ( 
00162                        ( ONSET> 60 ) 


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:020
	offset = 00:00:00:030
	value = pred_2(<arg1>), 00:00:02:000
00163                        ( OFFSET> 60 ) 
00164                        ( |<arg1>| |<arg1>| ) 
00165                        ( |<arg2>| |<arg2>| ) 
00166                      )
00167                      ( 
00168                        ( ONSET> 60 ) 


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = <arg1>, <arg2>
00169                        ( OFFSET> 60 ) 
00170                        ( |<arg1>| "first arg" ) 
00171                        ( |<arg2>| "second arg" ) 
00172                      )
00173                      ( 
00174                        ( ONSET> 61 ) 


Spreadsheet Variable Cell Definition:
	ord = 5
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = "first arg", "second arg"
00175                        ( OFFSET> 61 )
00176                        ( |<arg1>| "first arg" ) 
00177                        ( |<arg2>| "second arg" ) 
00178                      )
00179                      ( 
00180                        ( ONSET> 62 ) 


Spreadsheet Variable Cell Definition:
	ord = 6
	onset = 00:00:01:001
	offset = 00:00:01:001
	value = "first arg", "second arg"
00181                        ( OFFSET> 62 ) 
00182                        ( |<arg1>| "first arg" ) 
00183                        ( |<arg2>| "second arg" ) 
00184                      )
00185                      ( 
00186                        ( ONSET> 63 ) 


Spreadsheet Variable Cell Definition:
	ord = 7
	onset = 00:00:01:002
	offset = 00:00:01:002
	value = "first arg", "second arg"
00187                        ( OFFSET> 63 )
00188                        ( |<arg1>| "first arg" ) 
00189                        ( |<arg2>| "second arg" ) 
00190                      )
00191                    )
00192                  )
00193                  ( VOCAB> ( |pred_1| |pred_2| ) ) 


Spreadsheet Variable Cell Definition:
	ord = 8
	onset = 00:00:01:003
	offset = 00:00:01:003
	value = "first arg", "second arg"
00194                )
00195              )
00196              ( |var len matrix|
00197                (
00198                  ( CELLS>
00199                    (
00200                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<arg1>| 1 ) ( |<arg2>| 2.0 ) )
00201                      ( ( ONSET> 10 ) ( OFFSET> 20 ) ( |<arg1>| |a nominal| ) ( |<arg2>| "a string" ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 1, 2.000000
00202                      ( ( ONSET> 20 ) ( OFFSET> 30 ) ( |<arg1>| ( |pred_2| |<arg1>| ) ) ( |<arg2>| ( TIME> 120 ) ) )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:010
	offset = 00:00:00:020
	value = a nominal, "a string"
00203                      ( ( ONSET> 60 ) ( OFFSET> 60 ) ( |<arg1>| |<arg1>| ) )


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:020
	offset = 00:00:00:030
	value = pred_2(<arg1>), 00:00:02:000
00204                      ( ( ONSET> 60 ) ( OFFSET> 60 ) ( |<arg1>| |<arg1>| ) ( |<arg2>| |<arg2>| ) )


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = <arg1>, <arg2>
00205                      ( 
00206                        ( ONSET> 61 ) 


Spreadsheet Variable Cell Definition:
	ord = 5
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = <arg1>, <arg2>
00207                        ( OFFSET> 61 ) 
00208                        ( |<arg1>| "first arg" ) 
00209                        ( |<arg2>| "second arg" ) 
00210                      )
00211                      ( 
00212                        ( ONSET> 62 ) 


Spreadsheet Variable Cell Definition:
	ord = 6
	onset = 00:00:01:001
	offset = 00:00:01:001
	value = "first arg", "second arg"
00213                        ( OFFSET> 62 ) 
00214                        ( |<arg1>| "first arg" ) 
00215                        ( |<arg2>| "second arg" ) 
00216                      )
00217                      ( 
00218                        ( ONSET> 63 ) 


Spreadsheet Variable Cell Definition:
	ord = 7
	onset = 00:00:01:002
	offset = 00:00:01:002
	value = "first arg", "second arg"
00219                        ( OFFSET> 63 ) 
00220                        ( |<arg1>| "first arg" ) 
00221                        ( |<arg2>| "second arg" ) 
00222                      )
00223                      ( 
00224                        ( ONSET> 64 ) 


Spreadsheet Variable Cell Definition:
	ord = 8
	onset = 00:00:01:003
	offset = 00:00:01:003
	value = "first arg", "second arg"
00225                        ( OFFSET> 64 ) 
00226                        ( |<arg1>| "first arg" ) 
00227                        ( |<arg2>| "second arg" ) 
00228                      )
00229                    )
00230                  )
00231                  ( VOCAB> ( |pred_1| |pred_2| ) )


Spreadsheet Variable Cell Definition:
	ord = 9
	onset = 00:00:01:004
	offset = 00:00:01:004
	value = "first arg", "second arg"
00232                )
00233              )
00234              
00235              ( |a nominal var|
00236                (
00237                  ( CELLS>
00238                    (
00239                      ( 
00240                        ( ONSET> 0 ) 
00241                        ( OFFSET> 0 ) 
00242                        ( |<val>| |this is nominal cell| ) 
00243                      )
00244                      ( 
00245                        ( ONSET> 60 )  


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = this is nominal cell
00246                        ( OFFSET> 60 ) 
00247                        ( |<val>| |<val>| ) 
00248                      )
00249                      ( 
00250                        ( ONSET> 61 )  


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 
00251                        ( OFFSET> 61 ) 
00252                        ( |<val>| ) ; an empty nominal cell value
00253                      )
00254                      ( 

      WARNING  65 (Line 252:33): Encountered a cell value whose value appears to be missing.
        The nominal cell will be left undefined.

00255                        ( ONSET> 62 )  


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:01:001
	offset = 00:00:01:001
	value = 
00256                        ( OFFSET> 62 ) 
00257                        ( |<val>| |<val1>| ) ; formal arg name mismatch
00258                      )

      WARNING  66 (Line 257:33): Encountered a formal argument whose name does not match the expected formal argumentname.
        Mismatch occured in a nominal cell value.  The cell will be left undefined.

00259                      ( 
00260                        ( ONSET> 63 )  


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:01:002
	offset = 00:00:01:002
	value = 
00261                        ( OFFSET> 63 ) 
00262                        ( |<val>| |this nominal ends with a colon:| ) 
00263                      )

      WARNING  67 (Line 262:33): Nominals that appear as the value of cells in nominal spreadsheet variables cannot contain the characters '|' and ':'.
        These characters were coerced to '_', and the result used as the nominal cell value.
00264                      ( 
00265                        ( ONSET> 64 )  


Spreadsheet Variable Cell Definition:
	ord = 5
	onset = 00:00:01:003
	offset = 00:00:01:003
	value = this nominal ends with a colon_
00266                        ( OFFSET> 64 ) 
00267                        ( |<val>| |this one ends with a vertical bar \|| ) 
00268                      )

      WARNING  67 (Line 267:33): Nominals that appear as the value of cells in nominal spreadsheet variables cannot contain the characters '|' and ':'.
        These characters were coerced to '_', and the result used as the nominal cell value.
00269                      ( 
00270                        ( ONSET> 65 )  


Spreadsheet Variable Cell Definition:
	ord = 6
	onset = 00:00:01:004
	offset = 00:00:01:004
	value = this one ends with a vertical bar _
00271                        ( OFFSET> 65 ) 
00272                        ( |<val>| 33 ) ; nominal cell type mismatch
00273                      )

      WARNING  64 (Line 272:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Will discard the value && leave the nominal cell undefined.

00274                      ( 
00275                        ( ONSET> 66 )  


Spreadsheet Variable Cell Definition:
	ord = 7
	onset = 00:00:01:005
	offset = 00:00:01:005
	value = 
00276                        ( OFFSET> 66 ) 
00277                        ( |<val>| ( |an arbitraty| "list of" 4 "elements" ) ) 

      WARNING  64 (Line 277:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        The value is a list, which will be discarded. The nominal cell will be left undefined.

00278                      )
00279                      ( 
00280                        ( ONSET> 67 )  


Spreadsheet Variable Cell Definition:
	ord = 8
	onset = 00:00:01:006
	offset = 00:00:01:006
	value = 
00281                        ( OFFSET> 67 ) 
00282                        ( 
00283                          |<val>|
00284                          ; unexpected EOF in a nominal cell value 
00285  ;                        |a nominal| 
00286  ;                      ) 
00287  ;                    )
00288  ;                  )
00289  ;                )
00290  ;              )
00291  ;            )
00292  ;          )
00293  ;        )
00294  ;      ) 
00295  ;    ) 
00296  ;    ( QUERY> 2 )
00297  ;    ( SYSTEM> 3 )
00298  ;  ) 
00299  ;)

      ERROR  4 (Line 299:0): Encountered end of file unexpectedly.
        EOF in a nominal cell value.

Unable to continue parse -- Aborting...
