
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  65 (Line 258:33): Encountered a cell value whose value appears to be missing.
        The integer cell will be set to zero.


      WARNING  64 (Line 263:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Coerced the floating point value to the nearest legal integer cell value.


      WARNING  64 (Line 268:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Coerced the floating point value to the nearest legal integer cell value.


      WARNING  64 (Line 273:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Coerced the floating point value to the nearest legal integer cell value.


      WARNING  64 (Line 278:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Coerced the floating point value to the nearest legal integer cell value.


      WARNING  64 (Line 283:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Coerced the floating point value to the nearest legal integer cell value.


      WARNING  64 (Line 288:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Will discard the value && set the value of the integer cell to zero.


      WARNING  64 (Line 293:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        The value is a list, which will be discarded.  The integer cell will be set to zero.


      ERROR  4 (Line 325:0): Encountered end of file unexpectedly.
        EOF in an integer cell value.

Unable to continue parse -- Aborting...
