00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 0 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 
00019         1 ; type mismatch for value of the user section
00020         ("a random list" setf ' 3.3) macshapa-db |a_symbol| ; excess values in the user section

      WARNING  22 (Line 19:8): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> section must be a list.

00021  ;      (
00022  ;        ( PREDICATE-DEFINITIONS> 
00023  ;          (
00024  ;            ( |pred_1| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| ) ) ) )
00025  ;            ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )
00026  ;          ) 
00027  ;        )
00028  ;        ( SPREADSHEET-VARIABLE-DECLARATIONS> 1 )
00029  ;        ( SPREADSHEET-VARIABLE-DEFINITIONS> 1 )
00030  ;      )
00031      ) 
00032      ( QUERY> 2 )

      WARNING  16 (Line 31:5): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered in the USER> section.

00033      ( SYSTEM> 3 )

      WARNING  22 (Line 32:14): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the QUERY> section must be a list.

00034    ) 
00035  )
