00001  ; MacSHAPA Open Database
00002  ;
00003  ; The following comment is a test of the segmentation algorithm used to cut strings into
00004  ; chunks of size acceptable to the log file function.  This test is only active if maxChunkSize
00005  ; in CODBListingPane::BufferedWrite() is set to a small value (i.e. 10).
00006  ;
00007  ; abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
00008  ; abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0
00009  ; abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01
00010  ; abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ012
00011  ; abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123
00012  ; abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234
00013  ; abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ012345
00014  ; abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456
00015  ; abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567
00016  ; abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ012345678
00017  ; abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
00018  ;
00019  ; test over
00020  ;
00021  ( setf macshapa-db 
00022   '( 
00023      ( HEADER>
00024        ( 
00025          ( VERSION> 1 ) 
00026          ( NAME> "parser_test.db" )
00027          ;( DEBUG-LEVEL> 2 ) 
00028          ( MAX-ERRORS> 20 )
00029          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 28:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00030        )
00031      )
00032      (
00033        USER>
00034        (
00035          (
00036            PREDICATE-DEFINITIONS>
00037            (
00038              ( 
00039                |GOAL| 
00040                ( 
00041                  ( VARIABLE-LENGTH> FALSE )
00042                  ( FORMAL-ARG-LIST> ( |<TEMPERATURE>| |<VOLUME>| |<FLOWRATE>| ) ) 
00043                )
00044              )
00045              ( 
00046                |COMMAND|
00047                (
00048                  ( VARIABLE-LENGTH> FALSE )
00049                  ( FORMAL-ARG-LIST> ( |<SPEAKER>| |<TO>| |<MITIGATION>| ) ) 
00050                )
00051              )
00052              ( 
00053                |ACKNOWL|
00054                (
00055                  ( VARIABLE-LENGTH> FALSE )
00056                  ( FORMAL-ARG-LIST> ( |<SPEAKER>| |<TO>| |<MITIGATION>| ) ) 
00057                )
00058              )
00059              ( 
00060                |ANNOUNCE|
00061                (
00062                  ( VARIABLE-LENGTH> FALSE )
00063                  ( FORMAL-ARG-LIST> ( |<SPEAKER>| |<MITIGATION>| ) ) 
00064                )
00065              )
00066              ( 
00067                |OBSERVE|
00068                (
00069                  ( VARIABLE-LENGTH> FALSE )
00070                  ( FORMAL-ARG-LIST> ( |<SPEAKER>| |<MITIGATION>| ) ) 
00071                )
00072              )
00073              ( 
00074                |REASON|
00075                (
00076                  ( VARIABLE-LENGTH> FALSE )
00077                  ( FORMAL-ARG-LIST> ( |<SPEAKER>| |<MITIGATION>| ) ) 
00078                )
00079              )
00080              ( 
00081                |PREDICT|
00082                (
00083                  ( VARIABLE-LENGTH> FALSE )
00084                  ( FORMAL-ARG-LIST> ( |<SPEAKER>| |<MITIGATION>| ) ) 
00085                )
00086              )
00087            )
00088          )
00089          (
00090            SPREADSHEET-VARIABLE-DECLARATIONS>
00091            (
00092              (
00093                |verbal|
00094                (
00095                  ( TYPE>            <<TEXT>> )
00096                  ( VARIABLE-LENGTH> FALSE  )
00097                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
00098                  ( COLUMN-WIDTH>    183 )
00099                )
00100              )
00101              (
00102                |state.var|
00103                (
00104                  ( TYPE>            <<MATRIX>> )
00105                  ( VARIABLE-LENGTH> FALSE  )
00106                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<PARAM>| |<SUBSYS>| |<VAL>| ) )
00107                  ( COLUMN-WIDTH>    183 )
00108                )
00109              )
00110              (
00111                |sys.var|
00112                (
00113                  ( TYPE>            <<MATRIX>> )
00114                  ( VARIABLE-LENGTH> FALSE  )
00115                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<PARAM>| |<SUBSYS>| |<VAL>| ) )
00116                  ( COLUMN-WIDTH>    200 )
00117                )
00118              )
00119              (
00120                |speechcode|
00121                (
00122                  ( TYPE>            <<PREDICATE>> )
00123                  ( VARIABLE-LENGTH> FALSE  )
00124                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
00125                  ( COLUMN-WIDTH>    200 )
00126                )
00127              )
00128            )
00129          )
00130          (
00131            SPREADSHEET-VARIABLE-DEFINITIONS>
00132            (
00133              (
00134                |verbal|
00135                (
00136                  (
00137                    CELLS>
00138                    (
00139                      ( ( ONSET>   60 ) ( OFFSET>  360 ) ( |<val>| "Expter:  Please try to increase temperature, increase volume and increase flowrate." ) ) 
00140                      ( ( ONSET>  420 ) ( OFFSET>  540 ) ( |<val>| "Sam:  Tom, you can do the hydraulic side and I'll do the heat side." ) ) 
00141                      ( ( ONSET>  600 ) ( OFFSET>  660 ) ( |<val>| "Tom:  If you like." ) ) 
00142                      ( ( ONSET>  660 ) ( OFFSET>  780 ) ( |<val>| "Sam:  I'll set heater up to 8 for now." ) ) 
00143                      ( ( ONSET>  780 ) ( OFFSET> 1260 ) ( |<val>| "Tom:  OK.  First to increase flowrate I'm going to open the input valve a bit more and open up the output valve." ) ) 
00144                      ( ( ONSET> 1260 ) ( OFFSET> 1440 ) ( |<val>| "Sam:  OK, volume is starting to increase..." ) ) 
00145                      ( ( ONSET> 1440 ) ( OFFSET> 1560 ) ( |<val>| "Sam:  ...and so is flow rate." ) ) 
00146                      ( ( ONSET> 1680 ) ( OFFSET> 1800 ) ( |<val>| "Sam:  Nothing happening so far on temperature..." ) ) 
00147                      ( ( ONSET> 1800 ) ( OFFSET> 1860 ) ( |<val>| "Sam:  ...so I'll send it up to 9." ) ) 
00148                      ( ( ONSET> 1920 ) ( OFFSET> 2040 ) ( |<val>| "Sam:  You haven't done anything to the mixer value and volume is going up pretty fast." ) ) 
00149                      ( ( ONSET> 2160 ) ( OFFSET> 2220 ) ( |<val>| "Tom:  Oh sorry...I always forget that!" ) ) 
00150                      ( ( ONSET> 2280 ) ( OFFSET> 2400 ) ( |<val>| "Tom:  I wonder why the flow rate is decreasing?" ) ) 
00151                      ( ( ONSET> 2460 ) ( OFFSET> 2520 ) ( |<val>| "Tom:  I increased input and output so flow rate should increase." ) ) 
00152                      ( ( ONSET> 2580 ) ( OFFSET> 2700 ) ( |<val>| "Tom:  Oh!  It's because I forgot to open the mixer valve." ) ) 
00153                      ( ( ONSET> 2700 ) ( OFFSET> 2880 ) ( |<val>| "Tom:  So flow rate should increase in a minute or two." ) ) 
00154                      ( ( ONSET> 2760 ) ( OFFSET> 2820 ) ( |<val>| "Sam:  There the temperature goes!" ) ) 
00155                      ( ( ONSET> 2880 ) ( OFFSET> 3000 ) ( |<val>| "Tom:  ...and that's what it's doing." ) ) 
00156                      ( ( ONSET> 3000 ) ( OFFSET> 3120 ) ( |<val>| "Tom:  Oh hell!  It's going down again." ) ) 
00157                      ( ( ONSET> 3120 ) ( OFFSET> 3180 ) ( |<val>| "Tom:  So I'll open the output a bit." ) ) 
00158                      ( ( ONSET> 3300 ) ( OFFSET> 3480 ) ( |<val>| "Sam:  Why don't you let it settle rather than keeping on playing with it?" ) ) 
00159                      ( ( ONSET> 3540 ) ( OFFSET> 3840 ) ( |<val>| "Tom:  Oh well...I don't think I play with it too much." ) ) 
00160                      ( ( ONSET> 3840 ) ( OFFSET> 3960 ) ( |<val>| "Sam:  You do, you know." ) ) 
00161                      ( ( ONSET> 4200 ) ( OFFSET> 4320 ) ( |<val>| "Sam:  Temperature's still rising." ) ) 
00162                      ( ( ONSET> 4500 ) ( OFFSET> 4680 ) ( |<val>| "Tom:  You've confused me about the flowrate now, Sam!" ) ) 
00163                    )
00164                  )
00165                )
00166              )
00167              (
00168                |state.var|
00169                (
00170                  (
00171                    CELLS>
00172                    (
00173                      ( ( ONSET>    0 ) ( OFFSET>    0 ) ( |<PARAM>| |M| ) ( |<SUBSYS>| |L| ) ( |<VAL>| 5 ) ) 
00174                      ( ( ONSET>    0 ) ( OFFSET>    0 ) ( |<PARAM>| |I| ) ( |<SUBSYS>| |A| ) ( |<VAL>| 5 ) ) 
00175                      ( ( ONSET>    0 ) ( OFFSET>    0 ) ( |<PARAM>| |O| ) ( |<SUBSYS>| |A| ) ( |<VAL>| 1 ) ) 
00176                      ( ( ONSET>    0 ) ( OFFSET>    0 ) ( |<PARAM>| |H| ) ( |<SUBSYS>| |A| ) ( |<VAL>| 5 ) ) 
00177                      ( ( ONSET>  660 ) ( OFFSET>  720 ) ( |<PARAM>| |H| ) ( |<SUBSYS>| |A| ) ( |<VAL>| 9 ) ) 
00178                      ( ( ONSET> 1140 ) ( OFFSET> 1260 ) ( |<PARAM>| |O| ) ( |<SUBSYS>| |A| ) ( |<VAL>| 8 ) ) 
00179                      ( ( ONSET> 1260 ) ( OFFSET> 1380 ) ( |<PARAM>| |I| ) ( |<SUBSYS>| |A| ) ( |<VAL>| 8 ) ) 
00180                      ( ( ONSET> 1800 ) ( OFFSET> 1920 ) ( |<PARAM>| |H| ) ( |<SUBSYS>| |A| ) ( |<VAL>| 9 ) ) 
00181                      ( ( ONSET> 2460 ) ( OFFSET> 2580 ) ( |<PARAM>| |M| ) ( |<SUBSYS>| |L| ) ( |<VAL>| 8 ) ) 
00182                    )
00183                  )
00184                  ( VOCAB> ( ) )
00185                )
00186              )
00187              (
00188                |sys.var|
00189                (
00190                  (
00191                    CELLS>
00192                    (
00193                      ( ( ONSET>    0 ) ( OFFSET> 1320 ) ( |<PARAM>| |V|  ) ( |<SUBSYS>| |A| ) ( |<VAL>| 21 ) ) 
00194                      ( ( ONSET>    0 ) ( OFFSET> 1440 ) ( |<PARAM>| |FR| ) ( |<SUBSYS>| |A| ) ( |<VAL>|  5 ) ) 
00195                      ( ( ONSET>    0 ) ( OFFSET> 2760 ) ( |<PARAM>| |T|  ) ( |<SUBSYS>| |A| ) ( |<VAL>|  3 ) ) 
00196                      ( ( ONSET> 1320 ) ( OFFSET> 1500 ) ( |<PARAM>| |V|  ) ( |<SUBSYS>| |A| ) ( |<VAL>| 22 ) ) 
00197                      ( ( ONSET> 1440 ) ( OFFSET> 1680 ) ( |<PARAM>| |FR| ) ( |<SUBSYS>| |A| ) ( |<VAL>|  6 ) ) 
00198                      ( ( ONSET> 1500 ) ( OFFSET> 1860 ) ( |<PARAM>| |V|  ) ( |<SUBSYS>| |A| ) ( |<VAL>| 23 ) ) 
00199                      ( ( ONSET> 1680 ) ( OFFSET> 1920 ) ( |<PARAM>| |FR| ) ( |<SUBSYS>| |A| ) ( |<VAL>|  5 ) ) 
00200                      ( ( ONSET> 1860 ) ( OFFSET> 1980 ) ( |<PARAM>| |V|  ) ( |<SUBSYS>| |A| ) ( |<VAL>| 24 ) ) 
00201                      ( ( ONSET> 1920 ) ( OFFSET> 2760 ) ( |<PARAM>| |FR| ) ( |<SUBSYS>| |A| ) ( |<VAL>|  4 ) ) 
00202                      ( ( ONSET> 1980 ) ( OFFSET> 2040 ) ( |<PARAM>| |V|  ) ( |<SUBSYS>| |A| ) ( |<VAL>| 25 ) ) 
00203                      ( ( ONSET> 2040 ) ( OFFSET> 2580 ) ( |<PARAM>| |V|  ) ( |<SUBSYS>| |A| ) ( |<VAL>| 26 ) ) 
00204                      ( ( ONSET> 2580 ) ( OFFSET> 4800 ) ( |<PARAM>| |V|  ) ( |<SUBSYS>| |A| ) ( |<VAL>| 25 ) ) 
00205                      ( ( ONSET> 2760 ) ( OFFSET> 2820 ) ( |<PARAM>| |FR| ) ( |<SUBSYS>| |A| ) ( |<VAL>|  5 ) ) 
00206                      ( ( ONSET> 2760 ) ( OFFSET> 2880 ) ( |<PARAM>| |T|  ) ( |<SUBSYS>| |A| ) ( |<VAL>| 24 ) ) 
00207                      ( ( ONSET> 2820 ) ( OFFSET> 2880 ) ( |<PARAM>| |FR| ) ( |<SUBSYS>| |A| ) ( |<VAL>|  6 ) ) 
00208                      ( ( ONSET> 2880 ) ( OFFSET> 3300 ) ( |<PARAM>| |FR| ) ( |<SUBSYS>| |A| ) ( |<VAL>|  5 ) ) 
00209                      ( ( ONSET> 2880 ) ( OFFSET> 4200 ) ( |<PARAM>| |T|  ) ( |<SUBSYS>| |A| ) ( |<VAL>| 25 ) ) 
00210                      ( ( ONSET> 3300 ) ( OFFSET> 3780 ) ( |<PARAM>| |FR| ) ( |<SUBSYS>| |A| ) ( |<VAL>|  4 ) ) 
00211                      ( ( ONSET> 3780 ) ( OFFSET> 4800 ) ( |<PARAM>| |FR| ) ( |<SUBSYS>| |A| ) ( |<VAL>|  3 ) ) 
00212                      ( ( ONSET> 4200 ) ( OFFSET> 4800 ) ( |<PARAM>| |T|  ) ( |<SUBSYS>| |A| ) ( |<VAL>| 26 ) ) 
00213                    )
00214                  )
00215                  ( VOCAB> ( ) )
00216                )
00217              )
00218              ( |speechcode|
00219                (
00220                  (
00221                    CELLS>
00222                    (
00223                      ( ( ONSET>   60 ) ( OFFSET>  360 ) ( |<val>| ( |GOAL|     |+|   |+|   |+| ) ) ) 
00224                      ( ( ONSET>  420 ) ( OFFSET>  540 ) ( |<val>| ( |COMMAND|  |Sam| |Tom| +1  ) ) )
00225                      ( ( ONSET>  600 ) ( OFFSET>  660 ) ( |<val>| ( |ACKNOWL|  |Tom| |Sam| -1  ) ) ) 
00226                      ( ( ONSET>  660 ) ( OFFSET>  780 ) ( |<val>| ( |ANNOUNCE| |Sam| 0         ) ) ) 
00227                      ( ( ONSET>  780 ) ( OFFSET> 1260 ) ( |<val>| ( |ANNOUNCE| |Tom| 0         ) ) ) 
00228                      ( ( ONSET> 1260 ) ( OFFSET> 1440 ) ( |<val>| ( |OBSERVE|  |Sam| 0         ) ) ) 
00229                      ( ( ONSET> 1440 ) ( OFFSET> 1560 ) ( |<val>| ( |OBSERVE|  |Sam| 0         ) ) ) 
00230                      ( ( ONSET> 1680 ) ( OFFSET> 1800 ) ( |<val>| ( |OBSERVE|  |Sam| 0         ) ) ) 
00231                      ( ( ONSET> 1800 ) ( OFFSET> 1860 ) ( |<val>| ( |ANNOUNCE| |Sam| 0         ) ) ) 
00232                      ( ( ONSET> 1920 ) ( OFFSET> 2040 ) ( |<val>| ( |COMMAND|  |Sam| |Tom| -1  ) ) ) 
00233                      ( ( ONSET> 2160 ) ( OFFSET> 2220 ) ( |<val>| ( |ACKNOWL|  |Tom| |Sam| -1  ) ) ) 
00234                      ( ( ONSET> 2280 ) ( OFFSET> 2400 ) ( |<val>| ( |OBSERVE|  |Tom| -1        ) ) ) 
00235                      ( ( ONSET> 2460 ) ( OFFSET> 2520 ) ( |<val>| ( |REASON|   |Tom| 0         ) ) ) 
00236                      ( ( ONSET> 2580 ) ( OFFSET> 2700 ) ( |<val>| ( |REASON|   |Tom| 0         ) ) ) 
00237                      ( ( ONSET> 2700 ) ( OFFSET> 2880 ) ( |<val>| ( |PREDICT|  |Tom| 0         ) ) ) 
00238                      ( ( ONSET> 2760 ) ( OFFSET> 2820 ) ( |<val>| ( |OBSERVE|  |Sam| 0         ) ) ) 
00239                      ( ( ONSET> 2880 ) ( OFFSET> 3000 ) ( |<val>| ( |OBSERVE|  |Tom| 0         ) ) ) 
00240                      ( ( ONSET> 3000 ) ( OFFSET> 3120 ) ( |<val>| ( |OBSERVE|  |Tom| +1        ) ) ) 
00241                      ( ( ONSET> 3120 ) ( OFFSET> 3180 ) ( |<val>| ( |ANNOUNCE| |Tom| 0         ) ) ) 
00242                      ( ( ONSET> 3300 ) ( OFFSET> 3480 ) ( |<val>| ( |COMMAND|  |Sam| |Tom| +1  ) ) ) 
00243                      ( ( ONSET> 3540 ) ( OFFSET> 3840 ) ( |<val>| ( |ACKNOWL|  |Tom| |Sam| -1  ) ) ) 
00244                      ( ( ONSET> 3840 ) ( OFFSET> 3960 ) ( |<val>| ( |ACKNOWL|  |Sam| |Tom| +1  ) ) ) 
00245                      ( ( ONSET> 4200 ) ( OFFSET> 4320 ) ( |<val>| ( |OBSERVE|  |Sam| 0         ) ) ) 
00246                      ( ( ONSET> 4500 ) ( OFFSET> 4680 ) ( |<val>| ( |ACKNOWL|  |Tom| |Sam| +1  ) ) ) 
00247                    )
00248                  )
00249                  ( VOCAB> ( |GOAL| |COMMAND| |ACKNOWL| |ANNOUNCE| |OBSERVE| |REASON| |PREDICT| ) )
00250                )
00251              )
00252            )
00253          )
00254        )
00255      )
00256      (
00257        QUERY>
00258        (
00259          ( 
00260            |query| 
00261            ( 
00262              |or| 
00263              ( |speechcode| |?o1| |<onset>| |<offset>| |?x| ) 
00264              ( |speechcode| |?o2| |<onset>| |<offset>| |?y| ) 
00265            ) 
00266            ( |print| |?x| ) 
00267          ) 
00268        )
00269      )
00270      ( SYSTEM> 19 ; integer instead of the expected list
00271        ( 
00272          ( ALIGNMENTS> ( ) )

      WARNING  22 (Line 270:15): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the SYSTEM> section must be a list.

00273          ( SHAPA-PANE-VARS> ( |verbal| |speechcode| |state.var| |sys.var| ) )
00274          ( GROUPS> ( ) )
00275          ( IMPORT-FORMATS-LIST> ( ) )
00276        ) 
00277      )
00278    )
00279  )

      WARNING  16 (Line 277:5): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered in the SYSTEM> section.

00280  
