
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  14 (Line 24:73): Encountered a-list entry without a value.  A-list entries must be of the form '(' <tag> <value> ')'.
        A FORMAL-ARG-LIST> attribute appears not to contain a value.  Value forced to (|<val>|).


      WARNING  38 (Line 24:77): Encountered a duplicate definition of a predicate.  The second definition will be ignored.
        New definition doesn't match old definition -- formal argument name mismatch.  New definition ignored.

      WARNING  22 (Line 25:73): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the FORMAL-ARG-LIST> attribute must be a list of formal arguments.  Value forced to (|<val>|).


      WARNING  38 (Line 25:83): Encountered a duplicate definition of a predicate.  The second definition will be ignored.
        New definition doesn't match old definition -- formal argument name mismatch.  New definition ignored.

      WARNING  16 (Line 26:95): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered a FORMAL-ARG-LIST> attribute.


      ERROR  4 (Line 37:0): Encountered end of file unexpectedly.
        EOF in a FORMAL-ARG-LIST> attribute.

Unable to continue parse -- Aborting...
