
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING   9 (Line 90:19): Left parentheses expected.  Left parenthesis inserted to allow continued parse.
        The opening left parenthesis of a spreadsheet variable definition a-list appears to be missing.


      WARNING  20 (Line 101:16): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in a spreadsheet variable definition a-list.


      WARNING  60 (Line 119:19): Encountered VOCAB> attribute in the definition of a spreadsheet variable that is notof either <<MATRIX>> or <<PREDICATE>> type.
        The VOCAB> attribute will be discarded.


      WARNING  29 (Line 132:13): A required a-list entry appears to be missing.  Will attempt to proceed with a default value.  Errors may result.
        CELLS> entry missing from a spreadsheet variable definition?


      ERROR  4 (Line 203:0): Encountered end of file unexpectedly.
        EOF occurred in a spreadsheet variable definition a-list.

Unable to continue parse -- Aborting...
