
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  47 (Line 32:33): The integer value associated with a COLUMN-WIDTH> attribute is out of range.  The value will be forced to the nearest legal value.


      WARNING  47 (Line 40:33): The integer value associated with a COLUMN-WIDTH> attribute is out of range.  The value will be forced to the nearest legal value.


      WARNING  14 (Line 48:34): Encountered a-list entry without a value.  A-list entries must be of the form '(' <tag> <value> ')'.
        A COLUMN-WIDTH> attribute appears not to contain a value.  Default value used.


      WARNING  22 (Line 56:33): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the COLUMN-WIDTH> attribute must be an integer.  Default value used.


      WARNING  22 (Line 64:33): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the COLUMN-WIDTH> attribute must be an integer.  Default value used.


      ERROR  4 (Line 83:0): Encountered end of file unexpectedly.
        EOF in a COLUMN-WIDTH> attribute.
Unable to continue parse -- Aborting...
