
      WARNING  14 (Line 8:32): Encountered a-list entry without a value.  A-list entries must be of the form '(' <tag> <value> ')'.
        The HEADER> section appears not to contain a value.


      WARNING  22 (Line 9:30): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> section must be a list.


      WARNING  22 (Line 10:31): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the QUERY> section must be a list.

