00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 0 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 
00019         ( 
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022              ( 
00023                |pred_1| 
00024                ;( ; missing opening paren in pred def a-list
00025                  ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| ) ) 

      WARNING   9 (Line 25:19): Left parentheses expected.  Left parenthesis inserted to allow continued parse.
        The opening left parenthesis of a predicate definition a-list appears to be missing.

00026                ) 
00027              )
00028              ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )
00029            )
00030          ) 
00031          ( SPREADSHEET-VARIABLE-DECLARATIONS> 1 ) 
00032          ( SPREADSHEET-VARIABLE-DEFINITIONS> 1 )

      WARNING  22 (Line 31:46): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> SPREADSHEET-VARIABLE-DECLARATIONS> a-list entry must be a (possibly empty) list of spreadsheet variable declarations.

00033        ) 

      WARNING  22 (Line 32:45): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> SPREADSHEET-VARIABLE-DEFINITIONS> a-list entry must be a (possibly empty) list of spreadsheet variable definitions.

00034      ) 
00035      ( QUERY> 2 )
00036      ( SYSTEM> 3 )

      WARNING  22 (Line 35:14): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the QUERY> section must be a list.

00037    ) 
00038  )
