00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 0 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 
00019         ( 
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022              ( |pred_1| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| ) ) ) )
00023              ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )
00024              ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST>  ) ) )              ; missing formal arg list

      WARNING  14 (Line 24:73): Encountered a-list entry without a value.  A-list entries must be of the form '(' <tag> <value> ')'.
        A FORMAL-ARG-LIST> attribute appears not to contain a value.  Value forced to (|<val>|).

00025              ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST>  TRUE  ) ) )      ;type mismatch in formal arg list attribute

      WARNING  38 (Line 24:77): Encountered a duplicate definition of a predicate.  The second definition will be ignored.
        New definition doesn't match old definition -- formal argument name mismatch.  New definition ignored.

      WARNING  22 (Line 25:73): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the FORMAL-ARG-LIST> attribute must be a list of formal arguments.  Value forced to (|<val>|).

00026              ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) () 33 TRUE) ) )  ; excess values

      WARNING  38 (Line 25:83): Encountered a duplicate definition of a predicate.  The second definition will be ignored.
        New definition doesn't match old definition -- formal argument name mismatch.  New definition ignored.

      WARNING  16 (Line 26:95): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered a FORMAL-ARG-LIST> attribute.

00027              ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ; unexpected EOF ( |<arg1>| ) ) ) )
00028  ;          )
00029  ;        ) 
00030  ;        ( SPREADSHEET-VARIABLE-DECLARATIONS> 1 ) 
00031  ;        ( SPREADSHEET-VARIABLE-DEFINITIONS> 1 )
00032  ;      ) 
00033  ;    ) 
00034  ;    ( QUERY> 2 )
00035  ;    ( SYSTEM> 3 )
00036  ;  ) 
00037  ;)

      ERROR  4 (Line 37:0): Encountered end of file unexpectedly.
        EOF in a FORMAL-ARG-LIST> attribute.

Unable to continue parse -- Aborting...
