
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  65 (Line 254:34): Encountered a cell value whose value appears to be missing.
        The float cell will be set to zero.


      WARNING  64 (Line 264:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        The value is a list, which will be discarded.  The float cell will be set to zero.


      WARNING  64 (Line 269:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Will discard the value and set the value of the float cell to zero.


      ERROR  4 (Line 292:0): Encountered end of file unexpectedly.
        EOF in a float cell value.

Unable to continue parse -- Aborting...
