
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  16 (Line 248:49): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered a cell value attribute.


      WARNING  16 (Line 249:81): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered a cell value attribute.


      ERROR  4 (Line 269:0): Encountered end of file unexpectedly.
        EOF in a cell value attribute.

Unable to continue parse -- Aborting...
