
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  35 (Line 24:83): Encountered an atom or list in a formal argument list that isn't a formal argument.The atom or list will be discarded.
        This warning was occasioned by a nominal or predicate name.


      WARNING  35 (Line 24:102): Encountered an atom or list in a formal argument list that isn't a formal argument.The atom or list will be discarded.
        This warning was occasioned by a list.


      WARNING  35 (Line 24:105): Encountered an atom or list in a formal argument list that isn't a formal argument.The atom or list will be discarded.
        This warning was occasioned by an atom.


      WARNING  35 (Line 24:108): Encountered an atom or list in a formal argument list that isn't a formal argument.The atom or list will be discarded.
        This warning was occasioned by an atom.


      WARNING  36 (Line 25:76): Encountered an empty formal argument list.
        Will force the contents of the predicate formal argument list to (|<val>|).


      WARNING  38 (Line 25:80): Encountered a duplicate definition of a predicate.  The second definition will be ignored.
        New definition doesn't match old definition -- formal argument name mismatch.  New definition ignored.

      ERROR  4 (Line 36:0): Encountered end of file unexpectedly.
        EOF encountered in a predicate formal argument list.

Unable to continue parse -- Aborting...
