
      WARNING  25 (Line 9:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  41 (Line 110:15): Encountered a spreadsheet variable declaration in which the name of the spreadsheet variable is not a valid spreadsheet variable name.
        Will coerce the name to a valid spreadsheet variable name.


      WARNING  55 (Line 242:15): Encountered a spreadsheet variable definition in which the name of the spreadsheet variable is not a valid spreadsheet variable name.
        Will coerce the name to a valid spreadsheet variable name.


      WARNING  86 (Line 297:52): Encountered an invalid spreadsheet variable name in the list associated with the SYSTEM> SHAPA-PANE-VARS> attribute.
        Will coerce the name to a valid spreadsheet variable name.


      ERROR  4 (Line 330:0): Encountered end of file unexpectedly.
        EOF encountered in an arbitrary list that was being discarded.

Unable to continue parse -- Aborting...
