
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  40 (Line 27:13): Encountered an atom in the spreadsheet variable declarations list. The atom was discarded.


      WARNING  39 (Line 28:15): Encountered a list that is not a spreadsheet variable declarations in the spreadsheet variables declarations list.  List discarded.


      WARNING  40 (Line 29:13): Encountered an atom in the spreadsheet variable declarations list. The atom was discarded.


      ERROR  4 (Line 39:0): Encountered end of file unexpectedly.
        EOF encountered in the spreadsheet variables declarations list.

Unable to continue parse -- Aborting...
