; MacSHAPA Open Database
( setf macshapa-db
 '(
    ( HEADER>
      (
        ( NAME> "tttttttttttt" )
        ( VERSION> 1 )
        ( DEBUG-LEVEL> 3 )
        ( MAX_ERRORS> 10 )
        ( MAX-WARNINGS> 99 )
      )
    )
    ( USER>
      (
        ( PREDICATE-DEFINITIONS>
          (
          )
        )
        ( SPREADSHEET-VARIABLE-DECLARATIONS>
          (
            (
            )
          )
        )
        ( SPREADSHEET-VARIABLE-DEFINITIONS>
          (
          )
        )
      )
    )
    ( QUERY>
      (
      )
    )
    ( SYSTEM>
      (
      )
    )
  )
)
