00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ;1
00012          ;( 
00013            VERSION> 
00014            1 

      WARNING   9 (Line 13:11): Left parentheses expected.  Left parenthesis inserted to allow continued parse.
        The opening left parenthesis of the HEADER> a-list appears to be missing.

00015          ) 
00016          ( NAME> "parser_test.db" )
00017          ( DEBUG-LEVEL> 0 ) 
00018          ( MAX-ERRORS> 20 )
00019          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 18:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00020        )
00021      ) 
00022      ( USER> 
00023        (
00024          ;1 
00025          ;( 
00026            PREDICATE-DEFINITIONS> 
00027            (

      WARNING   9 (Line 26:11): Left parentheses expected.  Left parenthesis inserted to allow continued parse.
        The opening left parenthesis of the USER> a-list appears to be missing.

00028              ;1
00029              ;( 
00030                |pred_1| 
00031                ( 

      WARNING   9 (Line 30:15): Left parentheses expected.  Left parenthesis inserted to allow continued parse.
        The opening left parenthesis of the predicate definitions list appears to be missing.

00032                  ;1
00033                  ;( 
00034                    VARIABLE-LENGTH> 
00035                    FALSE 

      WARNING   9 (Line 34:19): Left parentheses expected.  Left parenthesis inserted to allow continued parse.
        The opening left parenthesis of a predicate definition a-list appears to be missing.

00036                  ) 
00037                  ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| ) ) 
00038                ) 
00039              )
00040              ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )
00041            )
00042          ) 
00043          ( SPREADSHEET-VARIABLE-DECLARATIONS> 1 ) 
00044          ( SPREADSHEET-VARIABLE-DEFINITIONS> 1 )

      WARNING  22 (Line 43:46): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> SPREADSHEET-VARIABLE-DECLARATIONS> a-list entry must be a (possibly empty) list of spreadsheet variable declarations.

00045        ) 

      WARNING  22 (Line 44:45): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> SPREADSHEET-VARIABLE-DEFINITIONS> a-list entry must be a (possibly empty) list of spreadsheet variable definitions.

00046      ) 
00047      ( QUERY> 2 )
00048      ( SYSTEM> 3 )

      WARNING  22 (Line 47:14): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the QUERY> section must be a list.

00049    ) 
00050  )
