
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING   9 (Line 20:11): Left parentheses expected.  Left parenthesis inserted to allow continued parse.
        The opening left parenthesis of the USER> a-list appears to be missing.


      WARNING  22 (Line 26:46): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> SPREADSHEET-VARIABLE-DECLARATIONS> a-list entry must be a (possibly empty) list of spreadsheet variable declarations.


      WARNING  22 (Line 27:45): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> SPREADSHEET-VARIABLE-DEFINITIONS> a-list entry must be a (possibly empty) list of spreadsheet variable definitions.


      WARNING  17 (Line 28:11): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate USER> PREDICATE-DEFINITIONS> entry


      WARNING  17 (Line 29:11): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate USER> SPREADSHEET-VARIABLE-DECLARATIONS> entry."


      WARNING  17 (Line 30:11): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate USER> SPREADSHEET-VARIABLE-DEFINITIONS> entry.


      WARNING  18 (Line 31:11): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the USER> a-list.


      WARNING  19 (Line 32:11): Encountered list that is not an a-list entry in an a-list.  The list will be read and discarded.
        The list is located in the USER> a-list.


      WARNING  20 (Line 33:9): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the USER> a-list.


      WARNING  20 (Line 33:14): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the USER> a-list.


      WARNING  20 (Line 33:26): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the USER> a-list.


      WARNING  20 (Line 33:29): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the USER> a-list.


      ERROR  4 (Line 39:0): Encountered end of file unexpectedly.
        EOF occurred in the USER> a-list.

Unable to continue parse -- Aborting...
