
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  16 (Line 32:55): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered a COLUMN-WIDTH> attribute.


      ERROR  4 (Line 51:0): Encountered end of file unexpectedly.
        EOF in a COLUMN-WIDTH> attribute.

Unable to continue parse -- Aborting...
