
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  37 (Line 24:15): Encountered a predicate definition in which the name of the predicate is not a valid predicate name.
        Will coerce the name to a valid predicate name.


      WARNING  63 (Line 255:52): Encountered a time that falls outside the range of values representable by MacSHAPA. The time will be forced to the nearest legal value.
        The out of range value appeared in a TIME> attribute


      WARNING  63 (Line 255:65): Encountered a time that falls outside the range of values representable by MacSHAPA. The time will be forced to the nearest legal value.
        The out of range value appeared in a TIME> attribute


      WARNING  14 (Line 260:53): Encountered a-list entry without a value.  A-list entries must be of the form '(' <tag> <value> ')'.
        A TIME> attribute appears not to contain a value.  Default value used.


      WARNING  22 (Line 260:63): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of a TIME> attribute must be an integer.  Default value used.


      WARNING  22 (Line 265:52): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of a TIME> attribute must be an integer.  Default value used.


      WARNING  22 (Line 265:67): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of a TIME> attribute must be an integer.  Default value used.


      WARNING  19 (Line 268:23): Encountered list that is not an a-list entry in an a-list.  The list will be read and discarded.
        The list is located in a spreadsheet variable cell a-list.


      ERROR  4 (Line 285:0): Encountered end of file unexpectedly.
        EOF encountered in an arbitrary list that was being discarded.

Unable to continue parse -- Aborting...
