00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db '( 
00008                        (HEADER> ) 
00009                        (USER> 1) 

      WARNING  14 (Line 8:32): Encountered a-list entry without a value.  A-list entries must be of the form '(' <tag> <value> ')'.
        The HEADER> section appears not to contain a value.

00010                        (QUERY> 2)

      WARNING  22 (Line 9:30): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> section must be a list.

00011                        (SYSTEM> 3)

      WARNING  22 (Line 10:31): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the QUERY> section must be a list.

00012                     ) 
00013  )
