00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 2 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 


Current Header Settings:
db.name = "parser_test.db"
odb file format version = 1
warning limit = 50
error limit = 10
debug level = 2

00019        (
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022            	; no predicate definitions, for now
00023            )
00024          ) 
00025          ( SPREADSHEET-VARIABLE-DECLARATIONS> 
00026             
00027          ) 
00028          ( SPREADSHEET-VARIABLE-DEFINITIONS> 1 )

      WARNING  14 (Line 27:9): Encountered a-list entry without a value.  A-list entries must be of the form '(' <tag> <value> ')'.
        The USER> SPREADSHEET-VARIABLE-DECLARATIONS> a-list entry doesn't seem to contain a value.

00029        ) 

      WARNING  22 (Line 28:45): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> SPREADSHEET-VARIABLE-DEFINITIONS> a-list entry must be a (possibly empty) list of spreadsheet variable definitions.

00030      ) 
00031      ( QUERY> 2 )
00032      ( SYSTEM> 3 )

      WARNING  22 (Line 31:14): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the QUERY> section must be a list.

00033    ) 

      WARNING  22 (Line 32:15): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the SYSTEM> section must be a list.

00034  )
