
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  20 (Line 29:17): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in a spreadsheet variable declaration a-list.


      WARNING  18 (Line 34:19): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in a spreadsheet variable declaration.


      WARNING  19 (Line 35:19): Encountered list that is not an a-list entry in an a-list.  The list will be read and discarded.
        The list is located in a spreadsheet variable declaration a-list.


      WARNING  17 (Line 36:19): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate TYPE> entry in a spreadsheet variable declaration.


      WARNING  17 (Line 37:19): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate VARIABLE-LENGTH> entry in a spreadsheet variable declaration.


      WARNING  17 (Line 38:19): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate FORMAL-ARG-LIST> entry in a spreadsheet variable declaration.


      WARNING  17 (Line 39:19): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate COLUMN-WIDTH> entry in a spreadsheet variable declaration.


      WARNING  20 (Line 40:17): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in a spreadsheet variable declaration a-list.


      ERROR  4 (Line 52:0): Encountered end of file unexpectedly.
        EOF occurred in a spreadsheet variable declaration a-list.

Unable to continue parse -- Aborting...
