
      WARNING  13 (Line 7:21): "'" expected.  "'" inserted to allow continued parse.
        A database file must start with "( setf macshapa-db '( ... ".


      ERROR 13 (Line 9:24): Encountered a-list entry prior to one or more of its required predicessors in its a-list.
        HEADER> a-list entry missing from the database body a-list?

Unable to continue parse -- Will continue lexer scan.

