00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 2 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 


Current Header Settings:
db.name = "parser_test.db"
odb file format version = 1
warning limit = 50
error limit = 10
debug level = 2

00019        (
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022            	( |a-pred| ( ( VARIABLE-LENGTH> FALSE) ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )
00023            	
00024            	; attempt to define a predicate with duplicate formal argument names
00025            	( |pred-2| ( ( VARIABLE-LENGTH> FALSE) ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| |<arg1>| ) ) ) )


Predicate Definition:
	name = "a-pred"
	variable length = false
	arg 0 = "<arg1>"


      WARNING  52 (Line 25:90): Encountered duplicate mention of a single formal argument name in a single formal argument list.  Duplicate formal argument will be ignored.
        Duplicate appeared in a predicate formal argument list.

00026            )
00027          ) 


Predicate Definition:
	name = "pred-2"
	variable length = false
	arg 0 = "<arg1>"
	arg 1 = "<arg2>"

00028          ( SPREADSHEET-VARIABLE-DECLARATIONS> 
00029            (
00030              ( |a text var| 
00031                ( 
00032                  ( TYPE> <<TEXT>> ) 
00033                  ( VARIABLE-LENGTH> FALSE )
00034                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) ) 
00035                  ( COLUMN-WIDTH> 125 ) 
00036                ) 
00037              )
00038              
00039              ( |a text var|  ; an identical duplicate spreadsheet variable declaration 


Spreadsheet Variable Definition:
	name = "a text var"
	type = TEXT
	variable length = false
	column width = 125
00040                ( 
00041                  ( TYPE> <<TEXT>> ) 
00042                  ( VARIABLE-LENGTH> FALSE )
00043                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) ) 
00044                  ( COLUMN-WIDTH> 125 ) 
00045                ) 
00046              )
00047              
00048              ( |a text var|  ; a non-identical duplicate spreadsheet variable declaration 


Spreadsheet Variable Definition:
	name = "a text var"
	type = TEXT
	variable length = false
	column width = 125

      WARNING  50 (Line 46:13): Encountered a duplicate declaration of a spreadsheet variable.  The second declaration will be ignored.
        The duplicate declaration differed from the initial definition.

00049                ( 
00050                  ( TYPE> <<INTEGER>> ) 
00051                  ( VARIABLE-LENGTH> FALSE )
00052                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) ) 
00053                  ( COLUMN-WIDTH> 125 ) 
00054                ) 
00055              )
00056              
00057              ( |a-pred| ; attempt to redefine a predicate as a spreadsheet variable


Spreadsheet Variable Definition:
	name = "a text var"
	type = INTEGER
	variable length = false
	column width = 125

      WARNING  50 (Line 55:13): Encountered a duplicate declaration of a spreadsheet variable.  The second declaration will be ignored.
        The duplicate declaration differed from the initial definition.

00058                ( 
00059                  ( TYPE> <<PREDICATE>> ) 
00060                  ( VARIABLE-LENGTH> FALSE )
00061                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00062                  ( COLUMN-WIDTH> 125 ) 
00063                ) 
00064              )
00065  
00066              ( |a nominal var| 


Spreadsheet Variable Definition:
	name = "a-pred"
	type = PREDICATE
	variable length = false
	column width = 125

      WARNING  49 (Line 64:13): Attempt to declare a spreadsheet variable with the same name as a previously definedpredicate detected.
        Spreadsheet variable declaration ignored.

00067                ( 
00068                  ( TYPE> <<NOMINAL>> ) 
00069                  ( VARIABLE-LENGTH> TRUE ) ; attempt to declare a variable length non-matrix spreadsheet variable
00070                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00071                  ( COLUMN-WIDTH> 125 ) 
00072                ) 
00073              )
00074              
00075              ( |really a matrix| ; attempt to declare an integer spreadsheet variable with a matrix arg list

      WARNING  51 (Line 73:13): Attempt to declare a variable length spreadsheet variable that is not of <<MATRIX>> type.  Spreadsheet variable forced to fixed length.



Spreadsheet Variable Definition:
	name = "a nominal var"
	type = NOMINAL
	variable length = false
	column width = 125
00076                ( 
00077                  ( TYPE> <<INTEGER>> ) 
00078                  ( VARIABLE-LENGTH> FALSE )
00079                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val1>| |<val2>| ) )  
00080                  ( COLUMN-WIDTH> 125 ) 
00081                ) 
00082              )
00083  
00084              ( |fixed len matrix| ; attempt to declare a spreadsheet variable with duplicate argument names

      WARNING  48 (Line 82:13): Attempt to declare a non matrix spreadsheet variable with a formal argument list that can only appear in a matrix spreadsheet variable.
        Will force the type of the spreadsheet variable to <<MATRIX>>.



Spreadsheet Variable Definition:
	name = "really a matrix"
	type = MATRIX
	variable length = false
	column width = 125
00085                ( 
00086                  ( TYPE> <<MATRIX>> ) 
00087                  ( VARIABLE-LENGTH> FALSE )
00088                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg1>| |<arg1>| ) )  

      WARNING  52 (Line 88:76): Encountered duplicate mention of a single formal argument name in a single formal argument list.  Duplicate formal argument will be ignored.
        Duplicate appeared in a spreadsheet variable formal argument list.

00089                  ( COLUMN-WIDTH> 125 ) 
00090                ) 
00091              )
00092  
00093              ( |fixed len matrix| ; another attempt to declare a spreadsheet variable with duplicate argument names


Spreadsheet Variable Definition:
	name = "fixed len matrix"
	type = MATRIX
	variable length = false
	column width = 125
00094                ( 
00095                  ( TYPE> <<MATRIX>> ) 
00096                  ( VARIABLE-LENGTH> FALSE )
00097                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg1>| |<arg1>| |<ord>| |<onset>| |<offset>| |<arg1>| |<arg1>| ) )  

      WARNING  52 (Line 97:76): Encountered duplicate mention of a single formal argument name in a single formal argument list.  Duplicate formal argument will be ignored.
        Duplicate appeared in a spreadsheet variable formal argument list.


      WARNING  52 (Line 97:85): Encountered duplicate mention of a single formal argument name in a single formal argument list.  Duplicate formal argument will be ignored.
        Duplicate appeared in a spreadsheet variable formal argument list.


      WARNING  52 (Line 97:93): Encountered duplicate mention of a single formal argument name in a single formal argument list.  Duplicate formal argument will be ignored.
        Duplicate appeared in a spreadsheet variable formal argument list.


      WARNING  52 (Line 97:103): Encountered duplicate mention of a single formal argument name in a single formal argument list.  Duplicate formal argument will be ignored.
        Duplicate appeared in a spreadsheet variable formal argument list.


      WARNING  52 (Line 97:114): Encountered duplicate mention of a single formal argument name in a single formal argument list.  Duplicate formal argument will be ignored.
        Duplicate appeared in a spreadsheet variable formal argument list.


      WARNING  52 (Line 97:123): Encountered duplicate mention of a single formal argument name in a single formal argument list.  Duplicate formal argument will be ignored.
        Duplicate appeared in a spreadsheet variable formal argument list.

00098                  ( COLUMN-WIDTH> 125 ) 
00099                ) 
00100              )
00101            ) 
00102          ) 


Spreadsheet Variable Definition:
	name = "fixed len matrix"
	type = MATRIX
	variable length = false
	column width = 125

      WARNING  50 (Line 100:13): Encountered a duplicate declaration of a spreadsheet variable.  The second declaration will be ignored.
        The duplicate declaration was identical to the initial definition.

00103          ( SPREADSHEET-VARIABLE-DEFINITIONS> 1 )
00104        ) 

      WARNING  22 (Line 103:45): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> SPREADSHEET-VARIABLE-DEFINITIONS> a-list entry must be a (possibly empty) list of spreadsheet variable definitions.

00105      ) 
00106      ( QUERY> 2 )
00107      ( SYSTEM> 3 )

      WARNING  22 (Line 106:14): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the QUERY> section must be a list.

00108    ) 
00109  )
