
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  22 (Line 86:45): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> SPREADSHEET-VARIABLE-DEFINITIONS> a-list entry must be a (possibly empty) list of spreadsheet variable definitions.


      ERROR 14 (Line 173:5): Encountered a-list with one or more required entries missing.
        Required entry(s) missing from the database body a-list.

Unable to continue parse -- Will continue lexer scan.

