00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007   setf macshapa-db '( (HEADER> 1.1) 

      WARNING   9 (Line 7:2): Left parentheses expected.  Left parenthesis inserted to allow continued parse.
        A database file must start with "( setf macshapa-db '( ... ".

00008                       (USER> "a string") 

      WARNING  22 (Line 7:31): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the HEADER> section must be a list.

00009                       (NONE-SUCH> (FALSE TRUE setf macshapa-db ' ()))

      WARNING  22 (Line 8:29): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> section must be a list.


      WARNING  18 (Line 9:23): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the database body a-list.

00010                       (QUERY> |<a formal argument>|) 

      WARNING   1 (Line 10:30): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ' ' (HEX 0x20)


      WARNING   1 (Line 10:30): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ' ' (HEX 0x20)

00011                       (SYSTEM> |a_predicate_name|) 

      WARNING  22 (Line 10:30): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the QUERY> section must be a list.

00012                     ) 

      WARNING  22 (Line 11:31): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the SYSTEM> section must be a list.


      WARNING  10 (Line 12:0): Right parentheses expected.  Right parenthesis inserted to allow continued parse.

