00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 2 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 


Current Header Settings:
db.name = "parser_test.db"
odb file format version = 1
warning limit = 50
error limit = 10
debug level = 2

00019        (
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022              ( |pred_1| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| ) ) ) )
00023              ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )


Predicate Definition:
	name = "pred_1"
	variable length = false
	arg 0 = "<arg1>"
	arg 1 = "<arg2>"

00024              ( |not a pred name| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )


Predicate Definition:
	name = "pred_2"
	variable length = true
	arg 0 = "<arg1>"


      WARNING  37 (Line 24:15): Encountered a predicate definition in which the name of the predicate is not a valid predicate name.
        Will coerce the name to a valid predicate name.

00025            )
00026          ) 


Predicate Definition:
	name = "not_a_pred_name"
	variable length = true
	arg 0 = "<arg1>"

00027          ( SPREADSHEET-VARIABLE-DECLARATIONS> 
00028            (
00029              ( |a text var| 
00030                ( 
00031                  ( TYPE> <<TEXT>> ) 
00032                  ( VARIABLE-LENGTH> FALSE )
00033                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) ) 
00034                  ( COLUMN-WIDTH> 200 ) 
00035                ) 
00036              )
00037              ( |a nominal var| 


Spreadsheet Variable Definition:
	name = "a text var"
	type = TEXT
	variable length = false
	column width = 200
00038                ( 
00039                  ( TYPE> <<NOMINAL>> ) 
00040                  ( VARIABLE-LENGTH> FALSE )
00041                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00042                  ( COLUMN-WIDTH> 200 ) 
00043                ) 
00044              )
00045              ( |an integer var| 


Spreadsheet Variable Definition:
	name = "a nominal var"
	type = NOMINAL
	variable length = false
	column width = 200
00046                ( 
00047                  ( TYPE> <<INTEGER>> ) 
00048                  ( VARIABLE-LENGTH> FALSE )
00049                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00050                  ( COLUMN-WIDTH> 200 ) 
00051                ) 
00052              )
00053              ( |a float var| 


Spreadsheet Variable Definition:
	name = "an integer var"
	type = INTEGER
	variable length = false
	column width = 200
00054                ( 
00055                  ( TYPE> <<FLOAT>> ) 
00056                  ( VARIABLE-LENGTH> FALSE )
00057                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00058                  ( COLUMN-WIDTH> 200 ) 
00059                ) 
00060              )
00061              ( |a predicate var| 


Spreadsheet Variable Definition:
	name = "a float var"
	type = FLOAT
	variable length = false
	column width = 200
00062                ( 
00063                  ( TYPE> <<PREDICATE>> ) 
00064                  ( VARIABLE-LENGTH> FALSE )
00065                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00066                  ( COLUMN-WIDTH> 200 ) 
00067                ) 
00068              )
00069              ( |fixed len matrix| 


Spreadsheet Variable Definition:
	name = "a predicate var"
	type = PREDICATE
	variable length = false
	column width = 200
00070                ( 
00071                  ( TYPE> <<MATRIX>> ) 
00072                  ( VARIABLE-LENGTH> FALSE )
00073                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg1>| |<arg2>| ) )  
00074                  ( COLUMN-WIDTH> 200 ) 
00075                ) 
00076              )
00077              ( |var len matrix| 


Spreadsheet Variable Definition:
	name = "fixed len matrix"
	type = MATRIX
	variable length = false
	column width = 200
00078                ( 
00079                  ( TYPE> <<MATRIX>> ) 
00080                  ( VARIABLE-LENGTH> TRUE )
00081                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg1>| |<arg2>| ) )  
00082                  ( COLUMN-WIDTH> 225 ) 
00083                ) 
00084              )
00085            ) 
00086          ) 


Spreadsheet Variable Definition:
	name = "var len matrix"
	type = MATRIX
	variable length = true
	column width = 225
00087          ( SPREADSHEET-VARIABLE-DEFINITIONS>
00088           ( 
00089              ( |a text var|
00090                ( 
00091                  ( CELLS>
00092                    ( 
00093                      (
00094                        ( ONSET>  0 ) 
00095                        ( OFFSET> 0 ) 
00096                        ( |<val>| "this is a text cell") 
00097                      )
00098                      ( 
00099                        ( ONSET>  60 ) 


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = this is a text cell
00100                        ( OFFSET> 60 ) 
00101                        ( |<val>| "") 
00102                      )
00103                    )
00104                  )
00105                )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 
00106              )
00107              
00108              ( |a nominal var|
00109                (
00110                  ( CELLS>
00111                    (
00112                      ( 
00113                        ( ONSET> 0 ) 
00114                        ( OFFSET> 0 ) 
00115                        ( |<val>| |this is nominal cell| ) 
00116                      )
00117                      ( 
00118                        ( ONSET> 60 )  


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = this is nominal cell
00119                        ( OFFSET> 60 ) 
00120                        ( |<val>| |<val>| ) 
00121                      )
00122                    )
00123                  )
00124                )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 
00125              )
00126  
00127              ( |an integer var|
00128                (
00129                  ( CELLS>
00130                    (
00131                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| 10 ) )
00132                      ( 
00133                        ( ONSET> 60 )  


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 10
00134                        ( OFFSET> 60 ) 
00135                        ( |<val>| 0 ) 
00136                      )
00137                    )
00138                  )
00139                )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 0
00140              )
00141  
00142              ( |a float var|
00143                (
00144                  ( CELLS>
00145                    (
00146                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| 10.0 ) )
00147                      ( 
00148                        ( ONSET> 60 )  


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 10.000000
00149                        ( OFFSET> 60 ) 
00150                        ( |<val>| 0.0 ) 
00151                      )
00152                    )
00153                  )
00154                )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 0.000000
00155              )
00156  
00157              ( |a predicate var|
00158                (
00159                  ( CELLS>
00160                    (
00161                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| ( |pred_1| ( TIME> 120 ) |a nominal| ) ) )
00162                      ( ( ONSET> 10 ) ( OFFSET> 20 ) ( |<val>| ( |pred_1| "a string" |<arg2>| ) ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = pred_1(00:00:02:000, a nominal)
00163                      ( ( ONSET> 20 ) ( OFFSET> 30 ) ( |<val>| ( |pred_1| 10 1.0 ) ) )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:010
	offset = 00:00:00:020
	value = pred_1("a string", <arg2>)
00164                      ( ( ONSET> 30 ) ( OFFSET> 40 ) ( |<val>| ( |pred_1| ( |pred_2| |<arg1>| ) |<arg2>| ) ) )


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:020
	offset = 00:00:00:030
	value = pred_1(10, 1.000000)
00165                      ( 
00166                        ( ONSET> 60 ) 


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:00:030
	offset = 00:00:00:040
	value = pred_1(pred_2(<arg1>), <arg2>)
00167                        ( OFFSET> 60 ) 
00168                        ( |<val>| ( ) ) 
00169                      )
00170                    )
00171                  )
00172                  ( VOCAB> 


Spreadsheet Variable Cell Definition:
	ord = 5
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = ()
00173                    ; an empty vocab
00174                    ; ( |pred_1| |pred_2| ) 
00175                  )
00176                )
00177              )

      WARNING  14 (Line 175:17): Encountered a-list entry without a value.  A-list entries must be of the form '(' <tag> <value> ')'.
        A VOCAB> attribute appears not to contain a value.  The attribute will be ignored.

00178  
00179              ( |fixed len matrix|
00180                (
00181                  ( CELLS>
00182                    (
00183                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<arg1>| 1 ) ( |<arg2>| 2.0 ) )
00184                      ( ( ONSET> 10 ) ( OFFSET> 20 ) ( |<arg1>| |a nominal| ) ( |<arg2>| "a string" ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 1, 2.000000
00185                      ( ( ONSET> 20 ) ( OFFSET> 30 ) ( |<arg1>| ( |pred_2| |<arg1>| ) ) ( |<arg2>| ( TIME> 120 ) ) )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:010
	offset = 00:00:00:020
	value = a nominal, "a string"
00186                      ( 
00187                        ( ONSET> 60 ) 


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:020
	offset = 00:00:00:030
	value = pred_2(<arg1>), 00:00:02:000
00188                        ( OFFSET> 60 ) 
00189                        ( |<arg1>| "first arg" ) 
00190                        ( |<arg2>|  "second arg" ) 
00191                      )
00192                    )
00193                  )
00194                  ( VOCAB> |sasquatch| ( |pred_1| |pred_2| ) ) 


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = "first arg", "second arg"

      WARNING  22 (Line 194:26): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of a VOCAB> attribute must be a list of predicate names.  The attribute will be ignored.

00195                )
00196              )

      WARNING  16 (Line 194:60): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered a VOCAB> attribute.

00197  
00198              ( |var len matrix|
00199                (
00200                  ( CELLS>
00201                    (
00202                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<arg1>| 1 ) ( |<arg2>| 2.0 ) )
00203                      ( ( ONSET> 10 ) ( OFFSET> 20 ) ( |<arg1>| |a nominal| ) ( |<arg2>| "a string" ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 1, 2.000000
00204                      ( ( ONSET> 20 ) ( OFFSET> 30 ) ( |<arg1>| ( |pred_2| |<arg1>| ) ) ( |<arg2>| ( TIME> 120 ) ) )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:010
	offset = 00:00:00:020
	value = a nominal, "a string"
00205                      ( ( ONSET> 60 ) ( OFFSET> 60 ) ( |<arg1>| |<arg1>| ) )


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:020
	offset = 00:00:00:030
	value = pred_2(<arg1>), 00:00:02:000
00206                      ( ( ONSET> 60 ) ( OFFSET> 60 ) ( |<arg1>| |<arg1>| ) ( |<arg2>| |<arg2>| ) )


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = <arg1>, <arg2>
00207                      ( 
00208                        ( ONSET> 61 ) 


Spreadsheet Variable Cell Definition:
	ord = 5
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = <arg1>, <arg2>
00209                        ( OFFSET> 61 ) 
00210                        ( |<arg1>| "first arg" ) 
00211                        ( |<arg2>| "second arg" ) 
00212                      )
00213                    )
00214                  )
00215                  ( VOCAB> ; ( |pred_1| |pred_2| ) ) ; eof before vocab list


Spreadsheet Variable Cell Definition:
	ord = 6
	onset = 00:00:01:001
	offset = 00:00:01:001
	value = "first arg", "second arg"
00216  ;              )
00217  ;            )
00218              
00219              
00220  ;          )
00221  ;        )
00222  ;      ) 
00223  ;    ) 
00224  ;    ( QUERY> 2 )
00225  ;    ( SYSTEM> 3 )
00226  ;  ) 
00227  ;)

      ERROR  4 (Line 227:0): Encountered end of file unexpectedly.
        EOF in a VOCAB> attribute.

Unable to continue parse -- Aborting...
