
      WARNING  17 (Line 17:35): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate HEADER> VERSION> entry.


      WARNING  17 (Line 18:35): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate HEADER> NAME> entry.


      WARNING  17 (Line 19:35): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate HEADER> MAX-ERRORS> entry.


      WARNING  17 (Line 20:35): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate HEADER> MAX-WARNINGS> entry.


      WARNING  17 (Line 21:35): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate HEADER> DEBUG-LEVEL> entry.


      WARNING  18 (Line 25:35): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the HEADER> a-list.


      WARNING  19 (Line 29:35): Encountered list that is not an a-list entry in an a-list.  The list will be read and discarded.
        The list is located in the HEADER> a-list.


      WARNING  20 (Line 33:34): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the HEADER> a-list.


      WARNING  20 (Line 33:36): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the HEADER> a-list.


      WARNING  20 (Line 33:40): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the HEADER> a-list.


      WARNING  20 (Line 33:51): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the HEADER> a-list.


      WARNING  20 (Line 33:61): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the HEADER> a-list.


      WARNING  20 (Line 33:72): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the HEADER> a-list.


      WARNING  20 (Line 33:77): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the HEADER> a-list.


      WARNING  20 (Line 33:83): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the HEADER> a-list.


      WARNING  20 (Line 33:94): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the HEADER> a-list.


      WARNING  20 (Line 33:99): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the HEADER> a-list.


      WARNING  20 (Line 33:111): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the HEADER> a-list.


      ERROR  4 (Line 42:0): Encountered end of file unexpectedly.
        EOF occurred the HEADER> a-list.

Unable to continue parse -- Aborting...
