00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 2 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 


Current Header Settings:
db.name = "parser_test.db"
odb file format version = 1
warning limit = 50
error limit = 10
debug level = 2

00019        (
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022              ( |pred_1| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| ) ) ) )
00023              ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )


Predicate Definition:
	name = "pred_1"
	variable length = false
	arg 0 = "<arg1>"
	arg 1 = "<arg2>"

00024            )
00025          ) 


Predicate Definition:
	name = "pred_2"
	variable length = true
	arg 0 = "<arg1>"

00026          ( SPREADSHEET-VARIABLE-DECLARATIONS> 
00027            (
00028              ( |a text var| 
00029                ( 
00030                  ( TYPE> <<TEXT>> ) 
00031                  ( VARIABLE-LENGTH> FALSE )
00032                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) ) 
00033                  ( COLUMN-WIDTH> 200 ) 
00034                ) 
00035              )
00036              ( |a nominal var| 


Spreadsheet Variable Definition:
	name = "a text var"
	type = TEXT
	variable length = false
	column width = 200
00037                ( 
00038                  ( TYPE> <<NOMINAL>> ) 
00039                  ( VARIABLE-LENGTH> FALSE )
00040                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00041                  ( COLUMN-WIDTH> 200 ) 
00042                ) 
00043              )
00044              ( |an integer var| 


Spreadsheet Variable Definition:
	name = "a nominal var"
	type = NOMINAL
	variable length = false
	column width = 200
00045                ( 
00046                  ( TYPE> <<INTEGER>> ) 
00047                  ( VARIABLE-LENGTH> FALSE )
00048                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00049                  ( COLUMN-WIDTH> 200 ) 
00050                ) 
00051              )
00052              ( |a float var| 


Spreadsheet Variable Definition:
	name = "an integer var"
	type = INTEGER
	variable length = false
	column width = 200
00053                ( 
00054                  ( TYPE> <<FLOAT>> ) 
00055                  ( VARIABLE-LENGTH> FALSE )
00056                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00057                  ( COLUMN-WIDTH> 200 ) 
00058                ) 
00059              )
00060              ( |a predicate var| 


Spreadsheet Variable Definition:
	name = "a float var"
	type = FLOAT
	variable length = false
	column width = 200
00061                ( 
00062                  ( TYPE> <<PREDICATE>> ) 
00063                  ( VARIABLE-LENGTH> FALSE )
00064                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00065                  ( COLUMN-WIDTH> 200 ) 
00066                ) 
00067              )
00068              ( |fixed len matrix| 


Spreadsheet Variable Definition:
	name = "a predicate var"
	type = PREDICATE
	variable length = false
	column width = 200
00069                ( 
00070                  ( TYPE> <<MATRIX>> ) 
00071                  ( VARIABLE-LENGTH> FALSE )
00072                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg1>| |<arg2>| ) )  
00073                  ( COLUMN-WIDTH> 200 ) 
00074                ) 
00075              )
00076              ( |var len matrix| 


Spreadsheet Variable Definition:
	name = "fixed len matrix"
	type = MATRIX
	variable length = false
	column width = 200
00077                ( 
00078                  ( TYPE> <<MATRIX>> ) 
00079                  ( VARIABLE-LENGTH> TRUE )
00080                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg1>| |<arg2>| ) )  
00081                  ( COLUMN-WIDTH> 225 ) 
00082                ) 
00083              )
00084            ) 
00085          ) 


Spreadsheet Variable Definition:
	name = "var len matrix"
	type = MATRIX
	variable length = true
	column width = 225
00086          ( SPREADSHEET-VARIABLE-DEFINITIONS>
00087           ( 
00088              ( |a text var|
00089                ( 
00090                  ( CELLS>
00091                    ( 
00092                      (
00093                        ( ONSET>  -1 ) ; time too small
00094                        ( OFFSET> -1 ) ; time too small

      WARNING  63 (Line 93:33): Encountered a time that falls outside the range of values representable by MacSHAPA. The time will be forced to the nearest legal value.
        The out of range value appeared in an ONSET> attribute

00095                        ( |<val>| "this is a text cell") 

      WARNING  63 (Line 94:33): Encountered a time that falls outside the range of values representable by MacSHAPA. The time will be forced to the nearest legal value.
        The out of range value appeared in an OFFSET> attribute

00096                      )
00097                      ( 
00098                        ( ONSET>  12960000 ) ; time too big


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = this is a text cell
00099                        ( OFFSET> 12960000 ) ; time too big

      WARNING  63 (Line 98:33): Encountered a time that falls outside the range of values representable by MacSHAPA. The time will be forced to the nearest legal value.
        The out of range value appeared in an ONSET> attribute

00100                        ( |<val>| "") 

      WARNING  63 (Line 99:33): Encountered a time that falls outside the range of values representable by MacSHAPA. The time will be forced to the nearest legal value.
        The out of range value appeared in an OFFSET> attribute

00101                      )
00102                      ( 
00103                        ( ONSET>   )  ; empty onset


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 59:59:59:059
	offset = 59:59:59:059
	value = 
00104                        ( OFFSET>  )  ; empty offset

      WARNING  14 (Line 103:34): Encountered a-list entry without a value.  A-list entries must be of the form '(' <tag> <value> ')'.
        An ONSET> attribute appears not to contain a value.  Default value used.

00105                        ( |<val>| "this is a text cell") 

      WARNING  14 (Line 104:34): Encountered a-list entry without a value.  A-list entries must be of the form '(' <tag> <value> ')'.
        An OFFSET> attribute appears  to contain a value.  Default value used.

00106                      )
00107                    )
00108                  )
00109                )


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = this is a text cell
00110              )
00111              
00112              ( |a nominal var|
00113                (
00114                  ( CELLS>
00115                    (
00116                      ( 
00117                        ( ONSET>  ( "this" "is" "a" "random" "list" ) )  ; list value in onset

      WARNING  22 (Line 117:33): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of an ONSET> attribute must be an integer.  Default value used.

00118                        ( OFFSET>  ( "this" "is" "a" "random" "list" ) ) ; list value in offset

      WARNING  22 (Line 118:34): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of an OFFSET> attribute must be an integer.  Default value used.

00119                        ( |<val>| |this is nominal cell| ) 
00120                      )
00121                      ( 
00122                        ( ONSET> 60.0 )  ; atom type mismatch in onset


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = this is nominal cell
00123                        ( OFFSET> 60.0 ) ; atom type mismatch in offset

      WARNING  22 (Line 122:32): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of an ONSET> attribute must be an integer.  Default value used.

00124                        ( |<val>| |<val>| ) 

      WARNING  22 (Line 123:33): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of an OFFSET> attribute must be an integer.  Default value used.

00125                      )
00126                    )
00127                  )
00128                )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 
00129              )
00130              ( |an integer var|
00131                (
00132                  ( CELLS>
00133                    (
00134                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| 10 ) )
00135                      ( 
00136                        ( ONSET> 60 |j random atom| )  ; excess atomic value in onset


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 10
00137                        ( OFFSET> 60 |j random atom| ) ; excess atomic value in offset

      WARNING  16 (Line 136:51): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered an ONSET> attribute.

00138                        ( |<val>| 0) 

      WARNING  16 (Line 137:52): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered an OFFSET> attribute.

00139                      )
00140                    )
00141                  )
00142                )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 0
00143              )
00144              ( |a float var|
00145                (
00146                  ( CELLS>
00147                    (
00148                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| 10.0 ) )
00149                      ( 
00150                        ( ONSET> 60 ( "this" "is" "a" "random" "list" ) 33 )   ; more excess values in an onset


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 10.000000
00151                        ( OFFSET> 60 ( "this" "is" "a" "random" "list" ) 33 )  ; more excess values in an offset

      WARNING  16 (Line 150:74): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered an ONSET> attribute.

00152                        ( |<val>| 0.0 ) 

      WARNING  16 (Line 151:75): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered an OFFSET> attribute.

00153                      )
00154                    )
00155                  )
00156                )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 0.000000
00157              )
00158              ( |a predicate var|
00159                (
00160                  ( CELLS>
00161                    (
00162                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| ( |pred_1| ( TIME> 120 ) |a nominal| ) ) )
00163                      ( ( ONSET> 10 ) ( OFFSET> 20 ) ( |<val>| ( |pred_1| "a string" |<arg2>| ) ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = pred_1(00:00:02:000, a nominal)
00164                      ( ( ONSET> 20 ) ( OFFSET> 30 ) ( |<val>| ( |pred_1| 10 1.0 ) ) )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:010
	offset = 00:00:00:020
	value = pred_1("a string", <arg2>)
00165                      ( ( ONSET> 30 ) ( OFFSET> 40 ) ( |<val>| ( |pred_1| ( |pred_2| |<arg1>| ) |<arg2>| ) ) )


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:020
	offset = 00:00:00:030
	value = pred_1(10, 1.000000)
00166                      ( 
00167                        ( ONSET> 60 ) 


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:00:030
	offset = 00:00:00:040
	value = pred_1(pred_2(<arg1>), <arg2>)
00168                        ( OFFSET> 60 ) 
00169                        ( |<val>| ( ) ) 
00170                      )
00171                    )
00172                  )
00173                  ( VOCAB> ( |pred_1| |pred_2| ) )


Spreadsheet Variable Cell Definition:
	ord = 5
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = ()
00174                )
00175              )
00176              ( |fixed len matrix|
00177                (
00178                  ( CELLS>
00179                    (
00180                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<arg1>| 1 ) ( |<arg2>| 2.0 ) )
00181                      ( ( ONSET> 10 ) ( OFFSET> 20 ) ( |<arg1>| |a nominal| ) ( |<arg2>| "a string" ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 1, 2.000000
00182                      ( ( ONSET> 20 ) ( OFFSET> 30 ) ( |<arg1>| ( |pred_2| |<arg1>| ) ) ( |<arg2>| ( TIME> 120 ) ) )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:010
	offset = 00:00:00:020
	value = a nominal, "a string"
00183                      ( 
00184                        ( ONSET> 60 ) 


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:020
	offset = 00:00:00:030
	value = pred_2(<arg1>), 00:00:02:000
00185                        ( OFFSET> 60 ) 
00186                        ( |<arg1>| |<arg1>| ) 
00187                        ( |<arg2>| |<arg2>| ) 
00188                      )
00189                      ( 
00190                        ( ONSET> 60 ) 


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = <arg1>, <arg2>
00191                        ( OFFSET> 60 ) 
00192                        ( |<arg1>| "first arg" ) 
00193                        ( |<arg2>| "second arg" ) 
00194                      )
00195                      ( 
00196                        ( ONSET> 61 ) 


Spreadsheet Variable Cell Definition:
	ord = 5
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = "first arg", "second arg"
00197                        ( OFFSET> 61 )
00198                        ( |<arg1>| "first arg" ) 
00199                        ( |<arg2>| "second arg" ) 
00200                      )
00201                      ( 
00202                        ( ONSET> 62 ) 


Spreadsheet Variable Cell Definition:
	ord = 6
	onset = 00:00:01:001
	offset = 00:00:01:001
	value = "first arg", "second arg"
00203                        ( OFFSET> 62 ) 
00204                        ( |<arg1>| "first arg" ) 
00205                        ( |<arg2>| "second arg" ) 
00206                      )
00207                      ( 
00208                        ( ONSET> 63 ) 


Spreadsheet Variable Cell Definition:
	ord = 7
	onset = 00:00:01:002
	offset = 00:00:01:002
	value = "first arg", "second arg"
00209                        ( OFFSET> 63 )
00210                        ( |<arg1>| "first arg" ) 
00211                        ( |<arg2>| "second arg" ) 
00212                      )
00213                    )
00214                  )
00215                  ( VOCAB> ( |pred_1| |pred_2| ) ) 


Spreadsheet Variable Cell Definition:
	ord = 8
	onset = 00:00:01:003
	offset = 00:00:01:003
	value = "first arg", "second arg"
00216                )
00217              )
00218              ( |var len matrix|
00219                (
00220                  ( CELLS>
00221                    (
00222                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<arg1>| 1 ) ( |<arg2>| 2.0 ) )
00223                      ( ( ONSET> 10 ) ( OFFSET> 20 ) ( |<arg1>| |a nominal| ) ( |<arg2>| "a string" ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 1, 2.000000
00224                      ( ( ONSET> 20 ) ( OFFSET> 30 ) ( |<arg1>| ( |pred_2| |<arg1>| ) ) ( |<arg2>| ( TIME> 120 ) ) )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:010
	offset = 00:00:00:020
	value = a nominal, "a string"
00225                      ( ( ONSET> 60 ) ( OFFSET> 60 ) ( |<arg1>| |<arg1>| ) )


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:020
	offset = 00:00:00:030
	value = pred_2(<arg1>), 00:00:02:000
00226                      ( ( ONSET> 60 ) ( OFFSET> 60 ) ( |<arg1>| |<arg1>| ) ( |<arg2>| |<arg2>| ) )


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = <arg1>, <arg2>
00227                      ( 
00228                        ( ONSET> 61 ) 


Spreadsheet Variable Cell Definition:
	ord = 5
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = <arg1>, <arg2>
00229                        ( OFFSET> 61 ) 
00230                        ( |<arg1>| "first arg" ) 
00231                        ( |<arg2>| "second arg" ) 
00232                      )
00233                      ( 
00234                        ( ONSET> 62 ) 


Spreadsheet Variable Cell Definition:
	ord = 6
	onset = 00:00:01:001
	offset = 00:00:01:001
	value = "first arg", "second arg"
00235                        ( OFFSET> 62 ) 
00236                        ( |<arg1>| "first arg" ) 
00237                        ( |<arg2>| "second arg" ) 
00238                      )
00239                      ( 
00240                        ( ONSET> 63 ) 


Spreadsheet Variable Cell Definition:
	ord = 7
	onset = 00:00:01:002
	offset = 00:00:01:002
	value = "first arg", "second arg"
00241                        ( OFFSET> 63 ) 
00242                        ( |<arg1>| "first arg" ) 
00243                        ( |<arg2>| "second arg" ) 
00244                      )
00245                      ( 
00246                        ( ONSET> 64 ) 


Spreadsheet Variable Cell Definition:
	ord = 8
	onset = 00:00:01:003
	offset = 00:00:01:003
	value = "first arg", "second arg"
00247                        ( OFFSET> 64 ) 
00248                        ( |<arg1>| "first arg" ) 
00249                        ( |<arg2>| "second arg" ) 
00250                      )
00251                      ( 
00252                        ( ONSET> ; unexpected EOF before value in an onset


Spreadsheet Variable Cell Definition:
	ord = 9
	onset = 00:00:01:004
	offset = 00:00:01:004
	value = "first arg", "second arg"
00253  ;                        65 
00254  ;                      ) 
00255  ;                      ( OFFSET> 65 ) 
00256  ;                      ( |<arg1>| "first arg" ) 
00257  ;                      ( |<arg2>| "second arg" ) 
00258  ;                    )
00259  ;                  )
00260  ;                )
00261  ;                ( VOCAB> ( |pred_1| |pred_2| ) )
00262  ;              )
00263  ;            )
00264  ;          )
00265  ;        )
00266  ;      ) 
00267  ;    ) 
00268  ;    ( QUERY> 2 )
00269  ;    ( SYSTEM> 3 )
00270  ;  ) 
00271  ;)

      ERROR  4 (Line 271:0): Encountered end of file unexpectedly.
        EOF in an ONSET> attribute.

Unable to continue parse -- Aborting...
