00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 0 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 
00019         ( 
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022              ( |pred_1| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| ) ) ) )
00023              ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )
00024              ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| |I am not a farg!| () 33 TRUE ) ) ) ) ; non-fargs in farg list

      WARNING  35 (Line 24:83): Encountered an atom or list in a formal argument list that isn't a formal argument.The atom or list will be discarded.
        This warning was occasioned by a nominal or predicate name.


      WARNING  35 (Line 24:102): Encountered an atom or list in a formal argument list that isn't a formal argument.The atom or list will be discarded.
        This warning was occasioned by a list.


      WARNING  35 (Line 24:105): Encountered an atom or list in a formal argument list that isn't a formal argument.The atom or list will be discarded.
        This warning was occasioned by an atom.


      WARNING  35 (Line 24:108): Encountered an atom or list in a formal argument list that isn't a formal argument.The atom or list will be discarded.
        This warning was occasioned by an atom.

00025              ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( ) ) ) )   ; empty farg list

      WARNING  36 (Line 25:76): Encountered an empty formal argument list.
        Will force the contents of the predicate formal argument list to (|<val>|).

00026              ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ; EOF in farg list ) ) ) )

      WARNING  38 (Line 25:80): Encountered a duplicate definition of a predicate.  The second definition will be ignored.
        New definition doesn't match old definition -- formal argument name mismatch.  New definition ignored.
00027  ;          )
00028  ;        ) 
00029  ;        ( SPREADSHEET-VARIABLE-DECLARATIONS> 1 ) 
00030  ;        ( SPREADSHEET-VARIABLE-DEFINITIONS> 1 )
00031  ;      ) 
00032  ;    ) 
00033  ;    ( QUERY> 2 )
00034  ;    ( SYSTEM> 3 )
00035  ;  ) 
00036  ;)

      ERROR  4 (Line 36:0): Encountered end of file unexpectedly.
        EOF encountered in a predicate formal argument list.

Unable to continue parse -- Aborting...
