
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING   9 (Line 92:25): Left parentheses expected.  Left parenthesis inserted to allow continued parse.
        The opening left parenthesis of a spreadsheet variable cell a-list appears to be missing.


      WARNING  61 (Line 103:21): Encountered an atom in a spreadsheet variable cell list.  The atom will be discarded.


      ERROR  4 (Line 179:0): Encountered end of file unexpectedly.
        EOF encountered in a spreadsheet variable cell list.

Unable to continue parse -- Aborting...
