
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  14 (Line 29:26): Encountered a-list entry without a value.  A-list entries must be of the form '(' <tag> <value> ')'.
        A TYPE> attribute appears not to contain a value.  Value forced to <<MATRIX>>.


      WARNING  22 (Line 37:25): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the TYPE> attribute must be a private value.  Value forced to <<MATRIX>>.


      WARNING  22 (Line 45:25): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the TYPE> attribute must be a private value.  Value forced to <<MATRIX>>.


      ERROR  4 (Line 67:0): Encountered end of file unexpectedly.
        EOF in a TYPE> attribute.

Unable to continue parse -- Aborting...
