
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  37 (Line 24:15): Encountered a predicate definition in which the name of the predicate is not a valid predicate name.
        Will coerce the name to a valid predicate name.


      WARNING  82 (Line 224:21): Encountered reference to an undefined predicate in a vocabulary list.  The undefinedpredicate will be ignored.


      WARNING  83 (Line 225:21): Encountered reference to a spreadsheet variable in a vocabulary list.  The spreadsheet variable will be ignored.


      WARNING  84 (Line 226:21): Encountered reference to a system predicate in a vocabulary list.  The system predicate will be ignored.


      WARNING  81 (Line 227:21): Encountered a item in a vocabulary list that is not a predicate name.  The entry will be ignored.
        The item was a nominal or column variable name.


      WARNING  81 (Line 228:21): Encountered a item in a vocabulary list that is not a predicate name.  The entry will be ignored.
        The item was a nominal or column variable name.


      WARNING  81 (Line 229:21): Encountered a item in a vocabulary list that is not a predicate name.  The entry will be ignored.
        The item was a list.


      WARNING  81 (Line 230:21): Encountered a item in a vocabulary list that is not a predicate name.  The entry will be ignored.
        The item was an atom.


      ERROR  4 (Line 245:0): Encountered end of file unexpectedly.
        EOF in a vocabulary list.
Unable to continue parse -- Aborting...
