; MacSHAPA Open Database
( setf macshapa-db
 '(
    ( HEADER>
      (
        ( NAME> "parser_test.db" )
        ( VERSION> 1 )
        ( DEBUG-LEVEL> 2 )
        ( MAX-ERRORS> 10 )
        ( MAX-WARNINGS> 50 )
      )
    )
    ( USER>
      (
        ( PREDICATE-DEFINITIONS>
          (
          )
        )
        ( SPREADSHEET-VARIABLE-DECLARATIONS>
          (
            ( |svar 2|
              (
                ( TYPE> <<MATRIX>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 200 )
              )
            )
            ( |svar 3|
              (
                ( TYPE> <<MATRIX>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg>| ) )
                ( COLUMN-WIDTH> 200 )
              )
            )
            ( |svar 1|
              (
                ( TYPE> <<TEXT>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 200 )
              )
            )
            ( |svar 4|
              (
                ( TYPE> <<TEXT>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 200 )
              )
            )
          )
        )
        ( SPREADSHEET-VARIABLE-DEFINITIONS>
          (
            ( |svar 2|
              (
                ( CELLS>
                  (
                  )
                )
                ( VOCAB> ( ) )
              )
            )
            ( |svar 3|
              (
                ( CELLS>
                  (
                  )
                )
                ( VOCAB> ( ) )
              )
            )
            ( |svar 1|
              (
                ( CELLS>
                  (
                  )
                )
              )
            )
            ( |svar 4|
              (
                ( CELLS>
                  (
                  )
                )
              )
            )
          )
        )
      )
    )
    ( QUERY>
      (
      )
    )
    ( SYSTEM>
      (
        ( SHAPA-PANE-VARS>
          (
            |svar 1|
            |svar 2|
            |svar 3|
            |svar 4|
          )
        )
      )
    )
  )
)
