00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 2 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 


Current Header Settings:
db.name = "parser_test.db"
odb file format version = 1
warning limit = 50
error limit = 10
debug level = 2

00019        (
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022            	; no predicate definitions, for now
00023            )
00024          ) 
00025          ( SPREADSHEET-VARIABLE-DECLARATIONS> 
00026            (
00027              ( |svar 1| 
00028                ( 
00029                  ( TYPE>  ) 
00030                  ( VARIABLE-LENGTH> FALSE )

      WARNING  14 (Line 29:26): Encountered a-list entry without a value.  A-list entries must be of the form '(' <tag> <value> ')'.
        A TYPE> attribute appears not to contain a value.  Value forced to <<MATRIX>>.

00031                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
00032                  ( COLUMN-WIDTH> 200 ) 
00033                )
00034              )
00035              ( |svar 2| 


Spreadsheet Variable Definition:
	name = "svar 1"
	type = MATRIX
	variable length = false
	column width = 200
00036                ( 
00037                  ( TYPE> (TRUE) ) 

      WARNING  22 (Line 37:25): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the TYPE> attribute must be a private value.  Value forced to <<MATRIX>>.

00038                  ( VARIABLE-LENGTH> FALSE )
00039                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
00040                  ( COLUMN-WIDTH> 200 ) 
00041                )
00042              )
00043              ( |svar 3| 


Spreadsheet Variable Definition:
	name = "svar 2"
	type = MATRIX
	variable length = false
	column width = 200
00044                ( 
00045                  ( TYPE> 1 ) 
00046                  ( VARIABLE-LENGTH> FALSE )

      WARNING  22 (Line 45:25): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the TYPE> attribute must be a private value.  Value forced to <<MATRIX>>.

00047                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
00048                  ( COLUMN-WIDTH> 200 ) 
00049                )
00050              )
00051              ( |svar 4| 


Spreadsheet Variable Definition:
	name = "svar 3"
	type = MATRIX
	variable length = false
	column width = 200
00052                ( 
00053                  ( TYPE> ; unexpeceted EOF <<TEXT>> ) 
00054  ;                ( VARIABLE-LENGTH> FALSE )
00055  ;                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
00056  ;                ( COLUMN-WIDTH> 200 ) 
00057  ;              )
00058  ;            )
00059  ;          )
00060  ;        ) 
00061  ;        ( SPREADSHEET-VARIABLE-DEFINITIONS> 1 )
00062  ;      ) 
00063  ;    ) 
00064  ;    ( QUERY> 2 )
00065  ;    ( SYSTEM> 3 )
00066  ;  ) 
00067  ;)

      ERROR  4 (Line 67:0): Encountered end of file unexpectedly.
        EOF in a TYPE> attribute.

Unable to continue parse -- Aborting...
