; MacSHAPA Open Database
( setf macshapa-db
 '(
    ( HEADER>
      (
        ( NAME> "parser_test.db" )
        ( VERSION> 1 )
        ( DEBUG-LEVEL> 2 )
        ( MAX-ERRORS> 10 )
        ( MAX-WARNINGS> 50 )
      )
    )
    ( USER>
      (
        ( PREDICATE-DEFINITIONS>
          (
          )
        )
        ( SPREADSHEET-VARIABLE-DECLARATIONS>
          (
            ( |a float var|
              (
                ( TYPE> <<FLOAT>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 125 )
              )
            )
            ( |a nominal var|
              (
                ( TYPE> <<NOMINAL>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 125 )
              )
            )
            ( |a predicate var|
              (
                ( TYPE> <<PREDICATE>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 125 )
              )
            )
            ( |fixed len matrix|
              (
                ( TYPE> <<MATRIX>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg1>| |<arg2>| ) )
                ( COLUMN-WIDTH> 125 )
              )
            )
            ( |an integer var|
              (
                ( TYPE> <<INTEGER>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 125 )
              )
            )
            ( |var len matrix|
              (
                ( TYPE> <<MATRIX>> )
                ( VARIABLE-LENGTH> TRUE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg1>| |<arg2>| ) )
                ( COLUMN-WIDTH> 125 )
              )
            )
            ( |a text var|
              (
                ( TYPE> <<TEXT>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 125 )
              )
            )
          )
        )
        ( SPREADSHEET-VARIABLE-DEFINITIONS>
          (
            ( |a float var|
              (
                ( CELLS>
                  (
                  )
                )
              )
            )
            ( |a nominal var|
              (
                ( CELLS>
                  (
                  )
                )
              )
            )
            ( |a predicate var|
              (
                ( CELLS>
                  (
                  )
                )
                ( VOCAB> ( ) )
              )
            )
            ( |fixed len matrix|
              (
                ( CELLS>
                  (
                  )
                )
                ( VOCAB> ( ) )
              )
            )
            ( |an integer var|
              (
                ( CELLS>
                  (
                  )
                )
              )
            )
            ( |var len matrix|
              (
                ( CELLS>
                  (
                  )
                )
                ( VOCAB> ( ) )
              )
            )
            ( |a text var|
              (
                ( CELLS>
                  (
                  )
                )
              )
            )
          )
        )
      )
    )
    ( QUERY>
      (
      )
    )
    ( SYSTEM>
      (
        ( SHAPA-PANE-VARS>
          (
            |a text var|
            |a nominal var|
            |an integer var|
            |a float var|
            |a predicate var|
            |fixed len matrix|
            |var len matrix|
          )
        )
      )
    )
  )
)
