00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 2 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 


Current Header Settings:
db.name = "parser_test.db"
odb file format version = 1
warning limit = 50
error limit = 10
debug level = 2

00019        (
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022            	; no predicate definitions, for now
00023            )
00024          ) 
00025          ( SPREADSHEET-VARIABLE-DECLARATIONS> 
00026            (
00027              ( |svar 1| 
00028                ( 
00029                  ( TYPE> <<TEXT>> ) 
00030                  ( VARIABLE-LENGTH> FALSE )
00031                  ( FORMAL-ARG-LIST> ( |<ord->| |<onset->| |<offset->| |<val>| ) )

      WARNING  45 (Line 31:38): Illegal formal argument name in a spreadsheet variable formal argument list.
        The first argument in a spreadsheet variable formal argument list must be "|<ord>|".  First argument forced to "|<ord>|".


      WARNING  45 (Line 31:47): Illegal formal argument name in a spreadsheet variable formal argument list.
        The second argument in a spreadsheet variable formal argument list must be "|<onset>|".  Second argument forced to "|<onset>|".


      WARNING  45 (Line 31:58): Illegal formal argument name in a spreadsheet variable formal argument list.
        The third argument in a spreadsheet variable formal argument list must be "|<offset>|".  Third argument forced to "|<offset>|".

00032                  ( COLUMN-WIDTH> 200 ) 
00033                )
00034              )
00035              ( |svar 2| 


Spreadsheet Variable Definition:
	name = "svar 1"
	type = TEXT
	variable length = false
	column width = 200
00036                ( 
00037                  ( TYPE> <<TEXT>> ) 
00038                  ( VARIABLE-LENGTH> FALSE )
00039                  ( FORMAL-ARG-LIST> (|a-pred||<ord>|(66)|<onset>|66|<offset>|TRUE|<val>| ) ) 

      WARNING  35 (Line 39:37): Encountered an atom or list in a formal argument list that isn't a formal argument.The atom or list will be discarded.
        This warning was occasioned by a nominal or predicate name.


      WARNING  35 (Line 39:52): Encountered an atom or list in a formal argument list that isn't a formal argument.The atom or list will be discarded.
        This warning was occasioned by a list.


      WARNING  35 (Line 39:65): Encountered an atom or list in a formal argument list that isn't a formal argument.The atom or list will be discarded.
        This warning was occasioned by an atom.


      WARNING  35 (Line 39:77): Encountered an atom or list in a formal argument list that isn't a formal argument.The atom or list will be discarded.
        This warning was occasioned by an atom.

00040                  ( COLUMN-WIDTH> 200 ) 
00041                )
00042              )
00043              ( |svar 3| 


Spreadsheet Variable Definition:
	name = "svar 2"
	type = TEXT
	variable length = false
	column width = 200
00044                ( 
00045                  ( TYPE> <<TEXT>> ) 
00046                  ( VARIABLE-LENGTH> FALSE )
00047                  ( FORMAL-ARG-LIST> ( ) ) ; empty argument list
00048                  ( COLUMN-WIDTH> 200 ) 

      WARNING  36 (Line 47:40): Encountered an empty formal argument list.
        Formal argument list forced to "(|<ord>| |<onset>| |<offset>| |<val>|)".

00049                )
00050              )
00051              ( |svar 4| 


Spreadsheet Variable Definition:
	name = "svar 3"
	type = TEXT
	variable length = false
	column width = 200
00052                ( 
00053                  ( TYPE> <<TEXT>> ) 
00054                  ( VARIABLE-LENGTH> FALSE )
00055                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| ) )  ; a short argument list
00056                  ( COLUMN-WIDTH> 200 ) 

      WARNING  46 (Line 55:69): The formal argument list of a spreadsheet variable must contain at least four arguments.
        Formal argument list forced to "(|<ord>| |<onset>| |<offset>| |<val>|)".

00057                )
00058              )
00059              ( |svar 5| 


Spreadsheet Variable Definition:
	name = "svar 4"
	type = TEXT
	variable length = false
	column width = 200
00060                ( 
00061                  ( TYPE> <<TEXT>> ) 
00062                  ( VARIABLE-LENGTH> FALSE )
00063                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ; unexpected EOF) ) 
00064  ;                ( COLUMN-WIDTH> 200 ) 
00065  ;              )
00066  ;            )
00067  ;          )
00068  ;        ) 
00069  ;        ( SPREADSHEET-VARIABLE-DEFINITIONS> 1 )
00070  ;      ) 
00071  ;    ) 
00072  ;    ( QUERY> 2 )
00073  ;    ( SYSTEM> 3 )
00074  ;  ) 
00075  ;)

      ERROR  4 (Line 75:0): Encountered end of file unexpectedly.
        EOF encountered in a spreadsheet variable formal argument list.

Unable to continue parse -- Aborting...
