00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db  ( 
00008                        ;(HEADER> 1.1) 
00009                        (USER> "a string") 

      WARNING  13 (Line 7:21): "'" expected.  "'" inserted to allow continued parse.
        A database file must start with "( setf macshapa-db '( ... ".


      ERROR 13 (Line 9:24): Encountered a-list entry prior to one or more of its required predicessors in its a-list.
        HEADER> a-list entry missing from the database body a-list?

Unable to continue parse -- Will continue lexer scan.

00010                        (QUERY> |<a_formal_argument>|) 
00011                        (SYSTEM> |a_predicate_name|) 
00012                    ) 
00013  )
