; MacSHAPA Open Database
( setf macshapa-db
 '(
    ( HEADER>
      (
        ( NAME> "parser_test.db" )
        ( VERSION> 1 )
        ( DEBUG-LEVEL> 2 )
        ( MAX-ERRORS> 10 )
        ( MAX-WARNINGS> 50 )
      )
    )
    ( USER>
      (
        ( PREDICATE-DEFINITIONS>
          (
          )
        )
        ( SPREADSHEET-VARIABLE-DECLARATIONS>
          (
            ( |_a-text-var_|
              (
                ( TYPE> <<TEXT>> )
                ( VARIABLE-LENGTH> FALSE )
                ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
                ( COLUMN-WIDTH> 200 )
              )
            )
          )
        )
        ( SPREADSHEET-VARIABLE-DEFINITIONS>
          (
            ( |_a-text-var_|
              (
                ( CELLS>
                )
              )
            )
          )
        )
      )
    )
    ( QUERY>
      (
      )
    )
    ( SYSTEM>
      (
        ( SHAPA-PANE-VARS>
          (
            |_a-text-var_|
          )
        )
      )
    )
  )
)
