
      WARNING   9 (Line 7:2): Left parentheses expected.  Left parenthesis inserted to allow continued parse.
        A database file must start with "( setf macshapa-db '( ... ".


      WARNING  22 (Line 7:31): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the HEADER> section must be a list.


      WARNING  22 (Line 8:29): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> section must be a list.


      WARNING  18 (Line 9:23): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the database body a-list.


      WARNING   1 (Line 10:30): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ' ' (HEX 0x20)


      WARNING   1 (Line 10:30): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ' ' (HEX 0x20)


      WARNING  22 (Line 10:30): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the QUERY> section must be a list.


      WARNING  22 (Line 11:31): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the SYSTEM> section must be a list.


      WARNING  10 (Line 12:0): Right parentheses expected.  Right parenthesis inserted to allow continued parse.

