00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db '( 
00008                        (HEADER> <<FLOAT>>) 
00009                        (USER> "a string") 

      WARNING  22 (Line 8:32): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the HEADER> section must be a list.

00010                        (QUERY> |a nominal|) 

      WARNING  22 (Line 9:30): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> section must be a list.

00011                        (SYSTEM> |a_predicate_name|) 

      WARNING  22 (Line 10:31): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the QUERY> section must be a list.

00012                        (NONE-SUCH> |<a_formal_arg>|)

      WARNING  22 (Line 11:32): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the SYSTEM> section must be a list.


      WARNING  18 (Line 12:24): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the database body a-list.

00013                        (NONE-SUCH> TRUE )

      WARNING  18 (Line 13:24): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the database body a-list.

00014                        (NONE-SUCH> 1 )

      WARNING  18 (Line 14:24): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the database body a-list.

00015                        (NONE-SUCH> 1.1 )

      WARNING  18 (Line 15:24): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the database body a-list.

00016                        (NONE-SUCH> ("this is an arbitrary list"))

      WARNING  18 (Line 16:24): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the database body a-list.

00017                        (NONE-SUCH> NONE-SUCH>)

      WARNING  18 (Line 17:24): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the database body a-list.

00018                        (NONE-SUCH> setf )

      WARNING  15 (Line 17:35): Illegal value in the value slot of an unknown or  unexpected a-list entry.


      WARNING  18 (Line 18:24): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the database body a-list.

00019                        (NONE-SUCH> macshapa-db)

      WARNING  15 (Line 18:35): Illegal value in the value slot of an unknown or  unexpected a-list entry.


      WARNING  18 (Line 19:24): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the database body a-list.

00020                        (NONE-SUCH> ')

      WARNING  15 (Line 19:35): Illegal value in the value slot of an unknown or  unexpected a-list entry.


      WARNING  18 (Line 20:24): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the database body a-list.

00021                        (NONE-SUCH>)        ; a-list entry without a value

      WARNING  15 (Line 20:35): Illegal value in the value slot of an unknown or  unexpected a-list entry.


      WARNING  18 (Line 21:24): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the database body a-list.

00022                        (NONE-SUCH> 1 2 (1 2))   ; a-list entry with two values

      WARNING  14 (Line 21:34): Encountered a-list entry without a value.  A-list entries must be of the form '(' <tag> <value> ')'.
        The empty a-list entry was unknown or unexpected, hence the point is probably moot.


      WARNING  18 (Line 22:24): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the database body a-list.

00023                        (NONE-SUCH> ; eof in the middle of an unknown or unexpected a-list entry.

      WARNING  16 (Line 22:44): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered in an unexpected or unknown a-list entry.

00024  ;                  ) 
00025  ; )

      WARNING  18 (Line 23:24): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the database body a-list.


      ERROR  4 (Line 25:0): Encountered end of file unexpectedly.
        EOF encountered in an unknown or unexpected a-list entry.

Unable to continue parse -- Aborting...
