
      WARNING  25 (Line 9:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING   9 (Line 253:11): Left parentheses expected.  Left parenthesis inserted to allow continued parse.
        The opening left parenthesis of the SYSTEM> a-list appears to be missing.


      WARNING 119 (Line 254:11): Encountered ALIGNMENTS> attribute after the SHAPA-PANE-VARS> attribute in the SYSTEM> section.  If both appear, the ALIGNMENTS> attribute must appear first.
        The ALIGNMENTS> attribute will be discarded.


      WARNING  20 (Line 257:9): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the SYSTEM> a-list.


      WARNING  19 (Line 258:10): Encountered list that is not an a-list entry in an a-list.  The list will be read and discarded.
        The list is located in the SYSTEM> a-list.


      WARNING  17 (Line 259:11): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate ALIGNMENTS> entry in the SYSTEM> alist.


      WARNING  17 (Line 260:11): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate SHAPA-PANE-VARS> entry in the SYSTEM> alist.


      WARNING  17 (Line 261:11): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate GROUPS> entry in the SYSTEM> alist.


      WARNING  17 (Line 262:11): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate IMPORT-FORMAT-LISTS> entry in the SYSTEM> alist.


      ERROR  4 (Line 268:0): Encountered end of file unexpectedly.
        EOF occurred in the SYSTEM> a-list.

Unable to continue parse -- Aborting...
