00001  ; MacSHAPA Open Database
00002  ( setf macshapa-db 
00003   '( 
00004      ( HEADER>
00005        ( 
00006          ( VERSION> 1 ) 
00007          ( NAME> "parser_test.db" )
00008          ;( DEBUG-LEVEL> 2 ) 
00009          ( MAX-ERRORS> 20 )
00010          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 9:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00011        )
00012      )
00013      (
00014        USER>
00015        (
00016          (
00017            PREDICATE-DEFINITIONS>
00018            (
00019            )
00020          )
00021          (
00022            SPREADSHEET-VARIABLE-DECLARATIONS>
00023            (
00024            )
00025          )
00026          (
00027            SPREADSHEET-VARIABLE-DEFINITIONS>
00028            (
00029            )
00030          )
00031        )
00032      )
00033      (
00034        QUERY>
00035        (
00036        )
00037      )
00038      ( SYSTEM>
00039        ( 
00040        )
00041      )
00042    )
00043  )
00044  
