00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 2 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 


Current Header Settings:
db.name = "parser_test.db"
odb file format version = 1
warning limit = 50
error limit = 10
debug level = 2

00019        (
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022            	; no predicate definitions, for now
00023            )
00024          ) 
00025          ( SPREADSHEET-VARIABLE-DECLARATIONS> 
00026            ; unexpected eof 
00027  ;        ) 
00028  ;        ( SPREADSHEET-VARIABLE-DEFINITIONS> 1 )
00029  ;      ) 
00030  ;    ) 
00031  ;    ( QUERY> 2 )
00032  ;    ( SYSTEM> 3 )
00033  ;  ) 
00034  ;)

      ERROR  4 (Line 34:0): Encountered end of file unexpectedly.
        EOF in USER> SPREADSHEET-VARIABLE-DECLARATIONS> attribute.

Unable to continue parse -- Aborting...
