00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 2 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 


Current Header Settings:
db.name = "parser_test.db"
odb file format version = 1
warning limit = 50
error limit = 10
debug level = 2

00019        (
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022            	; no predicate definitions, for now
00023            )
00024          ) 
00025          ( SPREADSHEET-VARIABLE-DECLARATIONS> 
00026            (
00027              ( |a text var| 
00028                ( 
00029                  ( TYPE> <<TEXT>> ) 
00030                  ( VARIABLE-LENGTH> FALSE )
00031                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) ) 
00032                  ( COLUMN-WIDTH> 125 ) 
00033                ) 
00034              )
00035              ( |a nominal var| 


Spreadsheet Variable Definition:
	name = "a text var"
	type = TEXT
	variable length = false
	column width = 125
00036                ( 
00037                  ( TYPE> <<NOMINAL>> ) 
00038                  ( VARIABLE-LENGTH> FALSE )
00039                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00040                  ( COLUMN-WIDTH> 125 ) 
00041                ) 
00042              )
00043              ( |an integer var| 


Spreadsheet Variable Definition:
	name = "a nominal var"
	type = NOMINAL
	variable length = false
	column width = 125
00044                ( 
00045                  ( TYPE> <<INTEGER>> ) 
00046                  ( VARIABLE-LENGTH> FALSE )
00047                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00048                  ( COLUMN-WIDTH> 125 ) 
00049                ) 
00050              )
00051              ( |a float var| 


Spreadsheet Variable Definition:
	name = "an integer var"
	type = INTEGER
	variable length = false
	column width = 125
00052                ( 
00053                  ( TYPE> <<FLOAT>> ) 
00054                  ( VARIABLE-LENGTH> FALSE )
00055                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00056                  ( COLUMN-WIDTH> 125 ) 
00057                ) 
00058              )
00059              ( |a predicate var| 


Spreadsheet Variable Definition:
	name = "a float var"
	type = FLOAT
	variable length = false
	column width = 125
00060                ( 
00061                  ( TYPE> <<PREDICATE>> ) 
00062                  ( VARIABLE-LENGTH> FALSE )
00063                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00064                  ( COLUMN-WIDTH> 125 ) 
00065                ) 
00066              )
00067              ( |fixed len matrix| 


Spreadsheet Variable Definition:
	name = "a predicate var"
	type = PREDICATE
	variable length = false
	column width = 125
00068                ( 
00069                  ( TYPE> <<MATRIX>> ) 
00070                  ( VARIABLE-LENGTH> FALSE )
00071                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg1>| |<arg2>| ) )  
00072                  ( COLUMN-WIDTH> 125 ) 
00073                ) 
00074              )
00075              ( |var len matrix| 


Spreadsheet Variable Definition:
	name = "fixed len matrix"
	type = MATRIX
	variable length = false
	column width = 125
00076                ( 
00077                  ( TYPE> <<MATRIX>> ) 
00078                  ( VARIABLE-LENGTH> TRUE )
00079                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg1>| |<arg2>| ) )  
00080                  ( COLUMN-WIDTH> 125 ) 
00081                ) 
00082              )
00083            ) 
00084          ) 


Spreadsheet Variable Definition:
	name = "var len matrix"
	type = MATRIX
	variable length = true
	column width = 125
00085          ( SPREADSHEET-VARIABLE-DEFINITIONS> 1 )
00086        ) 

      WARNING  22 (Line 85:45): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> SPREADSHEET-VARIABLE-DEFINITIONS> a-list entry must be a (possibly empty) list of spreadsheet variable definitions.

00087      ) 
00088      ( QUERY> 2 )
00089      ( SYSTEM> 3 )

      WARNING  22 (Line 88:14): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the QUERY> section must be a list.

00090    ) 

      WARNING  22 (Line 89:15): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the SYSTEM> section must be a list.

00091  )
