
      WARNING  25 (Line 28:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  22 (Line 270:15): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the SYSTEM> section must be a list.


      WARNING  16 (Line 277:5): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered in the SYSTEM> section.

