00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 2 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 


Current Header Settings:
db.name = "parser_test.db"
odb file format version = 1
warning limit = 50
error limit = 10
debug level = 2

00019        (
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022              ( |pred_1| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| ) ) ) )
00023              ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )


Predicate Definition:
	name = "pred_1"
	variable length = false
	arg 0 = "<arg1>"
	arg 1 = "<arg2>"

00024            )
00025          ) 


Predicate Definition:
	name = "pred_2"
	variable length = true
	arg 0 = "<arg1>"

00026          ( SPREADSHEET-VARIABLE-DECLARATIONS> 
00027            (
00028              ( |a text var| 
00029                ( 
00030                  ( TYPE> <<TEXT>> ) 
00031                  ( VARIABLE-LENGTH> FALSE )
00032                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) ) 
00033                  ( COLUMN-WIDTH> 200 ) 
00034                ) 
00035              )
00036              ( |a nominal var| 


Spreadsheet Variable Definition:
	name = "a text var"
	type = TEXT
	variable length = false
	column width = 200
00037                ( 
00038                  ( TYPE> <<NOMINAL>> ) 
00039                  ( VARIABLE-LENGTH> FALSE )
00040                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00041                  ( COLUMN-WIDTH> 200 ) 
00042                ) 
00043              )
00044              ( |an integer var| 


Spreadsheet Variable Definition:
	name = "a nominal var"
	type = NOMINAL
	variable length = false
	column width = 200
00045                ( 
00046                  ( TYPE> <<INTEGER>> ) 
00047                  ( VARIABLE-LENGTH> FALSE )
00048                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00049                  ( COLUMN-WIDTH> 200 ) 
00050                ) 
00051              )
00052              ( |a float var| 


Spreadsheet Variable Definition:
	name = "an integer var"
	type = INTEGER
	variable length = false
	column width = 200
00053                ( 
00054                  ( TYPE> <<FLOAT>> ) 
00055                  ( VARIABLE-LENGTH> FALSE )
00056                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00057                  ( COLUMN-WIDTH> 200 ) 
00058                ) 
00059              )
00060              ( |a predicate var| 


Spreadsheet Variable Definition:
	name = "a float var"
	type = FLOAT
	variable length = false
	column width = 200
00061                ( 
00062                  ( TYPE> <<PREDICATE>> ) 
00063                  ( VARIABLE-LENGTH> FALSE )
00064                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00065                  ( COLUMN-WIDTH> 200 ) 
00066                ) 
00067              )
00068              ( |fixed len matrix| 


Spreadsheet Variable Definition:
	name = "a predicate var"
	type = PREDICATE
	variable length = false
	column width = 200
00069                ( 
00070                  ( TYPE> <<MATRIX>> ) 
00071                  ( VARIABLE-LENGTH> FALSE )
00072                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg1>| |<arg2>| ) )  
00073                  ( COLUMN-WIDTH> 200 ) 
00074                ) 
00075              )
00076              ( |var len matrix| 


Spreadsheet Variable Definition:
	name = "fixed len matrix"
	type = MATRIX
	variable length = false
	column width = 200
00077                ( 
00078                  ( TYPE> <<MATRIX>> ) 
00079                  ( VARIABLE-LENGTH> TRUE )
00080                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg1>| |<arg2>| ) )  
00081                  ( COLUMN-WIDTH> 225 ) 
00082                ) 
00083              )
00084            ) 
00085          ) 


Spreadsheet Variable Definition:
	name = "var len matrix"
	type = MATRIX
	variable length = true
	column width = 225
00086          ( SPREADSHEET-VARIABLE-DEFINITIONS>
00087           ( 
00088              ( |a text var|
00089                ( 
00090                  ( CELLS>
00091                    ( 
00092                      (
00093                        ( ONSET>  0 ) 
00094                        ( OFFSET> 0 ) 
00095                        ( |<val>| "this is a text cell") 
00096                      )
00097                      ( 
00098                        ( ONSET>  60 ) 


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = this is a text cell
00099                        ( OFFSET> 60 ) 
00100                        ( |<val>| "") 
00101                      )
00102                    )
00103                  )
00104                )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 
00105              )
00106              
00107              ( |a nominal var|
00108                (
00109                  ( CELLS>
00110                    (
00111                      ( 
00112                        ( ONSET> 0 ) 
00113                        ( OFFSET> 0 ) 
00114                        ( |<val>| |this is nominal cell| ) 
00115                      )
00116                      ( 
00117                        ( ONSET> 60 )  


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = this is nominal cell
00118                        ( OFFSET> 60 ) 
00119                        ( |<val>| |<val>| ) 
00120                      )
00121                    )
00122                  )
00123                )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 
00124              )
00125  
00126              ( |an integer var|
00127                (
00128                  ( CELLS>
00129                    (
00130                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| 10 ) )
00131                      ( 
00132                        ( ONSET> 60 )  


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 10
00133                        ( OFFSET> 60 ) 
00134                        ( |<val>| 0 ) 
00135                      )
00136                    )
00137                  )
00138                )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 0
00139              )
00140  
00141              ( |a float var|
00142                (
00143                  ( CELLS>
00144                    (
00145                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| 10.0 ) )
00146                      ( 
00147                        ( ONSET> 60 )  


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 10.000000
00148                        ( OFFSET> 60 ) 
00149                        ( |<val>| 0.0 ) 
00150                      )
00151                    )
00152                  )
00153                )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 0.000000
00154              )
00155  
00156  
00157              ( |fixed len matrix|
00158                (
00159                  ( CELLS>
00160                    (
00161                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<arg1>| 1 ) ( |<arg2>| 2.0 ) )
00162                      ( ( ONSET> 10 ) ( OFFSET> 20 ) ( |<arg1>| |a nominal| ) ( |<arg2>| "a string" ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 1, 2.000000
00163                      ( ( ONSET> 20 ) ( OFFSET> 30 ) ( |<arg1>| ( |pred_2| |<arg1>| ) ) ( |<arg2>| ( TIME> 120 ) ) )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:010
	offset = 00:00:00:020
	value = a nominal, "a string"
00164                      ( 
00165                        ( ONSET> 60 ) 


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:020
	offset = 00:00:00:030
	value = pred_2(<arg1>), 00:00:02:000
00166                        ( OFFSET> 60 ) 
00167                        ( |<arg1>| |<arg1>| ) 
00168                        ( |<arg2>| |<arg2>| ) 
00169                      )
00170                      ( 
00171                        ( ONSET> 60 ) 


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = <arg1>, <arg2>
00172                        ( OFFSET> 60 ) 
00173                        ( |<arg1>| "first arg" ) 
00174                        ( |<arg2>| "second arg" ) 
00175                      )
00176                      ( 
00177                        ( ONSET> 61 ) 


Spreadsheet Variable Cell Definition:
	ord = 5
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = "first arg", "second arg"
00178                        ( OFFSET> 61 )
00179                        ( |<arg1>| "first arg" ) 
00180                        ( |<arg2>| "second arg" ) 
00181                      )
00182                      ( 
00183                        ( ONSET> 62 ) 


Spreadsheet Variable Cell Definition:
	ord = 6
	onset = 00:00:01:001
	offset = 00:00:01:001
	value = "first arg", "second arg"
00184                        ( OFFSET> 62 ) 
00185                        ( |<arg1>| "first arg" ) 
00186                        ( |<arg2>| "second arg" ) 
00187                      )
00188                      ( 
00189                        ( ONSET> 63 ) 


Spreadsheet Variable Cell Definition:
	ord = 7
	onset = 00:00:01:002
	offset = 00:00:01:002
	value = "first arg", "second arg"
00190                        ( OFFSET> 63 )
00191                        ( |<arg1>| "first arg" ) 
00192                        ( |<arg2>| "second arg" ) 
00193                      )
00194                    )
00195                  )
00196                  ( VOCAB> ( |pred_1| |pred_2| ) ) 


Spreadsheet Variable Cell Definition:
	ord = 8
	onset = 00:00:01:003
	offset = 00:00:01:003
	value = "first arg", "second arg"
00197                )
00198              )
00199              ( |var len matrix|
00200                (
00201                  ( CELLS>
00202                    (
00203                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<arg1>| 1 ) ( |<arg2>| 2.0 ) )
00204                      ( ( ONSET> 10 ) ( OFFSET> 20 ) ( |<arg1>| |a nominal| ) ( |<arg2>| "a string" ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 1, 2.000000
00205                      ( ( ONSET> 20 ) ( OFFSET> 30 ) ( |<arg1>| ( |pred_2| |<arg1>| ) ) ( |<arg2>| ( TIME> 120 ) ) )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:010
	offset = 00:00:00:020
	value = a nominal, "a string"
00206                      ( ( ONSET> 60 ) ( OFFSET> 60 ) ( |<arg1>| |<arg1>| ) )


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:020
	offset = 00:00:00:030
	value = pred_2(<arg1>), 00:00:02:000
00207                      ( ( ONSET> 60 ) ( OFFSET> 60 ) ( |<arg1>| |<arg1>| ) ( |<arg2>| |<arg2>| ) )


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = <arg1>, <arg2>
00208                      ( 
00209                        ( ONSET> 61 ) 


Spreadsheet Variable Cell Definition:
	ord = 5
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = <arg1>, <arg2>
00210                        ( OFFSET> 61 ) 
00211                        ( |<arg1>| "first arg" ) 
00212                        ( |<arg2>| "second arg" ) 
00213                      )
00214                      ( 
00215                        ( ONSET> 62 ) 


Spreadsheet Variable Cell Definition:
	ord = 6
	onset = 00:00:01:001
	offset = 00:00:01:001
	value = "first arg", "second arg"
00216                        ( OFFSET> 62 ) 
00217                        ( |<arg1>| "first arg" ) 
00218                        ( |<arg2>| "second arg" ) 
00219                      )
00220                      ( 
00221                        ( ONSET> 63 ) 


Spreadsheet Variable Cell Definition:
	ord = 7
	onset = 00:00:01:002
	offset = 00:00:01:002
	value = "first arg", "second arg"
00222                        ( OFFSET> 63 ) 
00223                        ( |<arg1>| "first arg" ) 
00224                        ( |<arg2>| "second arg" ) 
00225                      )
00226                      ( 
00227                        ( ONSET> 64 ) 


Spreadsheet Variable Cell Definition:
	ord = 8
	onset = 00:00:01:003
	offset = 00:00:01:003
	value = "first arg", "second arg"
00228                        ( OFFSET> 64 ) 
00229                        ( |<arg1>| "first arg" ) 
00230                        ( |<arg2>| "second arg" ) 
00231                      )
00232                    )
00233                  )
00234                  ( VOCAB> ( |pred_1| |pred_2| ) )


Spreadsheet Variable Cell Definition:
	ord = 9
	onset = 00:00:01:004
	offset = 00:00:01:004
	value = "first arg", "second arg"
00235                )
00236              )
00237              
00238              ( |a predicate var|
00239                (
00240                  ( CELLS>
00241                    (
00242                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| ( |pred_1| ( TIME> 120 ) |a nominal| ) ) )
00243                      ( ( ONSET> 10 ) ( OFFSET> 20 ) ( |<val>| ( |pred_1| "a string" |<arg2>| ) ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = pred_1(00:00:02:000, a nominal)
00244                      ( ( ONSET> 20 ) ( OFFSET> 30 ) ( |<val>| ( |pred_1| 10 1.0 ) ) )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:010
	offset = 00:00:00:020
	value = pred_1("a string", <arg2>)
00245                      ( ( ONSET> 30 ) ( OFFSET> 40 ) ( |<val>| ( |pred_1| ( |pred_2| |<arg1>| ) |<arg2>| ) ) )


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:020
	offset = 00:00:00:030
	value = pred_1(10, 1.000000)
00246                      ( 
00247                        ( ONSET> 60 ) 


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:00:030
	offset = 00:00:00:040
	value = pred_1(pred_2(<arg1>), <arg2>)
00248                        ( OFFSET> 60 ) 
00249                        ( |<val>| ( ) ) 
00250                      )
00251                      ( 
00252                        ( ONSET> 61 ) 


Spreadsheet Variable Cell Definition:
	ord = 5
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = ()
00253                        ( OFFSET> 61 ) 
00254                        ( |<val>|  ) ; missing predicate value
00255                      )
00256                      ( 

      WARNING  65 (Line 254:34): Encountered a cell value whose value appears to be missing.
        The predicate cell will be left empty.

00257                        ( ONSET> 62 ) 


Spreadsheet Variable Cell Definition:
	ord = 6
	onset = 00:00:01:001
	offset = 00:00:01:001
	value = ()
00258                        ( OFFSET> 62 ) 
00259                        ( |<val>| TRUE ) ; atom type mismatch
00260                      )

      WARNING  64 (Line 259:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Will discard the value and leave the predicate cell empty.

00261                      ( 
00262                        ( ONSET> 63 ) 


Spreadsheet Variable Cell Definition:
	ord = 7
	onset = 00:00:01:002
	offset = 00:00:01:002
	value = ()
00263                        ( OFFSET> 63 ) 
00264                        ( 
00265                          |<val>|
00266                          ; unexpected EOF in predicate value 
00267  ;                        ( ) 
00268  ;                      ) 
00269  ;                    )
00270  ;                  )
00271  ;                )
00272  ;                ( VOCAB> ( |pred_1| |pred_2| ) )
00273  ;              )
00274  ;            )
00275  ;            
00276  ;          )
00277  ;        )
00278  ;      ) 
00279  ;    ) 
00280  ;    ( QUERY> 2 )
00281  ;    ( SYSTEM> 3 )
00282  ;  ) 
00283  ;)

      ERROR  4 (Line 283:0): Encountered end of file unexpectedly.
        EOF in a predicate cell value.

Unable to continue parse -- Aborting...
