
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  63 (Line 93:33): Encountered a time that falls outside the range of values representable by MacSHAPA. The time will be forced to the nearest legal value.
        The out of range value appeared in an ONSET> attribute


      WARNING  63 (Line 94:33): Encountered a time that falls outside the range of values representable by MacSHAPA. The time will be forced to the nearest legal value.
        The out of range value appeared in an OFFSET> attribute


      WARNING  63 (Line 98:33): Encountered a time that falls outside the range of values representable by MacSHAPA. The time will be forced to the nearest legal value.
        The out of range value appeared in an ONSET> attribute


      WARNING  63 (Line 99:33): Encountered a time that falls outside the range of values representable by MacSHAPA. The time will be forced to the nearest legal value.
        The out of range value appeared in an OFFSET> attribute


      WARNING  14 (Line 103:34): Encountered a-list entry without a value.  A-list entries must be of the form '(' <tag> <value> ')'.
        An ONSET> attribute appears not to contain a value.  Default value used.


      WARNING  14 (Line 104:34): Encountered a-list entry without a value.  A-list entries must be of the form '(' <tag> <value> ')'.
        An OFFSET> attribute appears  to contain a value.  Default value used.


      WARNING  22 (Line 117:33): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of an ONSET> attribute must be an integer.  Default value used.


      WARNING  22 (Line 118:34): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of an OFFSET> attribute must be an integer.  Default value used.


      WARNING  22 (Line 122:32): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of an ONSET> attribute must be an integer.  Default value used.


      WARNING  22 (Line 123:33): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of an OFFSET> attribute must be an integer.  Default value used.


      WARNING  16 (Line 136:51): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered an ONSET> attribute.


      WARNING  16 (Line 137:52): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered an OFFSET> attribute.


      WARNING  16 (Line 150:74): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered an ONSET> attribute.


      WARNING  16 (Line 151:75): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered an OFFSET> attribute.


      ERROR  4 (Line 271:0): Encountered end of file unexpectedly.
        EOF in an ONSET> attribute.

Unable to continue parse -- Aborting...
