
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  30 (Line 24:15): Encountered a list that is not a predicate definition in the predicate definitions list.  List discarded.


      WARNING  31 (Line 25:13): Encountered an atom in the predicate definitions list. The atom was discarded.


      ERROR  4 (Line 36:0): Encountered end of file unexpectedly.
        EOF encountered in the predicate definitions list.

Unable to continue parse -- Aborting...
