
      WARNING  25 (Line 9:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  86 (Line 254:52): Encountered an invalid spreadsheet variable name in the list associated with the SYSTEM> SHAPA-PANE-VARS> attribute.
        Will coerce the name to a valid spreadsheet variable name.


      WARNING  87 (Line 254:52): Encountered reference to an undefined spreadsheet variable in the list associated with the SYSTEM> SHAPA-PANE-VARS> attribute.
        The entry in the shapa pane variables list will be ignored.


      ERROR  4 (Line 287:0): Encountered end of file unexpectedly.
        EOF encountered in an arbitrary list that was being discarded.

Unable to continue parse -- Aborting...
