00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 0 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 
00019         ( 
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022              ( |pred_1| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| ) ) ) )
00023              ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )
00024              ( |pred_3| 
00025                ( 
00026                  1 1.2 FALSE |a symbol|                ; some random atoms

      WARNING  20 (Line 26:17): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in a predicate definition a-list.


      WARNING  20 (Line 26:19): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in a predicate definition a-list.

00027                  ( VARIABLE-LENGTH> TRUE )  

      WARNING  20 (Line 26:23): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in a predicate definition a-list.


      WARNING  20 (Line 26:29): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in a predicate definition a-list.

00028                  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) 
00029                  ( VARIABLE-LENGTH> TRUE )             ; duplicate entry

      WARNING  17 (Line 29:19): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate VARIABLE-LENGTH> entry in a predicate definition.

00030                  ( FORMAL-ARG-LIST> ( |<arg1>| ) )     ; duplicate entry

      WARNING  17 (Line 30:19): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate FORMAL-ARG-LIST> entry in a predicate definition.

00031                  ( NONE-SUCH> "dummy" )                ; unexpected entry

      WARNING  18 (Line 31:19): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in a predicate definition a-list.

00032                  ( "j random list" 1 2 1.2 TRUE )      ; a random list

      WARNING  19 (Line 32:19): Encountered list that is not an a-list entry in an a-list.  The list will be read and discarded.
        The list is located in a predicate definition a-list.

00033                )
00034              )
00035              ( |pred_4| 
00036                ( 
00037                   ; an empty a-list
00038                )
00039              )
00040              ( |pred_5| 

      WARNING  29 (Line 39:13): A required a-list entry appears to be missing.  Will attempt to proceed with a default value.  Errors may result.
        VARIABLE-LENGTH> entry missing from predicate definition?  VARIABLE-LENGTH> forced to false.


      WARNING  29 (Line 39:13): A required a-list entry appears to be missing.  Will attempt to proceed with a default value.  Errors may result.
        FORMAL-ARG-LIST> entry missing from predicate definition?  Will use the arg list "(|<val>|)".

00041                ( 
00042                  ( VARIABLE-LENGTH> TRUE )  
00043                  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ; unexpected EOF
00044  ;              ) 
00045  ;            )
00046  ;        ) 
00047  ;        ( SPREADSHEET-VARIABLE-DECLARATIONS> 1 ) 
00048  ;        ( SPREADSHEET-VARIABLE-DEFINITIONS> 1 )
00049  ;      ) 
00050  ;    ) 
00051  ;    ( QUERY> 2 )
00052  ;    ( SYSTEM> 3 )
00053  ;  ) 
00054  ;)

      ERROR  4 (Line 54:0): Encountered end of file unexpectedly.
        EOF occurred in a predicate definition a-list.

Unable to continue parse -- Aborting...
