00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 2 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 


Current Header Settings:
db.name = "parser_test.db"
odb file format version = 1
warning limit = 50
error limit = 10
debug level = 2

00019        (
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022            	; no predicate definitions, for now
00023            )
00024          ) 
00025          ( SPREADSHEET-VARIABLE-DECLARATIONS> 
00026            (
00027              ( |svar 1| 
00028                ( 
00029                  FALSE ; j. random atom
00030                  ( TYPE> <<TEXT>> ) 

      WARNING  20 (Line 29:17): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in a spreadsheet variable declaration a-list.

00031                  ( VARIABLE-LENGTH> FALSE )
00032                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) ) 
00033                  ( COLUMN-WIDTH> 200 ) 
00034                  ( NONE-SUCH> 1 )

      WARNING  18 (Line 34:19): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in a spreadsheet variable declaration.

00035                  ( "j random list" 22 2.2 )

      WARNING  19 (Line 35:19): Encountered list that is not an a-list entry in an a-list.  The list will be read and discarded.
        The list is located in a spreadsheet variable declaration a-list.

00036                  ( TYPE> <<TEXT>> ) 

      WARNING  17 (Line 36:19): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate TYPE> entry in a spreadsheet variable declaration.

00037                  ( VARIABLE-LENGTH> FALSE )

      WARNING  17 (Line 37:19): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate VARIABLE-LENGTH> entry in a spreadsheet variable declaration.

00038                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) ) 

      WARNING  17 (Line 38:19): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate FORMAL-ARG-LIST> entry in a spreadsheet variable declaration.

00039                  ( COLUMN-WIDTH> 200 ) 

      WARNING  17 (Line 39:19): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate COLUMN-WIDTH> entry in a spreadsheet variable declaration.

00040                  TRUE ; j. random atom
00041                  ; unexpected EOF
00042  ;              )
00043  ;            )
00044  ;          )
00045  ;        ) 
00046  ;        ( SPREADSHEET-VARIABLE-DEFINITIONS> 1 )
00047  ;      ) 
00048  ;    ) 
00049  ;    ( QUERY> 2 )
00050  ;    ( SYSTEM> 3 )
00051  ;  ) 
00052  ;)

      WARNING  20 (Line 40:17): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in a spreadsheet variable declaration a-list.


      ERROR  4 (Line 52:0): Encountered end of file unexpectedly.
        EOF occurred in a spreadsheet variable declaration a-list.

Unable to continue parse -- Aborting...
