00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db '( 
00008                        (HEADER> <<FLOAT>>) 
00009                        (USER> "a string") 

      WARNING  22 (Line 8:32): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the HEADER> section must be a list.

00010                        (QUERY> ( <<FLOAT>>

      WARNING  22 (Line 9:30): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> section must be a list.

00011                        			 "a string"
00012                        			 |a nominal|

      WARNING  85 (Line 10:33): Encountered an atom in the query list.  The atom will be discarded.

00013                        			 1

      WARNING  85 (Line 11:27): Encountered an atom in the query list.  The atom will be discarded.

00014                        			 1.2

      WARNING  85 (Line 12:27): Encountered an atom in the query list.  The atom will be discarded.

00015                        			 FALSE

      WARNING  85 (Line 13:27): Encountered an atom in the query list.  The atom will be discarded.

00016                        			 TRUE

      WARNING  85 (Line 14:27): Encountered an atom in the query list.  The atom will be discarded.

00017                        			 QUERY>

      WARNING  85 (Line 15:27): Encountered an atom in the query list.  The atom will be discarded.

00018                        			 setf

      WARNING  85 (Line 16:27): Encountered an atom in the query list.  The atom will be discarded.

00019                        			 macshapa-db

      WARNING  85 (Line 17:27): Encountered an atom in the query list.  The atom will be discarded.

00020                        			 '

      WARNING  85 (Line 18:27): Encountered an atom in the query list.  The atom will be discarded.

00021                        			 ()

      WARNING  85 (Line 19:27): Encountered an atom in the query list.  The atom will be discarded.


      WARNING  85 (Line 20:27): Encountered an atom in the query list.  The atom will be discarded.

00022                        		    )
00023                        )
00024                        (SYSTEM> ( <<FLOAT>> ;unexpected eof in an arbitrary list
00025  ;                  ) 
00026  ;)

      WARNING  20 (Line 24:34): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the SYSTEM> a-list.


      ERROR  4 (Line 26:0): Encountered end of file unexpectedly.
        EOF occurred in the SYSTEM> a-list.

Unable to continue parse -- Aborting...
