
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  52 (Line 25:90): Encountered duplicate mention of a single formal argument name in a single formal argument list.  Duplicate formal argument will be ignored.
        Duplicate appeared in a predicate formal argument list.


      WARNING  50 (Line 46:13): Encountered a duplicate declaration of a spreadsheet variable.  The second declaration will be ignored.
        The duplicate declaration differed from the initial definition.


      WARNING  50 (Line 55:13): Encountered a duplicate declaration of a spreadsheet variable.  The second declaration will be ignored.
        The duplicate declaration differed from the initial definition.


      WARNING  49 (Line 64:13): Attempt to declare a spreadsheet variable with the same name as a previously definedpredicate detected.
        Spreadsheet variable declaration ignored.


      WARNING  51 (Line 73:13): Attempt to declare a variable length spreadsheet variable that is not of <<MATRIX>> type.  Spreadsheet variable forced to fixed length.


      WARNING  48 (Line 82:13): Attempt to declare a non matrix spreadsheet variable with a formal argument list that can only appear in a matrix spreadsheet variable.
        Will force the type of the spreadsheet variable to <<MATRIX>>.


      WARNING  52 (Line 88:76): Encountered duplicate mention of a single formal argument name in a single formal argument list.  Duplicate formal argument will be ignored.
        Duplicate appeared in a spreadsheet variable formal argument list.


      WARNING  52 (Line 97:76): Encountered duplicate mention of a single formal argument name in a single formal argument list.  Duplicate formal argument will be ignored.
        Duplicate appeared in a spreadsheet variable formal argument list.


      WARNING  52 (Line 97:85): Encountered duplicate mention of a single formal argument name in a single formal argument list.  Duplicate formal argument will be ignored.
        Duplicate appeared in a spreadsheet variable formal argument list.


      WARNING  52 (Line 97:93): Encountered duplicate mention of a single formal argument name in a single formal argument list.  Duplicate formal argument will be ignored.
        Duplicate appeared in a spreadsheet variable formal argument list.


      WARNING  52 (Line 97:103): Encountered duplicate mention of a single formal argument name in a single formal argument list.  Duplicate formal argument will be ignored.
        Duplicate appeared in a spreadsheet variable formal argument list.


      WARNING  52 (Line 97:114): Encountered duplicate mention of a single formal argument name in a single formal argument list.  Duplicate formal argument will be ignored.
        Duplicate appeared in a spreadsheet variable formal argument list.


      WARNING  52 (Line 97:123): Encountered duplicate mention of a single formal argument name in a single formal argument list.  Duplicate formal argument will be ignored.
        Duplicate appeared in a spreadsheet variable formal argument list.


      WARNING  50 (Line 100:13): Encountered a duplicate declaration of a spreadsheet variable.  The second declaration will be ignored.
        The duplicate declaration was identical to the initial definition.


      WARNING  22 (Line 103:45): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> SPREADSHEET-VARIABLE-DEFINITIONS> a-list entry must be a (possibly empty) list of spreadsheet variable definitions.


      WARNING  22 (Line 106:14): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the QUERY> section must be a list.


      WARNING  22 (Line 107:15): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the SYSTEM> section must be a list.

