
      WARNING  16 (Line 9:93): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered in the HEADER> VERSION> attribute.


      WARNING  16 (Line 10:69): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered in the HEADER> NAME> attribute.


      WARNING  16 (Line 11:64): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered in the HEADER> DEBUG-LEVEL> attribute.


      WARNING  25 (Line 12:47): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  16 (Line 12:84): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered in the HEADER> MAX-ERRORS> attribute.


      ERROR  4 (Line 20:0): Encountered end of file unexpectedly.
        EOF encountered in an alist entry with excess values.

Unable to continue parse -- Aborting...
