
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  37 (Line 24:15): Encountered a predicate definition in which the name of the predicate is not a valid predicate name.
        Will coerce the name to a valid predicate name.


      WARNING  74 (Line 231:87): Encountered excess arguments in a predicate value.  The excess arguments were discarded.


      WARNING  66 (Line 232:70): Encountered a formal argument whose name does not match the expected formal argumentname.
        The formal argument appeared in a predicate value.  The expected formal argument will be used.


      WARNING  74 (Line 234:38): Encountered excess arguments in a predicate value.  The excess arguments were discarded.


      WARNING  68 (Line 237:11): Encountered a predicate value with an invalid predicate name.
        Will coerce the name to a valid predicate name.


      WARNING  69 (Line 237:11): Encountered a predicate value that refers to an undefined predicate.  The predicate value will be discarded.


      WARNING 131 (Line 239:93): Encountered excess arguments in a column predicate value.  The excess arguments were discarded.


      WARNING  72 (Line 240:20): Attempt to use a declared predicate or column variable name as a nominal.  Will discard the name and use the appropriate formal argument in its place.
        The predicate or column variable name appeared in a predicate value.


      WARNING  72 (Line 240:29): Attempt to use a declared predicate or column variable name as a nominal.  Will discard the name and use the appropriate formal argument in its place.
        The predicate or column variable name appeared in a predicate value.


      WARNING  22 (Line 243:15): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the SYSTEM> section must be a list.

