00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa database.
00006  ;
00007  ( setf macshapa-db '((HEADER> 1) (USER> 2) (QUERY> 3) (SYSTEM> 4) ) )

      WARNING  22 (Line 7:31): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the HEADER> section must be a list.


      WARNING  22 (Line 7:41): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> section must be a list.


      WARNING  22 (Line 7:52): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the QUERY> section must be a list.

