
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  16 (Line 39:107): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered a FORMAL-ARG-LIST> attribute.


      ERROR  4 (Line 59:0): Encountered end of file unexpectedly.
        EOF in a FORMAL-ARG-LIST> attribute.

Unable to continue parse -- Aborting...
