00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 2 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 


Current Header Settings:
db.name = "parser_test.db"
odb file format version = 1
warning limit = 50
error limit = 10
debug level = 2

00019        (
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022              ( |pred_1| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| ) ) ) )
00023              ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )


Predicate Definition:
	name = "pred_1"
	variable length = false
	arg 0 = "<arg1>"
	arg 1 = "<arg2>"

00024            )
00025          ) 


Predicate Definition:
	name = "pred_2"
	variable length = true
	arg 0 = "<arg1>"

00026          ( SPREADSHEET-VARIABLE-DECLARATIONS> 
00027            (
00028              ( |a text var| 
00029                ( 
00030                  ( TYPE> <<TEXT>> ) 
00031                  ( VARIABLE-LENGTH> FALSE )
00032                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) ) 
00033                  ( COLUMN-WIDTH> 200 ) 
00034                ) 
00035              )
00036              ( |a nominal var| 


Spreadsheet Variable Definition:
	name = "a text var"
	type = TEXT
	variable length = false
	column width = 200
00037                ( 
00038                  ( TYPE> <<NOMINAL>> ) 
00039                  ( VARIABLE-LENGTH> FALSE )
00040                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00041                  ( COLUMN-WIDTH> 200 ) 
00042                ) 
00043              )
00044              ( |an integer var| 


Spreadsheet Variable Definition:
	name = "a nominal var"
	type = NOMINAL
	variable length = false
	column width = 200
00045                ( 
00046                  ( TYPE> <<INTEGER>> ) 
00047                  ( VARIABLE-LENGTH> FALSE )
00048                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00049                  ( COLUMN-WIDTH> 200 ) 
00050                ) 
00051              )
00052              ( |a float var| 


Spreadsheet Variable Definition:
	name = "an integer var"
	type = INTEGER
	variable length = false
	column width = 200
00053                ( 
00054                  ( TYPE> <<FLOAT>> ) 
00055                  ( VARIABLE-LENGTH> FALSE )
00056                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00057                  ( COLUMN-WIDTH> 200 ) 
00058                ) 
00059              )
00060              ( |a predicate var| 


Spreadsheet Variable Definition:
	name = "a float var"
	type = FLOAT
	variable length = false
	column width = 200
00061                ( 
00062                  ( TYPE> <<PREDICATE>> ) 
00063                  ( VARIABLE-LENGTH> FALSE )
00064                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00065                  ( COLUMN-WIDTH> 200 ) 
00066                ) 
00067              )
00068              ( |fixed len matrix| 


Spreadsheet Variable Definition:
	name = "a predicate var"
	type = PREDICATE
	variable length = false
	column width = 200
00069                ( 
00070                  ( TYPE> <<MATRIX>> ) 
00071                  ( VARIABLE-LENGTH> FALSE )
00072                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg1>| |<arg2>| ) )  
00073                  ( COLUMN-WIDTH> 200 ) 
00074                ) 
00075              )
00076              ( |var len matrix| 


Spreadsheet Variable Definition:
	name = "fixed len matrix"
	type = MATRIX
	variable length = false
	column width = 200
00077                ( 
00078                  ( TYPE> <<MATRIX>> ) 
00079                  ( VARIABLE-LENGTH> TRUE )
00080                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg1>| |<arg2>| ) )  
00081                  ( COLUMN-WIDTH> 225 ) 
00082                ) 
00083              )
00084            ) 
00085          ) 


Spreadsheet Variable Definition:
	name = "var len matrix"
	type = MATRIX
	variable length = true
	column width = 225
00086          ( SPREADSHEET-VARIABLE-DEFINITIONS>
00087           ( 
00088              
00089              ( |a nominal var|
00090                (
00091                  ( CELLS>
00092                    (
00093                      ( 
00094                        ( ONSET> 0 ) 
00095                        ( OFFSET> 0 ) 
00096                        ( |<val>| |this is nominal cell| ) 
00097                      )
00098                      ( 
00099                        ( ONSET> 60 )  


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = this is nominal cell
00100                        ( OFFSET> 60 ) 
00101                        ( |<val>| |<val>| ) 
00102                      )
00103                    )
00104                  )
00105                )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 
00106              )
00107              ( |an integer var|
00108                (
00109                  ( CELLS>
00110                    (
00111                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| 10 ) )
00112                      ( 
00113                        ( ONSET> 60 )  


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 10
00114                        ( OFFSET> 60 ) 
00115                        ( |<val>| 0) 
00116                      )
00117                    )
00118                  )
00119                )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 0
00120              )
00121              ( |a float var|
00122                (
00123                  ( CELLS>
00124                    (
00125                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| 10.0 ) )
00126                      ( 
00127                        ( ONSET> 60 )  


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 10.000000
00128                        ( OFFSET> 60 ) 
00129                        ( |<val>| 0.0 ) 
00130                      )
00131                    )
00132                  )
00133                )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 0.000000
00134              )
00135              ( |a predicate var|
00136                (
00137                  ( CELLS>
00138                    (
00139                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| ( |pred_1| ( TIME> 120 ) |a nominal| ) ) )
00140                      ( ( ONSET> 10 ) ( OFFSET> 20 ) ( |<val>| ( |pred_1| "a string" |<arg2>| ) ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = pred_1(00:00:02:000, a nominal)
00141                      ( ( ONSET> 20 ) ( OFFSET> 30 ) ( |<val>| ( |pred_1| 10 1.0 ) ) )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:010
	offset = 00:00:00:020
	value = pred_1("a string", <arg2>)
00142                      ( ( ONSET> 30 ) ( OFFSET> 40 ) ( |<val>| ( |pred_1| ( |pred_2| |<arg1>| ) |<arg2>| ) ) )


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:020
	offset = 00:00:00:030
	value = pred_1(10, 1.000000)
00143                      ( 
00144                        ( ONSET> 60 ) 


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:00:030
	offset = 00:00:00:040
	value = pred_1(pred_2(<arg1>), <arg2>)
00145                        ( OFFSET> 60 ) 
00146                        ( |<val>| ( ) ) 
00147                      )
00148                    )
00149                  )
00150                  ( VOCAB> ( |pred_1| |pred_2| ) )


Spreadsheet Variable Cell Definition:
	ord = 5
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = ()
00151                )
00152              )
00153              ( |fixed len matrix|
00154                (
00155                  ( CELLS>
00156                    (
00157                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<arg1>| 1 ) ( |<arg2>| 2.0 ) )
00158                      ( ( ONSET> 10 ) ( OFFSET> 20 ) ( |<arg1>| |a nominal| ) ( |<arg2>| "a string" ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 1, 2.000000
00159                      ( ( ONSET> 20 ) ( OFFSET> 30 ) ( |<arg1>| ( |pred_2| |<arg1>| ) ) ( |<arg2>| ( TIME> 120 ) ) )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:010
	offset = 00:00:00:020
	value = a nominal, "a string"
00160                      ( 
00161                        ( ONSET> 60 ) 


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:020
	offset = 00:00:00:030
	value = pred_2(<arg1>), 00:00:02:000
00162                        ( OFFSET> 60 ) 
00163                        ( |<arg1>| |<arg1>| ) 
00164                        ( |<arg2>| |<arg2>| ) 
00165                      )
00166                      ( 
00167                        ( ONSET> 60 ) 


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = <arg1>, <arg2>
00168                        ( OFFSET> 60 ) 
00169                        ( |<arg1>| "first arg" ) 
00170                        ( |<arg2>| "second arg" ) 
00171                      )
00172                      ( 
00173                        ( ONSET> 61 ) 


Spreadsheet Variable Cell Definition:
	ord = 5
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = "first arg", "second arg"
00174                        ( OFFSET> 61 )
00175                        ( |<arg1>| "first arg" ) 
00176                        ( |<arg2>| "second arg" ) 
00177                      )
00178                      ( 
00179                        ( ONSET> 62 ) 


Spreadsheet Variable Cell Definition:
	ord = 6
	onset = 00:00:01:001
	offset = 00:00:01:001
	value = "first arg", "second arg"
00180                        ( OFFSET> 62 ) 
00181                        ( |<arg1>| "first arg" ) 
00182                        ( |<arg2>| "second arg" ) 
00183                      )
00184                      ( 
00185                        ( ONSET> 63 ) 


Spreadsheet Variable Cell Definition:
	ord = 7
	onset = 00:00:01:002
	offset = 00:00:01:002
	value = "first arg", "second arg"
00186                        ( OFFSET> 63 )
00187                        ( |<arg1>| "first arg" ) 
00188                        ( |<arg2>| "second arg" ) 
00189                      )
00190                    )
00191                  )
00192                  ( VOCAB> ( |pred_1| |pred_2| ) ) 


Spreadsheet Variable Cell Definition:
	ord = 8
	onset = 00:00:01:003
	offset = 00:00:01:003
	value = "first arg", "second arg"
00193                )
00194              )
00195              ( |var len matrix|
00196                (
00197                  ( CELLS>
00198                    (
00199                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<arg1>| 1 ) ( |<arg2>| 2.0 ) )
00200                      ( ( ONSET> 10 ) ( OFFSET> 20 ) ( |<arg1>| |a nominal| ) ( |<arg2>| "a string" ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 1, 2.000000
00201                      ( ( ONSET> 20 ) ( OFFSET> 30 ) ( |<arg1>| ( |pred_2| |<arg1>| ) ) ( |<arg2>| ( TIME> 120 ) ) )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:010
	offset = 00:00:00:020
	value = a nominal, "a string"
00202                      ( ( ONSET> 60 ) ( OFFSET> 60 ) ( |<arg1>| |<arg1>| ) )


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:020
	offset = 00:00:00:030
	value = pred_2(<arg1>), 00:00:02:000
00203                      ( ( ONSET> 60 ) ( OFFSET> 60 ) ( |<arg1>| |<arg1>| ) ( |<arg2>| |<arg2>| ) )


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = <arg1>, <arg2>
00204                      ( 
00205                        ( ONSET> 61 ) 


Spreadsheet Variable Cell Definition:
	ord = 5
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = <arg1>, <arg2>
00206                        ( OFFSET> 61 ) 
00207                        ( |<arg1>| "first arg" ) 
00208                        ( |<arg2>| "second arg" ) 
00209                      )
00210                      ( 
00211                        ( ONSET> 62 ) 


Spreadsheet Variable Cell Definition:
	ord = 6
	onset = 00:00:01:001
	offset = 00:00:01:001
	value = "first arg", "second arg"
00212                        ( OFFSET> 62 ) 
00213                        ( |<arg1>| "first arg" ) 
00214                        ( |<arg2>| "second arg" ) 
00215                      )
00216                      ( 
00217                        ( ONSET> 63 ) 


Spreadsheet Variable Cell Definition:
	ord = 7
	onset = 00:00:01:002
	offset = 00:00:01:002
	value = "first arg", "second arg"
00218                        ( OFFSET> 63 ) 
00219                        ( |<arg1>| "first arg" ) 
00220                        ( |<arg2>| "second arg" ) 
00221                      )
00222                      ( 
00223                        ( ONSET> 64 ) 


Spreadsheet Variable Cell Definition:
	ord = 8
	onset = 00:00:01:003
	offset = 00:00:01:003
	value = "first arg", "second arg"
00224                        ( OFFSET> 64 ) 
00225                        ( |<arg1>| "first arg" 66 ) 
00226                        ( |<arg2>| "second arg" ( "a" "random" "list" setf ' 33 ) ) 

      WARNING  16 (Line 225:49): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered a cell value attribute.

00227                      )
00228                      ( 

      WARNING  16 (Line 226:81): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered a cell value attribute.

00229                        ( ONSET> 65 ) 


Spreadsheet Variable Cell Definition:
	ord = 9
	onset = 00:00:01:004
	offset = 00:00:01:004
	value = "first arg", "second arg"
00230                        ( OFFSET> 65 ) 
00231                        ( |<arg1>| "first arg" ) 
00232                        ( |<arg2>| "second arg" ) 
00233                      )
00234                    )
00235                  )
00236                  ( VOCAB> ( |pred_1| |pred_2| ) )


Spreadsheet Variable Cell Definition:
	ord = 10
	onset = 00:00:01:005
	offset = 00:00:01:005
	value = "first arg", "second arg"
00237                )
00238              )
00239              ( |a text var|
00240                ( 
00241                  ( CELLS>
00242                    ( 
00243                      (
00244                        ( ONSET>  0 ) 
00245                        ( OFFSET> 0 ) 
00246                        ( |<val>| "this is a text cell") 
00247                      )
00248                      ( 
00249                        ( ONSET>  60 ) 


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = this is a text cell
00250                        ( OFFSET> 60 ) 
00251                        ( |<val>| "") 
00252                      )
00253                      ( 
00254                        ( ONSET> 120 )  


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 
00255                        ( OFFSET> 120 )  
00256                        ( |<val>| )  ; an empty text cell value
00257                      )
00258                      ( 

      WARNING  65 (Line 256:33): Encountered a cell value whose value appears to be missing.
        Text cell value set to the empty string.

00259                        ( ONSET> 121 )  


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:02:000
	offset = 00:00:02:000
	value = 
00260                        ( OFFSET> 121 )  
00261                        ( |<val>| 1 ) ; text cell type mismatch
00262                      )

      WARNING  64 (Line 261:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Will force the text cell value to a text representation of the value.

00263                      ( 
00264                        ( ONSET> 121 )  


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:02:001
	offset = 00:00:02:001
	value = 1
00265                        ( OFFSET> 121 )  
00266                        ( |<val>| 1.0 ) ; text cell type mismatch
00267                      )

      WARNING  64 (Line 266:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Will force the text cell value to a text representation of the value.

00268                      ( 
00269                        ( ONSET> 121 )  


Spreadsheet Variable Cell Definition:
	ord = 5
	onset = 00:00:02:001
	offset = 00:00:02:001
	value = 1.0
00270                        ( OFFSET> 121 )  
00271                        ( |<val>| |sasquatch| ) ; text cell type mismatch
00272                      )

      WARNING  64 (Line 271:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Will force the text cell value to a text representation of the value.

00273                      ( 
00274                        ( ONSET> 121 )  


Spreadsheet Variable Cell Definition:
	ord = 6
	onset = 00:00:02:001
	offset = 00:00:02:001
	value = sasquatch
00275                        ( OFFSET> 121 )  
00276                        ( |<val>| TRUE ) ; text cell type mismatch
00277                      )

      WARNING  64 (Line 276:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Will force the text cell value to a text representation of the value.

00278                      ( 
00279                        ( ONSET> 121 )  


Spreadsheet Variable Cell Definition:
	ord = 7
	onset = 00:00:02:001
	offset = 00:00:02:001
	value = TRUE
00280                        ( OFFSET> 121 )  
00281                        ( |<val>| <<TEXT>> ) ; text cell type mismatch
00282                      )

      WARNING  64 (Line 281:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Will force the text cell value to a text representation of the value.

00283                      ( 
00284                        ( ONSET> 121 )  


Spreadsheet Variable Cell Definition:
	ord = 8
	onset = 00:00:02:001
	offset = 00:00:02:001
	value = <<TEXT>>
00285                        ( OFFSET> 121 )  
00286                        ( |<val>| NONE-SUCH> ) ; text cell type mismatch
00287                      )

      WARNING  64 (Line 286:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Will force the text cell value to a text representation of the value.

00288                      ( 
00289                        ( ONSET> 121 )  


Spreadsheet Variable Cell Definition:
	ord = 9
	onset = 00:00:02:001
	offset = 00:00:02:001
	value = NONE-SUCH>
00290                        ( OFFSET> 121 )  
00291                        ( |<val>| setf ) ; text cell type mismatch
00292                      )

      WARNING  64 (Line 291:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Will force the text cell value to a text representation of the value.

00293                      ( 
00294                        ( ONSET> 121 )  


Spreadsheet Variable Cell Definition:
	ord = 10
	onset = 00:00:02:001
	offset = 00:00:02:001
	value = setf
00295                        ( OFFSET> 121 )  
00296                        ( |<val>| macshapa-db ) ; text cell type mismatch
00297                      )

      WARNING  64 (Line 296:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Will force the text cell value to a text representation of the value.

00298                      ( 
00299                        ( ONSET> 121 )  


Spreadsheet Variable Cell Definition:
	ord = 11
	onset = 00:00:02:001
	offset = 00:00:02:001
	value = macshapa-db
00300                        ( OFFSET> 121 )  
00301                        ( |<val>| ' ) ; text cell type mismatch
00302                      )

      WARNING  64 (Line 301:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Will force the text cell value to a text representation of the value.

00303                      ( 
00304                        ( ONSET> 122 )  


Spreadsheet Variable Cell Definition:
	ord = 12
	onset = 00:00:02:001
	offset = 00:00:02:001
	value = '
00305                        ( OFFSET> 122 )  
00306                        ( |<val>| ( "a" |random| "list of" 3.0 ( "elements" ) ) ) ; another text cell type mismatch

      WARNING  64 (Line 306:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        The value is a list, which will be discarded. Text cell value will be set to the empty string.

00307                      )
00308                      ( 
00309                        ( ONSET> 123 )  


Spreadsheet Variable Cell Definition:
	ord = 13
	onset = 00:00:02:002
	offset = 00:00:02:002
	value = 
00310                        ( OFFSET> 123 )  
00311                        ( 
00312                          |<val>| 
00313                          ; unexpected EOF in a text cell value
00314  ;                        "this is a text cell"
00315  ;                      ) 
00316  ;                    )
00317  ;                  )
00318  ;                )
00319  ;              )
00320  ;            )
00321  ;          )
00322  ;        )
00323  ;      ) 
00324  ;    ) 
00325  ;    ( QUERY> 2 )
00326  ;    ( SYSTEM> 3 )
00327  ;  ) 
00328  ;)

      ERROR  4 (Line 328:0): Encountered end of file unexpectedly.
        EOF in a text cell value.

Unable to continue parse -- Aborting...
