00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 2 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 


Current Header Settings:
db.name = "parser_test.db"
odb file format version = 1
warning limit = 50
error limit = 10
debug level = 2

00019        (
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022            	; no predicate definitions, for now
00023            )
00024          ) 
00025          ( SPREADSHEET-VARIABLE-DECLARATIONS> 
00026            (
00027              ( |<a-text-var>| 
00028                ( 
00029                  ( TYPE> <<TEXT>> ) 

      WARNING  41 (Line 27:15): Encountered a spreadsheet variable declaration in which the name of the spreadsheet variable is not a valid spreadsheet variable name.
        Will coerce the name to a valid spreadsheet variable name.

00030                  ( VARIABLE-LENGTH> FALSE )
00031                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) ) 
00032                  ( COLUMN-WIDTH> 200 ) 
00033                ) 
00034              )
00035              ( |s-var 1| 


Spreadsheet Variable Definition:
	name = "_a-text-var_"
	type = TEXT
	variable length = false
	column width = 200
00036                ; an empty s-var dec
00037              )
00038              ( |s-var 2| 

      WARNING  42 (Line 37:13): Encountered a spreadsheet variable declaration that appears to be missing its a-list.  The declaration will be ignored.

00039                TRUE ; a random atom
00040              )
00041              ( |s-var 3| 

      WARNING  43 (Line 39:15): Type mis-match in the second item in a spreadsheet variable declaration.  This item must be an attribute list describing the spreadsheet variable.
        The spreadsheet variable declaration will be discarded.

00042                ; unexpected EOF
00043  ;            )
00044  ;          )
00045  ;        ) 
00046  ;        ( SPREADSHEET-VARIABLE-DEFINITIONS> 1 )
00047  ;      ) 
00048  ;    ) 
00049  ;    ( QUERY> 2 )
00050  ;    ( SYSTEM> 3 )
00051  ;  ) 
00052  ;)

      ERROR  4 (Line 52:0): Encountered end of file unexpectedly.
        EOF in a spreadsheet variable declaration.

Unable to continue parse -- Aborting...
