00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db '( 
00008                        (HEADER> ( 
00009                                   (VERSION> 2)
00010                                   (NAME> "parser_test.db")
00011                                   (MAX-ERRORS> 5)
00012                                   (MAX-WARNINGS> 30)
00013                                   (DEBUG-LEVEL> 5) 
00014                                   
00015                                   ; duplicates of all the expected attributes
00016                                   
00017                                   (VERSION> 2)

      WARNING  17 (Line 17:35): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate HEADER> VERSION> entry.

00018                                   (NAME> "parser_test.db")

      WARNING  17 (Line 18:35): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate HEADER> NAME> entry.

00019                                   (MAX-ERRORS> 5)

      WARNING  17 (Line 19:35): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate HEADER> MAX-ERRORS> entry.

00020                                   (MAX-WARNINGS> 10)

      WARNING  17 (Line 20:35): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate HEADER> MAX-WARNINGS> entry.

00021                                   (DEBUG-LEVEL> 5) 

      WARNING  17 (Line 21:35): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate HEADER> DEBUG-LEVEL> entry.

00022                                   
00023                                   ; and now an unexpected attribute
00024                                   
00025                                   (NONE-SUCH> 1)

      WARNING  18 (Line 25:35): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the HEADER> a-list.

00026                                   
00027                                   ; now a non a-list entry list in the HEADER> a-list
00028                                   
00029                                   (1)

      WARNING  19 (Line 29:35): Encountered list that is not an a-list entry in an a-list.  The list will be read and discarded.
        The list is located in the HEADER> a-list.

00030                                   
00031                                   ; and a bunch of miscelaneous atoms
00032                                   
00033                                   1 1.1 |a symbol| <<FLOAT>> "a string" TRUE FALSE NONE-SUCH> setf macshapa-db '

      WARNING  20 (Line 33:34): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the HEADER> a-list.


      WARNING  20 (Line 33:36): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the HEADER> a-list.


      WARNING  20 (Line 33:40): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the HEADER> a-list.


      WARNING  20 (Line 33:51): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the HEADER> a-list.


      WARNING  20 (Line 33:61): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the HEADER> a-list.


      WARNING  20 (Line 33:72): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the HEADER> a-list.


      WARNING  20 (Line 33:77): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the HEADER> a-list.


      WARNING  20 (Line 33:83): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the HEADER> a-list.


      WARNING  20 (Line 33:94): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the HEADER> a-list.

00034                                   
00035                                   ; unexpected EOF
00036  ;                               ) 
00037  ;                      ) 
00038  ;                      (USER> 1) 
00039  ;                      (QUERY> 2)
00040  ;                      (SYSTEM> 3)
00041  ;                   ) 
00042  ;)

      WARNING  20 (Line 33:99): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the HEADER> a-list.


      WARNING  20 (Line 33:111): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the HEADER> a-list.


      ERROR  4 (Line 42:0): Encountered end of file unexpectedly.
        EOF occurred the HEADER> a-list.

Unable to continue parse -- Aborting...


Current Header Settings:
db.name = "parser_test.db"
odb file format version = 2
warning limit = 30
error limit = 5
debug level = 3

