
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  41 (Line 27:15): Encountered a spreadsheet variable declaration in which the name of the spreadsheet variable is not a valid spreadsheet variable name.
        Will coerce the name to a valid spreadsheet variable name.


      WARNING  42 (Line 37:13): Encountered a spreadsheet variable declaration that appears to be missing its a-list.  The declaration will be ignored.


      WARNING  43 (Line 39:15): Type mis-match in the second item in a spreadsheet variable declaration.  This item must be an attribute list describing the spreadsheet variable.
        The spreadsheet variable declaration will be discarded.


      ERROR  4 (Line 52:0): Encountered end of file unexpectedly.
        EOF in a spreadsheet variable declaration.

Unable to continue parse -- Aborting...
