
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  45 (Line 31:38): Illegal formal argument name in a spreadsheet variable formal argument list.
        The first argument in a spreadsheet variable formal argument list must be "|<ord>|".  First argument forced to "|<ord>|".


      WARNING  45 (Line 31:47): Illegal formal argument name in a spreadsheet variable formal argument list.
        The second argument in a spreadsheet variable formal argument list must be "|<onset>|".  Second argument forced to "|<onset>|".


      WARNING  45 (Line 31:58): Illegal formal argument name in a spreadsheet variable formal argument list.
        The third argument in a spreadsheet variable formal argument list must be "|<offset>|".  Third argument forced to "|<offset>|".


      WARNING  35 (Line 39:37): Encountered an atom or list in a formal argument list that isn't a formal argument.The atom or list will be discarded.
        This warning was occasioned by a nominal or predicate name.


      WARNING  35 (Line 39:52): Encountered an atom or list in a formal argument list that isn't a formal argument.The atom or list will be discarded.
        This warning was occasioned by a list.


      WARNING  35 (Line 39:65): Encountered an atom or list in a formal argument list that isn't a formal argument.The atom or list will be discarded.
        This warning was occasioned by an atom.


      WARNING  35 (Line 39:77): Encountered an atom or list in a formal argument list that isn't a formal argument.The atom or list will be discarded.
        This warning was occasioned by an atom.


      WARNING  36 (Line 47:40): Encountered an empty formal argument list.
        Formal argument list forced to "(|<ord>| |<onset>| |<offset>| |<val>|)".


      WARNING  46 (Line 55:69): The formal argument list of a spreadsheet variable must contain at least four arguments.
        Formal argument list forced to "(|<ord>| |<onset>| |<offset>| |<val>|)".


      ERROR  4 (Line 75:0): Encountered end of file unexpectedly.
        EOF encountered in a spreadsheet variable formal argument list.

Unable to continue parse -- Aborting...
