00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 2 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 


Current Header Settings:
db.name = "parser_test.db"
odb file format version = 1
warning limit = 50
error limit = 10
debug level = 2

00019        (
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022            	; no predicate definitions, for now
00023            )
00024          ) 
00025          ( SPREADSHEET-VARIABLE-DECLARATIONS> 
00026            (
00027              1
00028              ( |svar 1| 

      WARNING  40 (Line 27:13): Encountered an atom in the spreadsheet variable declarations list. The atom was discarded.

00029                ( 
00030                  ( TYPE> <<TEXT>> ) 
00031                  ( VARIABLE-LENGTH> FALSE )
00032                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) ) 
00033                  ( COLUMN-WIDTH> 200 ) 
00034                )
00035              )
00036            )
00037          ) 


Spreadsheet Variable Definition:
	name = "svar 1"
	type = TEXT
	variable length = false
	column width = 200
00038          ( SPREADSHEET-VARIABLE-DEFINITIONS> 1 )
00039        ) 

      WARNING  22 (Line 38:45): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> SPREADSHEET-VARIABLE-DEFINITIONS> a-list entry must be a (possibly empty) list of spreadsheet variable definitions.

00040      ) 
00041      ( QUERY> 2 )
00042      ( SYSTEM> 3 )

      WARNING  22 (Line 41:14): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the QUERY> section must be a list.

00043    ) 
00044  )
