00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db '( 
00008                        (HEADER> 1.1) 
00009                        (USER> "a string") 

      WARNING  22 (Line 8:32): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the HEADER> section must be a list.

00010                        NONE-SUCH> 

      WARNING  22 (Line 9:30): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> section must be a list.

00011                        (QUERY> |<a formal argument>|) 

      WARNING  20 (Line 10:23): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the database body a-list.


      WARNING   1 (Line 11:31): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ' ' (HEX 0x20)


      WARNING   1 (Line 11:31): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ' ' (HEX 0x20)

00012                        (SYSTEM> |a_predicate_name|) 

      WARNING  22 (Line 11:31): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the QUERY> section must be a list.

00013                        (HEADER> 1.1) 

      WARNING  17 (Line 13:24): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate HEADER> entry

00014                        (USER> "a string") 

      WARNING  17 (Line 14:24): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate USER> entry."

00015                        (QUERY> |<a formal argument>|) 

      WARNING   1 (Line 15:31): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ' ' (HEX 0x20)


      WARNING   1 (Line 15:31): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ' ' (HEX 0x20)


      WARNING  17 (Line 15:24): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate QUERY> entry.

00016                        (SYSTEM> |a_predicate_name|) 

      WARNING  17 (Line 16:24): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate SYSTEM> entry.

00017                    ) 
00018  )
