
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  41 (Line 36:15): Encountered a spreadsheet variable declaration in which the name of the spreadsheet variable is not a valid spreadsheet variable name.
        Will coerce the name to a valid spreadsheet variable name.


      WARNING  55 (Line 96:13): Encountered a spreadsheet variable definition in which the name of the spreadsheet variable is not a valid spreadsheet variable name.
        Will coerce the name to a valid spreadsheet variable name.


      WARNING  55 (Line 107:13): Encountered a spreadsheet variable definition in which the name of the spreadsheet variable is not a valid spreadsheet variable name.
        Will coerce the name to a valid spreadsheet variable name.


      WARNING  56 (Line 108:15): Encountered reference to an undeclared spreadsheet variable.
        The definition of the undeclared spreadsheet variable will be discarded.


      WARNING  55 (Line 118:13): Encountered a spreadsheet variable definition in which the name of the spreadsheet variable is not a valid spreadsheet variable name.
        Will coerce the name to a valid spreadsheet variable name.


      WARNING  57 (Line 118:33): Encountered a spreadsheet variable definition that appears to be missing its a-list. The definition will be ignored.


      WARNING  58 (Line 121:15): Type mis-match in the second item in a spreadsheet variable definition.  This item must be an attribute list defining the spreadsheet variable.
        The spreadsheet variable definition will be discarded.


      WARNING  44 (Line 130:13): Encountered excess values in a spreadsheet variable declaration.  The excess values were discarded.


      WARNING  44 (Line 190:13): Encountered excess values in a spreadsheet variable declaration.  The excess values were discarded.


      ERROR  4 (Line 213:0): Encountered end of file unexpectedly.
        EOF encountered in the spreadsheet variable definitions list.

Unable to continue parse -- Aborting...
