
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  65 (Line 252:33): Encountered a cell value whose value appears to be missing.
        The nominal cell will be left undefined.


      WARNING  66 (Line 257:33): Encountered a formal argument whose name does not match the expected formal argumentname.
        Mismatch occured in a nominal cell value.  The cell will be left undefined.


      WARNING  67 (Line 262:33): Nominals that appear as the value of cells in nominal spreadsheet variables cannot contain the characters '|' and ':'.
        These characters were coerced to '_', and the result used as the nominal cell value.

      WARNING  67 (Line 267:33): Nominals that appear as the value of cells in nominal spreadsheet variables cannot contain the characters '|' and ':'.
        These characters were coerced to '_', and the result used as the nominal cell value.

      WARNING  64 (Line 272:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Will discard the value && leave the nominal cell undefined.


      WARNING  64 (Line 277:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        The value is a list, which will be discarded. The nominal cell will be left undefined.


      ERROR  4 (Line 299:0): Encountered end of file unexpectedly.
        EOF in a nominal cell value.

Unable to continue parse -- Aborting...
