
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  16 (Line 225:49): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered a cell value attribute.


      WARNING  16 (Line 226:81): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered a cell value attribute.


      WARNING  65 (Line 256:33): Encountered a cell value whose value appears to be missing.
        Text cell value set to the empty string.


      WARNING  64 (Line 261:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Will force the text cell value to a text representation of the value.


      WARNING  64 (Line 266:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Will force the text cell value to a text representation of the value.


      WARNING  64 (Line 271:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Will force the text cell value to a text representation of the value.


      WARNING  64 (Line 276:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Will force the text cell value to a text representation of the value.


      WARNING  64 (Line 281:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Will force the text cell value to a text representation of the value.


      WARNING  64 (Line 286:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Will force the text cell value to a text representation of the value.


      WARNING  64 (Line 291:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Will force the text cell value to a text representation of the value.


      WARNING  64 (Line 296:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Will force the text cell value to a text representation of the value.


      WARNING  64 (Line 301:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Will force the text cell value to a text representation of the value.


      WARNING  64 (Line 306:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        The value is a list, which will be discarded. Text cell value will be set to the empty string.


      ERROR  4 (Line 328:0): Encountered end of file unexpectedly.
        EOF in a text cell value.

Unable to continue parse -- Aborting...
