00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 2 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 


Current Header Settings:
db.name = "parser_test.db"
odb file format version = 1
warning limit = 50
error limit = 10
debug level = 2

00019        (
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022            	; no predicate definitions, for now
00023            )
00024          ) 
00025          ( SPREADSHEET-VARIABLE-DECLARATIONS> 
00026            (
00027              ( |svar 1| 
00028                ( 
00029                  ( TYPE> <<INTEGER>> ) 
00030                  ( VARIABLE-LENGTH> FALSE )
00031                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
00032                  ( COLUMN-WIDTH> 200 77 ("a list" 44 ) ) ; excess values
00033                )
00034              )

      WARNING  16 (Line 32:55): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered a COLUMN-WIDTH> attribute.

00035              ( |svar 2| 


Spreadsheet Variable Definition:
	name = "svar 1"
	type = INTEGER
	variable length = false
	column width = 200
00036                ( 
00037                  ( TYPE> <<TEXT>> ) 
00038                  ( VARIABLE-LENGTH> FALSE )
00039                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )
00040                  ( COLUMN-WIDTH> 200 ; unexpeceted EOF <<TEXT>> ) 
00041  ;              )
00042  ;            )
00043  ;          )
00044  ;        ) 
00045  ;        ( SPREADSHEET-VARIABLE-DEFINITIONS> 1 )
00046  ;      ) 
00047  ;    ) 
00048  ;    ( QUERY> 2 )
00049  ;    ( SYSTEM> 3 )
00050  ;  ) 
00051  ;)

      ERROR  4 (Line 51:0): Encountered end of file unexpectedly.
        EOF in a COLUMN-WIDTH> attribute.

Unable to continue parse -- Aborting...
