
      WARNING  14 (Line 9:44): Encountered a-list entry without a value.  A-list entries must be of the form '(' <tag> <value> ')'.
        The HEADER> VERSION> attribute appears not to contain a value.  Version # forced to 1.

      WARNING  14 (Line 10:41): Encountered a-list entry without a value.  A-list entries must be of the form '(' <tag> <value> ')'.
        The HEADER> NAME> attribute appears not to contain a value.  The attribute will be ignored.

      WARNING  14 (Line 11:48): Encountered a-list entry without a value.  A-list entries must be of the form '(' <tag> <value> ')'.
        The HEADER> DEBUG-LEVEL> attribute appears not to contain a value.  Debug level forced to 0.

      WARNING  14 (Line 12:47): Encountered a-list entry without a value.  A-list entries must be of the form '(' <tag> <value> ')'.
        The HEADER> MAX-ERRORS> attribute appears not to contain a value.  Errors limit forced to 1.


      WARNING  14 (Line 13:49): Encountered a-list entry without a value.  A-list entries must be of the form '(' <tag> <value> ')'.
        The HEADER> MAX-WARNINGS> attribute appears not to contain a value.  Warnings limit forced to 1.


      ERROR  0 (Line 13:49): Warning limit exceeded - load aborted.

Unable to continue parse -- Aborting...
