
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  20 (Line 26:17): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in a predicate definition a-list.


      WARNING  20 (Line 26:19): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in a predicate definition a-list.


      WARNING  20 (Line 26:23): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in a predicate definition a-list.


      WARNING  20 (Line 26:29): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in a predicate definition a-list.


      WARNING  17 (Line 29:19): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate VARIABLE-LENGTH> entry in a predicate definition.


      WARNING  17 (Line 30:19): Duplicate a-list entry detected.  All data contained in the duplicate entry will be discarded.
        Duplicate FORMAL-ARG-LIST> entry in a predicate definition.


      WARNING  18 (Line 31:19): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in a predicate definition a-list.


      WARNING  19 (Line 32:19): Encountered list that is not an a-list entry in an a-list.  The list will be read and discarded.
        The list is located in a predicate definition a-list.


      WARNING  29 (Line 39:13): A required a-list entry appears to be missing.  Will attempt to proceed with a default value.  Errors may result.
        VARIABLE-LENGTH> entry missing from predicate definition?  VARIABLE-LENGTH> forced to false.


      WARNING  29 (Line 39:13): A required a-list entry appears to be missing.  Will attempt to proceed with a default value.  Errors may result.
        FORMAL-ARG-LIST> entry missing from predicate definition?  Will use the arg list "(|<val>|)".


      ERROR  4 (Line 54:0): Encountered end of file unexpectedly.
        EOF occurred in a predicate definition a-list.

Unable to continue parse -- Aborting...
