
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  14 (Line 169:11): Encountered a-list entry without a value.  A-list entries must be of the form '(' <tag> <value> ')'.
        The USER> SPREADSHEET-VARIABLE-DEFINITIONS> a-list entry doesn't seem to contain a value.


      ERROR 14 (Line 173:5): Encountered a-list with one or more required entries missing.
        Required entry(s) missing from the database body a-list.

Unable to continue parse -- Will continue lexer scan.

