00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 0 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 
00019         ( 
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022              ( |pred_1| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| ) ) ) )
00023              ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )
00024              ( |pred_3| ( ( VARIABLE-LENGTH> )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )         ;empty boolean

      WARNING  14 (Line 24:45): Encountered a-list entry without a value.  A-list entries must be of the form '(' <tag> <value> ')'.
        A VARIABLE-LENGTH> attribute appears not to contain a value.  Value forced to FALSE.

00025              ( |pred_4| ( ( VARIABLE-LENGTH> () )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )      ;list in boolean 

      WARNING  22 (Line 25:45): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of a VARIABLE-LENGTH> attribute must be TRUE or FALSE.  Value forced to FALSE.

00026              ( |pred_5| ( ( VARIABLE-LENGTH> |true| )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )  ;type mismatch in boolean 

      WARNING  22 (Line 26:45): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of a VARIABLE-LENGTH> attribute must be TRUE or FALSE.  Value forced to FALSE.

00027              ( |pred_6| ( ( VARIABLE-LENGTH> TRUE 1 ())  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )  ; excess values is boolean

      WARNING  16 (Line 27:54): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered a VARIABLE-LENGTH> attribute.

00028              ( |pred_7| ( ( VARIABLE-LENGTH> ; (unexpected EOF in boolean) TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )
00029  ;          )
00030  ;        ) 
00031  ;        ( SPREADSHEET-VARIABLE-DECLARATIONS> 1 ) 
00032  ;        ( SPREADSHEET-VARIABLE-DEFINITIONS> 1 )
00033  ;      ) 
00034  ;    ) 
00035  ;    ( QUERY> 2 )
00036  ;    ( SYSTEM> 3 )
00037  ;  ) 
00038  ;)

      ERROR  4 (Line 38:0): Encountered end of file unexpectedly.
        EOF in a VARIABLE-LENGTH> attribute.

Unable to continue parse -- Aborting...
