
      WARNING  25 (Line 9:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  20 (Line 253:9): Encountered an atom in an a-list.  The atom will be read and discarded.
        The atom was detected in the SYSTEM> a-list.


      WARNING  18 (Line 258:11): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the SYSTEM> a-list.

