00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db '( 
00008                        (HEADER> 1.1) 
00009                        (USER> "a string") 

      WARNING  22 (Line 8:32): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the HEADER> section must be a list.

00010                        ;(QUERY> |<a_formal_argument>|) 
00011                        (SYSTEM> |a_predicate_name|) 

      WARNING  22 (Line 9:30): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> section must be a list.


      ERROR 13 (Line 11:24): Encountered a-list entry prior to one or more of its required predicessors in its a-list.
        HEADER>, USER>, or QUERY> a-list entry(s) missing from the database body a-list?
Unable to continue parse -- Aborting...
