
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  37 (Line 24:15): Encountered a predicate definition in which the name of the predicate is not a valid predicate name.
        Will coerce the name to a valid predicate name.


      WARNING  74 (Line 255:88): Encountered excess arguments in a predicate value.  The excess arguments were discarded.


      ERROR  4 (Line 274:0): Encountered end of file unexpectedly.
        EOF encountered in a predicate value with excess arguments.

Unable to continue parse -- Aborting...
