
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  37 (Line 24:15): Encountered a predicate definition in which the name of the predicate is not a valid predicate name.
        Will coerce the name to a valid predicate name.


      WARNING  14 (Line 175:17): Encountered a-list entry without a value.  A-list entries must be of the form '(' <tag> <value> ')'.
        A VOCAB> attribute appears not to contain a value.  The attribute will be ignored.


      WARNING  22 (Line 194:26): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of a VOCAB> attribute must be a list of predicate names.  The attribute will be ignored.


      WARNING  16 (Line 194:60): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered a VOCAB> attribute.


      ERROR  4 (Line 227:0): Encountered end of file unexpectedly.
        EOF in a VOCAB> attribute.

Unable to continue parse -- Aborting...
