
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING   9 (Line 88:15): Left parentheses expected.  Left parenthesis inserted to allow continued parse.
        The opening left parenthesis of the spreadsheet variable definitions list appears to be missing.


      WARNING  22 (Line 173:14): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the QUERY> section must be a list.

