00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 2 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 


Current Header Settings:
db.name = "parser_test.db"
odb file format version = 1
warning limit = 50
error limit = 10
debug level = 2

00019        (
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022              ; a pair of valid predicate definitions
00023              ( |pred_1| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| ) ) ) )
00024              ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )


Predicate Definition:
	name = "pred_1"
	variable length = false
	arg 0 = "<arg1>"
	arg 1 = "<arg2>"

00025              
00026              
00027              ; two more valid predicate definitions, but with the order of the attributes switched
00028              ( |pred_3| ( ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| ) ) ( VARIABLE-LENGTH> FALSE ) ) )


Predicate Definition:
	name = "pred_2"
	variable length = true
	arg 0 = "<arg1>"

00029              ( |pred_4| ( ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ( VARIABLE-LENGTH> TRUE ) ) )


Predicate Definition:
	name = "pred_3"
	variable length = false
	arg 0 = "<arg1>"
	arg 1 = "<arg2>"

00030  
00031              ; a predicate definition without a variable length attribute
00032              ( |pred_5| ( ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )


Predicate Definition:
	name = "pred_4"
	variable length = true
	arg 0 = "<arg1>"

00033  
00034              ; a predicate definition without an argument list attribute
00035              ( |pred_6| ( ( VARIABLE-LENGTH> TRUE ) ) )

      WARNING  29 (Line 32:62): A required a-list entry appears to be missing.  Will attempt to proceed with a default value.  Errors may result.
        VARIABLE-LENGTH> entry missing from predicate definition?  VARIABLE-LENGTH> forced to false.



Predicate Definition:
	name = "pred_5"
	variable length = false
	arg 0 = "<arg1>"

00036              
00037              ; a predicate definition with an empty attribute list
00038              ( |pred_7| ( ) )

      WARNING  29 (Line 35:54): A required a-list entry appears to be missing.  Will attempt to proceed with a default value.  Errors may result.
        FORMAL-ARG-LIST> entry missing from predicate definition?  Will use the arg list "(|<val>|)".



Predicate Definition:
	name = "pred_6"
	variable length = true
	arg 0 = "<val>"

00039              
00040              ; a predicate definition without a value
00041              ( |pred_8| )

      WARNING  29 (Line 38:28): A required a-list entry appears to be missing.  Will attempt to proceed with a default value.  Errors may result.
        VARIABLE-LENGTH> entry missing from predicate definition?  VARIABLE-LENGTH> forced to false.


      WARNING  29 (Line 38:28): A required a-list entry appears to be missing.  Will attempt to proceed with a default value.  Errors may result.
        FORMAL-ARG-LIST> entry missing from predicate definition?  Will use the arg list "(|<val>|)".



Predicate Definition:
	name = "pred_7"
	variable length = false
	arg 0 = "<val>"

00042  
00043              ; a predicate with an illegal name
00044              ( |not a pred name| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| ) ) ) )

      WARNING  32 (Line 41:24): Encountered a predicate definition that appears to be missing its a-list.  The definition will be ignored.


      WARNING  37 (Line 44:15): Encountered a predicate definition in which the name of the predicate is not a valid predicate name.
        Will coerce the name to a valid predicate name.

00045  
00046              ; aother predicate with an illegal name
00047              ( |<really_not_a_pred_name>| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| ) ) ) )


Predicate Definition:
	name = "not_a_pred_name"
	variable length = false
	arg 0 = "<arg1>"
	arg 1 = "<arg2>"


      WARNING  37 (Line 47:15): Encountered a predicate definition in which the name of the predicate is not a valid predicate name.
        Will coerce the name to a valid predicate name.

00048  
00049  			; duplicate definition
00050              ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )


Predicate Definition:
	name = "_really_not_a_pred_name_"
	variable length = false
	arg 0 = "<arg1>"
	arg 1 = "<arg2>"

00051              
00052              ; dup def - different # of args
00053              ( |pred_1| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )


Predicate Definition:
	name = "pred_2"
	variable length = true
	arg 0 = "<arg1>"

00054              
00055              ; dup def - variable_length TRUE instead of false
00056              ( |pred_1| ( ( VARIABLE-LENGTH> TRUE ) ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| ) ) ) )


Predicate Definition:
	name = "pred_1"
	variable length = false
	arg 0 = "<arg1>"


      WARNING  38 (Line 53:89): Encountered a duplicate definition of a predicate.  The second definition will be ignored.
        New definition doesn't match old definition.  New definition ignored.
00057  
00058  			; dup def - different argument names
00059              ( |pred_1| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<val-1>| |<val-2>| ) ) ) )


Predicate Definition:
	name = "pred_1"
	variable length = true
	arg 0 = "<arg1>"
	arg 1 = "<arg2>"


      WARNING  38 (Line 56:97): Encountered a duplicate definition of a predicate.  The second definition will be ignored.
        New definition doesn't match old definition.  New definition ignored.
00060            )
00061          ) 


Predicate Definition:
	name = "pred_1"
	variable length = false
	arg 0 = "<val-1>"
	arg 1 = "<val-2>"


      WARNING  38 (Line 59:100): Encountered a duplicate definition of a predicate.  The second definition will be ignored.
        New definition doesn't match old definition -- formal argument name mismatch.  New definition ignored.
00062          ( SPREADSHEET-VARIABLE-DECLARATIONS> 1 ) 
00063          ( SPREADSHEET-VARIABLE-DEFINITIONS> 1 )

      WARNING  22 (Line 62:46): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> SPREADSHEET-VARIABLE-DECLARATIONS> a-list entry must be a (possibly empty) list of spreadsheet variable declarations.

00064        ) 

      WARNING  22 (Line 63:45): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> SPREADSHEET-VARIABLE-DEFINITIONS> a-list entry must be a (possibly empty) list of spreadsheet variable definitions.

00065      ) 
00066      ( QUERY> 2 )
00067      ( SYSTEM> 3 )

      WARNING  22 (Line 66:14): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the QUERY> section must be a list.

00068    ) 

      WARNING  22 (Line 67:15): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the SYSTEM> section must be a list.

00069  )
