00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 2 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 


Current Header Settings:
db.name = "parser_test.db"
odb file format version = 1
warning limit = 50
error limit = 10
debug level = 2

00019        (
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022              ( |pred_1| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| ) ) ) )
00023              ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )


Predicate Definition:
	name = "pred_1"
	variable length = false
	arg 0 = "<arg1>"
	arg 1 = "<arg2>"

00024              ( |not a pred name| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )


Predicate Definition:
	name = "pred_2"
	variable length = true
	arg 0 = "<arg1>"


      WARNING  37 (Line 24:15): Encountered a predicate definition in which the name of the predicate is not a valid predicate name.
        Will coerce the name to a valid predicate name.

00025            )
00026          ) 


Predicate Definition:
	name = "not_a_pred_name"
	variable length = true
	arg 0 = "<arg1>"

00027          ( SPREADSHEET-VARIABLE-DECLARATIONS> 
00028            (
00029              ( |a text var| 
00030                ( 
00031                  ( TYPE> <<TEXT>> ) 
00032                  ( VARIABLE-LENGTH> FALSE )
00033                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) ) 
00034                  ( COLUMN-WIDTH> 200 ) 
00035                ) 
00036              )
00037              ( |a nominal var| 


Spreadsheet Variable Definition:
	name = "a text var"
	type = TEXT
	variable length = false
	column width = 200
00038                ( 
00039                  ( TYPE> <<NOMINAL>> ) 
00040                  ( VARIABLE-LENGTH> FALSE )
00041                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00042                  ( COLUMN-WIDTH> 200 ) 
00043                ) 
00044              )
00045              ( |an integer var| 


Spreadsheet Variable Definition:
	name = "a nominal var"
	type = NOMINAL
	variable length = false
	column width = 200
00046                ( 
00047                  ( TYPE> <<INTEGER>> ) 
00048                  ( VARIABLE-LENGTH> FALSE )
00049                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00050                  ( COLUMN-WIDTH> 200 ) 
00051                ) 
00052              )
00053              ( |a float var| 


Spreadsheet Variable Definition:
	name = "an integer var"
	type = INTEGER
	variable length = false
	column width = 200
00054                ( 
00055                  ( TYPE> <<FLOAT>> ) 
00056                  ( VARIABLE-LENGTH> FALSE )
00057                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00058                  ( COLUMN-WIDTH> 200 ) 
00059                ) 
00060              )
00061              ( |a predicate var| 


Spreadsheet Variable Definition:
	name = "a float var"
	type = FLOAT
	variable length = false
	column width = 200
00062                ( 
00063                  ( TYPE> <<PREDICATE>> ) 
00064                  ( VARIABLE-LENGTH> FALSE )
00065                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00066                  ( COLUMN-WIDTH> 200 ) 
00067                ) 
00068              )
00069              ( |fixed len matrix| 


Spreadsheet Variable Definition:
	name = "a predicate var"
	type = PREDICATE
	variable length = false
	column width = 200
00070                ( 
00071                  ( TYPE> <<MATRIX>> ) 
00072                  ( VARIABLE-LENGTH> FALSE )
00073                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg1>| |<arg2>| ) )  
00074                  ( COLUMN-WIDTH> 200 ) 
00075                ) 
00076              )
00077              ( |var len matrix| 


Spreadsheet Variable Definition:
	name = "fixed len matrix"
	type = MATRIX
	variable length = false
	column width = 200
00078                ( 
00079                  ( TYPE> <<MATRIX>> ) 
00080                  ( VARIABLE-LENGTH> TRUE )
00081                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg1>| |<arg2>| ) )  
00082                  ( COLUMN-WIDTH> 225 ) 
00083                ) 
00084              )
00085            ) 
00086          ) 


Spreadsheet Variable Definition:
	name = "var len matrix"
	type = MATRIX
	variable length = true
	column width = 225
00087          ( SPREADSHEET-VARIABLE-DEFINITIONS>
00088           ( 
00089              ( |a text var|
00090                ( 
00091                  ( CELLS>
00092                    ( 
00093                      (
00094                        ( ONSET>  0 ) 
00095                        ( OFFSET> 0 ) 
00096                        ( |<val>| "this is a text cell") 
00097                      )
00098                      ( 
00099                        ( ONSET>  60 ) 


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = this is a text cell
00100                        ( OFFSET> 60 ) 
00101                        ( |<val>| "") 
00102                      )
00103                    )
00104                  )
00105                )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 
00106              )
00107              
00108              ( |a nominal var|
00109                (
00110                  ( CELLS>
00111                    (
00112                      ( 
00113                        ( ONSET> 0 ) 
00114                        ( OFFSET> 0 ) 
00115                        ( |<val>| |this is nominal cell| ) 
00116                      )
00117                      ( 
00118                        ( ONSET> 60 )  


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = this is nominal cell
00119                        ( OFFSET> 60 ) 
00120                        ( |<val>| |<val>| ) 
00121                      )
00122                    )
00123                  )
00124                )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 
00125              )
00126  
00127              ( |an integer var|
00128                (
00129                  ( CELLS>
00130                    (
00131                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| 10 ) )
00132                      ( 
00133                        ( ONSET> 60 )  


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 10
00134                        ( OFFSET> 60 ) 
00135                        ( |<val>| 0 ) 
00136                      )
00137                    )
00138                  )
00139                )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 0
00140              )
00141  
00142              ( |a float var|
00143                (
00144                  ( CELLS>
00145                    (
00146                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| 10.0 ) )
00147                      ( 
00148                        ( ONSET> 60 )  


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 10.000000
00149                        ( OFFSET> 60 ) 
00150                        ( |<val>| 0.0 ) 
00151                      )
00152                    )
00153                  )
00154                )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 0.000000
00155              )
00156  
00157  
00158              ( |fixed len matrix|
00159                (
00160                  ( CELLS>
00161                    (
00162                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<arg1>| 1 ) ( |<arg2>| 2.0 ) )
00163                      ( ( ONSET> 10 ) ( OFFSET> 20 ) ( |<arg1>| |a nominal| ) ( |<arg2>| "a string" ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 1, 2.000000
00164                      ( ( ONSET> 20 ) ( OFFSET> 30 ) ( |<arg1>| ( |pred_2| |<arg1>| ) ) ( |<arg2>| ( TIME> 120 ) ) )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:010
	offset = 00:00:00:020
	value = a nominal, "a string"
00165                      ( 
00166                        ( ONSET> 60 ) 


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:020
	offset = 00:00:00:030
	value = pred_2(<arg1>), 00:00:02:000
00167                        ( OFFSET> 60 ) 
00168                        ( |<arg1>| |<arg1>| ) 
00169                        ( |<arg2>| |<arg2>| ) 
00170                      )
00171                      ( 
00172                        ( ONSET> 60 ) 


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = <arg1>, <arg2>
00173                        ( OFFSET> 60 ) 
00174                        ( |<arg1>| "first arg" ) 
00175                        ( |<arg2>| "second arg" ) 
00176                      )
00177                      ( 
00178                        ( ONSET> 61 ) 


Spreadsheet Variable Cell Definition:
	ord = 5
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = "first arg", "second arg"
00179                        ( OFFSET> 61 )
00180                        ( |<arg1>| "first arg" ) 
00181                        ( |<arg2>| "second arg" ) 
00182                      )
00183                      ( 
00184                        ( ONSET> 62 ) 


Spreadsheet Variable Cell Definition:
	ord = 6
	onset = 00:00:01:001
	offset = 00:00:01:001
	value = "first arg", "second arg"
00185                        ( OFFSET> 62 ) 
00186                        ( |<arg1>| "first arg" ) 
00187                        ( |<arg2>| "second arg" ) 
00188                      )
00189                      ( 
00190                        ( ONSET> 63 ) 


Spreadsheet Variable Cell Definition:
	ord = 7
	onset = 00:00:01:002
	offset = 00:00:01:002
	value = "first arg", "second arg"
00191                        ( OFFSET> 63 )
00192                        ( |<arg1>| "first arg" ) 
00193                        ( |<arg2>| "second arg" ) 
00194                      )
00195                    )
00196                  )
00197                  ( VOCAB> ( |pred_1| |pred_2| ) ) 


Spreadsheet Variable Cell Definition:
	ord = 8
	onset = 00:00:01:003
	offset = 00:00:01:003
	value = "first arg", "second arg"
00198                )
00199              )
00200              ( |var len matrix|
00201                (
00202                  ( CELLS>
00203                    (
00204                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<arg1>| 1 ) ( |<arg2>| 2.0 ) )
00205                      ( ( ONSET> 10 ) ( OFFSET> 20 ) ( |<arg1>| |a nominal| ) ( |<arg2>| "a string" ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 1, 2.000000
00206                      ( ( ONSET> 20 ) ( OFFSET> 30 ) ( |<arg1>| ( |pred_2| |<arg1>| ) ) ( |<arg2>| ( TIME> 120 ) ) )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:010
	offset = 00:00:00:020
	value = a nominal, "a string"
00207                      ( ( ONSET> 60 ) ( OFFSET> 60 ) ( |<arg1>| |<arg1>| ) )


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:020
	offset = 00:00:00:030
	value = pred_2(<arg1>), 00:00:02:000
00208                      ( ( ONSET> 60 ) ( OFFSET> 60 ) ( |<arg1>| |<arg1>| ) ( |<arg2>| |<arg2>| ) )


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = <arg1>, <arg2>
00209                      ( 
00210                        ( ONSET> 61 ) 


Spreadsheet Variable Cell Definition:
	ord = 5
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = <arg1>, <arg2>
00211                        ( OFFSET> 61 ) 
00212                        ( |<arg1>| "first arg" ) 
00213                        ( |<arg2>| "second arg" ) 
00214                      )
00215                      ( 
00216                        ( ONSET> 62 ) 


Spreadsheet Variable Cell Definition:
	ord = 6
	onset = 00:00:01:001
	offset = 00:00:01:001
	value = "first arg", "second arg"
00217                        ( OFFSET> 62 ) 
00218                        ( |<arg1>| "first arg" ) 
00219                        ( |<arg2>| "second arg" ) 
00220                      )
00221                      ( 
00222                        ( ONSET> 63 ) 


Spreadsheet Variable Cell Definition:
	ord = 7
	onset = 00:00:01:002
	offset = 00:00:01:002
	value = "first arg", "second arg"
00223                        ( OFFSET> 63 ) 
00224                        ( |<arg1>| "first arg" ) 
00225                        ( |<arg2>| "second arg" ) 
00226                      )
00227                      ( 
00228                        ( ONSET> 64 ) 


Spreadsheet Variable Cell Definition:
	ord = 8
	onset = 00:00:01:003
	offset = 00:00:01:003
	value = "first arg", "second arg"
00229                        ( OFFSET> 64 ) 
00230                        ( |<arg1>| "first arg" ) 
00231                        ( |<arg2>| ( |an integer var| 1 2 3 4 ) ) ; reference to a spreadsheet variable

      WARNING 126 (Line 231:55): Encountered type mismatch between argument and formal argument.  Argument replaced with an undefined value.

      WARNING 126 (Line 231:57): Encountered type mismatch between argument and formal argument.  Argument replaced with an undefined value.
00232                      )
00233                    )
00234                  )
00235                  ( VOCAB> ( |pred_1| |pred_2| ) )


Spreadsheet Variable Cell Definition:
	ord = 9
	onset = 00:00:01:004
	offset = 00:00:01:004
	value = "first arg", an integer var(1, <onset>, <offset>, 4)
00236                )
00237              )
00238              
00239              ( |a predicate var|
00240                (
00241                  ( CELLS>
00242                    (
00243                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| ( |pred_1| ( TIME> 120 ) |a nominal| ) ) )
00244                      ( ( ONSET> 10 ) ( OFFSET> 20 ) ( |<val>| ( |pred_1| "a string" |<arg2>| ) ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = pred_1(00:00:02:000, a nominal)
00245                      ( ( ONSET> 20 ) ( OFFSET> 30 ) ( |<val>| ( |pred_1| 10 1.0 ) ) )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:010
	offset = 00:00:00:020
	value = pred_1("a string", <arg2>)
00246                      ( ( ONSET> 30 ) ( OFFSET> 40 ) ( |<val>| ( |pred_1| ( |pred_2| |<arg1>| ) |<arg2>| ) ) )


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:020
	offset = 00:00:00:030
	value = pred_1(10, 1.000000)
00247                      ( 
00248                        ( ONSET> 60 ) 


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:00:030
	offset = 00:00:00:040
	value = pred_1(pred_2(<arg1>), <arg2>)
00249                        ( OFFSET> 60 ) 
00250                        ( |<val>| ( ) ) 
00251                      )
00252                      ( 
00253                        ( ONSET> 61 ) 


Spreadsheet Variable Cell Definition:
	ord = 5
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = ()
00254                        ( OFFSET> 61 ) 
00255                        ( |<val>| ( |not a pred name| 10 ) ) ; test to see if we coerse predicate names correctly

      WARNING  68 (Line 255:35): Encountered a predicate value with an invalid predicate name.
        Will coerce the name to a valid predicate name.

00256                      )
00257                      ( 
00258                        ( ONSET> 62 ) 


Spreadsheet Variable Cell Definition:
	ord = 6
	onset = 00:00:01:001
	offset = 00:00:01:001
	value = not_a_pred_name(10)
00259                        ( OFFSET> 62 ) 
00260                        ( |<val>| ( |pred_1| "a test quote string with a character that can't appear in a quote string --
00261  specifically, a <CR>." ) )

      WARNING  71 (Line 260:44): Illegal characters encountered in a quote string appearing in a matrix or predicate argument.  The illegal characters were replaced with spaces.
        The quote string appeared in a matrix or predicate value.

00262                      )
00263                      ( 

      WARNING  75 (Line 261:26): Encountered predicate value which is missing one or more required arguments.  These argument(s) will be filled in with formal arguments.

00264                        ( ONSET> 63 ) 


Spreadsheet Variable Cell Definition:
	ord = 7
	onset = 00:00:01:002
	offset = 00:00:01:002
	value = pred_1("a test quote string with a character that can't appear in a quote string -- specifically, a <CR>.", <arg2>)
00265                        ( OFFSET> 63 ) 
00266                        ( |<val>| ( |no_such_pred| 10 ) ) ; reference to an undefined predicate

      WARNING  69 (Line 266:35): Encountered a predicate value that refers to an undefined predicate.  The predicate value will be discarded.

00267                      )
00268                      ( 
00269                        ( ONSET> 64 ) 


Spreadsheet Variable Cell Definition:
	ord = 8
	onset = 00:00:01:003
	offset = 00:00:01:003
	value = ()
00270                        ( OFFSET> 64 )
00271                        ; Note that the following is not an error in MacSHAPA, as column predicates
00272                        ; can be used any place a predicate can be.
00273                        ;
00274                        ; In contrast, OpenSHAPA has stronger type checking, and only allows column
00275                        ; predicates to replace untyped and column predicate formal arguments.
00276                        ( |<val>| ( |an integer var| 1 2 3 4 ) ) ; reference to a spreadsheet variable

      WARNING  68 (Line 276:35): Encountered a predicate value with an invalid predicate name.
        Will coerce the name to a valid predicate name.


      WARNING  69 (Line 276:35): Encountered a predicate value that refers to an undefined predicate.  The predicate value will be discarded.

00277                      )
00278                      ( 
00279                        ( ONSET> 65 ) 


Spreadsheet Variable Cell Definition:
	ord = 9
	onset = 00:00:01:004
	offset = 00:00:01:004
	value = ()
00280                        ( OFFSET> 65 ) 
00281                        ( |<val>| ( |pred_2| ( "a random" 3.0 |item list| ) ) ) ; a random list as a predicate value

      WARNING  70 (Line 281:46): Encountered a list that does not describe a predicate value where a predicate value was expected.  The list will be discarded.

00282                      )
00283                      ( 
00284                        ( ONSET> 66 ) 


Spreadsheet Variable Cell Definition:
	ord = 10
	onset = 00:00:01:005
	offset = 00:00:01:005
	value = pred_2(<arg1>)
00285                        ( OFFSET> 66 ) 
00286                        ( |<val>| ( |pred_1| |pred_1| |an integer var| ) ) ; use of a pred & col name as a nominal
00287                      )
00288                      ( 
00289                        ( ONSET> 67 ) 


Spreadsheet Variable Cell Definition:
	ord = 11
	onset = 00:00:01:006
	offset = 00:00:01:006
	value = pred_1(pred_1, an integer var)
00290                        ( OFFSET> 67 ) 
00291                        ( |<val>| ( |pred_1| ) ) ; too few arguments
00292                      )
00293                      ( 

      WARNING  75 (Line 291:46): Encountered predicate value which is missing one or more required arguments.  These argument(s) will be filled in with formal arguments.

00294                        ( ONSET> 68 ) 


Spreadsheet Variable Cell Definition:
	ord = 12
	onset = 00:00:01:007
	offset = 00:00:01:007
	value = pred_1(<arg1>, <arg2>)
00295                        ( OFFSET> 68 ) 
00296                        ( |<val>| ( |pred_1| 1 2 3 4 5 ) ) ; too many arguments
00297                      )

      WARNING  74 (Line 296:54): Encountered excess arguments in a predicate value.  The excess arguments were discarded.

00298                      ( 
00299                        ( ONSET> 69 ) 


Spreadsheet Variable Cell Definition:
	ord = 13
	onset = 00:00:01:008
	offset = 00:00:01:008
	value = pred_1(1, 2)
00300                        ( OFFSET> 69 ) 
00301                        ( |<val>| ( |pred_2| ) ) ; too few arguments in a variable length predicate
00302                      )
00303                      ( 

      WARNING  75 (Line 301:46): Encountered predicate value which is missing one or more required arguments.  These argument(s) will be filled in with formal arguments.

00304                        ( ONSET> 70 ) 


Spreadsheet Variable Cell Definition:
	ord = 14
	onset = 00:00:01:009
	offset = 00:00:01:009
	value = pred_2(<arg1>)
00305                        ( OFFSET> 70 ) 
00306                        ( |<val>| ( |pred_2| 1 2 3 4 5 ) ) ; too many arguments in a variable length predicate
00307                      )

      WARNING  74 (Line 306:54): Encountered excess arguments in a predicate value.  The excess arguments were discarded.

00308                      ( 
00309                        ( ONSET> 71 ) 


Spreadsheet Variable Cell Definition:
	ord = 15
	onset = 00:00:01:010
	offset = 00:00:01:010
	value = pred_2(1)
00310                        ( OFFSET> 71 ) 
00311                        ( |<val>| ( |pred_1| NONE-SUCH> TRUE ) ) ; illegal argument types

      WARNING  73 (Line 311:44): Encountered an illegal argument in a predicate value argument list.  Will replace the argument with the associated formal argument.


      WARNING  73 (Line 311:55): Encountered an illegal argument in a predicate value argument list.  Will replace the argument with the associated formal argument.

00312                      )
00313                      ( 
00314                        ( ONSET> 72 ) 


Spreadsheet Variable Cell Definition:
	ord = 16
	onset = 00:00:01:011
	offset = 00:00:01:011
	value = pred_1(<arg1>, <arg2>)
00315                        ( OFFSET> 72 ) 
00316                        ( |<val>| ( |pred_1| |<first-arg>| |<second-arg>| ) ) ; bad argument names

      WARNING  66 (Line 316:44): Encountered a formal argument whose name does not match the expected formal argumentname.
        The formal argument appeared in a predicate value.  The expected formal argument will be used.


      WARNING  66 (Line 316:58): Encountered a formal argument whose name does not match the expected formal argumentname.
        The formal argument appeared in a predicate value.  The expected formal argument will be used.

00317                      )
00318                      ( 
00319                        ( ONSET> 73 ) 


Spreadsheet Variable Cell Definition:
	ord = 17
	onset = 00:00:01:012
	offset = 00:00:01:012
	value = pred_1(<arg1>, <arg2>)
00320                        ( OFFSET> 73 ) 
00321                        ( |<val>| ( |<really-not-a-pred-name>| |<first-arg>| |<second-arg>| ) ) ; use of a formal arg as a pred name

      WARNING  68 (Line 321:35): Encountered a predicate value with an invalid predicate name.
        Will coerce the name to a valid predicate name.


      WARNING  69 (Line 321:35): Encountered a predicate value that refers to an undefined predicate.  The predicate value will be discarded.

00322                      )
00323                      ( 
00324                        ( ONSET> 74 ) 


Spreadsheet Variable Cell Definition:
	ord = 18
	onset = 00:00:01:013
	offset = 00:00:01:013
	value = ()
00325                        ( OFFSET> 74 ) 
00326                        ( |<val>| ( |pred_1| 1 ; 2 ) ) ; Unexpected EOF in predicate argument list
00327  ;                    )
00328  ;                  )
00329  ;                )
00330  ;                ( VOCAB> ( |pred_1| |pred_2| ) )
00331  ;              )
00332  ;            )
00333  ;            
00334  ;          )
00335  ;        )
00336  ;      ) 
00337  ;    ) 
00338  ;    ( QUERY> 2 )
00339  ;    ( SYSTEM> 3 )
00340  ;  ) 
00341  ;)

      ERROR  4 (Line 341:0): Encountered end of file unexpectedly.
        EOF encountered in a predicate value argument list.

Unable to continue parse -- Aborting...
