
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  14 (Line 27:9): Encountered a-list entry without a value.  A-list entries must be of the form '(' <tag> <value> ')'.
        The USER> SPREADSHEET-VARIABLE-DECLARATIONS> a-list entry doesn't seem to contain a value.


      WARNING  22 (Line 28:45): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> SPREADSHEET-VARIABLE-DEFINITIONS> a-list entry must be a (possibly empty) list of spreadsheet variable definitions.


      WARNING  22 (Line 31:14): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the QUERY> section must be a list.

