
      WARNING  22 (Line 8:32): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the HEADER> section must be a list.


      WARNING  22 (Line 9:30): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> section must be a list.


      WARNING  22 (Line 10:31): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the QUERY> section must be a list.


      WARNING  22 (Line 11:32): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the SYSTEM> section must be a list.


      WARNING  18 (Line 12:24): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the database body a-list.


      WARNING  18 (Line 13:24): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the database body a-list.


      WARNING  18 (Line 14:24): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the database body a-list.


      WARNING  18 (Line 15:24): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the database body a-list.


      WARNING  18 (Line 16:24): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the database body a-list.


      WARNING  18 (Line 17:24): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the database body a-list.


      WARNING  15 (Line 17:35): Illegal value in the value slot of an unknown or  unexpected a-list entry.


      WARNING  18 (Line 18:24): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the database body a-list.


      WARNING  15 (Line 18:35): Illegal value in the value slot of an unknown or  unexpected a-list entry.


      WARNING  18 (Line 19:24): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the database body a-list.


      WARNING  15 (Line 19:35): Illegal value in the value slot of an unknown or  unexpected a-list entry.


      WARNING  18 (Line 20:24): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the database body a-list.


      WARNING  15 (Line 20:35): Illegal value in the value slot of an unknown or  unexpected a-list entry.


      WARNING  18 (Line 21:24): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the database body a-list.


      WARNING  14 (Line 21:34): Encountered a-list entry without a value.  A-list entries must be of the form '(' <tag> <value> ')'.
        The empty a-list entry was unknown or unexpected, hence the point is probably moot.


      WARNING  18 (Line 22:24): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the database body a-list.


      WARNING  16 (Line 22:44): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered in an unexpected or unknown a-list entry.


      WARNING  18 (Line 23:24): Encountered unknown or unexpected alist entry.  Entry will be read and discarded.
        The entry is located in the database body a-list.


      ERROR  4 (Line 25:0): Encountered end of file unexpectedly.
        EOF encountered in an unknown or unexpected a-list entry.

Unable to continue parse -- Aborting...
