00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 0 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 
00019         ( 
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022              ( |pred_1| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| ) ) ) )
00023              ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )
00024              ( FALSE ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )

      WARNING  30 (Line 24:15): Encountered a list that is not a predicate definition in the predicate definitions list.  List discarded.

00025              macshapa-db
00026              ; unexpected EOF
00027  ;          )
00028  ;        ) 
00029  ;        ( SPREADSHEET-VARIABLE-DECLARATIONS> 1 ) 
00030  ;        ( SPREADSHEET-VARIABLE-DEFINITIONS> 1 )
00031  ;      ) 
00032  ;    ) 
00033  ;    ( QUERY> 2 )
00034  ;    ( SYSTEM> 3 )
00035  ;  ) 
00036  ;)

      WARNING  31 (Line 25:13): Encountered an atom in the predicate definitions list. The atom was discarded.


      ERROR  4 (Line 36:0): Encountered end of file unexpectedly.
        EOF encountered in the predicate definitions list.

Unable to continue parse -- Aborting...
