
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  14 (Line 24:45): Encountered a-list entry without a value.  A-list entries must be of the form '(' <tag> <value> ')'.
        A VARIABLE-LENGTH> attribute appears not to contain a value.  Value forced to FALSE.


      WARNING  22 (Line 25:45): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of a VARIABLE-LENGTH> attribute must be TRUE or FALSE.  Value forced to FALSE.


      WARNING  22 (Line 26:45): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of a VARIABLE-LENGTH> attribute must be TRUE or FALSE.  Value forced to FALSE.


      WARNING  16 (Line 27:54): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered a VARIABLE-LENGTH> attribute.


      ERROR  4 (Line 38:0): Encountered end of file unexpectedly.
        EOF in a VARIABLE-LENGTH> attribute.

Unable to continue parse -- Aborting...
