
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  65 (Line 254:34): Encountered a cell value whose value appears to be missing.
        The predicate cell will be left empty.


      WARNING  64 (Line 259:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Will discard the value and leave the predicate cell empty.


      ERROR  4 (Line 283:0): Encountered end of file unexpectedly.
        EOF in a predicate cell value.

Unable to continue parse -- Aborting...
