00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 2 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 


Current Header Settings:
db.name = "parser_test.db"
odb file format version = 1
warning limit = 50
error limit = 10
debug level = 2

00019        (
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022            	; no predicate definitions, for now
00023            )
00024          ) 
00025          ( SPREADSHEET-VARIABLE-DECLARATIONS> 
00026            (
00027              33
00028              ( "an arbitrary list" 2 |symbol| )

      WARNING  40 (Line 27:13): Encountered an atom in the spreadsheet variable declarations list. The atom was discarded.


      WARNING  39 (Line 28:15): Encountered a list that is not a spreadsheet variable declarations in the spreadsheet variables declarations list.  List discarded.

00029              |symbol|
00030              ; unexpected EOF
00031  ;          )
00032  ;        ) 
00033  ;        ( SPREADSHEET-VARIABLE-DEFINITIONS> 1 )
00034  ;      ) 
00035  ;    ) 
00036  ;    ( QUERY> 2 )
00037  ;    ( SYSTEM> 3 )
00038  ;  ) 
00039  ;)

      WARNING  40 (Line 29:13): Encountered an atom in the spreadsheet variable declarations list. The atom was discarded.


      ERROR  4 (Line 39:0): Encountered end of file unexpectedly.
        EOF encountered in the spreadsheet variables declarations list.

Unable to continue parse -- Aborting...
