
      WARNING  22 (Line 8:32): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the HEADER> section must be a list.


      WARNING  22 (Line 9:30): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> section must be a list.


      ERROR 13 (Line 11:24): Encountered a-list entry prior to one or more of its required predicessors in its a-list.
        HEADER>, USER>, or QUERY> a-list entry(s) missing from the database body a-list?
Unable to continue parse -- Aborting...
