00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db '( 
00008                        (HEADER> ( 
00009                                   ; (VERSION> 2) missing version attribute
00010                                   (NAME> "parser_test.db")
00011                                   (MAX-ERRORS> 5)
00012                                   (MAX-WARNINGS> 30)
00013                                   (DEBUG-LEVEL> 5) 
00014                                 ; )  kill one closing parenthesis
00015                        ) 
00016                        (USER> 1) 

      WARNING  29 (Line 16:23): A required a-list entry appears to be missing.  Will attempt to proceed with a default value.  Errors may result.
        The missing entry == the HEADER> VERSION> entry.  Format version forced to 1.



Current Header Settings:
db.name = "parser_test.db"
odb file format version = 1
warning limit = 30
error limit = 5
debug level = 3

00017                        (QUERY> 2)
00018                        (SYSTEM> 3)
00019                     ) 
00020  )

      WARNING  16 (Line 19:20): Encountered a-list entry with more than one value.  Excess values were discarded.
        Excess values encountered in the HEADER> section.


      ERROR 14 (Line 20:0): Encountered a-list with one or more required entries missing.
        Required entry(s) missing from the database body a-list.

Unable to continue parse -- Will continue lexer scan.

