00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 2 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 


Current Header Settings:
db.name = "parser_test.db"
odb file format version = 1
warning limit = 50
error limit = 10
debug level = 2

00019        (
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022              ( |pred_1| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| ) ) ) )
00023              ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )


Predicate Definition:
	name = "pred_1"
	variable length = false
	arg 0 = "<arg1>"
	arg 1 = "<arg2>"

00024            )
00025          ) 


Predicate Definition:
	name = "pred_2"
	variable length = true
	arg 0 = "<arg1>"

00026          ( SPREADSHEET-VARIABLE-DECLARATIONS> 
00027            (
00028              ( |a text var| 
00029                ( 
00030                  ( TYPE> <<TEXT>> ) 
00031                  ( VARIABLE-LENGTH> FALSE )
00032                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) ) 
00033                  ( COLUMN-WIDTH> 200 ) 
00034                ) 
00035              )
00036              ( |a nominal var| 


Spreadsheet Variable Definition:
	name = "a text var"
	type = TEXT
	variable length = false
	column width = 200
00037                ( 
00038                  ( TYPE> <<NOMINAL>> ) 
00039                  ( VARIABLE-LENGTH> FALSE )
00040                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00041                  ( COLUMN-WIDTH> 200 ) 
00042                ) 
00043              )
00044              ( |an integer var| 


Spreadsheet Variable Definition:
	name = "a nominal var"
	type = NOMINAL
	variable length = false
	column width = 200
00045                ( 
00046                  ( TYPE> <<INTEGER>> ) 
00047                  ( VARIABLE-LENGTH> FALSE )
00048                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00049                  ( COLUMN-WIDTH> 200 ) 
00050                ) 
00051              )
00052              ( |a float var| 


Spreadsheet Variable Definition:
	name = "an integer var"
	type = INTEGER
	variable length = false
	column width = 200
00053                ( 
00054                  ( TYPE> <<FLOAT>> ) 
00055                  ( VARIABLE-LENGTH> FALSE )
00056                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00057                  ( COLUMN-WIDTH> 200 ) 
00058                ) 
00059              )
00060              ( |a predicate var| 


Spreadsheet Variable Definition:
	name = "a float var"
	type = FLOAT
	variable length = false
	column width = 200
00061                ( 
00062                  ( TYPE> <<PREDICATE>> ) 
00063                  ( VARIABLE-LENGTH> FALSE )
00064                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00065                  ( COLUMN-WIDTH> 200 ) 
00066                ) 
00067              )
00068              ( |fixed len matrix| 


Spreadsheet Variable Definition:
	name = "a predicate var"
	type = PREDICATE
	variable length = false
	column width = 200
00069                ( 
00070                  ( TYPE> <<MATRIX>> ) 
00071                  ( VARIABLE-LENGTH> FALSE )
00072                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg1>| |<arg2>| ) )  
00073                  ( COLUMN-WIDTH> 200 ) 
00074                ) 
00075              )
00076              ( |var len matrix| 


Spreadsheet Variable Definition:
	name = "fixed len matrix"
	type = MATRIX
	variable length = false
	column width = 200
00077                ( 
00078                  ( TYPE> <<MATRIX>> ) 
00079                  ( VARIABLE-LENGTH> TRUE )
00080                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg1>| |<arg2>| ) )  
00081                  ( COLUMN-WIDTH> 225 ) 
00082                ) 
00083              )
00084            ) 
00085          ) 


Spreadsheet Variable Definition:
	name = "var len matrix"
	type = MATRIX
	variable length = true
	column width = 225
00086          ( SPREADSHEET-VARIABLE-DEFINITIONS>
00087           ( 
00088              ( |a text var|
00089                ( 
00090                  ( CELLS>
00091                    ( 
00092                      (
00093                        ( ONSET>  0 ) 
00094                        ( OFFSET> 0 ) 
00095                        ( |<val>| "this is a text cell") 
00096                      )
00097                      ( 
00098                        ( ONSET>  60 ) 


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = this is a text cell
00099                        ( OFFSET> 60 ) 
00100                        ( |<val>| "") 
00101                      )
00102                    )
00103                  )
00104                )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 
00105              )
00106              
00107              ( |a nominal var|
00108                (
00109                  ( CELLS>
00110                    (
00111                      ( 
00112                        ( ONSET> 0 ) 
00113                        ( OFFSET> 0 ) 
00114                        ( |<val>| |this is nominal cell| ) 
00115                      )
00116                      ( 
00117                        ( ONSET> 60 )  


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = this is nominal cell
00118                        ( OFFSET> 60 ) 
00119                        ( |<val>| |<val>| ) 
00120                      )
00121                    )
00122                  )
00123                )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 
00124              )
00125  
00126  
00127              ( |a float var|
00128                (
00129                  ( CELLS>
00130                    (
00131                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| 10.0 ) )
00132                      ( 
00133                        ( ONSET> 60 )  


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 10.000000
00134                        ( OFFSET> 60 ) 
00135                        ( |<val>| 0.0 ) 
00136                      )
00137                    )
00138                  )
00139                )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 0.000000
00140              )
00141              ( |a predicate var|
00142                (
00143                  ( CELLS>
00144                    (
00145                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| ( |pred_1| ( TIME> 120 ) |a nominal| ) ) )
00146                      ( ( ONSET> 10 ) ( OFFSET> 20 ) ( |<val>| ( |pred_1| "a string" |<arg2>| ) ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = pred_1(00:00:02:000, a nominal)
00147                      ( ( ONSET> 20 ) ( OFFSET> 30 ) ( |<val>| ( |pred_1| 10 1.0 ) ) )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:010
	offset = 00:00:00:020
	value = pred_1("a string", <arg2>)
00148                      ( ( ONSET> 30 ) ( OFFSET> 40 ) ( |<val>| ( |pred_1| ( |pred_2| |<arg1>| ) |<arg2>| ) ) )


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:020
	offset = 00:00:00:030
	value = pred_1(10, 1.000000)
00149                      ( 
00150                        ( ONSET> 60 ) 


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:00:030
	offset = 00:00:00:040
	value = pred_1(pred_2(<arg1>), <arg2>)
00151                        ( OFFSET> 60 ) 
00152                        ( |<val>| ( ) ) 
00153                      )
00154                    )
00155                  )
00156                  ( VOCAB> ( |pred_1| |pred_2| ) )


Spreadsheet Variable Cell Definition:
	ord = 5
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = ()
00157                )
00158              )
00159              ( |fixed len matrix|
00160                (
00161                  ( CELLS>
00162                    (
00163                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<arg1>| 1 ) ( |<arg2>| 2.0 ) )
00164                      ( ( ONSET> 10 ) ( OFFSET> 20 ) ( |<arg1>| |a nominal| ) ( |<arg2>| "a string" ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 1, 2.000000
00165                      ( ( ONSET> 20 ) ( OFFSET> 30 ) ( |<arg1>| ( |pred_2| |<arg1>| ) ) ( |<arg2>| ( TIME> 120 ) ) )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:010
	offset = 00:00:00:020
	value = a nominal, "a string"
00166                      ( 
00167                        ( ONSET> 60 ) 


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:020
	offset = 00:00:00:030
	value = pred_2(<arg1>), 00:00:02:000
00168                        ( OFFSET> 60 ) 
00169                        ( |<arg1>| |<arg1>| ) 
00170                        ( |<arg2>| |<arg2>| ) 
00171                      )
00172                      ( 
00173                        ( ONSET> 60 ) 


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = <arg1>, <arg2>
00174                        ( OFFSET> 60 ) 
00175                        ( |<arg1>| "first arg" ) 
00176                        ( |<arg2>| "second arg" ) 
00177                      )
00178                      ( 
00179                        ( ONSET> 61 ) 


Spreadsheet Variable Cell Definition:
	ord = 5
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = "first arg", "second arg"
00180                        ( OFFSET> 61 )
00181                        ( |<arg1>| "first arg" ) 
00182                        ( |<arg2>| "second arg" ) 
00183                      )
00184                      ( 
00185                        ( ONSET> 62 ) 


Spreadsheet Variable Cell Definition:
	ord = 6
	onset = 00:00:01:001
	offset = 00:00:01:001
	value = "first arg", "second arg"
00186                        ( OFFSET> 62 ) 
00187                        ( |<arg1>| "first arg" ) 
00188                        ( |<arg2>| "second arg" ) 
00189                      )
00190                      ( 
00191                        ( ONSET> 63 ) 


Spreadsheet Variable Cell Definition:
	ord = 7
	onset = 00:00:01:002
	offset = 00:00:01:002
	value = "first arg", "second arg"
00192                        ( OFFSET> 63 )
00193                        ( |<arg1>| "first arg" ) 
00194                        ( |<arg2>| "second arg" ) 
00195                      )
00196                    )
00197                  )
00198                  ( VOCAB> ( |pred_1| |pred_2| ) ) 


Spreadsheet Variable Cell Definition:
	ord = 8
	onset = 00:00:01:003
	offset = 00:00:01:003
	value = "first arg", "second arg"
00199                )
00200              )
00201              ( |var len matrix|
00202                (
00203                  ( CELLS>
00204                    (
00205                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<arg1>| 1 ) ( |<arg2>| 2.0 ) )
00206                      ( ( ONSET> 10 ) ( OFFSET> 20 ) ( |<arg1>| |a nominal| ) ( |<arg2>| "a string" ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 1, 2.000000
00207                      ( ( ONSET> 20 ) ( OFFSET> 30 ) ( |<arg1>| ( |pred_2| |<arg1>| ) ) ( |<arg2>| ( TIME> 120 ) ) )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:010
	offset = 00:00:00:020
	value = a nominal, "a string"
00208                      ( ( ONSET> 60 ) ( OFFSET> 60 ) ( |<arg1>| |<arg1>| ) )


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:020
	offset = 00:00:00:030
	value = pred_2(<arg1>), 00:00:02:000
00209                      ( ( ONSET> 60 ) ( OFFSET> 60 ) ( |<arg1>| |<arg1>| ) ( |<arg2>| |<arg2>| ) )


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = <arg1>, <arg2>
00210                      ( 
00211                        ( ONSET> 61 ) 


Spreadsheet Variable Cell Definition:
	ord = 5
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = <arg1>, <arg2>
00212                        ( OFFSET> 61 ) 
00213                        ( |<arg1>| "first arg" ) 
00214                        ( |<arg2>| "second arg" ) 
00215                      )
00216                      ( 
00217                        ( ONSET> 62 ) 


Spreadsheet Variable Cell Definition:
	ord = 6
	onset = 00:00:01:001
	offset = 00:00:01:001
	value = "first arg", "second arg"
00218                        ( OFFSET> 62 ) 
00219                        ( |<arg1>| "first arg" ) 
00220                        ( |<arg2>| "second arg" ) 
00221                      )
00222                      ( 
00223                        ( ONSET> 63 ) 


Spreadsheet Variable Cell Definition:
	ord = 7
	onset = 00:00:01:002
	offset = 00:00:01:002
	value = "first arg", "second arg"
00224                        ( OFFSET> 63 ) 
00225                        ( |<arg1>| "first arg" ) 
00226                        ( |<arg2>| "second arg" ) 
00227                      )
00228                      ( 
00229                        ( ONSET> 64 ) 


Spreadsheet Variable Cell Definition:
	ord = 8
	onset = 00:00:01:003
	offset = 00:00:01:003
	value = "first arg", "second arg"
00230                        ( OFFSET> 64 ) 
00231                        ( |<arg1>| "first arg" ) 
00232                        ( |<arg2>| "second arg" ) 
00233                      )
00234                    )
00235                  )
00236                  ( VOCAB> ( |pred_1| |pred_2| ) )


Spreadsheet Variable Cell Definition:
	ord = 9
	onset = 00:00:01:004
	offset = 00:00:01:004
	value = "first arg", "second arg"
00237                )
00238              )
00239              
00240              ( |an integer var|
00241                (
00242                  ( CELLS>
00243                    (
00244                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| 10 ) )
00245                      ( 
00246                        ( ONSET> 60 )  


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 10
00247                        ( OFFSET> 60 ) 
00248                        ( |<val>| 0 ) 
00249                      )
00250                      ( 
00251                        ( ONSET> 61 )  


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 0
00252                        ( OFFSET> 61 ) 
00253                        ( |<val>| 0) 
00254                      )
00255                      ( 
00256                        ( ONSET> 62 )  


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:01:001
	offset = 00:00:01:001
	value = 0
00257                        ( OFFSET> 62 ) 
00258                        ( |<val>| ) ; empty integer value
00259                      )
00260                      ( 

      WARNING  65 (Line 258:33): Encountered a cell value whose value appears to be missing.
        The integer cell will be set to zero.

00261                        ( ONSET> 63 )  


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:01:002
	offset = 00:00:01:002
	value = 0
00262                        ( OFFSET> 63 ) 
00263                        ( |<val>| 0.9 ) ; should round to 1
00264                      )

      WARNING  64 (Line 263:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Coerced the floating point value to the nearest legal integer cell value.

00265                      ( 
00266                        ( ONSET> 64 )  


Spreadsheet Variable Cell Definition:
	ord = 5
	onset = 00:00:01:003
	offset = 00:00:01:003
	value = 1
00267                        ( OFFSET> 64 ) 
00268                        ( |<val>| 1.1 ) ; should round to 1
00269                      )

      WARNING  64 (Line 268:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Coerced the floating point value to the nearest legal integer cell value.

00270                      ( 
00271                        ( ONSET> 65 )  


Spreadsheet Variable Cell Definition:
	ord = 6
	onset = 00:00:01:004
	offset = 00:00:01:004
	value = 1
00272                        ( OFFSET> 65 ) 
00273                        ( |<val>| -0.1 ) ; should round to 0
00274                      )

      WARNING  64 (Line 273:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Coerced the floating point value to the nearest legal integer cell value.

00275                      ( 
00276                        ( ONSET> 66 )  


Spreadsheet Variable Cell Definition:
	ord = 7
	onset = 00:00:01:005
	offset = 00:00:01:005
	value = 0
00277                        ( OFFSET> 66 ) 
00278                        ( |<val>| 0.1 ) ; should round to 0
00279                      )

      WARNING  64 (Line 278:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Coerced the floating point value to the nearest legal integer cell value.

00280                      ( 
00281                        ( ONSET> 67 )  


Spreadsheet Variable Cell Definition:
	ord = 8
	onset = 00:00:01:006
	offset = 00:00:01:006
	value = 0
00282                        ( OFFSET> 67 ) 
00283                        ( |<val>| -0.9 ) ; should round to -1
00284                      )

      WARNING  64 (Line 283:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Coerced the floating point value to the nearest legal integer cell value.

00285                      ( 
00286                        ( ONSET> 68 )  


Spreadsheet Variable Cell Definition:
	ord = 9
	onset = 00:00:01:007
	offset = 00:00:01:007
	value = -1
00287                        ( OFFSET> 68 ) 
00288                        ( |<val>| TRUE ) ; type mismatch - should force to 0
00289                      )

      WARNING  64 (Line 288:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        Will discard the value && set the value of the integer cell to zero.

00290                      ( 
00291                        ( ONSET> 69 )  


Spreadsheet Variable Cell Definition:
	ord = 10
	onset = 00:00:01:008
	offset = 00:00:01:008
	value = 0
00292                        ( OFFSET> 69 ) 
00293                        ( |<val>| ( |a list of| 3 "elements" ) ) ; type mismatch - should force to 0

      WARNING  64 (Line 293:33): Encountered a cell value that does not match the type of spreadsheet variable in which the cell occurs.
        The value is a list, which will be discarded.  The integer cell will be set to zero.

00294                      )
00295                      ( 
00296                        ( ONSET> 70 )  


Spreadsheet Variable Cell Definition:
	ord = 11
	onset = 00:00:01:009
	offset = 00:00:01:009
	value = 0
00297                        ( OFFSET> 70 ) 
00298                        ( |<val>| 0) 
00299                      )
00300                      ( 
00301                        ( ONSET> 71 )  


Spreadsheet Variable Cell Definition:
	ord = 12
	onset = 00:00:01:010
	offset = 00:00:01:010
	value = 0
00302                        ( OFFSET> 71 ) 
00303                        ( |<val>| 0) 
00304                      )
00305                      ( 
00306                        ( ONSET> 72 )  


Spreadsheet Variable Cell Definition:
	ord = 13
	onset = 00:00:01:011
	offset = 00:00:01:011
	value = 0
00307                        ( OFFSET> 72 ) 
00308                        ( 
00309                          |<val>| 
00310                          ; unexpected EOF in integer cell value
00311  ;                        0
00312  ;                      ) 
00313  ;                    )
00314  ;                  )
00315  ;                )
00316  ;              )
00317  ;            )
00318  ;          )
00319  ;        )
00320  ;      ) 
00321  ;    ) 
00322  ;    ( QUERY> 2 )
00323  ;    ( SYSTEM> 3 )
00324  ;  ) 
00325  ;)

      ERROR  4 (Line 325:0): Encountered end of file unexpectedly.
        EOF in an integer cell value.

Unable to continue parse -- Aborting...
