
      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.


      WARNING  44 (Line 36:13): Encountered excess values in a spreadsheet variable declaration.  The excess values were discarded.


      WARNING  50 (Line 54:0): Encountered a duplicate declaration of a spreadsheet variable.  The second declaration will be ignored.
        The duplicate declaration differed from the initial definition.


      ERROR  4 (Line 54:0): Encountered end of file unexpectedly.
        EOF encountered in a spreadsheet variable declaration.

Unable to continue parse -- Aborting...
