00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 2 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 


Current Header Settings:
db.name = "parser_test.db"
odb file format version = 1
warning limit = 50
error limit = 10
debug level = 2

00019        (
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022              ( |pred_1| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| ) ) ) )
00023              ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )


Predicate Definition:
	name = "pred_1"
	variable length = false
	arg 0 = "<arg1>"
	arg 1 = "<arg2>"

00024  
00025              ; a predicate with an illegal name
00026              ( |not a pred name| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| ) ) ) )


Predicate Definition:
	name = "pred_2"
	variable length = true
	arg 0 = "<arg1>"


      WARNING  37 (Line 26:15): Encountered a predicate definition in which the name of the predicate is not a valid predicate name.
        Will coerce the name to a valid predicate name.

00027  
00028              ; aother predicate with an illegal name
00029              ( |<really_not_a_pred_name>| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| ) ) ) )


Predicate Definition:
	name = "not_a_pred_name"
	variable length = false
	arg 0 = "<arg1>"
	arg 1 = "<arg2>"


      WARNING  37 (Line 29:15): Encountered a predicate definition in which the name of the predicate is not a valid predicate name.
        Will coerce the name to a valid predicate name.

00030  
00031  			; duplicate definition
00032              ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )


Predicate Definition:
	name = "_really_not_a_pred_name_"
	variable length = false
	arg 0 = "<arg1>"
	arg 1 = "<arg2>"

00033              
00034              ; dup def - different # of args
00035              ( |pred_1| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )


Predicate Definition:
	name = "pred_2"
	variable length = true
	arg 0 = "<arg1>"

00036              
00037              ; dup def - variable_length TRUE instead of false
00038              ( |pred_1| ( ( VARIABLE-LENGTH> TRUE ) ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| ) ) ) )


Predicate Definition:
	name = "pred_1"
	variable length = false
	arg 0 = "<arg1>"


      WARNING  38 (Line 35:89): Encountered a duplicate definition of a predicate.  The second definition will be ignored.
        New definition doesn't match old definition.  New definition ignored.
00039  
00040  			; dup def - different argument names
00041              ( |pred_1| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<val-1>| |<val-2>| ) ) ) )


Predicate Definition:
	name = "pred_1"
	variable length = true
	arg 0 = "<arg1>"
	arg 1 = "<arg2>"


      WARNING  38 (Line 38:97): Encountered a duplicate definition of a predicate.  The second definition will be ignored.
        New definition doesn't match old definition.  New definition ignored.
00042            )
00043          ) 


Predicate Definition:
	name = "pred_1"
	variable length = false
	arg 0 = "<val-1>"
	arg 1 = "<val-2>"


      WARNING  38 (Line 41:100): Encountered a duplicate definition of a predicate.  The second definition will be ignored.
        New definition doesn't match old definition -- formal argument name mismatch.  New definition ignored.
00044          ( SPREADSHEET-VARIABLE-DECLARATIONS> 1 ) 
00045          ( SPREADSHEET-VARIABLE-DEFINITIONS> 1 )

      WARNING  22 (Line 44:46): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> SPREADSHEET-VARIABLE-DECLARATIONS> a-list entry must be a (possibly empty) list of spreadsheet variable declarations.

00046        ) 

      WARNING  22 (Line 45:45): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the USER> SPREADSHEET-VARIABLE-DEFINITIONS> a-list entry must be a (possibly empty) list of spreadsheet variable definitions.

00047      ) 
00048      ( QUERY> 2 )
00049      ( SYSTEM> 3 )

      WARNING  22 (Line 48:14): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the QUERY> section must be a list.

00050    ) 
00051  )
