
      WARNING  22 (Line 9:44): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the HEADER> VERSION> attribute must be a positive integer.  Version # forced to 1.

      WARNING  22 (Line 10:48): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the HEADER> DEBUG-LEVEL> attribute must be a non-negative integer.  Debug level forced to 0.

      WARNING  22 (Line 11:41): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the HEADER> NAME> attribute must be a quoted string.  The attribute will be ignored.

      WARNING  22 (Line 12:47): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the HEADER> MAX-ERRORS> attribute must be a positive integer.  Errors limit forced to 1.


      WARNING  22 (Line 13:49): The type of the value supplied for the a-list entry is inconsistant with that entry.
        The value of the HEADER> MAX-WARNINGS> attribute must be a positive integer.  Warnings limit forced to 1.


      ERROR  0 (Line 13:49): Warning limit exceeded - load aborted.

Unable to continue parse -- Aborting...
