00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is one of a series of test databases intended to test the partially
00004  ; constructed parser.  Neither this nor any of its bretheren are a valid
00005  ; macshapa databases.
00006  ;
00007  ( setf macshapa-db 
00008   '( 
00009      ( HEADER> 
00010        ( 
00011          ( VERSION> 1 ) 
00012          ( NAME> "parser_test.db" )
00013          ( DEBUG-LEVEL> 2 ) 
00014          ( MAX-ERRORS> 20 )
00015          ( MAX-WARNINGS> 50 )

      WARNING  25 (Line 14:23): The error limit in the MAX-ERRORS> attribute is too large.  Error limit forced to largest legal value.

00016        )
00017      ) 
00018      ( USER> 


Current Header Settings:
db.name = "parser_test.db"
odb file format version = 1
warning limit = 50
error limit = 10
debug level = 2

00019        (
00020          ( PREDICATE-DEFINITIONS> 
00021            (
00022              ( |pred_1| ( ( VARIABLE-LENGTH> FALSE ) ( FORMAL-ARG-LIST> ( |<arg1>| |<arg2>| ) ) ) )
00023              ( |pred_2| ( ( VARIABLE-LENGTH> TRUE )  ( FORMAL-ARG-LIST> ( |<arg1>| ) ) ) )


Predicate Definition:
	name = "pred_1"
	variable length = false
	arg 0 = "<arg1>"
	arg 1 = "<arg2>"

00024            )
00025          ) 


Predicate Definition:
	name = "pred_2"
	variable length = true
	arg 0 = "<arg1>"

00026          ( SPREADSHEET-VARIABLE-DECLARATIONS> 
00027            (
00028              ( |a text var| 
00029                ( 
00030                  ( TYPE> <<TEXT>> ) 
00031                  ( VARIABLE-LENGTH> FALSE )
00032                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) ) 
00033                  ( COLUMN-WIDTH> 200 ) 
00034                ) 
00035              )
00036              ( |<this-isnt-an-svar-name>| ; test to see if we are coercing s-var names correctly - part 1


Spreadsheet Variable Definition:
	name = "a text var"
	type = TEXT
	variable length = false
	column width = 200
00037                ( 
00038                  ( TYPE> <<TEXT>> ) 

      WARNING  41 (Line 36:15): Encountered a spreadsheet variable declaration in which the name of the spreadsheet variable is not a valid spreadsheet variable name.
        Will coerce the name to a valid spreadsheet variable name.

00039                  ( VARIABLE-LENGTH> FALSE )
00040                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) ) 
00041                  ( COLUMN-WIDTH> 200 ) 
00042                ) 
00043              )
00044              ( |a nominal var| 


Spreadsheet Variable Definition:
	name = "_this-isnt-an-svar-name_"
	type = TEXT
	variable length = false
	column width = 200
00045                ( 
00046                  ( TYPE> <<NOMINAL>> ) 
00047                  ( VARIABLE-LENGTH> FALSE )
00048                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00049                  ( COLUMN-WIDTH> 200 ) 
00050                ) 
00051              )
00052              ( |an integer var| 


Spreadsheet Variable Definition:
	name = "a nominal var"
	type = NOMINAL
	variable length = false
	column width = 200
00053                ( 
00054                  ( TYPE> <<INTEGER>> ) 
00055                  ( VARIABLE-LENGTH> FALSE )
00056                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00057                  ( COLUMN-WIDTH> 200 ) 
00058                ) 
00059              )
00060              ( |a float var| 


Spreadsheet Variable Definition:
	name = "an integer var"
	type = INTEGER
	variable length = false
	column width = 200
00061                ( 
00062                  ( TYPE> <<FLOAT>> ) 
00063                  ( VARIABLE-LENGTH> FALSE )
00064                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00065                  ( COLUMN-WIDTH> 200 ) 
00066                ) 
00067              )
00068              ( |a predicate var| 


Spreadsheet Variable Definition:
	name = "a float var"
	type = FLOAT
	variable length = false
	column width = 200
00069                ( 
00070                  ( TYPE> <<PREDICATE>> ) 
00071                  ( VARIABLE-LENGTH> FALSE )
00072                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<val>| ) )  
00073                  ( COLUMN-WIDTH> 200 ) 
00074                ) 
00075              )
00076              ( |fixed len matrix| 


Spreadsheet Variable Definition:
	name = "a predicate var"
	type = PREDICATE
	variable length = false
	column width = 200
00077                ( 
00078                  ( TYPE> <<MATRIX>> ) 
00079                  ( VARIABLE-LENGTH> FALSE )
00080                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg1>| |<arg2>| ) )  
00081                  ( COLUMN-WIDTH> 200 ) 
00082                ) 
00083              )
00084              ( |var len matrix|


Spreadsheet Variable Definition:
	name = "fixed len matrix"
	type = MATRIX
	variable length = false
	column width = 200
00085                (
00086                  ( TYPE> <<MATRIX>> )
00087                  ( VARIABLE-LENGTH> TRUE )
00088                  ( FORMAL-ARG-LIST> ( |<ord>| |<onset>| |<offset>| |<arg1>| |<arg2>| ) )
00089                  ( COLUMN-WIDTH> 225 )
00090                )
00091              )
00092            ) 
00093          ) 


Spreadsheet Variable Definition:
	name = "var len matrix"
	type = MATRIX
	variable length = true
	column width = 225
00094          ( SPREADSHEET-VARIABLE-DEFINITIONS>
00095           ( 
00096           	( |<this-isnt-an-svar-name>| ; test to see if we are coercing s-var names correctly - part 2
00097                (
00098                  ( CELLS>

      WARNING  55 (Line 96:13): Encountered a spreadsheet variable definition in which the name of the spreadsheet variable is not a valid spreadsheet variable name.
        Will coerce the name to a valid spreadsheet variable name.

00099                    (
00100                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| "this is a text cell") )
00101                      ( ( ONSET> 60 ) ( OFFSET> 60 ) ( |<val>| "") )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = this is a text cell
00102                    )
00103                  )
00104                )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 
00105           	)
00106           	
00107           	( |<neither-is_this>| ; undefined spreadsheet variable
00108                (
00109                  ( CELLS>

      WARNING  55 (Line 107:13): Encountered a spreadsheet variable definition in which the name of the spreadsheet variable is not a valid spreadsheet variable name.
        Will coerce the name to a valid spreadsheet variable name.


      WARNING  56 (Line 108:15): Encountered reference to an undeclared spreadsheet variable.
        The definition of the undeclared spreadsheet variable will be discarded.

00110                    (
00111                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| "this is a text cell") )
00112                      ( ( ONSET> 60 ) ( OFFSET> 60 ) ( |<val>| "") )
00113                    )
00114                  )
00115                )
00116           	)
00117           	
00118           	( |<nor-this-either>| ) ; undefined spreadsheet variable that is missing its attribute list
00119           	
00120              ( |a text var|

      WARNING  55 (Line 118:13): Encountered a spreadsheet variable definition in which the name of the spreadsheet variable is not a valid spreadsheet variable name.
        Will coerce the name to a valid spreadsheet variable name.


      WARNING  57 (Line 118:33): Encountered a spreadsheet variable definition that appears to be missing its a-list. The definition will be ignored.

00121                |j random atom| ; a random atom in the value place in a spreadsheet variable definition
00122                (
00123                  ( CELLS>

      WARNING  58 (Line 121:15): Type mis-match in the second item in a spreadsheet variable definition.  This item must be an attribute list defining the spreadsheet variable.
        The spreadsheet variable definition will be discarded.

00124                    (
00125                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| "this is a text cell") )
00126                      ( ( ONSET> 60 ) ( OFFSET> 60 ) ( |<val>| "") )
00127                    )
00128                  )
00129                )
00130              )
00131              
00132              ( |a nominal var|

      WARNING  44 (Line 130:13): Encountered excess values in a spreadsheet variable declaration.  The excess values were discarded.

00133                (
00134                  ( CELLS>
00135                    (
00136                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| |this is nominal cell| ) )
00137                      ( ( ONSET> 60 ) ( OFFSET> 60 ) ( |<val>| |<val>| ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = this is nominal cell
00138                    )
00139                  )
00140                )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 
00141              )
00142              ( |an integer var|
00143                (
00144                  ( CELLS>
00145                    (
00146                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| 10 ) )
00147                      ( ( ONSET> 60 ) ( OFFSET> 60 ) ( |<val>| 0) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 10
00148                    )
00149                  )
00150                )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 0
00151              )
00152              ( |a float var|
00153                (
00154                  ( CELLS>
00155                    (
00156                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| 10.0 ) )
00157                      ( ( ONSET> 60 ) ( OFFSET> 60 ) ( |<val>| 0.0 ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 10.000000
00158                    )
00159                  )
00160                )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = 0.000000
00161              )
00162              ( |a predicate var|
00163                (
00164                  ( CELLS>
00165                    (
00166                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<val>| ( |pred_1| ( TIME> 120 ) |a nominal| ) ) )
00167                      ( ( ONSET> 10 ) ( OFFSET> 20 ) ( |<val>| ( |pred_1| "a string" |<arg2>| ) ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = pred_1(00:00:02:000, a nominal)
00168                      ( ( ONSET> 20 ) ( OFFSET> 30 ) ( |<val>| ( |pred_1| 10 1.0 ) ) )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:010
	offset = 00:00:00:020
	value = pred_1("a string", <arg2>)
00169                      ( ( ONSET> 30 ) ( OFFSET> 40 ) ( |<val>| ( |pred_1| ( |pred_2| |<arg1>| ) |<arg2>| ) ) )


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:020
	offset = 00:00:00:030
	value = pred_1(10, 1.000000)
00170                      ( ( ONSET> 60 ) ( OFFSET> 60 ) ( |<val>| ( ) ) )


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:00:030
	offset = 00:00:00:040
	value = pred_1(pred_2(<arg1>), <arg2>)
00171                    )
00172                  )
00173                  ( VOCAB> ( |pred_1| |pred_2| ) )


Spreadsheet Variable Cell Definition:
	ord = 5
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = ()
00174                )
00175              )
00176              ( |fixed len matrix|
00177                (
00178                  ( CELLS>
00179                    (
00180                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<arg1>| 1 ) ( |<arg2>| 2.0 ) )
00181                      ( ( ONSET> 10 ) ( OFFSET> 20 ) ( |<arg1>| |a nominal| ) ( |<arg2>| "a string" ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 1, 2.000000
00182                      ( ( ONSET> 20 ) ( OFFSET> 30 ) ( |<arg1>| ( |pred_2| |<arg1>| ) ) ( |<arg2>| ( TIME> 120 ) ) )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:010
	offset = 00:00:00:020
	value = a nominal, "a string"
00183                      ( ( ONSET> 60 ) ( OFFSET> 60 ) ( |<arg1>| |<arg1>| ) ( |<arg2>| |<arg2>| ) )


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:020
	offset = 00:00:00:030
	value = pred_2(<arg1>), 00:00:02:000
00184                    )
00185                  )
00186                  ( VOCAB> ( |pred_1| |pred_2| ) )


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = <arg1>, <arg2>
00187                )
00188                ( "j" "random" "list" ) ; execess list value in a spreadsheet variable definition
00189                |j random atom| ; a random atom excess value in a spreadsheet variable definition
00190              )
00191              ( |var len matrix|

      WARNING  44 (Line 190:13): Encountered excess values in a spreadsheet variable declaration.  The excess values were discarded.

00192                (
00193                  ( CELLS>
00194                    (
00195                      ( ( ONSET>  0 ) ( OFFSET>  0 ) ( |<arg1>| 1 ) ( |<arg2>| 2.0 ) )
00196                      ( ( ONSET> 10 ) ( OFFSET> 20 ) ( |<arg1>| |a nominal| ) ( |<arg2>| "a string" ) )


Spreadsheet Variable Cell Definition:
	ord = 1
	onset = 00:00:00:000
	offset = 00:00:00:000
	value = 1, 2.000000
00197                      ( ( ONSET> 20 ) ( OFFSET> 30 ) ( |<arg1>| ( |pred_2| |<arg1>| ) ) ( |<arg2>| ( TIME> 120 ) ) )


Spreadsheet Variable Cell Definition:
	ord = 2
	onset = 00:00:00:010
	offset = 00:00:00:020
	value = a nominal, "a string"
00198                      ( ( ONSET> 60 ) ( OFFSET> 60 ) ( |<arg1>| |<arg1>| ) )


Spreadsheet Variable Cell Definition:
	ord = 3
	onset = 00:00:00:020
	offset = 00:00:00:030
	value = pred_2(<arg1>), 00:00:02:000
00199                      ( ( ONSET> 60 ) ( OFFSET> 60 ) ( |<arg1>| |<arg1>| ) ( |<arg2>| |<arg2>| ) )


Spreadsheet Variable Cell Definition:
	ord = 4
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = <arg1>, <arg2>
00200                    )
00201                  )
00202                  ( VOCAB> ( |pred_1| |pred_2| ) )


Spreadsheet Variable Cell Definition:
	ord = 5
	onset = 00:00:01:000
	offset = 00:00:01:000
	value = <arg1>, <arg2>
00203                )
00204                ; unexpected EOF in a spreasheet variable definition 
00205  ;            )
00206  ;          )
00207  ;        )
00208  ;      ) 
00209  ;    ) 
00210  ;    ( QUERY> 2 )
00211  ;    ( SYSTEM> 3 )
00212  ;  ) 
00213  ;)

      ERROR  4 (Line 213:0): Encountered end of file unexpectedly.
        EOF encountered in a spreadsheet variable definition.

Unable to continue parse -- Aborting...
