/**
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.datavyu.event.component;

import org.datavyu.models.id.Identifier;

import java.util.EventObject;
import java.util.List;


/**
 * Event object for a track carriage event.
 */
public final class CarriageEvent extends EventObject {

    /**
     * Auto generated by Eclipse.
     */
    private static final long serialVersionUID = 4009420871939032673L;

    /**
     * Describes the type of event that occured.
     */
    public enum EventType {

        /**
         * Snap position changed.
         */
        BOOKMARK_CHANGED,

        /**
         * Requesting snap position.
         */
        BOOKMARK_REQUEST,

        /**
         * Requesting snap saving.
         */
        BOOKMARK_SAVE,

        /**
         * Track changed selection state.
         */
        CARRIAGE_SELECTION,

        /**
         * Track changed offset position.
         */
        OFFSET_CHANGE,

        /**
         * Track is (un)locked.
         */
        CARRIAGE_LOCK
    }

    /**
     * Track identifier.
     */
    private final Identifier trackId;

    /**
     * New time offset, in milliseconds, for the given track.
     */
    private final long offset;

    /**
     * Duration of the track in milliseconds.
     */
    private final long duration;

    /**
     * Track bookmark positions in milliseconds.
     */
    private final List<Long> bookmarks;

    /**
     * Temporal position of the mouse. Only meaningful for
     * EventType.OFFSET_CHANGE
     */
    private final long temporalPosition;

    /**
     * What event does this represent.
     */
    private final EventType eventType;

    /**
     * Were there input modifiers.
     */
    private final boolean hasModifiers;

    /**
     * @param source
     * @param trackId
     * @param offset
     * @param bookmark
     * @param duration
     * @param temporalPosition
     * @param eventType
     * @param hasModifiers;
     */
    public CarriageEvent(final Object source, final Identifier trackId,
                         final long offset, final List<Long> bookmarks, final long duration,
                         final long temporalPosition, final EventType eventType,
                         final boolean hasModifiers) {
        super(source);
        this.trackId = trackId;
        this.offset = offset;
        this.bookmarks = bookmarks;
        this.duration = duration;
        this.temporalPosition = temporalPosition;
        this.eventType = eventType;
        this.hasModifiers = hasModifiers;
    }

    /**
     * @return New time offset in milliseconds.
     */
    public long getOffset() {
        return offset;
    }

    /**
     * @return the bookmarks
     */
    public List<Long> getBookmarks() {
        return bookmarks;
    }

    /**
     * @return Track identifier
     */
    public Identifier getTrackId() {
        return trackId;
    }

    /**
     * @return Track duration in milliseconds
     */
    public long getDuration() {
        return duration;
    }

    /**
     * @return the temporal position of the mouse in milliseconds. Only
     * meaningful for OFFSET_CHANGE events.
     */
    public long getTemporalPosition() {
        return temporalPosition;
    }

    /**
     * @return event type
     */
    public EventType getEventType() {
        return eventType;
    }

    /**
     * @return true if modifiers were present, false otherwise..
     */
    public boolean hasModifiers() {
        return hasModifiers;
    }

}
