00001  ; MacSHAPA Open Database
00002  ; 
00003  ; This database starts to get rough with the lexer.  The general idea is to 
00004  ; generate all the errors and warnings that the lexer is capable of flagging.
00005  ;
00006  ; Needless to say, this is not a legal database, and will cause even more
00007  ; fireworks if fed to the parser instead of just the lexer.
00008  ;
00009  ; This file deals only with errors that can be generated with symbol tokens.
00010  ;
00011  ; This formal argument contains an illegal escape sequence
00012  
00013  |<illegal_escape_seq:\i>|

      WARNING   0 (Line 13:1): Illegal escape sequence detected in a symbol.  Sequence replaced with a '_'.
        The sequence was: \i

((code = 3(SYMBOL_TOK)) (aux = 8(FORMAL_ARG_FLAG)) (val = 0.0) (str = <illegal_escape_seq:_>) (line_number = 13) (line_index = 1))

00014  
00015  ; These formal arguments contain a variety of illegal characters
00016  
00017  |<<to_many_brackets>>| |<spaces are frobidden in formal arguments>|

      WARNING   1 (Line 17:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: '<'.


      WARNING   1 (Line 17:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: '>'.

((code = 3(SYMBOL_TOK)) (aux = 8(FORMAL_ARG_FLAG)) (val = 0.0) (str = <_to_many_brackets_>) (line_number = 17) (line_index = 1))


      WARNING   1 (Line 17:24): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ' ' (HEX 0x20)


      WARNING   1 (Line 17:24): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ' ' (HEX 0x20)


      WARNING   1 (Line 17:24): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ' ' (HEX 0x20)


      WARNING   1 (Line 17:24): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ' ' (HEX 0x20)


      WARNING   1 (Line 17:24): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ' ' (HEX 0x20)

((code = 3(SYMBOL_TOK)) (aux = 8(FORMAL_ARG_FLAG)) (val = 0.0) (str = <spaces_are_frobidden_in_formal_arguments>) (line_number = 17) (line_index = 24))

00018  
00019  |<()", are_all_forbidden_characters>|

      WARNING   1 (Line 19:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was '('


      WARNING   1 (Line 19:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was ')'


      WARNING   1 (Line 19:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was '"'


      WARNING   1 (Line 19:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was ','


      WARNING   1 (Line 19:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ' ' (HEX 0x20)

((code = 3(SYMBOL_TOK)) (aux = 8(FORMAL_ARG_FLAG)) (val = 0.0) (str = <_____are_all_forbidden_characters>) (line_number = 19) (line_index = 1))

00020  
00021  |<this_formal_argument_contains_a_BS_char:(hex_0x08)>|

      WARNING   1 (Line 21:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: '' (HEX 0x8)


      WARNING   1 (Line 21:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was '('


      WARNING   1 (Line 21:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was ')'

((code = 3(SYMBOL_TOK)) (aux = 8(FORMAL_ARG_FLAG)) (val = 0.0) (str = <this_formal_argument_contains_a_BS_char:__hex_0x08_>) (line_number = 21) (line_index = 1))

00022  
00023  ; this formal argument isn't terminated properly
00024  
00025  |<unterminated_formal_argument|

      ERROR  2 (Line 25:1): Encountered formal argument symbol that is not terminated with a '>'.

Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = <unterminated_formal_argument) (line_number = 25) (line_index = 1))

forcing modbr.abort_scan back to false...

00026  
00027  ; this formal argument contains a new line
00028  
00029  |<broken_
00030  formal_arg>|

      ERROR  1 (Line 29:1): New line encountered in a symbol.  Symbol not terminated with a '|'?

Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = <broken_) (line_number = 29) (line_index = 1))

forcing modbr.abort_scan back to false...


      ERROR  6 (Line 30:1): Encountered unrecognizable token in the input stream.
        Perhaps an unescaped symbol?
Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = formal) (line_number = 30) (line_index = 1))

forcing modbr.abort_scan back to false...


      ERROR  6 (Line 30:7): Encountered unrecognizable token in the input stream.

Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = _) (line_number = 30) (line_index = 7))

forcing modbr.abort_scan back to false...


      ERROR  6 (Line 30:8): Encountered unrecognizable token in the input stream.
        Perhaps an unescaped symbol?
Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = arg) (line_number = 30) (line_index = 8))

forcing modbr.abort_scan back to false...


      ERROR  6 (Line 30:11): Encountered unrecognizable token in the input stream.

Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = >) (line_number = 30) (line_index = 11))

forcing modbr.abort_scan back to false...

00031  

      ERROR  1 (Line 30:12): New line encountered in a symbol.  Symbol not terminated with a '|'?

Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = ) (line_number = 30) (line_index = 12))

forcing modbr.abort_scan back to false...

00032  ; now, on to predicate names, nominals, and column names
00033  ;
00034  ; a symbol with an invalid escape sequence:
00035  
00036  |the following escape sequence is invalid:\*|

      WARNING   0 (Line 36:1): Illegal escape sequence detected in a symbol.  Sequence replaced with a '_'.
        The sequence was: '*'

((code = 3(SYMBOL_TOK)) (aux = 6(COLUMN_FLAG|NOMINAL_FLAG)) (val = 0.0) (str = the following escape sequence is invalid:_) (line_number = 36) (line_index = 1))

00037  
00038  ; a symbol with leading and trailing spaces:
00039  
00040  |  this symbol has two leading and two trailing spaces  |

      WARNING   2 (Line 40:1): Leading white space detected in a symbol.  Whitespace converted to a '_'.


      WARNING   3 (Line 40:1): Trailing white space detected in a symbol.  Whitespace converted to a '_'.

((code = 3(SYMBOL_TOK)) (aux = 6(COLUMN_FLAG|NOMINAL_FLAG)) (val = 0.0) (str = _ this symbol has two leading and two trailing spaces _) (line_number = 40) (line_index = 1))

00041  
00042  ; symbols with a variety of illegal characters
00043  
00044  |()<>",are_all_forbidden_characters|

      WARNING   1 (Line 44:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: '('


      WARNING   1 (Line 44:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ')'


      WARNING   1 (Line 44:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: '<'


      WARNING   1 (Line 44:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: '>'


      WARNING   1 (Line 44:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: '"'


      WARNING   1 (Line 44:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ','

((code = 3(SYMBOL_TOK)) (aux = 7(PRED_FLAG|COLUMN_FLAG|NOMINAL_FLAG)) (val = 0.0) (str = ______are_all_forbidden_characters) (line_number = 44) (line_index = 1))

00045  
00046  |this_fsymbol_contains_a_BS_char:(hex_0x08)|

      WARNING   1 (Line 46:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: '' (HEX 0x8)


      WARNING   1 (Line 46:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: '('


      WARNING   1 (Line 46:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ')'

((code = 3(SYMBOL_TOK)) (aux = 7(PRED_FLAG|COLUMN_FLAG|NOMINAL_FLAG)) (val = 0.0) (str = this_fsymbol_contains_a_BS_char:__hex_0x08_) (line_number = 46) (line_index = 1))

00047  
00048  ; a symbol with an embedded new line
00049  
00050  |this-symbol-contains
00051  -a-new-line|

      ERROR  1 (Line 50:1): New line encountered in a symbol.  Symbol not terminated with a '|'?

Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = this-symbol-contains) (line_number = 50) (line_index = 1))

forcing modbr.abort_scan back to false...


      ERROR  5 (Line 51:1): Ill formed numerical constant.

Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = -) (line_number = 51) (line_index = 1))

forcing modbr.abort_scan back to false...


      ERROR  6 (Line 51:2): Encountered unrecognizable token in the input stream.
        Perhaps an unescaped symbol?
Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = a-new-line) (line_number = 51) (line_index = 2))

forcing modbr.abort_scan back to false...

00052  

      ERROR  1 (Line 51:12): New line encountered in a symbol.  Symbol not terminated with a '|'?

Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = ) (line_number = 51) (line_index = 12))

forcing modbr.abort_scan back to false...

00053  ; finally, an unterminated symbol
00054  ;
00055  ; True in MacSHAPA but not in OpenSHAPA -- the class used to read the input file 
00056  ; in MacshapaODBReader (java.io.BufferedReader) strips the new line character 
00057  ; (be it \r or \n) from each line as it reads it.  That causes us to recognize the
00058  ; end of file one character later than we used to -- hence we can no longer get 
00059  ; an unexpected eof error in this context.  Instead we get another symbol contains
00060  ; a new line error.
00061  
00062  |this symbol is unterminated and thus ends in an EOF

      ERROR  1 (Line 62:1): New line encountered in a symbol.  Symbol not terminated with a '|'?

Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = this symbol is unterminated and thus ends in an EOF) (line_number = 62) (line_index = 1))

forcing modbr.abort_scan back to false...

((code = 13(EOF_TOK)) (aux = 0) (val = 0.0) (str = ) (line_number = 62) (line_index = 0))

