
      ERROR  7 (Line 18:1): Encountered syntactically incorrect private value.
        Private values must begin with "<<".

Unable to continue parse -- Aborting...

      ERROR  6 (Line 18:16): Encountered unrecognizable token in the input stream.

Unable to continue parse -- Aborting...

      ERROR  7 (Line 23:1): Encountered syntactically incorrect private value.
        Private values must end with ">>".

Unable to continue parse -- Aborting...

      ERROR  7 (Line 27:1): Encountered syntactically incorrect private value.
        Only upper case letters & "-"s may appear in the body of a private value.

Unable to continue parse -- Aborting...

      ERROR  6 (Line 27:17): Encountered unrecognizable token in the input stream.

Unable to continue parse -- Aborting...

      ERROR  7 (Line 31:1): Encountered syntactically incorrect private value.
        Only upper case letters & '-'s may appear in the body of a private value.

Unable to continue parse -- Aborting...

      ERROR  6 (Line 31:16): Encountered unrecognizable token in the input stream.

Unable to continue parse -- Aborting...

      ERROR  6 (Line 31:17): Encountered unrecognizable token in the input stream.

Unable to continue parse -- Aborting...

      ERROR  7 (Line 35:1): Encountered syntactically incorrect private value.
        Encountered new line in private value.

Unable to continue parse -- Aborting...

      ERROR  6 (Line 36:7): Encountered unrecognizable token in the input stream.

Unable to continue parse -- Aborting...

      ERROR  4 (Line 45:1): Encountered end of file unexpectedly.
        EOF was encountered in a private value.
Unable to continue parse -- Aborting...
