00001  ; MacSHAPA Open Database
00002  ; 
00003  ; This database starts to get rough with the lexer.  The general idea is to 
00004  ; generate all the errors and warnings that the lexer is capable of flagging.
00005  ;
00006  ; Needless to say, this is not a legal database, and will cause even more
00007  ; fireworks if fed to the parser instead of just the lexer.
00008  ;
00009  ; This file deals only with errors that can be generated with reserved word tokens.
00010  ;
00011  ; This reserved word doesn't exist
00012  
00013   none-such

      ERROR  6 (Line 13:2): Encountered unrecognizable token in the input stream.
        Perhaps an unescaped symbol?
Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = none-such) (line_number = 13) (line_index = 2))

forcing modbr.abort_scan back to false...

00014   
00015  ; and this one contains an illegal character
00016  
00017   none-Such

      ERROR  6 (Line 17:2): Encountered unrecognizable token in the input stream.
        Perhaps an unescaped symbol?
Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = none-) (line_number = 17) (line_index = 2))

forcing modbr.abort_scan back to false...


      ERROR  6 (Line 17:7): Encountered unrecognizable token in the input stream.
        Perhaps an unescaped symbol?

Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = S) (line_number = 17) (line_index = 7))

forcing modbr.abort_scan back to false...


      ERROR  6 (Line 17:8): Encountered unrecognizable token in the input stream.
        Perhaps an unescaped symbol?
Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = uch) (line_number = 17) (line_index = 8))

forcing modbr.abort_scan back to false...

00018  
00019  ; finally, this one has an unexpected end of file
00020  ;
00021  ; True in MacSHAPA but not in OpenSHAPA -- the class used to read the input file 
00022  ; in MacshapaODBReader (java.io.BufferedReader) strips the new line character 
00023  ; (be it \r or \n) from each line as it reads it.  That causes us to recognize the
00024  ; end of file one character later than we used to -- hence we can no longer get 
00025  ; an unexpected eof error in this context.  Instead we get another unrecognized 
00026  ; token error.
00027  
00028  unxepected-eof

      ERROR  6 (Line 28:1): Encountered unrecognizable token in the input stream.
        Perhaps an unescaped symbol?
Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = unxepected-eof) (line_number = 28) (line_index = 1))

forcing modbr.abort_scan back to false...

((code = 13(EOF_TOK)) (aux = 0) (val = 0.0) (str = ) (line_number = 28) (line_index = 0))

