
      WARNING   6 (Line 13:9): Integer value out of range.  Coerced value to nearest legal value.


      ERROR  0 (Line 13:9): Warning limit exceeded - load aborted.

Unable to continue parse -- Aborting...

      WARNING   6 (Line 17:3): Integer value out of range.  Coerced value to nearest legal value.


      ERROR  0 (Line 17:3): Warning limit exceeded - load aborted.

Unable to continue parse -- Aborting...

      ERROR  5 (Line 21:1): Ill formed numerical constant.

Unable to continue parse -- Aborting...

      WARNING   7 (Line 25:1): Absolute value of floating point value too large.  Coerced value to nearest legal value.


      ERROR  0 (Line 25:1): Warning limit exceeded - load aborted.

Unable to continue parse -- Aborting...

      WARNING   8 (Line 29:1): Discarded one or more least significant digits from fractional part of floating point value.


      ERROR  0 (Line 29:1): Warning limit exceeded - load aborted.

Unable to continue parse -- Aborting...

      WARNING   7 (Line 33:1): Absolute value of floating point value too large.  Coerced value to nearest legal value.


      ERROR  0 (Line 33:1): Warning limit exceeded - load aborted.

Unable to continue parse -- Aborting...

      WARNING   8 (Line 33:1): Discarded one or more least significant digits from fractional part of floating point value.


      ERROR  0 (Line 33:1): Warning limit exceeded - load aborted.

Unable to continue parse -- Aborting...

      WARNING   6 (Line 44:1): Integer value out of range.  Coerced value to nearest legal value.


      ERROR  0 (Line 44:1): Warning limit exceeded - load aborted.

Unable to continue parse -- Aborting...
