00001  ; MacSHAPA Open Database
00002  ; 
00003  ; This is a duplicate of lexer_test_07.txt, save with '\n' substituted for 
00004  ; '\r' throughout the file.  The purpose of the substitution is to verify that
00005  ; the Openshapa MacshapaODBReader class doesn't care whether new lines are marked
00006  ; with '\r' or '\n'.
00007  ;
00008  ; This database starts to get rough with the lexer.  The general idea is to 
00009  ; generate all the errors and warnings that the lexer is capable of flagging.
00010  ;
00011  ; Needless to say, this is not a legal database, and will cause even more
00012  ; fireworks if fed to the parser instead of just the lexer.
00013  ;
00014  ; This file deals only with errors that can be generated with symbol tokens.
00015  ;
00016  ; This formal argument contains an illegal escape sequence
00017  
00018  |<illegal_escape_seq:\i>|

      WARNING   0 (Line 18:1): Illegal escape sequence detected in a symbol.  Sequence replaced with a '_'.
        The sequence was: \i

((code = 3(SYMBOL_TOK)) (aux = 8(FORMAL_ARG_FLAG)) (val = 0.0) (str = <illegal_escape_seq:_>) (line_number = 18) (line_index = 1))

00019  
00020  ; These formal arguments contain a variety of illegal characters
00021  
00022  |<<to_many_brackets>>| |<spaces are frobidden in formal arguments>|

      WARNING   1 (Line 22:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: '<'.


      WARNING   1 (Line 22:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: '>'.

((code = 3(SYMBOL_TOK)) (aux = 8(FORMAL_ARG_FLAG)) (val = 0.0) (str = <_to_many_brackets_>) (line_number = 22) (line_index = 1))


      WARNING   1 (Line 22:24): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ' ' (HEX 0x20)


      WARNING   1 (Line 22:24): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ' ' (HEX 0x20)


      WARNING   1 (Line 22:24): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ' ' (HEX 0x20)


      WARNING   1 (Line 22:24): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ' ' (HEX 0x20)


      WARNING   1 (Line 22:24): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ' ' (HEX 0x20)

((code = 3(SYMBOL_TOK)) (aux = 8(FORMAL_ARG_FLAG)) (val = 0.0) (str = <spaces_are_frobidden_in_formal_arguments>) (line_number = 22) (line_index = 24))

00023  
00024  |<()", are_all_forbidden_characters>|

      WARNING   1 (Line 24:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was '('


      WARNING   1 (Line 24:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was ')'


      WARNING   1 (Line 24:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was '"'


      WARNING   1 (Line 24:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was ','


      WARNING   1 (Line 24:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ' ' (HEX 0x20)

((code = 3(SYMBOL_TOK)) (aux = 8(FORMAL_ARG_FLAG)) (val = 0.0) (str = <_____are_all_forbidden_characters>) (line_number = 24) (line_index = 1))

00025  
00026  |<this_formal_argument_contains_a_BS_char:(hex_0x08)>|

      WARNING   1 (Line 26:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: '' (HEX 0x8)


      WARNING   1 (Line 26:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was '('


      WARNING   1 (Line 26:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was ')'

((code = 3(SYMBOL_TOK)) (aux = 8(FORMAL_ARG_FLAG)) (val = 0.0) (str = <this_formal_argument_contains_a_BS_char:__hex_0x08_>) (line_number = 26) (line_index = 1))

00027  
00028  ; this formal argument isn't terminated properly
00029  
00030  |<unterminated_formal_argument|

      ERROR  2 (Line 30:1): Encountered formal argument symbol that is not terminated with a '>'.

Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = <unterminated_formal_argument) (line_number = 30) (line_index = 1))

forcing modbr.abort_scan back to false...

00031  
00032  ; this formal argument contains a new line
00033  
00034  |<broken_
00035  formal_arg>|

      ERROR  1 (Line 34:1): New line encountered in a symbol.  Symbol not terminated with a '|'?

Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = <broken_) (line_number = 34) (line_index = 1))

forcing modbr.abort_scan back to false...


      ERROR  6 (Line 35:1): Encountered unrecognizable token in the input stream.
        Perhaps an unescaped symbol?
Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = formal) (line_number = 35) (line_index = 1))

forcing modbr.abort_scan back to false...


      ERROR  6 (Line 35:7): Encountered unrecognizable token in the input stream.

Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = _) (line_number = 35) (line_index = 7))

forcing modbr.abort_scan back to false...


      ERROR  6 (Line 35:8): Encountered unrecognizable token in the input stream.
        Perhaps an unescaped symbol?
Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = arg) (line_number = 35) (line_index = 8))

forcing modbr.abort_scan back to false...


      ERROR  6 (Line 35:11): Encountered unrecognizable token in the input stream.

Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = >) (line_number = 35) (line_index = 11))

forcing modbr.abort_scan back to false...

00036  

      ERROR  1 (Line 35:12): New line encountered in a symbol.  Symbol not terminated with a '|'?

Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = ) (line_number = 35) (line_index = 12))

forcing modbr.abort_scan back to false...

00037  ; now, on to predicate names, nominals, and column names
00038  ;
00039  ; a symbol with an invalid escape sequence:
00040  
00041  |the following escape sequence is invalid:\*|

      WARNING   0 (Line 41:1): Illegal escape sequence detected in a symbol.  Sequence replaced with a '_'.
        The sequence was: '*'

((code = 3(SYMBOL_TOK)) (aux = 6(COLUMN_FLAG|NOMINAL_FLAG)) (val = 0.0) (str = the following escape sequence is invalid:_) (line_number = 41) (line_index = 1))

00042  
00043  ; a symbol with leading and trailing spaces:
00044  
00045  |  this symbol has two leading and two trailing spaces  |

      WARNING   2 (Line 45:1): Leading white space detected in a symbol.  Whitespace converted to a '_'.


      WARNING   3 (Line 45:1): Trailing white space detected in a symbol.  Whitespace converted to a '_'.

((code = 3(SYMBOL_TOK)) (aux = 6(COLUMN_FLAG|NOMINAL_FLAG)) (val = 0.0) (str = _ this symbol has two leading and two trailing spaces _) (line_number = 45) (line_index = 1))

00046  
00047  ; symbols with a variety of illegal characters
00048  
00049  |()<>",are_all_forbidden_characters|

      WARNING   1 (Line 49:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: '('


      WARNING   1 (Line 49:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ')'


      WARNING   1 (Line 49:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: '<'


      WARNING   1 (Line 49:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: '>'


      WARNING   1 (Line 49:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: '"'


      WARNING   1 (Line 49:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ','

((code = 3(SYMBOL_TOK)) (aux = 7(PRED_FLAG|COLUMN_FLAG|NOMINAL_FLAG)) (val = 0.0) (str = ______are_all_forbidden_characters) (line_number = 49) (line_index = 1))

00050  
00051  |this_fsymbol_contains_a_BS_char:(hex_0x08)|

      WARNING   1 (Line 51:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: '' (HEX 0x8)


      WARNING   1 (Line 51:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: '('


      WARNING   1 (Line 51:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ')'

((code = 3(SYMBOL_TOK)) (aux = 7(PRED_FLAG|COLUMN_FLAG|NOMINAL_FLAG)) (val = 0.0) (str = this_fsymbol_contains_a_BS_char:__hex_0x08_) (line_number = 51) (line_index = 1))

00052  
00053  ; a symbol with an embedded new line
00054  
00055  |this-symbol-contains
00056  -a-new-line|

      ERROR  1 (Line 55:1): New line encountered in a symbol.  Symbol not terminated with a '|'?

Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = this-symbol-contains) (line_number = 55) (line_index = 1))

forcing modbr.abort_scan back to false...


      ERROR  5 (Line 56:1): Ill formed numerical constant.

Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = -) (line_number = 56) (line_index = 1))

forcing modbr.abort_scan back to false...


      ERROR  6 (Line 56:2): Encountered unrecognizable token in the input stream.
        Perhaps an unescaped symbol?
Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = a-new-line) (line_number = 56) (line_index = 2))

forcing modbr.abort_scan back to false...

00057  

      ERROR  1 (Line 56:12): New line encountered in a symbol.  Symbol not terminated with a '|'?

Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = ) (line_number = 56) (line_index = 12))

forcing modbr.abort_scan back to false...

00058  ; finally, an unterminated symbol
00059  ;
00060  ; True in MacSHAPA but not in OpenSHAPA -- the class used to read the input file 
00061  ; in MacshapaODBReader (java.io.BufferedReader) strips the new line character 
00062  ; (be it \r or \n) from each line as it reads it.  That causes us to recognize the
00063  ; end of file one character later than we used to -- hence we can no longer get 
00064  ; an unexpected eof error in this context.  Instead we get another symbol contains
00065  ; a new line error.
00066  
00067  |this symbol is unterminated and thus ends in an EOF

      ERROR  1 (Line 67:1): New line encountered in a symbol.  Symbol not terminated with a '|'?

Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = this symbol is unterminated and thus ends in an EOF) (line_number = 67) (line_index = 1))

forcing modbr.abort_scan back to false...

((code = 13(EOF_TOK)) (aux = 0) (val = 0.0) (str = ) (line_number = 67) (line_index = 0))

