00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is a duplicate of lexer_test_05.txt, save with '\n' substituted for 
00004  ; '\r' throughout the file.  The purpose of the substitution is to verify that
00005  ; the Openshapa MacshapaODBReader class doesn't care whether new lines are marked
00006  ; with '\r' or '\n'.
00007  ; 
00008  ; This database starts to get rough with the lexer.  The general idea is to 
00009  ; generate all the errors and warnings that the lexer is capable of flagging.
00010  ;
00011  ; Needless to say, this is not a legal database, and will cause even more
00012  ; fireworks if fed to the parser instead of just the lexer.
00013  ;
00014  ; This file deals only with errors that can be generated with reserved word tokens.
00015  ;
00016  ; This reserved word doesn't exist
00017  
00018   none-such

      ERROR  6 (Line 18:2): Encountered unrecognizable token in the input stream.
        Perhaps an unescaped symbol?
Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = none-such) (line_number = 18) (line_index = 2))

forcing modbr.abort_scan back to false...

00019   
00020  ; and this one contains an illegal character
00021  
00022   none-Such

      ERROR  6 (Line 22:2): Encountered unrecognizable token in the input stream.
        Perhaps an unescaped symbol?
Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = none-) (line_number = 22) (line_index = 2))

forcing modbr.abort_scan back to false...


      ERROR  6 (Line 22:7): Encountered unrecognizable token in the input stream.
        Perhaps an unescaped symbol?

Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = S) (line_number = 22) (line_index = 7))

forcing modbr.abort_scan back to false...


      ERROR  6 (Line 22:8): Encountered unrecognizable token in the input stream.
        Perhaps an unescaped symbol?
Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = uch) (line_number = 22) (line_index = 8))

forcing modbr.abort_scan back to false...

00023  
00024  ; finally, this one has an unexpected end of file
00025  ;
00026  ; True in MacSHAPA but not in OpenSHAPA -- the class used to read the input file 
00027  ; in MacshapaODBReader (java.io.BufferedReader) strips the new line character 
00028  ; (be it \r or \n) from each line as it reads it.  That causes us to recognize the
00029  ; end of file one character later than we used to -- hence we can no longer get 
00030  ; an unexpected eof error in this context.  Instead we get another unrecognized 
00031  ; token error.
00032  
00033  unxepected-eof

      ERROR  6 (Line 33:1): Encountered unrecognizable token in the input stream.
        Perhaps an unescaped symbol?
Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = unxepected-eof) (line_number = 33) (line_index = 1))

forcing modbr.abort_scan back to false...

((code = 13(EOF_TOK)) (aux = 0) (val = 0.0) (str = ) (line_number = 33) (line_index = 0))

