00001  ; MacSHAPA Open Database
00002  ;
00003  ; This is a duplicate of lexer_test_08.txt, save with '\n' substituted for 
00004  ; '\r' throughout the file.  The purpose of the substitution is to verify that
00005  ; the Openshapa MacshapaODBReader class doesn't care whether new lines are marked
00006  ; with '\r' or '\n'.
00007  ; 
00008  ; This database starts to get rough with the lexer.  The general idea is to 
00009  ; generate all the errors and warnings that the lexer is capable of flagging.
00010  ;
00011  ; Needless to say, this is not a legal database, and will cause even more
00012  ; fireworks if fed to the parser instead of just the lexer.
00013  ;
00014  ; This file is a follow on to lexer_test_07.txt.  It exists as I want to test
00015  ; an eof in a formal argument.
00016  ;
00017  
00018  ; an unterminated formal argument symbol
00019  ;
00020  ; True in MacSHAPA but not in OpenSHAPA -- the class used to read the input file 
00021  ; in MacshapaODBReader (java.io.BufferedReader) strips the new line character 
00022  ; (be it \r or \n) from each line as it reads it.  That causes us to recognize the
00023  ; end of file one character later than we used to -- hence we can no longer get 
00024  ; an unexpected eof error in this context.  Instead we get a symbol contains
00025  ; a new line error.
00026  
00027  |<this_formal_argument_is_unterminated_and_thus_ends_in_an_EOF

      ERROR  1 (Line 27:1): New line encountered in a symbol.  Symbol not terminated with a '|'?

Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = <this_formal_argument_is_unterminated_and_thus_ends_in_an_EOF) (line_number = 27) (line_index = 1))

forcing modbr.abort_scan back to false...

((code = 13(EOF_TOK)) (aux = 0) (val = 0.0) (str = ) (line_number = 27) (line_index = 0))

