00001  ; MacSHAPA Open Database
00002  ; 
00003  ; This database starts to get rough with the lexer.  The general idea is to 
00004  ; generate all the errors and warnings that the lexer is capable of flagging.
00005  ;
00006  ; Needless to say, this is not a legal database, and will cause even more
00007  ; fireworks if fed to the parser instead of just the lexer.
00008  ;
00009  ; This file deals only with errors that can be generated with booleans and 
00010  ; a-list tag names.
00011  ;
00012  ; This shouldn't generate an error, but it should generate an unknown a-list tag token:
00013  
00014          NONE-SUCH>
((code = 8(ALIST_LABEL_TOK)) (aux = 35(UNKNOWN_ALIST_LABEL)) (val = 0.0) (str = NONE-SUCH>) (line_number = 14) (line_index = 9))

00015  
00016  ; Now a mis-spelled boolean - this should generate a fatal error
00017  
00018  		TRU

      ERROR  6 (Line 18:3): Encountered unrecognizable token in the input stream.
        Perhaps an unescaped symbol?

Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = TRU) (line_number = 18) (line_index = 3))

forcing modbr.abort_scan back to false...

00019  
00020  ; and now an unexpected end of file error:
00021  ;
00022  ; True in MacSHAPA but not in OpenSHAPA -- the class used to read the input file 
00023  ; in MacshapaODBReader (java.io.BufferedReader) strips the new line character 
00024  ; (be it \r or \n) from each line as it reads it.  That causes us to recognize the
00025  ; end of file one character later than we used to -- hence we can no longer get 
00026  ; an unexpected eof error in this context.  Instead we get an unrecognizable
00027  ; token error.
00028  
00029  	AN-UNEXPECTED-EOF

      ERROR  6 (Line 29:2): Encountered unrecognizable token in the input stream.
        Perhaps an unescaped symbol?

Unable to continue parse -- Aborting...
((code = 0(ERROR_TOK)) (aux = 0) (val = 0.0) (str = AN-UNEXPECTED-EOF) (line_number = 29) (line_index = 2))

forcing modbr.abort_scan back to false...

((code = 13(EOF_TOK)) (aux = 0) (val = 0.0) (str = ) (line_number = 29) (line_index = 0))

