
      WARNING   0 (Line 13:1): Illegal escape sequence detected in a symbol.  Sequence replaced with a '_'.
        The sequence was: \i


      WARNING   1 (Line 17:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: '<'.


      WARNING   1 (Line 17:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: '>'.


      WARNING   1 (Line 17:24): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ' ' (HEX 0x20)


      WARNING   1 (Line 17:24): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ' ' (HEX 0x20)


      WARNING   1 (Line 17:24): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ' ' (HEX 0x20)


      WARNING   1 (Line 17:24): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ' ' (HEX 0x20)


      WARNING   1 (Line 17:24): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ' ' (HEX 0x20)


      WARNING   1 (Line 19:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was '('


      WARNING   1 (Line 19:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was ')'


      WARNING   1 (Line 19:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was '"'


      WARNING   1 (Line 19:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was ','


      WARNING   1 (Line 19:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ' ' (HEX 0x20)


      WARNING   1 (Line 21:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: '' (HEX 0x8)


      WARNING   1 (Line 21:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was '('


      WARNING   1 (Line 21:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was ')'


      ERROR  2 (Line 25:1): Encountered formal argument symbol that is not terminated with a '>'.

Unable to continue parse -- Aborting...

      ERROR  1 (Line 29:1): New line encountered in a symbol.  Symbol not terminated with a '|'?

Unable to continue parse -- Aborting...

      ERROR  6 (Line 30:1): Encountered unrecognizable token in the input stream.
        Perhaps an unescaped symbol?
Unable to continue parse -- Aborting...

      ERROR  6 (Line 30:7): Encountered unrecognizable token in the input stream.

Unable to continue parse -- Aborting...

      ERROR  6 (Line 30:8): Encountered unrecognizable token in the input stream.
        Perhaps an unescaped symbol?
Unable to continue parse -- Aborting...

      ERROR  6 (Line 30:11): Encountered unrecognizable token in the input stream.

Unable to continue parse -- Aborting...

      ERROR  1 (Line 30:12): New line encountered in a symbol.  Symbol not terminated with a '|'?

Unable to continue parse -- Aborting...

      WARNING   0 (Line 36:1): Illegal escape sequence detected in a symbol.  Sequence replaced with a '_'.
        The sequence was: '*'


      WARNING   2 (Line 40:1): Leading white space detected in a symbol.  Whitespace converted to a '_'.


      WARNING   3 (Line 40:1): Trailing white space detected in a symbol.  Whitespace converted to a '_'.


      WARNING   1 (Line 44:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: '('


      WARNING   1 (Line 44:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ')'


      WARNING   1 (Line 44:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: '<'


      WARNING   1 (Line 44:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: '>'


      WARNING   1 (Line 44:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: '"'


      WARNING   1 (Line 44:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ','


      WARNING   1 (Line 46:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: '' (HEX 0x8)


      WARNING   1 (Line 46:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: '('


      WARNING   1 (Line 46:1): Illegal character detected in a symbol.  Character replaced with a '_'.
        The illegal character was: ')'


      ERROR  1 (Line 50:1): New line encountered in a symbol.  Symbol not terminated with a '|'?

Unable to continue parse -- Aborting...

      ERROR  5 (Line 51:1): Ill formed numerical constant.

Unable to continue parse -- Aborting...

      ERROR  6 (Line 51:2): Encountered unrecognizable token in the input stream.
        Perhaps an unescaped symbol?
Unable to continue parse -- Aborting...

      ERROR  1 (Line 51:12): New line encountered in a symbol.  Symbol not terminated with a '|'?

Unable to continue parse -- Aborting...

      ERROR  1 (Line 62:1): New line encountered in a symbol.  Symbol not terminated with a '|'?

Unable to continue parse -- Aborting...
