
      ERROR  7 (Line 13:1): Encountered syntactically incorrect private value.
        Private values must begin with "<<".

Unable to continue parse -- Aborting...

      ERROR  6 (Line 13:16): Encountered unrecognizable token in the input stream.

Unable to continue parse -- Aborting...

      ERROR  7 (Line 18:1): Encountered syntactically incorrect private value.
        Private values must end with ">>".

Unable to continue parse -- Aborting...

      ERROR  7 (Line 22:1): Encountered syntactically incorrect private value.
        Only upper case letters & "-"s may appear in the body of a private value.

Unable to continue parse -- Aborting...

      ERROR  6 (Line 22:17): Encountered unrecognizable token in the input stream.

Unable to continue parse -- Aborting...

      ERROR  7 (Line 26:1): Encountered syntactically incorrect private value.
        Only upper case letters & '-'s may appear in the body of a private value.

Unable to continue parse -- Aborting...

      ERROR  6 (Line 26:16): Encountered unrecognizable token in the input stream.

Unable to continue parse -- Aborting...

      ERROR  6 (Line 26:17): Encountered unrecognizable token in the input stream.

Unable to continue parse -- Aborting...

      ERROR  7 (Line 30:1): Encountered syntactically incorrect private value.
        Encountered new line in private value.

Unable to continue parse -- Aborting...

      ERROR  6 (Line 31:7): Encountered unrecognizable token in the input stream.

Unable to continue parse -- Aborting...

      ERROR  4 (Line 40:1): Encountered end of file unexpectedly.
        EOF was encountered in a private value.
Unable to continue parse -- Aborting...
