package org.openshapa.event;

import java.util.EventObject;

/**
 * Event object for a track carriage event
 */
public class CarriageEvent extends EventObject {

    /**
     * Auto generated by Eclipse
     */
    private static final long serialVersionUID = 4009420871939032673L;

    public enum EventType {
        OFFSET_CHANGE, BOOKMARK_REQUEST, CARRIAGE_SELECTION
    }

    /** Track identifier */
    private final String trackId;
    /** New time offset, in milliseconds, for the given track */
    private final long offset;
    /** Duration of the track in milliseconds */
    private final long duration;
    /**
     * Temporal position of the mouse. Only meaningful for
     * EventType.OFFSET_CHANGE
     */
    private final long temporalPosition;
    /** What event does this represent */
    private final EventType eventType;

    public CarriageEvent(final Object source, final String trackId,
            final long offset, final long duration,
            final long temporalPosition, final EventType eventType) {
        super(source);
        this.trackId = trackId;
        this.offset = offset;
        this.duration = duration;
        this.temporalPosition = temporalPosition;
        this.eventType = eventType;
    }

    /**
     * @return New time offset in milliseconds.
     */
    public long getOffset() {
        return offset;
    }

    /**
     * @return Track identifier
     */
    public String getTrackId() {
        return trackId;
    }

    /**
     * @return Track duration in milliseconds
     */
    public long getDuration() {
        return duration;
    }

    /**
     * @return the temporal position of the mouse in milliseconds. Only
     *         meaningful for OFFSET_CHANGE events.
     */
    public long getTemporalPosition() {
        return temporalPosition;
    }

    /**
     * @return event type
     */
    public EventType getEventType() {
        return eventType;
    }

}
